### ISSUE TITLE
Access to Raw Data

### ISSUE THREAD

**Issue by nyshocka** [nicolaskruchten/pivottable#1004]
Hi, I am looking for a way to access the Raw data that is used to build the PivotUI.

Use Case: 

I build a table #tbl-rawdata and apply the pivotUI to it. I would like to do two things
1) I would like to update rows the raw data with real time data via AJAX but I can't find #tbl-rawdata 
2) I have a method to export a table to CSV, I want to apply this to the raw data at any moment.

**Comment by nicolaskruchten** [comment]
I’m not sure I understand... if you are building tbl-rawdata then you
already have access to it, no?

**Comment by nyshocka** [comment]
@nicolaskruchten thanks for replying so quickly.

after I built tbl-rawdata and apply the pivotUI to it,I am unable to access it again. 

I ran the following: 

```
alert($("#tbl_time").html());
$("#out").pivotUI($("#tbl_time")
{rows: ["Dept","Role"], cols: ["Month"],
});
alert($("#tbl_time").html());
```

The first alert shows the HTML of the table, the second returns Undefined. The pivot shows up and works perfectly! 

In my ucase I would like to call the table after the pivot in invoked in order to manipulate it.

**Comment by nicolaskruchten** [comment]
That seems... very strange. If you look at this example https://pivottable.js.org/examples/simple_ui_from_table.html you'll see that although the pivot table has rendered, the input table is still there and you can still access it from the console etc...

**Comment by nicolaskruchten** [comment]
Is `#tbl_time` contained *within* `#out` originally by any chance? `pivotUI()` will completely overwrite the contents of the element it's called on...

**Comment by nyshocka** [comment]
Yes #tbl_time is within #out.

**Comment by nicolaskruchten** [comment]
OK, that's your problem right there. You'd be better off putting your data table in a hidden div, or just using an array or object or something if you don't ever need to render it.

**Comment by nyshocka** [comment]
Awesome thanks! That was it!
