### ISSUE TITLE
Combination chart with C3

### ISSUE THREAD

**Issue by GaryLChew** [nicolaskruchten/pivottable#1005]
Hello Nicolas,
I trying to overlay a line (y=x) on top of a C3 scatter chart with PivotUI, like so:
https://jsfiddle.net/GaryLChew/5Ldk92qr/11/

Is there a way to do this with PivotTable? I know you can use rendererOptions, but I don't believe that you can have multiple datasets, so I'm not sure what to do here. Thanks.

`
types: {
     ?: 'scatter',
     ?: 'line'
}
`

**Comment by nicolaskruchten** [comment]
Unfortunately I don't think this will be possible, as the pivot table assumes it has full control over what goes into the chart data...

**Comment by GaryLChew** [comment]
I see, thanks for letting me know.
