### ISSUE TITLE
Pivottable coloumns selection

### ISSUE THREAD

**Issue by viraj12345** [nicolaskruchten/pivottable#1009]
The field selections in the pivot table sometimes breaks in to a column and shows on the  leftside (of the Yaxis) in the pivot table  instead of showing up on the top of the table. I have attached an example . Please suggest how can I fix this and make the field names always appear on top of the table

![2018-09-20 15_58_49-pivot demo with r datasets](https://user-images.githubusercontent.com/42563223/45846758-550db480-bcee-11e8-9604-15310e31e346.jpg)

**Comment by nicolaskruchten** [comment]
Check out the “unusedAttrsVertical” parameter.

**Comment by viraj12345** [comment]
This worked.,Thank you !
