### ISSUE TITLE
Correct total field on pivots that use average as aggregator name

### ISSUE THREAD

**Issue by VascoB** [nicolaskruchten/pivottable#1011]
The pivots, that are using the average as an aggregator name, incorrectly calculate the total field. As I understood, the formula of the an average is the sum of all occurrences devices by the number of occurrences. However the average is being made through the number of occurrences plus one (n+1).

**Comment by nicolaskruchten** [comment]
If you can provide me with sample code that replicates this I'd gladly take a look at it but I suspect you're misunderstanding the functioning of the aggregators in this library. If you're using "average" then the total row will display the average of all the *records* in each column, not all the *cells* in each column. Quite often these differ quite a bit.

By way of example, if you have a year's worth of daily data arranged in monthly rows aggregated by average, then each cell will show the daily average for the given month, and the total will be the daily average for the year, which might be different from the average of monthly averages.

**Comment by VascoB** [comment]
My original code is:
$("#output9").pivotUI($("#receivements"),
    	    {
    	        rows: ["Month"],
    	        vals: ["Amount"],
    	        aggregatorName: ["Average"],
     	        filter: function(record){ 
     	        	var mm = new Date().getMonth()+1;
    	        	if(mm<10) {
    	        	    mm = '0'+mm
    	        	}
    	        	var actualMonth =  new Date().getFullYear() + '/' + mm;
    	        	
    	            return record["Month"].substr(5, 7) == mm && record["Month"] != actualMonth && record["Entity"] == "Car"; 
    	        }

    	    });

**Comment by nicolaskruchten** [comment]
Right, I would need to have access to some sample data that shows the behaviour as well :) Can you put together a CodePen or JSFiddle or something please?

Before you do that though, does my explanation of the intended behaviour make sense? It's not expected that the "total" average shows the average of the displayed cells.

**Comment by VascoB** [comment]
Sorry for my English, I understand your explanation but I think that in this case it could be different.
I don't know how to give you a code pen but my sample with excel is:
[average-pivot.xlsx](https://github.com/nicolaskruchten/pivottable/files/2409436/average-pivot.xlsx)
<img width="476" alt="screen shot 2018-09-24 at 02 41 52" src="https://user-images.githubusercontent.com/12829075/45935547-5ec04200-bfa4-11e8-9d10-eb3df2b2163b.png">

**Comment by nicolaskruchten** [comment]
Here's a JSFiddle of PivotTable.js operating on the data above, and giving the same output as Excel: 
https://jsfiddle.net/nicolaskruchten/3u5qga8j/

If you're seeing different output, I suspect you've got different data being fed to your pivot table, with a ninth row of data in there somewhere :)

**Comment by VascoB** [comment]
Yes you found my bug, I have a row with a value 0 and because of this my average is not ok, sorry for all the time and thank you :)

**Comment by nicolaskruchten** [comment]
Glad you sorted out the problem :)
