### ISSUE TITLE
pivot.nl.js is missing the 'First' and 'Last' aggregators

### ISSUE THREAD

**Issue by klinckag** [nicolaskruchten/pivottable#1021]
pivot.nl.js is missing the 'First' and 'Last' aggregators.

      aggregators: {
...
        "Eerste": tpl.first(frFmt),
        "Laatste": tpl.last(frFmt),
...)
      },

**Comment by nicolaskruchten** [comment]
Thanks! Fixed in  4aa381, will be in the next release :)
