### ISSUE TITLE
PivotTable should use container's sizes for generated content

### ISSUE THREAD

**Issue by Flaurite** [nicolaskruchten/pivottable#1025]
Now `PivotTable` doesn't use size of parent div container, but the whole page size.

**Comment by nicolaskruchten** [comment]
Can you provide a running example of what you’re seeing please, like
 jsfiddle or a codepen?

**Comment by nicolaskruchten** [comment]
I see what you mean. The short answer is that this component isn't really responsive... If you don't specify a width/height for the charts via `rendererOptions` then on each render, the width and height are computed based on the viewport (the logic is [here](https://github.com/nicolaskruchten/pivottable/blob/master/src/c3_renderers.coffee#L19)).

**Comment by Flaurite** [comment]
Ok, so I close the issue.
