### ISSUE TITLE
How to apply plotly configuration options 

### ISSUE THREAD

**Issue by JyothiGandi** [nicolaskruchten/pivottable#1034]
Hi,

In [pivotUI() with Plotly chart renderers](https://pivottable.js.org/examples/plotly.html) example is there any way I could hide the [plotly mode bar](https://plot.ly/javascript/configuration-options/#hide-the-modebar)?

I see that there is a [possibility](https://github.com/nicolaskruchten/pivottable/wiki/Optional-Extra-Renderers#plotly-rendereroptions) to apply plotly [layout options](https://plot.ly/javascript/reference/#layout), but not the [configuration options](https://plot.ly/javascript/configuration-options/).

Thank you.

**Comment by nicolaskruchten** [comment]
Yes, this is an oversight. I'll add support for this in the coming days.

**Comment by nicolaskruchten** [comment]
This is now possible via the `plotlyConfig` renderer option: https://github.com/nicolaskruchten/pivottable/wiki/Optional-Extra-Renderers#plotly-rendereroptions
