### ISSUE TITLE
issue with custom aggregator in PivotUi, while passing the aggregator value from another dropdown

### ISSUE THREAD

**Issue by gparida1989** [nicolaskruchten/pivottable#1036]
Hi,
I am passing a custom aggregator to PivotUi function.
here the custom aggregator is --
 customAggregator = sum() aggregator + aggregator field name from an external parameter

first time it renders the table . But when i change the aggregator field param , it gives the below messege and renders with the last used aggregator field
Error : opts.aggregators[aggregator.val(...)] is not a function

On debugging i found that the below line causing the issue --
numInputsToProcess = (ref4 = opts.aggregators[aggregator.val()]([])().numInputs) != null ? ref4 : 0;

Except the first time, aggregator.val() is null for the subsequent attempts.
While the below code properly set the value ---
aggregator = $("<select>").addClass('pvtAggregator').bind("change", function() {
          return refresh();
        });
        ref1 = opts.aggregators;
        for (x in ref1) {
          if (!hasProp.call(ref1, x)) continue;
          aggregator.append($("<option>").val(x).html(x));
        }

Please assist at your earliest.

Thanks

**Comment by gparida1989** [comment]
To add to the above issue,  this works perfectly with pivot() function

**Comment by nicolaskruchten** [comment]
Can you provide a runnable example like a CodePen or JSFiddle so that I can more easily help you?

**Comment by gparida1989** [comment]
Thanks.
Please fins the codepen --
https://codepen.io/gparida1989/pen/VVZPNK?editors=0010#0

I tried to explain , where the custom aggregator field name is getting passed from another dropdown

**Comment by gparida1989** [comment]
this piece of block resolves the above issue too
_this.find('input.pvtFilter:checked').each(function() {
              var filter;
              filter = $(this).data("filter");
              if (filter && exclusions[filter[0]] != null) {
                if (inclusions[filter[0]] != null) {
                  return inclusions[filter[0]].push(filter[1]);
                } else {
                  return inclusions[filter[0]] = [filter[1]];
                }
              }
            });

only adding one extra null check

**Comment by gparida1989** [comment]
Hi Nicolas,

I have raised a PR regarding the above issue.

update pivot.cofee(extra null check added to avoid error in case there is no filter data)
#1039 opened an hour ago by gparida1989 

Could you please validate the same at your earliest.
@nicolaskruchten 

Regards,

**Comment by gparida1989** [comment]
Hi @nicolaskruchten ,

The issue solved by removing shadowdom.. it seems pivot table features like (dragNdrop etc) doesn't work smoothly with shadowDom enabled.

Closing the case
