### ISSUE TITLE
issue with mouse dragging unused attributes

### ISSUE THREAD

**Issue by gparida1989** [nicolaskruchten/pivottable#1040]
suppose i have 5 unused attributes displayed as a vertical list with .pvtAttr.
ex:- 
pvt1
pvt2
pvt3
pvt4
pvt5

When i click on pvt1 in order to drag , immediately pvt1 moves to the last in the list after pvt5 but the mouse remains at the on pvt1 place.

It creates an offset for the pvt1 item from the mouse and this offset distance continues till i put the pvt1 to either row or cols.

How can I get rid of this.

In codepen this is not reproducible. I am getting this in my code. But i have not done any customization to pivottable.js library.

FYI I am using pivottable  : "pivottable": "^2.22.0",

Please assist.

**Comment by nicolaskruchten** [comment]
There's not much I can do to help you if you can't show me what the problem is :) 

If you can't reproduce it in a CodePen then it's likely due to something outside of PivotTable.js...

**Comment by gparida1989** [comment]
this issue is due to the pivottable's lack of support for shadow dom
