### ISSUE TITLE
custom display label to the data attributes

### ISSUE THREAD

**Issue by gparida1989** [nicolaskruchten/pivottable#1045]
Hi @nicolaskruchten ,

I just want to have a custom display name to the data attributes.
ex :- i have attr1,attr2 as my data attributes and currently displayed in unused attribute list.

I want attr1 to be displayed as "My Attribute".

To do this I had to use derivedAttributes and create another attribute as " My Attribute" which returns attr1.

Though this works, this iterates for each record and if i have a huge record set then this turns out to be an overhead.

Can we have another  parameter "attributeNameMapping" where this parameter takes the key as the attribute and name as the value.
Ex:- 
attributeNameMapping:{ attr1 : "My Attribute"}

and pivot.js will handle it automatically while default it to the attr1.

Regards,

**Comment by nicolaskruchten** [comment]
There's no feature for this right now. It's been requested before in issue #492 so I'm closing this as a duplicate.
