### ISSUE TITLE
It seems that rendererOptions:  { plotlyConfig: } isn't working. I can't set displayModeBar: true.

### ISSUE THREAD

**Issue by MikeGen** [nicolaskruchten/pivottable#1049]
Hi,

It seems that the `plotlyConfig `option is not working as the bar is not always visible for me.

I'm loading the data through a asp.net generic handler which returns a JSON by using `JsonConvert.SerializeObject`.

In the below example I'm able to add `rendererOptions: { plotly: { width: 1200, height: 800 } }` and it works perfectly.

Snippet of the code I use to load the pivottable.

```
$.getJSON("KL_Handler.ashx?selectorCompany=<%= authentication%>", function (mps) {
	$("#output").pivotUI(mps,
	{
		rows: ["Pack"],
		cols: ["Week"],
		aggregatorName: "Count",
		rendererName: "Line Chart",
		menuLimit: "100000",
		renderers: $.extend(
			$.pivotUtilities.renderers,
			$.pivotUtilities.plotly_renderers,
			$.pivotUtilities.export_renderers
		),
		rendererOptions: {
			plotlyConfig: {
				displayModeBar: true,
				displaylogo: false
			}
		}
	});
});
```

**Comment by nicolaskruchten** [comment]
Are you using the latest version of PivotTable.js?

**Comment by nicolaskruchten** [comment]
OK, I'm glad this is working for you now. Not sure what version you were using before but the files on `master` in this repo are the same ones as are on the CDN.
