### ISSUE TITLE
inclusion option is confusing & doesn't work 

### ISSUE THREAD

**Issue by gparida1989** [nicolaskruchten/pivottable#1050]
Hi, as per my understanding if I specify only inclusion option then it will include only those value for that attribute and only those value will be checked in the filterbox for that attribute.

but this doesn't work like that.

Below is the fiddle
https://jsfiddle.net/d9c2xgro/

Please assist me understanding this in a better way.

**Comment by nicolaskruchten** [comment]
The parameter is `inclusions` (plural, with an `s` at the end) rather than `inclusion` as you have in your fiddle.
