### ISSUE TITLE
Available field list to the left?? Anyone help?

### ISSUE THREAD

**Issue by jenspr** [nicolaskruchten/pivottable#1051]
Hello, 
used pivottable for couple of month. Brilliant thing. And I had the available fields on the left side (rather than the top).

I did an update to react-pivottable and they are on top now. I do not find any information how to move them to the left. Is there a parameter? :-( .. I am out of ideas right now.

**Comment by nicolaskruchten** [comment]
A couple of things:

1. `react-pivottable` is a different project from this one, and issues with that project should be raised here please: https://github.com/plotly/react-pivottable/issues
2. You're likely looking for the `unusedOrientationCutoff` prop from `react-pivottable`

I'm going to close this issue now... If you need any more help, I'd be happy to answer issues in the `react-pivottable` project :)
