### ISSUE TITLE
Hiding the aggregation stuff

### ISSUE THREAD

**Issue by newt0311** [nicolaskruchten/pivottable#1060]
First off, great library. Highly flexible and very easy to use. Thanks.

I'm using it for some reports where I never actually want to change the aggregation or sorting order. So the section in the PivotUI used for those things is pretty much wasted. I can definitely think of other things I want to put there. Any recommendations on how to do that? Happy to make the updates and contribute them back to the project if that turns out to be the best way to do it.

Thanks again.

**Comment by newt0311** [comment]
It looks like those elements are all inside a td tag with class pvtVals. Think just grabbing that and replacing the contents is a reasonable approach?

Thanks again.

**Comment by nicolaskruchten** [comment]
I think that's the best approach, yes. I'm unlikely to accept any invasive changes like this into the main library :)

**Comment by newt0311** [comment]
Quick update: I did that. It worked. Thanks for the advice.
