### ISSUE TITLE
Display totals for several values

### ISSUE THREAD

**Issue by jmiguelpinto** [nicolaskruchten/pivottable#1063]
Hi guys. I'm wondering if its possible to display the totals of several values. I can only agregate the Sum of one value:

For example:

    $("#output").pivotUI($("#myTable"),{
         rows: ["source", "medium", "campaign"],
         vals: ["impressions", "clicks", "conversions"]
     });

I need to display the totals for impressions, clicks and conversions in the same view, but in the UI I can ony agregate one of this values.
If there's a away to achieve this can someone explain it to me. Otherwise, I think it would be a must have feature.

Thanks.

**Comment by nicolaskruchten** [comment]
Unfortunately this is not supported... See the FAQ entry here: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi
