### ISSUE TITLE
Heatmap for List Unique Values - New Dimension

### ISSUE THREAD

**Issue by muftaye** [nicolaskruchten/pivottable#1071]
I was wondering if there was a way to add another dimension to the PivotTable using the heatmap but based on another data element.  

**For example:**  You have user and movie data.  You can use the list of unique values to show which movies a user watched grouped by a genre (users on rows and genres as columns with movies listed as unique values) so you can not only see how many for that user/genre but you can list out the exact movies as well (would be nice if each unique value was displayed as a list rather than comma separated).  Now lets say there was another data element you had on each movie like box office gross and you wanted to show this as a heatmap in your pivot.  It would be really nice to see that additional dimension of not only what movies a user watched for each genre, but also the gross box office revenue.  So each movie title would be colored (like highlighted) depending on its gross.

Let me know if this is something that can be done already or if its easy to enhance.

**Comment by nicolaskruchten** [comment]
Neat idea!

You could start by trying to make a special aggregator that works a bit like the builtin `listUniques` in terms of the output of its `format` function (which is what is displayed in the table) but returns a different `value` i.e. not an array.

The reason this might work is that the heatmap renderers reads the value to colour by not from the textual contents of the cell but from a `data` attribute added to the `<td>` tag by the underlying table renderer *before* calling the `format` function.

Set here: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L556

Read here: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L1068

**Comment by muftaye** [comment]
Thanks, i'll look into it.
