### ISSUE TITLE
PivotTable on Python Dash

### ISSUE THREAD

**Issue by popohoma** [nicolaskruchten/pivottable#1084]
Hi Nicolas,

I have been using Python Dash framework for a while and really love it.

However, I think they still don't have full pivot table gear like your pivottable.js.

Is there an example how we can integrate pivottable.js with Dash framework?

Do I need to write extra js or component package code?

Thanks,

Fortitude999

**Comment by popohoma** [comment]
Hi Nicolas,

Can I get your 2 cents on this?  I want to kick off an earth shattering project and need to confirm the framework or API for it.

Thank you very much for your time.


Allen

**Comment by nicolaskruchten** [comment]
Hi there! 

It's definitely in my plans to wrap the sibling project to this one, `react-pivottable`, so as to make it accessible from Dash, but I haven't found the time recently and likely won't in the coming weeks.

That said, it's actually pretty easy to do: the process is well-documented here https://dash.plot.ly/plugins

My plan has been to add a `PivotTable` Dash component to our `dash-extra-components` library here https://github.com/plotly/dash-extra-components so if you felt like doing it and submitting it as a PR, someone from our Dash team might be able to give you a hand, and it would likely be maintained by us moving forward :)

Good luck with your earth-shattering! Please leave us enough to live on :P

Nick

**Comment by nicolaskruchten** [comment]
looks like one of Plotly’s superstar interns got motivated to do this :)

https://community.plot.ly/t/show-and-tell-dash-pivottable/20112

**Comment by popohoma** [comment]
Thank you very much Nicolas.

Sorry forgot to reply two months back.

Glad to see Dash framework is getting more mature now and supports a lot of contempory web behaviours.
________________________________
