### ISSUE TITLE
Canceling report generation

### ISSUE THREAD

**Issue by klemenzeleznik** [nicolaskruchten/pivottable#1086]
Is there a way to cancel report generation? I cant seem to find any sollution.
Thanks in advance.

**Comment by nicolaskruchten** [comment]
What is “report generation” in this context?

**Comment by klemenzeleznik** [comment]
Lets say when i pass tons of data to pivotUi() and dont want to wait for it to finish processing all the data and want to cancel the execution.

The for loop in line 329 in pivot.coffee

**Comment by nicolaskruchten** [comment]
Ah i see. No, there is feature for interrupting this process.

**Comment by klemenzeleznik** [comment]
Too bad, maybe an idea for future implementations :)
