### ISSUE TITLE
Jasmin test failure

### ISSUE THREAD

**Issue by jjagielka** [nicolaskruchten/pivottable#1087]
Current release fails one test in Jasmin:
`@file:///home/jakub/pivottable/dist/pivot_spec.js:405:63`

```
$.pivotUtilities .aggregatorTemplates .listUnique works
Expected 'female,male' to be 'male,female'.
```

**Comment by nicolaskruchten** [comment]
Thanks for letting me know! Clearly I've been remiss at actually running these tests, as this one didn't get updated for new behaviour introduced over a year ago in https://github.com/nicolaskruchten/pivottable/commit/2467d69953a442a11ab708447499792f74c601a7 :) They're running clean again now: https://pivottable.js.org/tests/

**Comment by jjagielka** [comment]
I thought I was doing something wrong with my modifications.
Currently I'm doing the equivalent of subtotal with only few changes in your code.
Check it out: https://github.com/jjagielka/pivottable
