### ISSUE TITLE
Browser crashing with 5000*5000 data points.

### ISSUE THREAD

**Issue by roopesh95** [nicolaskruchten/pivottable#1091]
I am using pivottable.js from long time, we are using pagination to show 100 records per page. For one specific need, we want to remove the pagination and want to show all the data. for 1000x1000 though its taking time we are able to see the data but when we move to 5000x5000 browser is crashing. Is there any way to show whole data may be by using lazy loading or something?

**Comment by nicolaskruchten** [comment]
This library is not designed to display 5k x 5k tables... That's 25 *million* cells. As I said in a previous issue (#599), if each cell was 1px by 1px, you would need a grid of 3 by 5 HDTVs to render it, and I just don't think that this kind of thing gives a reasonable user experience, so I'm not interested in supporting this use-case.

**Comment by jtrcarlos** [comment]
@roopesh95 how did you manage to add pagination? I´ve been trying to add it but without success so far.
