### ISSUE TITLE
Date Filter in Filter Result Area

### ISSUE THREAD

**Issue by jackiemanzzz** [nicolaskruchten/pivottable#1095]
Firstly, thank u for this amazing tool:) 

I have one problem about filtering data of which type is date. I didnt find a way to filter my date column with >, <, = these operators in filter result area. Is there any way to filter dynamically ?

My dates like this. format --> dd.mm.yyyy

![image](https://user-images.githubusercontent.com/47844848/54128621-8c4b5b80-441d-11e9-82e5-1dfe4c9d29aa.png)

**Comment by jackiemanzzz** [comment]
Is there anyone to suggest something?

**Comment by nicolaskruchten** [comment]
If you use ISO format like `2012-04-30` then you can use the builtin `>` and `<` operators.

**Comment by nicolaskruchten** [comment]
Alternatively, you can use `sorters` to build a sorting function that accepts your date format, and then the `<`/`>` operators will respect that.

For example in this page https://pivottable.js.org/examples/montreal_2014.html you can see that `<may` returns the appropriate months. Note that you can build a sorter that doesn't require enumeration of the values, the example there uses the handy shortcut of `sortAs` :)

![image](https://user-images.githubusercontent.com/203523/56760438-261a5e00-6769-11e9-881c-de826337bc92.png)

**Comment by jackiemanzzz** [comment]
Thank you for your respond. I cant change my date format because of my regional format. As a result, I made a little changes in pivot.js to fit my format.

**Comment by nicolaskruchten** [comment]
The sorters approach would work with your current format but if you have a workaround that’s good.
