### ISSUE TITLE
Unused items filters are applied to active dataset

### ISSUE THREAD

**Issue by buckelieg** [nicolaskruchten/pivottable#1102]
Whenever I choose any filters in an unused section they are affect main table.

**Comment by nicolaskruchten** [comment]
Yes, this is by design.

**Comment by buckelieg** [comment]
It might confuse end-user. Unused attributes implies by their name not to be taken into account in calculations.
Or I misunderstood something

**Comment by nicolaskruchten** [comment]
Thanks for the feedback! As far as I know it hasn't confused anyone else in the past, so I'm not that worried about it in the general case enough to want to change anything :)
