### ISSUE TITLE
Drag and Drop issue, when dragable element needs to scroll up.

### ISSUE THREAD

**Issue by FloPrey** [nicolaskruchten/pivottable#1104]
Hi, 
we have a minor but constant error when using the pivot table in a small div container.
As you can see in the gif attached, when the screen is too small for the pivot table, the dragged element needs to initiate a scrolling to the top. After this scrolling the drop area seems to be unavailable.
But once you hover over the first column again, the drop area seems to work again.
![pivot-table-drag-drop-issue](https://user-images.githubusercontent.com/6198742/55245890-62c76800-5244-11e9-9f55-7b78fa500582.gif)

You can try it on your own within this fiddle:
http://jsfiddle.net/gv9oc326/

I hope you could help us by either provide a fix or help us create a workaround for this.

Thanks in advance.

**Comment by nicolaskruchten** [comment]
Hmm, this works on on MacOS/Chrome... I think it's a jQueryUI/IE bug which I don't have any good recommendations on how to fix. Are you using the very latest versions of jQuery/jQueryUI?

**Comment by FloPrey** [comment]
You are right, we retested it on MacOs and there it works on Chrome/Firefox/Safari and on Windows it's also working with Firefox but not on Chrome nor IE. Pretty weird, but I guess you are right and it is some jQuery/jQueryUI bug. I try to update both and see if this will fix the issue.
Thank you very much!

**Comment by FloPrey** [comment]
I updated the versions and the bug still appears, I guess we just have to live with it as I don't see any other possible bug fix.
Therefore I will close this issue here.
