### ISSUE TITLE
Im not able to get the Aggregators or filter

### ISSUE THREAD

**Issue by santoshrnath** [nicolaskruchten/pivottable#1109]
![No Aggregators or filters](https://user-images.githubusercontent.com/34038160/56642122-d44dd700-6687-11e9-8776-b04496e7e2ab.PNG)

**Comment by nicolaskruchten** [comment]
Hmm, it seems like you have some CSS on the page which is hiding them!

**Comment by santoshrnath** [comment]
Awesome, Materilize CSS was actually hiding them. Thanks a lot. PivotTable JS is fantastic
