### ISSUE TITLE
Style change when using json with more than 10 elements

### ISSUE THREAD

**Issue by juliomorel** [nicolaskruchten/pivottable#1111]
When using this json, the pivot table changes its style putting the selectable elements vertically in a column, reducing the space for the table or chart. Here is json with 12 elements: **(Codigo,Nombre,Fecha Inicial,Fecha Final,Dias,Estado,Fecha Retorno,Periodo Tomado,Monto Sueldo,Provision Vacaciones,Base de Calculo)**
Grid ok

![grid_ok](https://user-images.githubusercontent.com/8481193/56819385-9b446c80-6817-11e9-8100-de2ed87c35b1.jpg)

Grid wrong
![grid_wrong](https://user-images.githubusercontent.com/8481193/56819405-a5666b00-6817-11e9-86b3-78b944be76c5.png)

If I use only 10 or less everything looks good. Any suggestions?

**Sample json:**

[{"Codigo":"      101014","Nombre":"YUPANQUI  MALLQUI,TEOFILO","Fecha Inicial":"16-07-2018","Fecha Final":"30-07-2018","Dias":15.00,"Estado":"Vacaciones Normales","Fecha Retorno":"31-07-2018","Periodo Tomado":"2013 - 2014         ","Monto Sueldo":1900.0000,"Provision Vacaciones":158.3300,"Base de Calculo":1900.0000},{"Codigo":"      101509","Nombre":"VALVERDE  FERNANDEZ,RONAL GENARO","Fecha Inicial":"30-07-2018","Fecha Final":"31-07-2018","Dias":2.00,"Estado":"Vacaciones Normales","Fecha Retorno":"01-08-2018","Periodo Tomado":"2002 - 2003         ","Monto Sueldo":2000.0000,"Provision Vacaciones":174.4200,"Base de Calculo":2093.0000},{"Codigo":"      102204","Nombre":"YUTCA  LOPEZ,JOSE ALFREDO","Fecha Inicial":"30-07-2018","Fecha Final":"31-07-2018","Dias":2.00,"Estado":"Vacaciones Normales","Fecha Retorno":"01-08-2018","Periodo Tomado":"2011 - 2012         ","Monto Sueldo":2300.0000,"Provision Vacaciones":199.4200,"Base de Calculo":2393.0000},{"Codigo":"      200454","Nombre":"ABANTO  TORIBIO,FERNANDO LEONCIO","Fecha Inicial":"16-07-2018","Fecha Final":"30-07-2018","Dias":15.00,"Estado":"Vacaciones Normales","Fecha Retorno":"31-07-2018","Periodo Tomado":"2007 - 2008         ","Monto Sueldo":4400.0000,"Provision Vacaciones":374.4200,"Base de Calculo":4493.0000},{"Codigo":"      200690","Nombre":"VENET  ---, DOMINIQUE RAYMOND PIERRE","Fecha Inicial":"01-07-2018","Fecha Final":"02-07-2018","Dias":2.00,"Estado":"Vacaciones Normales","Fecha Retorno":"03-07-2018","Periodo Tomado":"2015 - 2016         ","Monto Sueldo":40000.0000,"Provision Vacaciones":3341.0800,"Base de Calculo":40093.0000},{"Codigo":"      200751","Nombre":"ARANDA  SANCHEZ, LITA LILIANA           ","Fecha Inicial":"04-11-2018","Fecha Final":"02-12-2018","Dias":29.00,"Estado":"Vacaciones Normales","Fecha Retorno":"03-12-2018","Periodo Tomado":"0                   ","Monto Sueldo":4850.0000,"Provision Vacaciones":null,"Base de Calculo":null},{"Codigo":"      200784","Nombre":"ACOSTA  RAMOS, SAUL ERNESTO","Fecha Inicial":"10-11-2018","Fecha Final":"29-11-2018","Dias":20.00,"Estado":"Vacaciones Normales","Fecha Retorno":"30-11-2018","Periodo Tomado":"2017 - 2018         ","Monto Sueldo":2500.0000,"Provision Vacaciones":null,"Base de Calculo":null}]

**Comment by nicolaskruchten** [comment]
Yes, this is by design and there is an option to control if/when this happens. unusedAttrCutoff or something like that

**Comment by juliomorel** [comment]
Great! unusedAttrsVertical, set to False. I also add this to css: span.pvtAttr{display:inline-block;
That way, it wont exceed the length of the row, it will create another row.
Thank you very much.

**Comment by nicolaskruchten** [comment]
Great!
