### ISSUE TITLE
Include PivotTable.js in ethercalc

### ISSUE THREAD

**Issue by eddyparkinson** [nicolaskruchten/pivottable#1112]
Nicolaskruchten 
  I like your PivotTable.js 

 just cross posting this so you are aware of it.  

Someone suggested adding PivotTable.js to ethercalc:
  https://github.com/audreyt/ethercalc/issues/666

Ethercalc 
---

is a muti user, feature rich, open source, online spreadsheet, with UI formulas. 
 
   speadsheet -https://ethercalc.org/
   code -  https://github.com/audreyt/ethercalc/

**Comment by nicolaskruchten** [comment]
Cool, thanks for letting me know :)
