### ISSUE TITLE
How to categorize/group the field, if i have many fields?

### ISSUE THREAD

**Issue by ghaliarkan** [nicolaskruchten/pivottable#1140]
Hi @nicolaskruchten ,

Thanks for the awesome library.
I am having an issue about many fields that i have in my database. Can i categorize/group it? So it will help me to search the field that i need to process?

Any help will be appreciated.
Thanks

![pivottest](https://user-images.githubusercontent.com/33263116/62916367-580c0a80-bdc2-11e9-9eaa-55ee3ab735c0.png)

**Comment by nicolaskruchten** [comment]
Unfortunately there’s no feature for this at the moment and I can’t think of a simple workaround other than prefixing your field names and turning on sorting

**Comment by ghaliarkan** [comment]
Thank you sir, it totally help me a lot, keep doing great sir.
