### ISSUE TITLE
How to find out if pivot table is filtered?

### ISSUE THREAD

**Issue by uminder** [nicolaskruchten/pivottable#1144]
I'm using **pivottable.js** in the open source project project [Koia](https://github.com/centeractive/koia), thanks for sharing this amazing library!  

In my project, the [CellClickHandler ](https://github.com/centeractive/koia/blob/master/src/app/pivot-table/options/cell-click-handler.ts) class is responsible for showing a raw data dialog when the user clicks on a table cell. In order to query accurate data for total cells also, I need to know if the pivot table data has been filtered by the user.

Is there a way to automatically find out if the pivot table is currently filtered?

**Comment by mpf82** [comment]
I guess you could check the inclusions / exclusions of the config object, as demonstrated in this demo: https://pivottable.js.org/examples/onrefresh.html

**Comment by uminder** [comment]
Thanks [Mike ](https://github.com/mpf82), this is what I was looking for!
