### ISSUE TITLE
Showing PrivotUI() output like Pivot()

### ISSUE THREAD

**Issue by adispartadev** [nicolaskruchten/pivottable#1156]
Hey, thanks for making this awesome plugin. I need a help in showing my data in pivotUI style.
The data is just look like this:

```
[
  {
    "nama_kecamatan": "Gerokgak",
    "nama_kelurahan": "Sumber Klampok",
    "jenis": "hindu_pria",
    "jumlah": 23
  },
  {
    "nama_kecamatan": "Gerokgak",
    "nama_kelurahan": "Sumber Klampok",
    "jenis": "hindu_wanita",
    "jumlah": 24
  },
  {
    "nama_kecamatan": "Gerokgak",
    "nama_kelurahan": "Sumber Klampok",
    "jenis": "islam_pria",
    "jumlah": 25
  },
  ....
]
```

When I showing this data, it looks well when I using privot() on calling it. The output is like this:

![image](https://user-images.githubusercontent.com/16744864/65375709-280e2c00-dccb-11e9-8816-d69250bff7bd.png)

And calling it using this code:
```
$("#output").pivot(data, 
	{
        rows: ["nama_kelurahan"],
        cols: ["jenis"],
        aggregator: sum(intFormat)(["jumlah"])
    }
);
```

It just looks like what I want.

But the problem is, when I call it via privotUI(), the result is become like this:
![image](https://user-images.githubusercontent.com/16744864/65375752-76bbc600-dccb-11e9-91d5-a04aea66c8c3.png)

The value in each cell is not like what return when using privot() function. Is there any custom option to make my data just look like privot() function output when I call it using privotUI()? 

I need to show it just look like privot() but wanted your drag and drop feature like privotUI

Thanks in advance...

**Comment by adispartadev** [comment]
Thanks, my bad. Just realize it already yesterday. Did you know any option to make it default at the first load?

**Comment by nicolaskruchten** [comment]
Yes, you can control this with `aggregatorName` and `vals`... check out the `pivotUI()` docs here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by adispartadev** [comment]
It just like what I want now by using this code
```
$("#output").pivotUI(mps,
                    {
                        renderers: renderers,
                        aggregatorName : "Integer Sum",
                        vals : ["Jumlah"],
                        rows : ["Nama Kecamatan", "Nama Kelurahan"],
                        cols : ["Kategori"]
                    }, true
                );
```

And this is the result 
![image](https://user-images.githubusercontent.com/16744864/65832777-f57fb700-e2fa-11e9-8f93-9548d6f16681.png)

Thanks for your help @nicolaskruchten
