### ISSUE TITLE
Multiple numberformats in the same column?

### ISSUE THREAD

**Issue by Erik-2019** [nicolaskruchten/pivottable#1160]
I'm sorry if this was answered before but I wasn't able to find it. 

I'm getting data from a stored procedure that I have no control over. The columns have whole numbers and decimal numbers (percentages) intermixed. 

Is there a way to check the number for a decimal point and multiply it by 100 then add a %, if there is no decimal point just add the commas like normal? 

I have another question about formatting each column with a different numberformat, but I can create a new issue if needed.

Thank you for the great script.

**Comment by nicolaskruchten** [comment]
It should be possible for you to write a custom number formatter for this, yes.

**Comment by ilyaguy** [comment]
I've implemented my own aggregator.
It uses different format per row. And I use "format" subfield to define data format. It passed to getFormat function.
```
	function getFormat(short) {
		if (short == '%') {
			return $.pivotUtilities.numberFormat({ digitsAfterDecimal: 2, scaler: 100, suffix: "%" });
		}
		if (short == '$') {
			return $.pivotUtilities.numberFormat({prefix:'$'});
		}
		if (short == '#') {
			return $.pivotUtilities.numberFormat({digitsAfterDecimal: 0});
		}
		if (short == '$M') {
			return $.pivotUtilities.numberFormat({digitsAfterDecimal: 2, scaler: 1000, prefix: '$'});
		}
		return $.pivotUtilities.numberFormat();
	}

```

I had plans to improve this function to use row/column name: use last character as format description like "Users, #", "Profit, $", "KPI, %"

**Comment by Erik-2019** [comment]
Thank you guy, I was able to get it working. sorry it took me so long to get back to you.
