### ISSUE TITLE
sowUI parameter not working

### ISSUE THREAD

**Issue by franpic** [nicolaskruchten/pivottable#1180]
subtotal 1.11.0-alpha.0 - pivottable 2.23.0

Good morning,
the showUi parameter is not working

**Comment by nicolaskruchten** [comment]
Can you provide a codepen or jsfiddle showing the problem you’re seeing please?

**Comment by franpic** [comment]
Sure!
If you go to https://jsfiddle.net/073cdmqu/1/ and add the showUI parameter with the value "false" it doesn't produce any effect.

**Comment by nicolaskruchten** [comment]
This fiddle is using version 2.13.0 rather than 2.23.0 :)

**Comment by franpic** [comment]
Oh! I'm sorry for making you waste time. I was using the 2.19, in my local code ....
Many thanks for your wonderful work

**Comment by nicolaskruchten** [comment]
No worries! Glad it works :)
