### ISSUE TITLE
Redmine Version 4.1 (Seems wonderfull)

### ISSUE THREAD

**Issue by konpega** [nicolaskruchten/pivottable#1203]
Could you touch for 4.1 users? It is great work really. Could you support us?

**Comment by nicolaskruchten** [comment]
I'm glad you like this library! The Redmine plugin is actually maintained by someone else, I just look after the Javascript component. I would recommend you chat with the author of https://github.com/deecay/redmine_pivot_table

**Comment by konpega** [comment]
Thanks for the info.
