### ISSUE TITLE
Center align pivot table

### ISSUE THREAD

**Issue by len-ny** [nicolaskruchten/pivottable#1207]
How to align the table/chart to center screen horizontally? It is always left align.
I set margin to auto but it doesn't work:
```
<div id="output" style="margin:auto"></div>
	<script type="text/javascript">
	$(function () {
        $("#output").pivot(
                [
                    {color: "blue", shape: "circle"},
                    {color: "red", shape: "triangle"}
                ],
                {
                    rows: ["color"],
                    cols: ["shape"]
                }
            );	
</script>
```

**Comment by mpndang** [comment]
<center>

<div id="output" style="margin:auto"></div>
	<script type="text/javascript">
	$(function () {
        $("#output").pivot(
                [
                    {color: "blue", shape: "circle"},
                    {color: "red", shape: "triangle"}
                ],
                {
                    rows: ["color"],
                    cols: ["shape"]
                }
            );	
</script>

</center>

**Comment by len-ny** [comment]
I used this class & it works:

```
    .center-container {
	  display: flex;
	  justify-content: center;
	}
```

Thanks anyway.
