### ISSUE TITLE
Add formatting to renderers

### ISSUE THREAD

**Issue by HStuart18** [nicolaskruchten/pivottable#1209]
Hi,

Firstly, this tool is a lifesaver, so thanks! 

I know there are similar questions regarding formatting, but mine is specifically related to rendering. Say I have the 3 input cell values `1000`, `10000000` and `1000000000`. I would like to format them to `1K`, `10M` and `1B` respectively. However, it is important that I maintain their integer values for sorting, because ranking `1000`, `10000000` and `1000000000` by ascending order will yield a different final order than ranking by ascending order on `1K`, `10M` and `1B`. Thus, I cannot merely preprocess the cells.

Therefore, I need to apply this formatting during "render time". Any thoughts? Is there anything built-in? If not, what could a work around be?

Thanks!
Harry

**Comment by nicolaskruchten** [comment]
Yes, aggregators all have a `format()` method, and there is an existing `numberFormat` function you can look at for inspiration. You'll need to create a custom set of aggregators with your chosen number-formatting function similar to the built-in ones here which all use `usFmt`: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L155

**Comment by HStuart18** [comment]
I've had a look at the aggregator functions and formatting etc. However, I need this to work with renderers and NOT aggregators. In other words, I need to format the cells not in the aggregation column/s.

**Comment by nicolaskruchten** [comment]
You mean you want to control the label formatting within the row/cell header area? In this case, I would recommend preprocessing to get the display you want, and then user `sorters` to enforce the desired order.
