### ISSUE TITLE
Prevent one field from drag & drop.

### ISSUE THREAD

**Issue by len-ny** [nicolaskruchten/pivottable#1220]
By default a user can drag & drop fields/properties which are not belong to rows & cols. For example my codes as below, the "overdue" & "payment" will appear at the top drag & drop panel.

```
$(function(){

    var tpl = $.pivotUtilities.aggregatorTemplates;
    var numberFormat = $.pivotUtilities.numberFormat;
    var intFormat = numberFormat({digitsAfterDecimal: 0});

    $("#output").pivotUI(
        [
            {name: "bill", year: 2020, overdue: false, payment: 1800},
            {name: "bill", year: 2017, overdue: true, payment: 2000},
            {name: "steve", year: 2019, overdue: false, payment: 900},
            {name: "steve", year: 2020, overdue: false, payment: 780},
            {name: "donald", year: 2017, overdue: true, payment: 4}
        ],
        {
            rows: ["name"],
            cols: ["year"],
            aggregators: {
                "Payment": function() { return tpl.sum(intFormat)(['payment']) }
            },            
        }
    );
 });
```
Now I want to remove the "payment" from the top panel, in order to prevent it to be dropped to columns or rows. Is it possible?

![image](https://user-images.githubusercontent.com/43208828/86565551-9b530700-bf9a-11ea-8600-78f895e72582.png)

**Comment by nicolaskruchten** [comment]
Yes, check out the `hiddenFromDragDrop` configuration option: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

There is also `hiddenFromAggregators`

**Comment by len-ny** [comment]
Thank you.
