### ISSUE TITLE
How to hide dropdown panel Attributes

### ISSUE THREAD

**Issue by Dcoder30** [nicolaskruchten/pivottable#1248]
This is an awesome project!!Great work. 
I am new in Reactjs, I have used this library and i want to **hide Dropdown panel Attributes.**  I have used "hiddenFromAggregators" and "hiddenAttributes" but its not working. Is there any other methods?
If yes, Please let me know with example. 
![Screenshot (1)](https://user-images.githubusercontent.com/72870473/95993320-98469d00-0e4c-11eb-955b-5aba0ba28222.png)
![Screenshot (2)](https://user-images.githubusercontent.com/72870473/95999656-bbc11600-0e53-11eb-9d7d-7a570dcbb1aa.png)
Thank you.

**Comment by nicolaskruchten** [comment]
This is the aggregator dropdown, and it's populated from the `aggregators` argument :)

**Comment by Dcoder30** [comment]
ohh okay. Can we hide some aggregators. As i dont need (Table heatmap, Table Col Heatmap, etc. ) is there any methods?

**Comment by nicolaskruchten** [comment]
Yes, you provide a new list of aggregators you want.

**Comment by Dcoder30** [comment]
where  i have to taken new list? In which file? How to use it ? Can you give me example how to remove aggregators?

**Comment by Dcoder30** [comment]
any suggestions?

**Comment by Dcoder30** [comment]
> Yes, you provide a new list of aggregators you want.

Thank you so much for this , i have successfully run **aggregators** as i need.
