### ISSUE TITLE
pivot() working but calling pivotUI() gets an error

### ISSUE THREAD

**Issue by andy194** [nicolaskruchten/pivottable#125]
Hi,

I'm just reviewing this lib with a view to using it.  It's fine calling pivot() but when I use the pivotUI call, it stops with the following errors:-

<b>1st</b> - Exception was thrown at line 1147, column 7 in http://localhost:62045/Scripts/pivot.js

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'sortable'

<b>2nd</b> - Unhandled exception at line 1088, column 9 in http://localhost:62045/Scripts/pivot.js

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'null'

This is the page...

Script...

```
$(function(){
    $("#div1").pivotUI(
    [
        { color: "blue", shape: "circle" },
        { color: "blue", shape: "circle" },
        { color: "red", shape: "triangle" },
        { color: "red", shape: "triangle" },
        { color: "red", shape: "triangle" }
    ],
    {
        rows: ["color"],
        cols: ["shape"]
    }
);
});
```

div id="div1"
div

It's in MVC so the scripts are bundled as follows...

```
        bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                    "~/Scripts/jquery-{version}.js"));

        bundles.Add(new ScriptBundle("~/bundles/jqueryui").Include(
                    "~/Scripts/jquery-ui-{version}.js",
                    "~/Scripts/jquery-ui-1.9.2.custom.min.js"));

        bundles.Add(new ScriptBundle("~/bundles/jquerytables").Include(
                     "~/Scripts/jquery.dataTables*",
                     "~/Scripts/FixedColumns*",
                     "~/Scripts/pivot.js"
                     ));
```

**Comment by PagnaKong** [comment]
I got error too when calling privotUI(): "An error occurred rendering the PivotTable UI." Please help me!

**Comment by mtechmaths** [comment]
An error occurred rendering the PivotTable UI
Line 1354 in Pivot.js

**Comment by mtechmaths** [comment]
Solved error occurred rendering the PivotTable UI

I had the same issue when a page using the sortable() function was required by a main php page. Adding the following code within the head of the main page wasn't sufficient. Adding it also at the beginning of the required page (inside the body in my case) fixed everything.

<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

**Comment by nicolaskruchten** [comment]
@PagnaKong please don't ask for help on closed issue threads... If you're having a problem, please create a new issue and I'll see if I can help you. I will need more than just the generic error message, though!
