### ISSUE TITLE
Add API function to get PivotData object

### ISSUE THREAD

**Issue by dorthrithil** [nicolaskruchten/pivottable#1271]
I wrote an external custom renderer (for exporting as XLSX) which I want to trigger via a button outside of the table. My renderer function depends on the `PivotData` object. 
It would be nice if you could add an API function to get the current `PivotData` from. 
Or is there some recommended way to get it that I missed while reading the documentation?

**Comment by nicolaskruchten** [comment]
There's no easy way to access this object from outside... Your best bet would be to build a renderer that displays as the table plus the button, and then your renderer would get access to the PivotData object.

**Comment by dorthrithil** [comment]
Thanks Nicolas! I ended up doing exactly that.
