### ISSUE TITLE
How to show full texts?

### ISSUE THREAD

**Issue by ckarmy** [nicolaskruchten/pivottable#1300]
Its a very simple question... How can I display the full text in each cell? The library add "..." if the characters exceed 20 characters I think.
Like this:
<img width="595" alt="Screen Shot 2022-03-28 at 16 34 40" src="https://user-images.githubusercontent.com/10090783/160473393-53ea68f3-3956-4765-8558-32388a657c63.png">

And is posible to force the width to the 100%?

Thanks!

**Comment by nicolaskruchten** [comment]
There's nothing in this library that adds "...", no.

There's also no built-in feature for forcing the width to any given value, but you can likely do this in CSS.

**Comment by ckarmy** [comment]
Thanks! I will review my entire code for the "..."
