### ISSUE TITLE
The server side event during the drag and drop of the grouping and column element to filter the data.

### ISSUE THREAD

**Issue by Ekotenggara** [nicolaskruchten/pivottable#1302]
Hi,

We are currently using pivottable.jsx to do our data analysis tab.
Which works impressively very well, we cannot thank you enough :)

However our data is growing to few GBs, we need to be able to call some event in the server side to filter the data (or group the data) to help not to throw all the memory into the google chrome application memory. 

Is there anyway to fire the server side event during the drag and drop of the grouping and column element?

Thank you,

Eko

**Comment by nicolaskruchten** [comment]
Unfortunately this is not a feature of this library, no... See FAQ: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#server-side-integration

**Comment by Ekotenggara** [comment]
@nicolaskruchten Thank you for the clarification :)
