### ISSUE TITLE
colorScaleGenerator in heatmap for Python

### ISSUE THREAD

**Issue by umitsarioz** [nicolaskruchten/pivottable#1337]
Hi Nicolas! Thanks for your effort and this repo. I can not change heatmap color scale with **Python**. I read your documentation and tried renderers parameter. Renderers parameter for heatmap does not work for python i guess. (colorScaleGenerator) Does the repo have the capacity to do this job, with the renderers parameter etc.? I cannot actually, do you have any idea how can i achieve it?

**Comment by juanmantelli** [comment]
Can you share your code? 

 heatmap: {
        colorScaleGenerator: function(values) {
            return Plotly.d3.scale.linear()
                .domain([-100, -1, 0, 1, 200])
                .range(["#a0432c", "#a37265", "#dbdbdb", "#b0c67a", "#68c44f"]);
        }
    },
    
    that should work.

**Comment by umitsarioz** [comment]
Yes, of course. My code is like that:
```
import pandas as pd 
import pivottablejs

def pivot_ui(df, **kwargs):
    # Function redefine to remove null values in pivot table
    class _DataFrame(pd.DataFrame):
        def to_csv(self, **kwargs):
            return super().to_csv(**kwargs).replace("\r\n", "\n")
    return pivottablejs.pivot_ui(_DataFrame(df), **kwargs)


def main(src_filepath:str,dst_filepath="avg_price_pivot.html"):
    df = pd.read_csv(src_filepath) # read data as csv
    
    # convert to pivot and save it as html
    pivot_ui(df=df,
             rows=["Year"],
             cols=["Brand"],
             aggregatorName="Average",
             vals=["Price"],
             rendererName="Heatmap",
             hiddenFromDragDrop=["Price"],
             hiddenFromAggregators=[""],
             outfile_path=dst_filepath)
    print(f">> Pivot table created as {dst_filepath}")

# Run code
main(src_filepath="mini_train.csv")
```
And my data format is like that, a mini sample is below . After all, i want to change background of heatmap yellow to green instead of only red.

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th>Brand</th>      <th>Model</th>      <th>Year</th>      <th>Mileage</th>      <th>Price</th>    </tr>  </thead>  <tbody>    <tr>      <td>BMW</td>      <td>225</td>      <td>2004</td>      <td>190000</td>      <td>8467</td>    </tr>    <tr>      <td>BMW</td>      <td>528</td>      <td>2008</td>      <td>280000</td>      <td>17876</td>    </tr>    <tr>      <td>HYUNDAI</td>      <td>Tucson</td>      <td>2012</td>      <td>151995</td>      <td>24543</td>    </tr>    <tr>      <td>FORD</td>      <td>C-MAX</td>      <td>2013</td>      <td>74000</td>      <td>20385</td>    </tr>    <tr>      <td>HYUNDAI</td>      <td>Elantra</td>      <td>2011</td>      <td>137213</td>      <td>23239</td>    </tr>    <tr>      <td>HYUNDAI</td>      <td>Sonata</td>      <td>2016</td>      <td>240573</td>      <td>19914</td>    </tr>    <tr>      <td>HYUNDAI</td>      <td>H1</td>      <td>2008</td>      <td>234278</td>      <td>13589</td>    </tr>    <tr>      <td>MERCEDES-BENZ</td>      <td>E 350</td>      <td>2010</td>      <td>205968</td>      <td>1646</td>    </tr>    <tr>      <td>TOYOTA</td>      <td>CHR</td>      <td>2018</td>      <td>46733</td>      <td>549</td>    </tr>    <tr>      <td>MERCEDES-BENZ</td>      <td>Sprinter</td>      <td>2006</td>      <td>37440</td>      <td>35850</td>    </tr>  </tbody></table>

**Comment by umitsarioz** [comment]
solved with implemented js to generated html file with python.
