### ISSUE TITLE
Why not to display the "0"?

### ISSUE THREAD

**Issue by nocquidant** [nicolaskruchten/pivottable#139]
Why not to display the "0" in numberFormat?

```
 numberFormat = function(sigfig, scaler, thousandsSep, decimalSep) {
    ...
    return function(x) {
      // if (x === 0 || isNaN(x) || !isFinite(x)) {
      if (isNaN(x) || !isFinite(x)) {
        return "";
      } else {
        return addSeparators((scaler * x).toFixed(sigfig), thousandsSep, decimalSep);
      }
    };
  };
```

![capture](https://f.cloud.github.com/assets/217054/2399569/fe64994c-a9ff-11e3-9be5-3550bad858f4.PNG)

Thanks for your work!
++nick

**Comment by nicolaskruchten** [comment]
Updating an old issue: this aesthetic choice has been reversed, and zeros are always displayed now when there is data in the cell (i.e. 'count' will never show zero because there is nothing to count).
