### ISSUE TITLE
Styling Compatibility with Bootstrap 3.1

### ISSUE THREAD

**Issue by woozyking** [nicolaskruchten/pivottable#149]
Hi,

I tried to just drop in Bootstrap 3.1 with [this demo](http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html) and it instantly breaks the UI to nearly unusable. I noticed that there's a recent issue fixed regarding CSS extraction but cannot find any detailed guide/how-to on how to properly style it with given CSS framework such as Bootstrap.

The broken UI looks like this:
![screenshot from 2014-03-26 10 01 39](https://f.cloud.github.com/assets/2837532/2525473/1645e84a-b4f0-11e3-88ce-6a3840f3e72b.png)

**Comment by rkralston** [comment]
@woozyking or @nicolaskruchten if anyone has the calls for adding bootstrap, could you post them somewhere? Don't mind doing myself; prefer the more excellent work of others. ;-)

**Comment by woozyking** [comment]
@rkralston sorry I must admit that I haven't used this library for a long time. As far as I can remember though, after the change 6f6577a5bc05afc18d84fe6e9af2aaecedee663b, this has become as simple as just including bootstrap and then apply custom styles as needed. I don't think any special means of adding bootstrap other than 

```html
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<!-- and  -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js" integrity="sha384-u/bQvRA/1bobcXlcEYpsEdFVK/vJs3+T+nXLsBYJthmdBuavHvAW6UsmqO2Gd/F9" crossorigin="anonymous"></script>
```
