### ISSUE TITLE
Is it possible to disable Natural Sort for filterBox list?

### ISSUE THREAD

**Issue by faheydesign** [nicolaskruchten/pivottable#153]
How can we show the filterBox list exactly in the way that the data is passed to the pivot control rather than sorting the list alphabetically or numerically?

**Comment by nicolaskruchten** [comment]
see #236

**Comment by nicolaskruchten** [comment]
There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.
