### ISSUE TITLE
Close button on filter popup

### ISSUE THREAD

**Issue by sabas** [nicolaskruchten/pivottable#154]
If I click on the filter, and I change idea (I don't want to filter anymore) I must reload the pivot clicking ok for example.

The close button should:
-close the popup
-if I modified the filters don't apply the filter to the data. (only when clicking ok button)

**Comment by nicolaskruchten** [comment]
2.5 years later... I finally got around to implementing a proper 'cancel' button on the filter box :)

**Comment by sabas** [comment]
Thanks for the Christmas gift :-)
