### ISSUE TITLE
Using Google Chart/HighChart scatterplot

### ISSUE THREAD

**Issue by nascif** [nicolaskruchten/pivottable#160]
Hi Nicolas,

First of all, thanks for the awesome project, it is amazing how much functionality one can get out of it with very little setup. Well done!

I have a question about the Google Chart renderer. I noticed that I can double click on the chart to get a chart type selector, with a number of options in addition to the ones surfaced by default. I was able to use this method to convert a bar chart into a pie chart, for example.

But I can't use it to create a scatter plot. It complains about the data format, saying I need to supply two numeric columns - which I did, in all combinations I could thing of. Would you have any idea on why that could be happening?

It would be great if the scatter plot could be make a top level visualization (like the bar and line charts). The problem with this secondary selection method is that the pivottable will revert back to the primary chart type as soon as you make a change to any of the data role assignments.

Cheers,
  /Nascif

**Comment by shaminpola** [comment]
bluechips23,

Can you please tell me from where i will get  getChart method?

 var chartResults = getChart(chartType, dataArray, metaData);

thanks.

**Comment by nicolaskruchten** [comment]
I ended up building a Scatter Chart in both the Google Chart and C3 renderers. Feel free to check it out here: http://nicolas.kruchten.com/pivottable/examples/rcsvs.html
