### ISSUE TITLE
Sort vs Display of Values (Specifically Dates)

### ISSUE THREAD

**Issue by programmernathan** [nicolaskruchten/pivottable#184]
I may have figured out a way you may be able to take care of the sort vs display that may fit within your paradigm and also may even help to add some interactivity.

This is a mock-up to see if it would work and my javascript is a bit rusty right now, so the code is a bit rough.
I am sure someone with your remarkable skill can make the code cleaner.

I added a dictionary called onDisplayDictionary to the renderOptions so that it passes through the pivot and pivotUI to the renderer

```
pivotTableRenderer = function(pivotData, opts) {
    var aggregator, c, colAttrs, colKey, colKeys, defaults, i, j, r, result, rowAttrs, rowKey, rowKeys, spanSize, td, th, totalAggregator, tr, txt, val, x;
    defaults = {
      localeStrings: {
          totals: "Totals",
      },
        onDisplayDictionary: {}
    };
```
I added a test to check if there is an entry in the Renderer for the attr and to use it if there is one..
You may notice I used innerHTML, this was a test to see if I could get interaction with it.

```
          if (!(opts.onDisplayDictionary)) {
              th.textContent = colKey[j];
          }
          else {
              if (opts.onDisplayDictionary[colAttrs[j]]) {
                  th.innerHTML = opts.onDisplayDictionary[colAttrs[j]](colKey[j]);
              }
              else {
                  th.textContent = colKey[j];
              }
          }
```

I then pass it a function to use on the display/render that won't impact the sorting.

```
        ETAFunction = function (value){
                if (Date.parse(value)){
                    var d1 = Date.parse(value);
                    return '<a onClick="alert(\'test\');">' + d1.toString("MMMM-dd") + '</a>';
                }

                return value;
        };

        onDisplayDict=
            {
                "ETA" : ETAFunction
            };

        options = {
            rows: ["City"],
            cols: ["ETA"],
            onRefresh: function () {
                options.rows = this.rows;
                options.cols = this.cols;
            }
            ,
            rendererOptions: {
                onDisplayDictionary: onDisplayDict
            }
        };
```

This way the data can be sortable and you can still get a nice customizable format on the table.
What do you think?

![ondisplaydictionary](https://cloud.githubusercontent.com/assets/2225461/3621448/bbdfa8d4-0e16-11e4-8242-449c09aceea4.jpg)

I was also thinking about trying a special dictionary item for an OnDisplay for the value cells or add another OnDisplayValue to be able to format and add interactive elements to value cells..

I plan to use this for a project of mine and really appreciate your work.

Thanks

**Comment by nicolaskruchten** [comment]
Related to #236

**Comment by nicolaskruchten** [comment]
I ended up solving this problem in the opposite way: the output is displayed just like the input but you can selectively override the sorting.

There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.
