### ISSUE TITLE
Pre-select pivotui row/col values

### ISSUE THREAD

**Issue by vz28bh** [nicolaskruchten/pivottable#192]
My apologies if this feature exists but I have not found it in the documentation. I would like to be able to preselect the values in a row or column attributes drop downs. For example, if one of the attributes is "color" and the options are red, white, and blue, I would like to be able to have only red selected at initial display of the pivot table. I am already using the parameters 'rows' and 'cols' to preselect which attributes to initially use in the pivot. Thanks

**Comment by luxystech** [comment]
Hello.
We have a pivot table for row value each question and answer, like this:
Date, Quesiton, Answer  
Where Answer is a group_concat value from SQL using , separator. 

Currently our pivot understand for question with answers: 
- YES, MAY BE 
- YES
- NO, MAY BE

as a different answer. Is it possible to aggregate answer one by one, just say 2 YES, 2 MAY BE and 1 NO. And we need to keep one row for one question. 

Any advice will be very appreciated.
