### ISSUE TITLE
Adding C3 render

### ISSUE THREAD

**Issue by nitinuttarwar** [nicolaskruchten/pivottable#193]
we can Add D3charts and google chart in pivot.js using D3 renderers and gChart rederers. Is there is any functionality to add C3 charts which are reusable charts.and data handling is done using Json data.

**Comment by nicolaskruchten** [comment]
Partial support implemented here: http://nicolas.kruchten.com/pivottable/examples/c3.html

**Comment by nitinuttarwar** [comment]
Thanks for supporting c3 charts in pivottable (y)

**Comment by nicolaskruchten** [comment]
C3 charts are now fully supported.

**Comment by nitinuttarwar** [comment]
You can also add c3 pie chart,c3 donut chart,c3 step chart
