### ISSUE TITLE
Question about date-time values helper

### ISSUE THREAD

**Issue by deeciple** [nicolaskruchten/pivottable#195]
Greetings and thank you for your excellent work.  This is very useful.  

I have a question about the proper use of the date-time values helper.  Under my derivedAttributes: {}, parameter I have coded 
"Month": derivers.bin("Month","%n"),
but when my chart loads up I have NaN instead of month names and there is only one series (like all the months are being grouped together).  

The values I have in my source table for my months are only the month numbers.  Can you offer any help as to the correct way to get the month names from the numbers?

UPDATE:
I was able to get the month names by creating this function:
      "Month Name": function(rows) {
        var mths=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"];
        var datestr = rows["Month"];
        var monthNum = Number(datestr.split("-")[1]);
        return mths[monthNum-1];
      }
I changed the values in my source table to the actual time stamps, example:
2014-05-05 15:38:49

But now the months are sorting alphabetically :(  Is there a way to do this with your helper and using the timesatmp?
Thanks in advance!

Ken

**Comment by nicolaskruchten** [comment]
There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.
