### ISSUE TITLE
ChartJS rendering support

### ISSUE THREAD

**Issue by deadserious** [nicolaskruchten/pivottable#200]
I'd love to see a renderer for ChartJS (http://www.chartjs.org/ ). Has anyone worked on such a thing or is it in the works?

**Comment by LittleHamster** [comment]
I am bringing this up from dead but has anyone implemented chartjs and is willing to share ?

**Comment by LittleHamster** [comment]
@nicolaskruchten 
if you can implement this whenever you feel like it that would be great :) 
...if you feel like it :)
