### ISSUE TITLE
How to specify only some aggregators and Translation Issue

### ISSUE THREAD

**Issue by raaffaaeell** [nicolaskruchten/pivottable#202]
Hello there, first of all, thank you very much, this library rules.

I was trying to translate what is possible, like the french example, I even achieved it, but if I specify the renderers or aggregators, I don't get them translated, hope you can help me.

This would work here

```
        $(function(){
            var derivers = $.pivotUtilities.derivers;

            $.getJSON("mps.json", function(mps) {
                $("#output").pivotUI(mps, {}, false, "br");
            });
         });
```

But if I try to specify the aggregators or renderers like this

```
        $(function(){
            var derivers = $.pivotUtilities.derivers;
            var renderers = $.extend($.pivotUtilities.renderers, $.pivotUtilities.gchart_renderers);

            $.getJSON("mps.json", function(mps) {
                $("#output").pivotUI(mps, {renderers: renderers}, false, "br");
            });
         });
```

It doesn't translate the renderers. Am I doing something wrong ?

<strike>Also, is there a way to specify only some aggregators ? For the beggning I'ld need only some more common/simple, e.g: Count, Sum only.</strike>

Cheers and thanks in advance.

**Comment by EmilMoe** [comment]
I'm confused.

I tried to follow the steps here, but I get `Uncaught TypeError: I.aggregators[l.val(...)] is not a function`

~~~~
var derivers  = $.pivotUtilities.derivers;
var renderers = $.extend($.pivotUtilities.renderers, $.pivotUtilities.gchart_renderers, $.pivotUtilities.export_renderers, $.pivotUtilities.locales["da"].renderers);
var aggregators = $.extend($.pivotUtilities.locales["da"].aggregators);

$('#pivot').pivotUI(pivotData, $.extend(
    {
        aggregators : aggregators,
        renderers: renderers,
        derivedAttributes: {
            "Hours Bin": derivers.bin("Hours", 50)
        }
    }
), false, "da");

**Comment by Ahmetgnczl** [comment]
Hi
How can I resolve such a screen output while I am running

![screencapture-localhost-56110-container-monthlystockreport-1519656744435](https://user-images.githubusercontent.com/36701116/36676943-01f1e626-1b1e-11e8-9565-8804936d57a2.png)

` $("#output").pivotUI(
                            result_parse,
                            {
                                aggregators: $.pivotUtilities.locales["tr"].aggregators,
                                cols: ["Unvani", "Rejimi", "BosDolu"]
                            },
                    false,
                    "tr"
                );`

**Comment by nicolaskruchten** [comment]
@Ahmetgnczl please do not post unrelated comments to closed issues :)

I'll respond to you in the other issue you created #874

**Comment by jonny64** [comment]
run into same thing
so, I need to specify
var renderers = $.extend($.pivotUtilities.locales["ru"].renderers,
                $.pivotUtilities.c3_renderers,
                custom_renderers);
and then to translate every renderer (including c3 ones) in pivot.ru.js?
