### ISSUE TITLE
Printing googlecharts

### ISSUE THREAD

**Issue by raaffaaeell** [nicolaskruchten/pivottable#204]
Is there any way to get something similar to <a href="https://developers.google.com/chart/interactive/docs/printing">this</a> to work ?

I used an ID to the div container that the chart is created, but I don't know how to save the reference of the chart created and then getImageURI()

I think that if I could get the reference of the chart I could use a button to print it.

Cheers

**Comment by deeciple** [comment]
raaffaaeell,

Sorry to revive an almost 1 year old thread but how exactly did you create the wrapper?  I've been struggling with a way to save the chart as a png file for a couple of days now.  I had it working before google changed their API.

How did you get it working?

Thanks,

Ken

**Comment by hissingpanda** [comment]
I just threw raaffaaeell's code into the gchart_renders.js file (line 151 in recent versions):

        resultPrint = $("< div id='printGraph '>"); // line 151
        wrapper = new google.visualization.ChartWrapper({
          dataTable: dataTable,
          chartType: chartType,
          options: options
        });
        //adds the listener to execute the function when the graph is ready
        google.visualization.events.addListener(wrapper, 'ready', onReady);

        //the actual code for the onReady function
        function onReady() {
              resultPrint[0].innerHTML = '<p><center><a href="' + wrapper.getChart().getImageURI() + '" download="Graph.png">Download Graph</a><center></p>';
              result.append(resultPrint[0].innerHTML);
        }

The "wrapper = new google.visualization.ChartWrapper" should already be in the file in case your line numbers are different. Anyways, that works for me.

**Comment by deeciple** [comment]
Hi hissingpanda,

I was trying to create a function on the page where my chart is being rendered that I could call via a button's click event.  I was under the mistaken impression that in his second post raaffaaeell was adding his code to another file.  I didn't realize that he was modifying the gcharts_renderer.js file all along.

I will add raaffaaeell's code into my gcharts_renderer.js.  It should work just fine.  

Thanks for your help.

Ken

**Comment by deeciple** [comment]
I was able to create a download button with the use of this function:
http://danml.com/#/download.html

First modifying the gcharts_renderer.js file as follows after line 156:

        // Wait for the chart to finish drawing before calling the getImageURI() method.
        google.visualization.events.addListener(wrapper, 'ready', function () {
			imgData = "<div id='image' style='display:none'>" + wrapper.getChart().getImageURI() + "</div>";
          	result.append(imgData);          
        });

Then on the page where I am injecting my chart I link the function:
    
    <script type="text/javascript" src="../javascripts/download.js"></script>

and add this code which is called by a button onclick event:

    function saveImage(){
	    var imgData = document.getElementById('image').innerHTML;
        download(imgData, "chart.png", "image/png");
    }

Hope this helps.

Ken
