### ISSUE TITLE
Group dates to weeks, monts, Quarters and Years

### ISSUE THREAD

**Issue by Geerten** [nicolaskruchten/pivottable#212]
Hi Nicolas,

Is it possible to group dates to weeks, monts, Quarters and Years? We are looking into using your excellent pivot tool to show sales data based on order dates, but of course it would be great if dates could be grouped. Did you include any functionality to do this?

Cheers,
Geerten

**Comment by clarako** [comment]
hi @nicolaskruchten,
How do you group by weeks using the dateFormat deriver?
Thanks,
Clara
