### ISSUE TITLE
Linkable/Addressable Configurations

### ISSUE THREAD

**Issue by psychemedia** [nicolaskruchten/pivottable#220]
Is it possible to generate a javascript link that will configure the table as required?

For example, for a table with columns A,B,C, something like:

`javascript:configTable( rows=['A'], topCols=['C'], bottomCols=['B'] )`

or 

`javascript:configTable( rows=['A','B'], topCols=['C'] )`

The idea is to be able to have a web page containing links to different configuration views of the pivot table, rather than requiring the user to know what to put where for a particular report.

From this, it might also be useful to define the group operator:

`javascript:configTable( rows=['A','B'], topCols=['C'], groupOp="Sum", groupRange="C", view="Table" )`

**Comment by tonyfast** [comment]
@nicolaskruchten Pivottable is really cool!

I wanted to riff off of this issue and make pivot table live on [nbviewer](http://nbviewer.ipython.org/gist/tonyfast/77df79d7adacc1bb6ec5).  I figured I would share.

**Comment by nicolaskruchten** [comment]
Cool! I recently created this package as well, to make this kind of thing easier: https://pypi.python.org/pypi/pivottablejs (demo can be found here: https://www.youtube.com/watch?v=ZbrRrXiWBKc )
