### ISSUE TITLE
Set default aggregator on creation at pivot() method

### ISSUE THREAD

**Issue by cristoffersantoro** [nicolaskruchten/pivottable#230]
How do I set an aggregator just like List Unique Items in this situation:

$("#output").pivot(
    [
        {color: "blue", shape: "circle"},
        {color: "red", shape: "triangle"}
    ],
    {
        rows: ["color"],
        cols: ["shape"]
    }
);

**Comment by alanKhosro** [comment]
I read the documentation. It is quite common to have sum (as the default aggregator) and "value" as the vals but it seems impossible to change the default from count()() to sum(["value"]).
I can define a custom function but then it is the only function that pivottable shows. How can I change default aggregator from count()() to sum(["value"])?
BTW, thank you for very useful pivottable tool.

**Comment by nicolaskruchten** [comment]
@alanKhosro please create a new issue and I'd be happy to help you! Commenting on old issues like this creates unnecessary and unwelcome notifications for previous issue participants :)
