### ISSUE TITLE
get col , row chose by user

### ISSUE THREAD

**Issue by bennnnnnn** [nicolaskruchten/pivottable#231]
hello

it is possible to know col and row  chose by user
used : rowname1 then rowname2
not used rowname3

used : colname1
not used colname2

i want to save it with cookie in order to reload the same table next time the user come again

thx

**Comment by ramasamynk** [comment]
hi,
I have used the below code to save the cols and row of pivot table, but it not working for me.

$.getJSON("mps.json", function(mps) {
                    $("#output").pivotUI(mps, {
                        derivedAttributes: {
                            "Age Bin": derivers.bin("Age", 10),
                            "Gender Imbalance": function(mp) {
                                return mp["Gender"] == "Male" ? 1 : -1;
                            }
                        },
						onRefresh: function (pivotUIOptions)
						{
						createCookie( "pivotcols" , pivotUIOptions["cols"] , 50);
						createCookie( "pivotrows" , pivotUIOptions["rows"] , 50);
						},
						rows: readCookie("pivotrows"),
						cols: readCookie("pivotcols")						
                    });
                });

thanks

**Comment by nicolaskruchten** [comment]
Hi @ramasamynk 

Please create a new issue for this question so that we may discuss in more detail.

Nicolas

**Comment by ramasamynk** [comment]
ok i will create.
