### ISSUE TITLE
"replace sort function" functionality

### ISSUE THREAD

**Issue by hoyeol** [nicolaskruchten/pivottable#236]
according pivot.coffee, there naturalSort defined "case-insensitive".
sometimes, does not want to use "default" natural sort function when viewing there pivot data. (e.g "case-sensitive" sorting applied to pivot data...)
but it seems no mechanism replace(or override) sort function... at client side.

**Comment by nicolaskruchten** [comment]
There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.
