### ISSUE TITLE
How to ignore Auto or Natural Sorting

### ISSUE THREAD

**Issue by srikanthj09** [nicolaskruchten/pivottable#245]
HI,
How to ignore the Sorting while adding or inserting to the X or Y axis,
I needed Y axis to be as is ( example:- sizes in cols should show "XXS, S, M, L ,XL, XXL, XXL).
I am not able to achieve this.

Can u please help me out in this.

Thanks For this Tool

**Comment by nicolaskruchten** [comment]
There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.
