### ISSUE TITLE
Firefox print table bug -> missing HTML tags

### ISSUE THREAD

**Issue by widdi** [nicolaskruchten/pivottable#248]
Hi,
I encountered a problem trying to print (or print preview) a pivot table. On most tables of my database it works fine, but on one particular table the firefox print functionality hides parts of it.

Details on my pivottables:
I'm using the following Pivotatbles libraries d3_renderers.js,  gchart_renderers.js and pivot.js  (all downloaded on July 24th 2014).
I use the following code to call the pivot table with ui:

``` javascript
 var options = {
        rows: defaultRowsNames,
        cols: defaultColsNames,
        vals: defaultValuesNames,
        rendererName: defaultRenderer
        // although the use of google charts would require an extension of the standard renderers
        // with google renderers here in the options, we must not do this here, because we already
        // did that in our localization library pivotables.DATE.pivot.de.js.view
    }

    data.unshift(columnNames);

    if (<%= $usePivotUI %>) {
        options.aggregatorName = defaultAggregator;
        options.menuLimit = 500;
        $("#table-view").pivotUI(data, options, false, "de");
    } 

```

As I mentioned above, around 20 other tables are shown/printed fine this way, but one isn't. The table itself is nothing special, its not the longest (around 100 rows, 4 columns, using sum aggregator).

So my first thought was this is a Firefox bug (since it works fine on Safari and Chrome) and I can do nothing about it, but then I noticed a little suspicious detail: 
Using the Firefox developer tools I saw the following in your pivot tables' HTML:

``` html
<table class="tbg" id="table-view" cellpadding="0" cellspacing="0" border="0">
    <table cellpadding="5">
        <tbody>
            <tr>
                <td>
                    ...
                </td>
            </tr>
        </tbody>
    </table>
</table>
```

So your using neste table tags and I wondered if this might be the problem, so I added the tbody, tr and td tags for the first table tag manually getting

``` html
<table class="tbg" id="table-view" cellpadding="0" cellspacing="0" border="0">
   <tbody>
      <tr>
         <td>
            <table cellpadding="5">
               <tbody>
                  <tr>
                     <td>
                        ...
                     </td>
                  </tr>
               </tbody> 
            </table>
         </td>
      </tr>
   </tbody>
</table>
```

and it worked fine!

That's why I'm writting this to you. It seems Firefox's print functionality needs the additional tags to work properly in every case. So would you please add them to your pivot tables tool?
Or maybe you have an idea how to fix my problem another way.

It's not very urgent, but I want to fix that bug. It haunts my dreams ;-)

Greetings,
widdi

**Comment by jobinspr** [comment]
this issue still exists on the firefox 98 version
