### ISSUE TITLE
Show empty derived attributes values

### ISSUE THREAD

**Issue by ni-ka** [nicolaskruchten/pivottable#249]
Hey,

thanks for this great plugin! I am using derived attributes to pivot data over time. Unfortunately, some hours do not contain data, and those entries are skipped from the output. However, I want them to appear as zeros so that my graphs show the drops to 0.

I've tried the showZero param of numberFormat but that seems to be something else.

For example, no data for 19h00-19h59 (row is missing)

![screen shot 2014-11-27 at 23 20 55](https://cloud.githubusercontent.com/assets/1225776/5222385/645d4bbe-768c-11e4-9e57-fd89015e0225.png)

Thanks

**Comment by capesean** [comment]
Is there an example of how to use the showZero option? I'm trying to get the pivottable to show the zeros instead of blanks. I'm not sure where to put the `showZero = true` option though.

**Comment by nicolaskruchten** [comment]
You'll need to create a custom set of aggregators with a different numberFormatter, similar to localizing to a different locale: https://github.com/nicolaskruchten/pivottable/wiki/Localization

**Comment by sogol-kh** [comment]
Hi, 
I want to have a age filter (Derived attributes) so I created function for it as you can see below but the point is I want it to show all filters even if there is no input for it . 
"age filter": function(mp) {
                                if(mp["age"] > 65){
                                    return "Age > 65";
                                } else if (19 < mp["age"] < 65){
                                    return "19 < Age < 65";
                                } else if (19 > mp["age"]){
                                    return "19 > Age";
                                }
                            }
What I have now is : 
![screen shot 2015-04-21 at 2 00 52 pm](https://cloud.githubusercontent.com/assets/10942682/7259165/76d8902c-e82f-11e4-9586-0dd9adc55e92.png)

but I want to have something like this also : age < 19 (0)

Thanks

**Comment by nicolaskruchten** [comment]
This is not going to be possible: if you have no matching rows in your input, the UI has no way of knowing what to display.

**Comment by diegobill** [comment]
I have the same problem reported by @ni-ka , any workaround solution for this?
