### ISSUE TITLE
Expand/Collapse Fields

### ISSUE THREAD

**Issue by rafaels86** [nicolaskruchten/pivottable#25]
Good morning Nicolas, i'm using this tool and it is so interesting. But miss a resource of expand or collapse a cell like occurs in microsoft excel. Do you intend to develop this? Or is this already exists?
Sorry for my english.
Rafael

**Comment by nagarajanchinnasamy** [comment]
![pivottablerollupsummary](https://cloud.githubusercontent.com/assets/1784880/13555708/b5fcbd4a-e3ed-11e5-8aaf-2a4ddafb3565.png)
@nicolaskruchten, Thanks a lot for such a useful library.

I have added the support for roll-up summary (sub-total rows) using aggregators and renderer concepts . Its available at [OnFieldClick branch of the fork that I have made](https://github.com/nagarajanchinnasamy/pivottable)

Would like to receive your comments/feedback from friends here before I send the pull request. I plan to add collapse-and-expand feature on top of this. Thanks.

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten , friends... I have further enhanced subtotal_renderers with **both row-wise and column-wise subtotals**. Also added **Collapse/Expand functionality for rows**. Collapse/Expand for column subtotals is under construction....

Please check [Subtotals branch](https://github.com/nagarajanchinnasamy/pivottable/tree/SubTotals). and provide your feedback. Steps to use:

1. Download pivottable-Subtotals.zip
2. Extract and place pivottable and its subfolders under document root of your local webserver
3. Access the demo using url: http://localhost/pivottable/examples/subtotal.html

Sample screenshot:
![pivotrowcolumnsubtotal](https://cloud.githubusercontent.com/assets/1784880/14060501/8ca879d0-f38c-11e5-93cc-3813c064a186.png)

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten and friends, happy to inform you that [Subtotal.js](http://nagarajanchinnasamy.com/subtotal) is available for download as an NPM module or Bower component.

[Subtotal.js](http://nagarajanchinnasamy.com/subtotal) is hosted in GitHub as [pivottable-subtotal-renderer](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer.git)

@nicolaskruchten , In setting up [Subtotal.js](http://nagarajanchinnasamy.com/subtotal), I have shamelessly copied the structure, style and some portions of text and code as is from Pivottable.js repository. Hope you don't mind.

Thanks again to all of you for your feedback and support :+1:

**Comment by nicolaskruchten** [comment]
All right, I think we can finally consider this issue resolved! The [official answer in the FAQ](https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#subtotals) is now "use [Subtotal.js](http://nagarajanchinnasamy.com/subtotal/examples/)" :)

**Comment by kalimuthu123** [comment]
onrefresh in collapse

**Comment by james1293** [comment]
@kalimuthu123 probably create an issue in the [subtotal repo](https://github.com/nagarajanchinnasamy/subtotal/issues). 🙂
