### ISSUE TITLE
how to show two fields aggregation at the same pivot ???

### ISSUE THREAD

**Issue by kumar31rajesh** [nicolaskruchten/pivottable#259]
Hi Nicolas,
 I want to show two fields aggregations at the same time.For example i want to show average of salary as one column and sum of childrens as another column for names in row Just like microsoft excel did .your library provide only single field aggregation at one time is it possible to do for more then one fields.

**Comment by thearyoun** [comment]
Hello Nicolas,

I have one problem with pivot table js. I want to change aggregation count to Integer Sum, how can i do it? Please let me know.

**Comment by nicolaskruchten** [comment]
@thearyoun please open a different issue rather than commenting on an unrelated one.

**Comment by nicolaskruchten** [comment]
(closing as duplicate)

**Comment by shiva659** [comment]
Hy, I am also trying for the two fields aggregator, Please let me know if anyone success doing this.

**Comment by ariouche** [comment]
Hi, does this feature available?
I'm looking to compare multiple columns and multiple calculation?
Thanks
