### ISSUE TITLE
Subtotals

### ISSUE THREAD

**Issue by rafaels86** [nicolaskruchten/pivottable#26]
Is there a way to create subtotals on rows and columns when exists more than one field in each axis?

Rafael

**Comment by anandakumarramaswamy** [comment]
hi nicolas great work done by you..:)
 i need subtotals concept in that pivot table..is there any progress in it..?if it means please let me know nicolas ..:)

**Comment by nicolaskruchten** [comment]
I'm not actively working on this feature, no.

**Comment by hazwanfowzi** [comment]
anyone done this feature? 
i can managed do for first level, but next level,i cant . :(

**Comment by onetwothere** [comment]
anyone manage to do this? :)

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten, Thanks a lot for such a useful library.

I have added the support for roll-up summary (sub-total rows) using aggregators and renderer concepts . Its available at [OnFieldClick branch of the fork that I have made](https://github.com/nagarajanchinnasamy/pivottable)

Would like to receive your comments/feedback from friends here before I send the pull request. I plan to add collapse-and-expand feature on top of this. Thanks.

**Comment by anandakumarramaswamy** [comment]
goooood work Nagaraj :)

**Comment by vivianjayakaran** [comment]
@nagarajanchinnasamy do you have a sample of how to use your SubTotals branch. Are there any settings to turn it on or off?

**Comment by nagarajanchinnasamy** [comment]
@vivianjayakaran there are no settings as of now... its directly built into the code. You can try any of the pivot or pivotUI examples... you will get to see them with new summary (sub-total) rows.

**Comment by nicolaskruchten** [comment]
@nagarajanchinnasamy thanks for this contribution!

My feedback is as follows:

1. I don't wish to add subtotals to the main Table renderer, so I would ask that any PR you submit contains a new renderer in a new file.
2. I understand that enabling subtotals requires some changes to the `PivotData` class, so these are the changes that are of greatest interest to me. I will need to take some time to carefully read through the changes you made. I notice that you've modified the most performance-sensitive part of the `PivotData` class (this bit with the "tight loop" comment) so this will require a bit of performance-testing on very large datasets as well.

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten Thanks for your feedback.

1. I've made a new commit [to the SubTotals branch](https://github.com/nagarajanchinnasamy/pivottable/tree/SubTotals) with `subtotal_renderers.coffee` added. Name of the renderers is: `subtotal_renderers`.
2. Added a new example subtotal.html to demo the `subtotal_renderers`

Pls check and let me know your feedback

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten , friends... I have further enhanced subtotal_renderers with **both row-wise and column-wise subtotals**. Also added **Collapse/Expand functionality for rows**. Collapse/Expand for column subtotals is under construction....

Please check [Subtotals branch](https://github.com/nagarajanchinnasamy/pivottable/tree/SubTotals). and provide your feedback. Steps to use:

1. Download pivottable-Subtotals.zip
2. Extract and place pivottable and its subfolders under document root of your local webserver
3. Access the demo using url: http://localhost/pivottable/examples/subtotal.html

Sample screenshot:
![pivotrowcolumnsubtotal](https://cloud.githubusercontent.com/assets/1784880/14060501/8ca879d0-f38c-11e5-93cc-3813c064a186.png)

**Comment by ahmad003** [comment]
@nagarajanchinnasamy There is an error in computation of "Sum as Fraction of Rows" and "Count as Fraction of Rows". Do you know how to correct this?

**Comment by ahmad003** [comment]
I think the "Totals" of Subtotals don't include in computation element in aggregator "fraction Of", cause i check the subtotal Alberta don't divided with itself but with subtotal of NDP in Quebec, etc... etc...

**Comment by ahmad003** [comment]
Ups sorry, not subtotal "Alberta" but subtotal "Female"... subtotal "Alberta" divided by subtotal "conservative"...

**Comment by nagarajanchinnasamy** [comment]
@ahmad003  Thanks for the feedback... I will look into this issue and get back. Thanks again.

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 I do not see any issue with the aggregators. For e.g., in the picture shown below, after selecting **Sum as Fraction of Total** and **Age**, the overall total is 15603 and for **Females in Age Bin 60**, the subtotal value is 883. Converting this to percentage ((883/15603)*100)) yields 5.7% as shown rightly in the pivot. Or, am I missing something? Please confirm.
 
![image](https://cloud.githubusercontent.com/assets/1784880/14228769/1e5a1856-f93d-11e5-97e6-7b68006e6a61.png)

**Comment by ahmad003** [comment]
Thank you @nagarajanchinnasamy for reply my question... And, yes, for **Sum as Fraction of Total** there is no error, but if you use **Sum as Fraction of Rows**, you will see there is an error like this...
![screenshoot](https://cloud.githubusercontent.com/assets/18167434/14238225/6adcdbfc-fa58-11e5-85f4-5018f9ed742e.jpg)

**Comment by ahmad003** [comment]
And if you continue to make **subtotals for column**, most likely there will be an error in  **Sum as Fraction of Columns**... Thank you once again for fast reply... I hope this will help you in developing this project...

**Comment by ahmad003** [comment]
If you see the image bellow, the result of **Sum as Fraction of Rows** for **subtotal Alberta** is divided by total of **Conservative in Alberta**... (240/180)*100 = 133.3... When i check the result of **Sum as Fraction of Rows** for **Female **, it divided by total of **NDP in Quebec**.

![screenshoot2](https://cloud.githubusercontent.com/assets/18167434/14238320/e959159e-fa59-11e5-93e8-ef882fbf15f7.jpg)

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 , Yes... I see the issue now. Let me check and get back to you. Thanks for clarification.

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 the issues is fixed now in both **as Fraction of Rows** and **as Fraction of Columns** 

Please check-out the latest version from [SubTotals Branch](https://github.com/nagarajanchinnasamy/pivottable/tree/SubTotals)

Thanks again for your feedback.

**Comment by ahmad003** [comment]
Thank you once again @nagarajanchinnasamy... You're Awesome... For my reference, is there a way to make default expand/collapse to expand,.. And for future development, I think it's necessary to make tool to **expand/collapse all rows**, to **hide/show subtotals** for **row** and **column**... when your data so many, you don't want to click one by one to expand/collapse all rows, isn't it...

**Anyway Great Work !!**

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 Thanks :-)

Yes, I plan to add `rendererOptions`  to control expansion/collapsing of pivot when it is drawn initially. I am still thinking what the option could be. Of course, expandAllRows or expandAllColumns are easy ones. Just wondering if more finer control can be given or not!!!

I have enabled issues tab in the [forked repository here](https://github.com/nagarajanchinnasamy/pivottable/issues) in case if you want to discuss `subtotal_renderers` specific issues.

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 I have added an option `collapseRowsAt` as a `rendererOptions` that takes one of the row attributes as it's value and collapses rows at that level.E.g.:

    rendererOptions: {
        collpseRowsAt: "Province"
    }

Default behavior is to expand all rows. 

Please check `subtotal.html` example at the [forked repository here...](https://github.com/nagarajanchinnasamy/pivottable/issues)

Thanks for your feedback.

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 in addition to the `collapseRowsAt` option, I will also **expose a function to be invoked at runtime to expand/collapse rows/columns**. I would not want to change the standard user interface to provide the tool to expand/collapse rows/columns. Instead, the application can have its own UI, when clicked, can call the exposed function.

I will also see if I can provide a **function to show/hide subtotals**

**Comment by ahmad003** [comment]
@nagarajanchinnasamy, its awesome.
I think you can make new aggregation function like **% of Parent Row Total** and **% of Parent Column Total** in excel (option **Show Value as**), that you can make subtotals output...

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 Thanks.

**% of Parent Row/Column** is a good suggestion. Willl add and let you know. Thanks again.

**Comment by ahmad003** [comment]
@nagarajanchinnasamy, can subtotals generate without UI?

**Comment by nagarajanchinnasamy** [comment]
@ahmad003 sorry I did not understand what you mean by: 

> can subtotals generate without UI?

**Comment by ahmad003** [comment]
@nagarajanchinnasamy, Sorry..

I mean to change this code in example/subtotal.html in line 38

            **$("#output").pivotUI(mps, {**

to

            **$("#output").pivot(mps, {**

but when i try, the subtotals didn't generate..

**Comment by nagarajanchinnasamy** [comment]
@ahmad003  got it. I will check. Thanks for the feedback.

**Comment by janscas** [comment]
Are you gona PR this on the nicolaskruchten repo?

**Comment by nicolaskruchten** [comment]
@nagarajanchinnasamy I've put some thought into how we can modify this library to allow your fine work to be compatible. My proposal is that we accept a new parameter which would allow the developer to override the `PivotData` class altogether, instead of just the `processData` function, so that someone could actually choose to store the data differently as well as process it differently. If I made this change, would you consider modifying your code to follow?

**Comment by nagarajanchinnasamy** [comment]
Definitely @nicolaskruchten.... My pleasure :+1: Please confirm once this change is done. I will modify the code accordingly and submit a PR.

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten, as u had suggested, I've created `SubtotalPivotData` class that extends `PivotData`. Overridden `ProcessRecord` function. Introduced a link in `index.html` to the example `subtotal.html`.

Submitted PR #506. Please review and let me know of your feedback.

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten , @ahmad003 , @anandakumarramaswamy , @vivianjayakaran  and friends, happy to inform you that [Subtotal.js](http://nagarajanchinnasamy.com/subtotal) is available for download as an NPM module or Bower component.

[Subtotal.js](http://nagarajanchinnasamy.com/subtotal) is hosted in GitHub as [pivottable-subtotal-renderer](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer.git)

@nicolaskruchten , In setting up [Subtotal.js](http://nagarajanchinnasamy.com/subtotal), I have shamelessly copied the structure, style and some portions of text and code as is from Pivottable.js repository. Hope you don't mind.

Thanks again to all of you for your feedback and support :+1:

**Comment by nicolaskruchten** [comment]
All right, I think we can finally consider this issue resolved! The [official answer in the FAQ](https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#subtotals) is now "use [Subtotal.js](http://nagarajanchinnasamy.com/subtotal/examples/)" :)
