### ISSUE TITLE
Pivot table js error with hosting on server

### ISSUE THREAD

**Issue by thearyoun** [nicolaskruchten/pivottable#262]
Dear Developer,

I am using pivot table js. When I runs it on localhost, it has no error, but when I upload this module on server, I got error. My error is blank page when I do search with many data in php codeigniter. This message i got  Uncaught ReferenceError: google is not defined, and one more is Failed to load resource: the server responded with a status of 500 (Internal Server Error). Another point is I want to change aggregation count default to Integer Sum. How can i solve these problems. Please help to solve it.

**Comment by nicolaskruchten** [comment]
Unfortunately I won't be able to help you unless I have some sample code to work with. It sounds like your codeigniter setup is introducing problems with this library...

**Comment by thearyoun** [comment]
So, you mean that pivot table js cannot use with Codeigniter.

**Comment by nicolaskruchten** [comment]
Not necessarily, but if you are not seeing problems locally and when you run it within a Codeigniter setup you are seeing problems, then something about your particular setup is causing problems. This is a client-side library, which is not capable of returning a "500 (internal server error)" response so the problem must lie somewhere within the rest of your code.

**Comment by thearyoun** [comment]
Thanks you for your response. But if I have medium data, pivot table js is working. When I have many data pivot table js cannot work. If you know how to solve it, please let me know. Thanks for your help and your plugin. I am really interesting with your plugin.

**Comment by nicolaskruchten** [comment]
OK, so it sounds like you've hit the data size limit of your client or server. How many rows is "many data" where it no longer works? And when it doesn't work, are you still seeing "500 internal server error" problems? If so, the problem is in the PHP side of things, not in PivotTable.js

**Comment by thearyoun** [comment]
Yes thanks you again for your reply to me. Now my data have 64,243 rows. On the real sever it no longer to work, but if it is on localhost everything is working. When i have data start from 16,869 rows to over this data, on sever cannot run. For message error  I still see "500 internal server error" . Sometime I got this message "google is not defined". So, how we know the exactly of this problem?

**Comment by nicolaskruchten** [comment]
"500 internal server error" is a problem within your server for sure, and is unrelated to PivotTable.js, which runs exclusively in the browser. You will need to look at your server or application logs to find out what is the cause of these errors.

"google not defined" is likely because you have not included `<script type="text/javascript" src="https://www.google.com/jsapi"></script>` in the `<head>` of your HTML.

**Comment by thearyoun** [comment]
Many thanks. For <script type="text/javascript" src="https://www.google.com/jsapi"></script>, I have included it already in the <head> of my page. And "500 internal server error"  this message when I do research, some people say that it comes from my process.
