### ISSUE TITLE
Make pivottable work better in IE8

### ISSUE THREAD

**Issue by gdevilee** [nicolaskruchten/pivottable#263]
In IE8 i got 'ghost' items (-1) in the field list.
I have changed line:

1045: for (i=0; i<shownAttributes.length; i++) {	// work around IE8   for (i in shownAttributes) {

May be it is better to change all 'for in' combinations.

**Comment by nicolaskruchten** [comment]
Do you see this issue with any of the examples here http://nicolas.kruchten.com/pivottable/examples/ ? If so, which ones and which OS are you using?

**Comment by nicolaskruchten** [comment]
Also, please note that IE8 is not currently really supported: see #100
