### ISSUE TITLE
tag misalignment in example files

### ISSUE THREAD

**Issue by Polfo** [nicolaskruchten/pivottable#267]
the html example files contains the following sequence
`    </head>`
`    <css />`
`    <body>`
In order to make the html valid, that should be changed to 
`    <css />`
`    </head>`
`    <body>`

**Comment by Polfo** [comment]
Correction proposed in https://github.com/nicolaskruchten/pivottable/pull/266

**Comment by nicolaskruchten** [comment]
Thanks!
