### ISSUE TITLE
error on refresh pivot

### ISSUE THREAD

**Issue by diogonesbitt** [nicolaskruchten/pivottable#273]
when try to refresh pivot configuration calling pivotui again i got this error,

TypeError: Cannot read property 'tooMany' of undefined
    at $.fn.pivotUI._fn (https://xxxxx.com/Addons/pivottable-master/dist/pivot.min.js?20140924010000:978:60)
    at $.fn.pivotUI (https://xxxxx.com/Addons/pivottable-master/dist/pivot.min.js?20140924010000:1053:9)
    at Object.success (<anonymous>:6:56)
    at x.Callbacks.c (https://xxxxxxx.com/Addons/jquery-1.10.2.min.js?20140924010000:4:26036)
    at Object.x.Callbacks.p.fireWith [as resolveWith] (https://xxxxxx.com/Addons/jquery-1.10.2.min.js?20140924010000:4:26840)
    at k (https://xxxxxxx.com/Addons/jquery-1.10.2.min.js?20140924010000:6:14277)
    at XMLHttpRequest.x.ajaxTransport.send.r (https://xxxxxxx.com/Addons/jquery-1.10.2.min.js?20140924010000:6:18646)

it appers to be on line 792
            console.error(e.stack) if console?
            @html opts.localeStrings.uiRenderError
        return this

**Comment by nicolaskruchten** [comment]
What are the parameters that you are passing into `pivotUI()` ?

**Comment by diogonesbitt** [comment]
$.getJSON('AllData.aspx?IsClearFilters=True', function(mps) {
                    $('#wt5_wtMainContent_wtdivPivot').pivotUI(mps,
{"onRefresh": function(config) {
                            //delete some bulky default values
                            delete config['rendererOptions'];
                            delete config['localeStrings'];

$('#wt5_wtMainContent_wtPivotConfiguration_Configuration').text(JSON.stringify(config,
undefined, 2));
                       }})
        });


--------------------------------

Diogo Nesbitt Gonçalves

**Comment by nicolaskruchten** [comment]
OK but I'm going to need to see the actual object that gets passed in, not the code that generates it.

**Comment by diogonesbitt** [comment]
are you talking about json?

in attach


--------------------------------

Diogo Nesbitt Gonçalves

**Comment by nicolaskruchten** [comment]
Yes, I will need to see the JSON representation of the `options` parameter. Attachments will not work when emailing into Github Issues, so you will have to paste it into your response.

**Comment by nicolaskruchten** [comment]
Is this issue still active?

**Comment by diogonesbitt** [comment]
No Thanks


--------------------------------

Diogo Nesbitt Gonçalves

**Comment by maximl337** [comment]
@diogonesbitt How did you resolve your issue? I'm getting the same problem.

**Comment by maximl337** [comment]
@nicolaskruchten Are certain characters not allowed in property name of the data objects?

**Comment by nicolaskruchten** [comment]
@maximl337 please create a new issue rather than commenting on an old one and I will try to help out :)
