### ISSUE TITLE
Pivot() with data coming from a JSON and exporting current state of pivottable

### ISSUE THREAD

**Issue by sunnypatel165** [nicolaskruchten/pivottable#274]
First of all, this is a superb utility. A big Thanks for making this:)

Need help on these 2 matters:
So, i have an internal dashboard for my company

1. On the homepage i just want a summary, ie no customization options for the table( the customizable-PivotUI() tables will be under dedicated tabs).

So, on the home page i simply want a table with:
<code>
                        cols: ["Week"], <br>
                        rows: ["category"],<br>
                        aggregatorName: "intSum",<br>
                        vals: ["live_listings"],<br>
                        rendererName: "Table"<br>
</code>

This is easily done in PivotUI.
But all i want is a simple table as shown in "simple.html" but data coming from JSON and not defined in the code within [ and ]. Is there a way to import JSON data with Pivot()?

And 2nd: Also, when somebody uses customizable options to reach particular state, is there a way by which  we can allow the user to download/export/save table in that format? i mean the data will obviously come from my own database, but i want user to be able to store the snapshot of the table(not a screenshot of course) into a CSV or any excel format?

Please help.
Thanks.

**Comment by nicolaskruchten** [comment]
Glad you like this library!

1) for your first concern, yes, you can load JSON data via AJAX-style calls (see example: http://nicolas.kruchten.com/pivottable/examples/mps.html)

2) for your second concern, you can use the `onRefresh` parameter to capture the settings of `pivotUI()` for later re-renderings (see example: http://nicolas.kruchten.com/pivottable/examples/onrefresh.html)

**Comment by sunnypatel165** [comment]
Thank you for your response. 
But there seems to be a mismatch in what i want and what it is producing.

My JSON data(see the highlighted values, in 1000s)
![untitled](https://cloud.githubusercontent.com/assets/9017668/5695886/8664291c-99dc-11e4-848f-4bbf51c2b91a.png)

My code:
<code><pre>
<script type="text/javascript">
            $(function(){
                $.getJSON("live_listings.json", function(mps) {
                    $("#output").pivot(mps, {
                        cols: ["week_live"], 
                        rows: ["category"],
                        aggregatorName: "intSum",
                        vals: ["live_listings"],
                        rendererName: "Table"
                       
                    });
                });
             });
        </script>
</code></pre>

OUTPUT:
![untitled2](https://cloud.githubusercontent.com/assets/9017668/5695894/a2a8c272-99dc-11e4-88c2-3b426353ae3d.png)

The values in the output have to be in 1000s right? Maybe it is still printing the count() and not intSum() is it?

**Comment by nicolaskruchten** [comment]
Yes, you are not passing in an aggregator to `pivot()`. If you look at the [Parameters](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) page you will see that `pivot()` and `pivotUI()` do not take the same parameters. Specifically, `pivot()` does not take `aggregatorName` but rather `aggregator` which is a function, not a string. This page contains more information on Aggregators and the built-in ones and how to use them: [Aggregators](https://github.com/nicolaskruchten/pivottable/wiki/Aggregators).

**Comment by sunnypatel165** [comment]
Thanks i referred to the parameters page but i am not able to figure out
what to pass exactly as a parameter.
Can you please give me a small example? what i want to do is:

Call the pivot()
Using the renderer intSum of data field C
Cols A
Rows B

I tried several things, none of which seem to work!

I also tried this:
I used PivotUI() instead of Pivot() and set all the default parameters
which works fine but i don't want to let the user to see all the drag and
drop functions for a particular page(it is supposed to have only the
summary). So can I simply Hide all the top rows and side columns with
options of renderers, fields, etc?

Also for my 2nd concern, i can implement the cookie to store the state of
the table but how do i export it to a CSV? i think this will empower your
utility to even larger extent, as often, we need to work on data on this
utility and then export the data and apply functions like linear regression
etc in excel. So how do i export the data?

Maybe our doubts will seem to be stupid to you, but we are bunch of young
enthusiasts trying run a small venture and pretty inexperienced in jQuery.
We would love if you could help us.


On Sun, Jan 11, 2015 at 11:24 PM, Nicolas Kruchten <notifications@github.com

**Comment by sunnypatel165** [comment]
Okay, i finally figured out how to pass the parameters.
Can you tell me why this doesn't seem to work? It produces no output?

```javascript
            <script type="text/javascript">
            $(function(){
                  $.getJSON("live_listings.json", function(mps) {
                        $("#output").pivot(mps, {
                                  cols: ["Week"], 
                                  rows: ["cat"],
                                  $.pivotUtilities.aggregators.intSum(["properties_added"])
                     });
                });
             });
        </script>

**Comment by nicolaskruchten** [comment]
Your javascript is not valid... on the line which contains `$.pivotUtilities.aggregators.intSum(["properties_added"])` you need to prepend `aggregator:`

:)

**Comment by sunnypatel165** [comment]
Tried that already. Produces no output with <code>intSum()</code> but with <code>Sum()</code> it does have floating values.

**Comment by nicolaskruchten** [comment]
OK. You're mixing up `aggregators` and `aggregatorTemplates`. 

Here's the line you need if you want to use the predefined english-locale "Integer Sum":

```javascript
aggregator: $.pivotUtilities.aggregators["Integer Sum"](["properties_added"])
```

If you want to be able to control formatting you can use:

```javascript
aggregator: $.pivotUtilities.aggregatorTemplates.sum()(["Age"])`
```

while passing in a formatting function into the `sum()` call to e.g. get integers only. 

The "Integer Sum" aggregator is itself defined using the `sum()` aggregator template.

**Comment by sunnypatel165** [comment]
Got it. So sorry, goofed it up completely. Again thanks, this is such a good library for customization.

**Comment by nicolaskruchten** [comment]
No sweat. Is everything working now? The aggregator system is very flexible but pretty confusing as well, so don't feel bad.

**Comment by sunnypatel165** [comment]
Yes, All that part is sorted but i recently realized something that i fee is a bug.

So i have this large data set which i was viewing date-wise and hence obviously table had a huge number of rows.

When i changed my renderer from <code> table</code> to <code> line chart </code>, i guess the div was now re-sized to the table size. This isn't desirable is it? I mean, the graph dimensions(in terms of pixel area) should remain the same, only the table should grow and shrink?

I guess a workaround will be to re-size the renderer area div at the start of each function call for each renderer

**Comment by sunnypatel165** [comment]
Yes, All that part is sorted but i recently realized something that i fee is a bug.

So i have this large data set which i was viewing date-wise and hence obviously table had a huge number of rows.

When i changed my renderer from  table to  line chart , i guess the div was now re-sized to the table size. This isn't desirable is it? I mean, the graph dimensions(in terms of pixel area) should remain the same, only the table should grow and shrink?

I guess a workaround will be to re-size the renderer area div at the start of each function call for each renderer

**Comment by nicolaskruchten** [comment]
OK, I'm going to re-close this issue so that you can create a new one... I'm trying to keep one issue per issue :)

Also, I'm afraid that I don't understand the new problem you're reporting... In the new issue, can you please try to re-explain, perhaps with a screenshot?

thanks.
