### ISSUE TITLE
How to set session  drag and drop row in Pivot table js?

### ISSUE THREAD

**Issue by thearyoun** [nicolaskruchten/pivottable#276]
First of all, Thanks for making this great tool.

I need somebody help related to set session when do drag and drop field to rows. I try to use this pivot with codeigniter. So, I would like to set session for rows which we have dragged and dropped.

Please help.

Thanks.

Theary

**Comment by nicolaskruchten** [comment]
I'm not sure I fully understand your question, but perhaps this example will help? http://nicolas.kruchten.com/pivottable/examples/onrefresh.html

If not, could you please try to restate your question more clearly?

**Comment by thearyoun** [comment]
Yes. Thanks for your response. In pivot table have field to drag and drop right. How can we set session when you drag those field to row or column? Please help.
![capture](https://cloud.githubusercontent.com/assets/6762549/5751259/7c2ddd9e-9c93-11e4-9e8d-17487d43a32e.PNG)

Here is example. I have articleNo in row, so how we set session when drag articleNo to row.

Theary

**Comment by nicolaskruchten** [comment]
I don't understand what you mean by "set the session". Please explain.

**Comment by thearyoun** [comment]
Set the session mean that, how can we define action of drag and drop object. Example, when I drag field ArticleNo, I want alert name of this field before it shows the result.

Thanks.

**Comment by nicolaskruchten** [comment]
You would have to adapt the code here: http://nicolas.kruchten.com/pivottable/examples/onrefresh.html to capture the event that has just occured, or you could watch the drag and drop events yourself in the DOM.
