### ISSUE TITLE
dispose of pivot table?

### ISSUE THREAD

**Issue by trystanclarke** [nicolaskruchten/pivottable#277]
Hi Nicolas,

I am enjoying working with your pivot table, thanks.

I plan to use your pivot control in a single page app, where it may be updated multiple times with new data over its lifetime, and at some point the control may be closed.

I would like to know if I need to do any kind of disposal of the control when I am finished to make sure resources are released.  I am planning to at least remove the dom element it is attached to, but I don't know if I should do anything further - I can't see any reference to disposal or cleanup in your docs.

Thanks

Trystan

**Comment by nicolaskruchten** [comment]
Interesting question, I have not really considered this. I would assume that just removing the parent `div` contents from the DOM would cause the browser's garbage collector to dispose of everything correctly but I've not tested this.
