### ISSUE TITLE
How can we extraction criteria from Pivot Table js?

### ISSUE THREAD

**Issue by thearyoun** [nicolaskruchten/pivottable#278]
Dear Nicolas,

Thanks for your making this plugin. It is great tool.
Exactly everything is perfect from this tool. Now I am enjoy using it for my developing, but I got one requirement from my manager and it is my problem. I would like to extract some criteria from pivot table js. I have criteria like this picture.
![criteria_pivot table](https://cloud.githubusercontent.com/assets/6762549/5787331/f36c8d5c-9e2c-11e4-8f4b-c31deaf2379a.PNG).

Example I want to extract criteria which I have drop in row like Month, Place, and ArticleNo. So, how can we do extraction those criteria. Addition, I am using this pivot table js with PHP Framework( Codeigniter).

Please help me to solve it.

Many thanks,

RIN Theary

**Comment by nicolaskruchten** [comment]
I'm really having trouble understanding what you want to do here. Can you give me an example of the output you are trying to achieve?

**Comment by thearyoun** [comment]
Example: I have field ArticleNo, Month like in the picture, and I want to extract to csv file for this criteria.

**Comment by nicolaskruchten** [comment]
OK. You cannot "extract a csv file" with this library, unfortunately.
