### ISSUE TITLE
building a R wrapper for pivottable - Help request!

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolaskruchten/pivottable#282]
I would like to build a wrapper for this great library to make it available to R programmers as R package.

Thanks to the R package[ htmlwidgets](http://www.htmlwidgets.org), all / most of the scaffolding needed is already provided allowing even people like me with little to no JS experience to implement these type of wrappers (I've successfully done it already with the D3 library d3pie, available as rd3pie in my github page).

[Here](https://github.com/smartinsightsfromdata/rpivotTable) is my present attempt.

I've used Nicolas's demos and the code in [this](http://jsfiddle.net/8z00j4oe/3/) fiddle to get where I've got.

Sadly it does not work, and I do not know how to fix it.

Could somebody with more pivottable expertise (and JS!) than me help to fix the problem?

Thanks in advance!

**Comment by timelyportfolio** [comment]
@smartinsightsfromdata in my opinion probably better not to distract the fine JavaScript work being done here.  I had planned to work on this so maybe we can figure it out together.  I will check it out and provide feedback.
