### ISSUE TITLE
New R library rpivotTable: R wrapper for pivottable (with the help of htmlwidgets)

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolaskruchten/pivottable#283]
Hi
If anybody is interested in using the pivottable library with R a starting point is the new library rpivotTable [here](https://github.com/smartinsightsfromdata/rpivotTable).

Nicolas Krutchen acknowledged directly in the DESCRIPTION file (as per CRAN norms). Please let me know if OK.

Thanks for this great library!

**Comment by nicolaskruchten** [comment]
This is really cool, I'll definitely play with it later today :)

Well done!
