### ISSUE TITLE
handling localised date formats - ie dd/mm/yyyy

### ISSUE THREAD

**Issue by tobybellwood** [nicolaskruchten/pivottable#284]
Having thrashed around this for the best part of an afternoon, I think the wiki could benefit from a brief spiel on date formats.  Obivously ISO 8601 yyyy/mm/dd dates are handled universally and should be the norm and the docs should probably reflect this, but those of us in Australia, the UK etc still have dd/mm/yyyy to contend with..

I just created a formula and used the American Date value to lookup the month name (adding the zero-padded number for sorting)

````
var monthDeriver = function(record) {
	var mthNames = ["01-Jan", "02-Feb", "03-Mar", "04-Apr", "05-May", "06-Jun", "07-Jul", "08-Aug", "09-Sep", "10-Oct", "11-Nov", "12-Dec"];
	var dayasmonth = new Date(record.Date).getDate()-1;
  	return mthNames[dayasmonth];
}
...
derivedAttributes: {
	"Mth": monthDeriver,
},
rows: ["Mth"],
````

Hopefully this saves someone else the time I spent trying to get it running...

**Comment by nicolaskruchten** [comment]
Ah, I'm sorry you had trouble with this... There's actually code for this already here: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L156 which can be called like this to get the same output: `$.pivotUtilities.derivers.dateFormat("Name of Attribute", "%m-%n")`

**Comment by tobybellwood** [comment]
Thanks Nicolas - I'd used the %m-%n at first, but the default date.parse on ddmmyyyy dates assumes mmddyyyy - this'll then lead .getMonth to convert the dd to month(hence throwing out the lookup).

    > var December11th = "11/12/2014"
    < undefined
    > date = new Date(Date.parse(December11th)).getMonth()
    < 10

Until someone comes up with a clever way of JS parsing dates in any format correctly (or the whole world unites behind a common format) - the rest of the world using non-us formats will always have to build workarounds!

Thanks so much for an awesome library - I'm just getting to grips with it's power - keep up the good work!

**Comment by nicolaskruchten** [comment]
Right, I see the problem now.
