### ISSUE TITLE
Is possible calculate a new column?

### ISSUE THREAD

**Issue by danynt** [nicolaskruchten/pivottable#287]
Good day.

I wonder if it is possible to create a new column which is calculated using the values of other columns.
For example, I have the following columns:

Col1 - Col2 - Col3 - Total - Column calculated - Calculated Column 2
[_10]- [_20]- [_18] - [_48] - [Col1*(Col3+Col2)] - [(Col1+Col2)*100]
[_20]- [_30]- [_15] - [_65] - [Col1*(Col3+Col2)] - [(Col1+Col2)*100]

In other words, create new columns using formulas with the facts that I possess.
Thank you very much.

**Comment by nicolaskruchten** [comment]
Yep! Check out this wiki page: https://github.com/nicolaskruchten/pivottable/wiki/Derived-Attributes

**Comment by danynt** [comment]
Hello, sorry for the inconvenience.

I'm trying to use derivatives, but d'not know how interact with other columns, and how to add the values derived to the new columns.

For example I own:

STATUS - SECONDS
=================
[DELAY] - [3600]
[READY] - [650]
[DELAY] - [3600]

I try to use:

"DELAY": function (record) {
if (record ["Status"] == "READY") return record ["SECONDS"];
else return null;
},
"READY": function (record) {
if (record ["Status"] == "READY") return record ["SECONDS"];
else return null;
},

This returns me the seconds found in DELAY and READY, but I try to apply the formula:

% USE = READY / (DELAY + READY) * 100

I've been trying but I have not been able to get, would I could give a hand? thx

**Comment by nicolaskruchten** [comment]
Can you give me a clearer example of the input data you have and the output you're looking for?

**Comment by danynt** [comment]
Thank you very much Nicolas

Here I attached a ".rar" with the json file and the template that I use:
http://bit.ly/18Cn80c

The idea is to show two new columns which are calculated based on the formulas:

New column: % Use = [(Ready) / (Ready + Delay)] * 100				
New column: % Availability = [(Ready + Delay + Stand by) / (Ready + Delay + Stand by + Maint)] * 100

These columns would be displayed after (or before) the total.

Thank you very much again.
