### ISSUE TITLE
Issue with for...in loops with frameworks that extend the Array object

### ISSUE THREAD

**Issue by davidacampos** [nicolaskruchten/pivottable#288]
At line 1055 of pivot.js there is a loop that uses "in" to get all the array's values. This throws an exception when used with applications that are extending the Array object (i.e. ExtJS 3.x) because it's also trying to use those "ghost" values when calling the next function. A proposed solution could be to check with the hasOwnProperty method, that would be changing from:

```javascript
        for (i in shownAttributes) {
          c = shownAttributes[i];
          _fn(c);
        }
```

To:

```javascript
                for (i in shownAttributes) {
                    if (shownAttributes.hasOwnProperty(i)) {
                        c = shownAttributes[i];
                        _fn(c);
                    }
                }
```

**Comment by nicolaskruchten** [comment]
Thanks for the bug report! I've just pushed a fix. Note that this has to be fixed in `pivot.coffee` and that all that is needed is to change `for` to `for own` :)

**Comment by davidacampos** [comment]
Nice! thanks, that was quick :+1:
