### ISSUE TITLE
derived attributes - sort month names

### ISSUE THREAD

**Issue by itsmejainh** [nicolaskruchten/pivottable#289]
Hi, 

I am looking to sort month names in their proper order. I know pivottable uses natural sort and hence it is sorted alphabetically by default. 

There is a solution to this too on FAQ section - that append month numbers before month names, that actually solves problem.. 

But, when displayed on report (pivot table), I don't want numbers.. want only month names. What's the best way to achieve this ?

Thank you.

**Comment by scriptdude** [comment]
Make sure your months have numbers so thery are sorted naturally in the correct order.

I use "01." (include the period, we'll use it later)

![image](https://cloud.githubusercontent.com/assets/400155/6040981/36c9158a-ac78-11e4-9e21-9a956634a6b0.png)

Now in the `pivotTableRenderer` function definition, declare a regex pattern. 

`var sortPattern = /^\d\d\./;`

Example:

![image](https://cloud.githubusercontent.com/assets/400155/6041043/cb6a645a-ac78-11e4-99c3-5bd4a73c053e.png)

Now it is really simple to display month-names without numbers.

The `<th>` headers with the month names are populated in a loop.

![image](https://cloud.githubusercontent.com/assets/400155/6041094/4b1db2ce-ac79-11e4-8ef0-cbbfa527d973.png)

Simply apply the `sortPattern` to the content of the `<th>` tag, In our case, we're stripping the numbers off the months. The original version - with numbers - will be used for sorting, but they are now displayed without the numbers.

Problem solved. No need for difficult add-on methods or anything.

**Comment by nicolaskruchten** [comment]
In general, the pivot table sorts based on what it displays and displays the input given. If you want to sort based on one thing and display another you'll have to either override the natural sort function in the library or do some post-processing as with the solution posted above.

I'm considering making the sorting function overridable given how often this issue comes up... See #236

**Comment by nicolaskruchten** [comment]
There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.
