### ISSUE TITLE
pivot() always return count() values

### ISSUE THREAD

**Issue by Kirkos101** [nicolaskruchten/pivottable#290]
Hi,
I am trying to use pivot() to create a table as follows:
        <script type="text/javascript">
            $(function(){
                var tpl = $.pivotUtilities.aggregatorTemplates;

                $.getJSON("9_Response.json", function(mps) {
                    $("#output").pivot(mps, {
			derivedAttributes: {
                            "Market": function(mp) {
                                return mp["market"];
                            },
                            "Year": function(mp) {
                                return mp["stYear"];
                            }
                        },
                        aggregators: {
                            "Sum1": function() { return tpl.sum()(["totSale"])}
			},
			rows: ["Market"],
                        cols: ["Year"],
                        aggregatorName: "Sum1",
                        rendererName: "Table"
                    });
                });
             });
        </script>

When I use PivotUI() it works fine but I would like to create a static table only, without UI (without drag n' drop attributes, renderers and aggregator selectors). I need just the table.
With pivot() I am getting always sums of the record count, not the sums of the field values.
Could you please advise of how to resolve this?

**Comment by nicolaskruchten** [comment]
Can you provide a bit more detail here please? I think your post got cut off...

**Comment by Kirkos101** [comment]
Hi, I am posting the same again. I hope you can see it.

 I am trying to use pivot() to create a table as follows:
        <script type="text/javascript">
            $(function(){
                var tpl = $.pivotUtilities.aggregatorTemplates;

                $.getJSON("9_Response.json", function(mps) {
                    $("#output").pivot(mps, {
            derivedAttributes: {
                            "Market": function(mp) {
                                return mp["market"];
                            },
                            "Year": function(mp) {
                                return mp["stYear"];
                            }
                        },
                        aggregators: {
                            "Sum1": function() { return tpl.sum()(["totSale"])}
            },
            rows: ["Market"],
                        cols: ["Year"],
                        aggregatorName: "Sum1",
                        rendererName: "Table"
                    });
                });
             });
        </script>

When I use PivotUI() it works fine but I would like to create a static table only, without UI (without drag n' drop attributes, renderers and aggregator selectors). I need just the table.
With pivot() I am getting always sums of the record count, not the sums of the field values.
Could you please advise of how to resolve this?

**Comment by Kirkos101** [comment]
It seems there is some problem with the code I am attaching, so I am posting an image:
![code1](https://cloud.githubusercontent.com/assets/10725027/6058373/606da740-ad2f-11e4-95bf-9b96f878afab.jpg)
So, I am trying to use pivot() to create a table with the code which (I hope) you can see in the attached image.
When I use PivotUI() it works fine but I would like to create a static table only, without UI (without drag n' drop attributes, renderers and aggregator selectors). I need just the table.
With pivot() I am getting always sums of the record count, not the sums of the field values.
Could you please advise of how to resolve this?

**Comment by nicolaskruchten** [comment]
You are calling `pivot()` as if it were `pivotUI()` but they accept different parameters... If you check the documentation for `pivot()` you will see that it does not accept `aggregators`/`aggregatorName` as parameters, but rather a single function called `aggregator`.

**Comment by nicolaskruchten** [comment]
See new example here: http://nicolas.kruchten.com/pivottable/examples/simple_agg.html

**Comment by miraculixx** [comment]
how can the pivotUI drag/drop options be hidden? Essentially I want to pass in the options as for `pivotUI()`, but have a display that looks like `pivot()`. Rationale: I'm offering users to customize the pivot table, store the options, then hide the drag/drop areas.
