### ISSUE TITLE
default aggregator

### ISSUE THREAD

**Issue by yuli06** [nicolaskruchten/pivottable#291]
hi I'm so satisfied with pivottable, but I have to display a report for the end users and need sum as default aggregator for this report, I've read all documentation and examples but I can´t find a solution
hope you can help me

**Comment by nicolaskruchten** [comment]
Are you using `pivot()` or `pivotUI()` ?

**Comment by yuli06** [comment]
hi thanks for your answer, I'm using pivot ()

**Comment by nicolaskruchten** [comment]
See new example here: http://nicolas.kruchten.com/pivottable/examples/simple_agg.html

**Comment by yuli06** [comment]
thank you so much , it´s just what I need... I tried by this way before but I missed some parameters
wonderful tool
