### ISSUE TITLE
how to install pivot table using npm..?

### ISSUE THREAD

**Issue by sandeeppatel344** [nicolaskruchten/pivottable#294]
npm install pivottable@1.3.0 using this command i cant install pivot table

**Comment by nicolaskruchten** [comment]
What happens when you run the command? What are you expecting to have happen?

**Comment by sandeeppatel344** [comment]
i am using ubuntu os i want extract all file of pivot table js i want install using bower ...

**Comment by nicolaskruchten** [comment]
OK you don't need NPM for that. You can just grab the files from the dist directory here in the repo.
