### ISSUE TITLE
Exclusions not working with simple html table as input for pivotUI function

### ISSUE THREAD

**Issue by abanaik** [nicolaskruchten/pivottable#295]
Hi Nicolas. 

Exclusions parameter is working with the fully_loaded example but it is not working for me in the simple_ui_from_table example. I am using it in the pivotUI function. This seems to be happening when I am using an html table as the input for the function. Is there any solution for this issue?

**Comment by nicolaskruchten** [comment]
You'll have to make sure that the values in the `exclusions` exactly match the values of your table cells including whitespace and markup... If you're still having problems, can you post a URL where I can see the issue in action?

**Comment by abanaik** [comment]
Thanks a ton! I had not included the complete markup. Resolved my issue. Although, I have another question. Currently I am getting an attribute that has some 20 values, and I need to filter that attribute with just 1 value before I load the pivot. Is there any better way to do that besides the exclusions parameter? As of now I am excluding the other 19 odd values.

I would like to add that this is an absolutely fantastic plugin. Amazing work!

**Comment by nicolaskruchten** [comment]
Thanks!

If you don't mind your user not having controls over the exclusions you can use the filter parameter (which is a function) instead to prevent certain rows from being included in the input...

**Comment by abanaik** [comment]
Filters won't do as i need the user to have that control. Anyway exclusions accomplishes my task. Thanks!
