### ISSUE TITLE
PivotTable dynamically update data passed to pivotUI

### ISSUE THREAD

**Issue by Chipsi** [nicolaskruchten/pivottable#296]
Hello, I want to dynamically update data passed to pivotUI(data...{});

For example 
```javascript
 $('#output').pivotUI($scope.data, {
            onRefresh: function(config){
                console.log(config);
            }
        });
```
Is there any way to update $scope.data and affect data passed in pivotUI ? thank 

What I want is:

in callback onRefresh() make new request to API, and update $scope.data (pivotUI data)

**Comment by nicolaskruchten** [comment]
You'll have to call `pivotUI()` again if you want to change the input data. Watch out for infinite recursion!

**Comment by Chipsi** [comment]
@nicolaskruchten thank you, i have solved it like: $watch the data for changes, and if data changed, I call pivotUI again :) thank you, you can mark this issue as solved ;)

**Comment by Chipsi** [comment]
@nicolaskruchten Hi, how can I avoid to infinite callback ?

**Comment by nicolaskruchten** [comment]
Well you need to make sure you don't recurse if nothing has changed...
