### ISSUE TITLE
set default sum in pivot

### ISSUE THREAD

**Issue by sandeeppatel344** [nicolaskruchten/pivottable#297]
How to set default sum in pivot ...?

**Comment by nicolaskruchten** [comment]
See example here http://nicolas.kruchten.com/pivottable/examples/simple_agg.html

**Comment by jwhitmarsh** [comment]
If we're using the aggregatorName property, is there a way to set the default value of the pvtAttrDropdown?

**Comment by nicolaskruchten** [comment]
@jwhitmarsh that's what the `aggregatorName` property does...
