### ISSUE TITLE
Integration with Google Charts: Legend Position and Paging does not work well

### ISSUE THREAD

**Issue by enriquemolinari** [nicolaskruchten/pivottable#301]
Hey Nicolas, 

By default, the legend from Google Charts appears on the right of the chart. With that, if you have long legends, you will get each long word cut (you can check here http://nicolas.kruchten.com/pivottable/examples/fully_loaded.html with Gender and Province on the rows). 
If I try to put it on the Top or Bottom, it seems paging does not work. All the labels from the legend appears together and in a reduced space, which makes a complete mess of words. 
However, if you open the customize dialog from Google charts (double click on the chart) and choose to put the legend on the Top or Bottom, then, it is lovely how that is shown. Paging works and you will have 2 legends per page. If one word in the page does not fit in the space, then "..." are shown and you will see a tooltip with the complete word.

What can be done to get that same behavior by default?

Thanks!

**Comment by nicolaskruchten** [comment]
I'm not understanding here... You say "If I try to put it on the Top or Bottom, it seems paging does not work." but how did you try to do this?

**Comment by enriquemolinari** [comment]
Sorry, probably I was not very clear. Looks like when the google charts are drawn the DOM is not yet finished loaded so the dimentions are not well calculated and the paging with legends are not done correctly. What I had to do, was to call the wrapper.draw, inside a setTimeout function in the gchart_renderers.js. Something like this:

window.setTimeout(function() {
            wrapper.draw(result[0]);
        }, 0); 

With this, the paging is done correct. This problem was occurring to me when trying to use options with the legend aligned on top or bottom.
