### ISSUE TITLE
multiple measures

### ISSUE THREAD

**Issue by aalberici** [nicolaskruchten/pivottable#302]
hi Nicholas,
my compliments for the great work! 

One shot question: can we have multiple dimensions in the same client? I mean... counting one variable and summing another, in order to show 2 values per column (or 2 columns per dimensions)

**Comment by nicolaskruchten** [comment]
Unfortunately no, this is not possible atm, see the first question in the FAQ: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions
