### ISSUE TITLE
twitter bootstrap support

### ISSUE THREAD

**Issue by taraman** [nicolaskruchten/pivottable#303]
Hi,
thanks for your effort
do you have plans to support twitter bootstrap style??

thanks
Mohamed Taraman

**Comment by nicolaskruchten** [comment]
Hi there,

What do you mean by "support" ? You can apply the bootstrap CSS file to this library and tweak as required... ?

n

**Comment by nicolaskruchten** [comment]
I've just tweaked the CSS to make it more Bootstrap-friendly.
