### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by andre-santos** [nicolaskruchten/pivottable#304]
Hi Nicolas,

First, congratulations for pivottable scripts!

I used javascript (navigator.language || navigator.userLanguage) to detect the browser language and select the correct language pack.

In addition, I made some modifications on language packs (pt, fr, es, and created an en) to add all renderer options like Gchart, d3 and export instead of using "$.extend" merge.
 
The html is like this:

```
<script type="text/javascript">
            google.load("visualization", "1", {packages:["corechart", "charteditor"]});
            $(function(){
                var lingua = "en", rendererName = "Line Chart";
                var userLang = (navigator.language || navigator.userLanguage).split("-")[0];
                    if (userLang == "pt") {
                        var lingua="pt",
                            rendererName = "Grafico de Linhas";
                    } else if (userLang == "fr") {
                        var lingua="fr",
                            rendererName = "Graphique de Courbes";
                    } else {
                        var lingua="en";
                        rendererName = "Line Chart"
                    }
                var derivers = $.pivotUtilities.derivers;
                var renderers = $.pivotUtilities.locales[lingua].renderers;
                $.getJSON("dengue-grupos-todos.json", function(mps) {
                    $("#output").pivotUI(mps, {
                    renderers: renderers,
                    cols: ["ano"],
                    rendererName: rendererName
                    },false,lingua);
                });
             });
 </script>
```
This helped us to solve the problem, but we don´t know if is a better way to do.

**Comment by andre-santos** [comment]
adding...

This is  a example of the language detection (using pivottable to show research data in a more powerfull and friendly way to end user)

http://vlab4u.info/doencas%20negligenciadas/Dengue/pivot/dengue-grupos-core.html

**Comment by nicolaskruchten** [comment]
This seems like a good approach if you want to simultaneously support multiple languages.

**Comment by andre-santos** [comment]
That is it. An international website.
Tks a lot. I have another issue but i will open in other topic.

**Comment by andre-santos** [comment]
Hi Nicolas,

I made some modifications in language packs (pivot.en.js, pivot.es.js, pivot.pt.js, pivot.fr.js.) to support multiple languages simultaneously with automatic detection. Modifications include codding for adding all renderers and aggregators.

Would you like to see these files and if approved, add to git? May be useful to others too.

Tks
André.
