### ISSUE TITLE
Resize google charts after ajax load

### ISSUE THREAD

**Issue by wreiske** [nicolaskruchten/pivottable#306]
Hello!

I've been having fun building some pivottables, but i'm having issues with Google Graphs....

I'm currently doing an ajax call to pull a saved JSON object of the config JSON, then another ajax call to grab a CSV with some data. Once the ajax calls are completed, I call the pivotUI function to output to a div. This works perfectly for everything except the Google Graph and the new C3 renderer. 

The issue is that for some reason it's not respecting the width of the container, or what i'm passing to the rendererOptions. If I click on the bar graph and the google window pops up, then I hit "OK" it re sizes and fits in the div perfectly..... Just not on the first load?

The config json saves that it's a Bar Graph using the google's graphs (it does not however save anything customized inside the google graphs...). 

I've tried the following before running the pivotUI,

`a.rendererOptions = {width: 300, height:200,title:'Test'};`

It doesn't seem to have any affect on the output size of the Google Bar Graphs.

Any ideas?

![pivot2](https://cloud.githubusercontent.com/assets/6295044/6423962/bba28f1a-bebc-11e4-8ede-146a55511fc9.png)
![pivot1](https://cloud.githubusercontent.com/assets/6295044/6423963/bba2a428-bebc-11e4-8ad4-25f7c0c253a6.png)

**Comment by wreiske** [comment]
Seperate topic, but I would like it if pivotUI would save the google serialized configs - https://google-developers.appspot.com/chart/interactive/docs/drawing_charts#charteditor

**Comment by nicolaskruchten** [comment]
I don't think I can address your second point, but I've just added options to control the dimensions (you were trying to pass in height/width into the options but this was not supported!). The renderer Options are under `gchart.height` and `gchart.width` and they are functions which should return dimensions in pixels.
