### ISSUE TITLE
Dependencies and dependency versions

### ISSUE THREAD

**Issue by mikeymckay** [nicolaskruchten/pivottable#309]
It's not clear to me what versions of the various dependencies are required (jquery, jquery-ui, d3, etc).

**Comment by nicolaskruchten** [comment]
The examples have all been tested and all work with jQuery 1.8.3 and jQueryUI 1.9.2. It's a good bet that later versions will work well, and it's kind of a crapshoot if you want to use later versions.

Version 3.0 of d3 I believe works, but if you want to use c3 you'll need a compatible version of d3 (which I believe is the very latest one)
