### ISSUE TITLE
Additional Renderers/Plugin Database

### ISSUE THREAD

**Issue by doveyg** [nicolaskruchten/pivottable#310]
Would it be possible to show the Renderers a bit of love? 

I know I could use [Flot](http://www.flotcharts.org/) support in my own projects and i'm sure someone has managed to successfully create a Renderer for Flot in PivotTable but It seems to me if a plugin repository/database was available for PilotTable then Renderers created by other people would be much easier to find.

**Comment by nicolaskruchten** [comment]
If someone submits a renderer addition that's broadly compatible with the rest of the code, I'll gladly add it to this repo but to date no one ever has.
