### ISSUE TITLE
add the parameter numInputs to the Aggregator documentation

### ISSUE THREAD

**Issue by Jogrin** [nicolaskruchten/pivottable#311]
First of all i want to thank you for your great job!
I've read all the documentation and i can't find a way to create a custom aggregator that show a second  dropdown list with the fields (like sum, average, etc..). How can i create it?
Thank you!

Alessandro

**Comment by nicolaskruchten** [comment]
Ah yes, the Aggregator documentation doesn't cover this... You'll need to include a `numInputs` field :)

**Comment by Jogrin** [comment]
Perfect, thanks.
Just one question:
I noticed that adding this parameter it show ALL the fields (and this is what i want).. is there a way to show only some of them?

**Comment by nicolaskruchten** [comment]
There is no way to do this, no. You may want to define a number of Aggregators with no parameters instead.

**Comment by Jogrin** [comment]
I understand.
Anyway, thank for your help and please add the parameter `numInputs` to the documentation :)

Alessandro
