### ISSUE TITLE
Example for filters

### ISSUE THREAD

**Issue by jiteshsharma** [nicolaskruchten/pivottable#313]
Can someone please post a simple example using the filters parameter? I know how to use the exclusions parameter.

**Comment by jiteshsharma** [comment]
The filter parameter not filters

**Comment by nicolaskruchten** [comment]
Say you have input like `[{"a":"b","c":"d"},{"a":"b","c":"e"}]` and you only wanted to show rows which have attribute `c` equal to `"d"`, then you could pass in `function(row){return row["c"] == "d";}` as the `filter` parameter.
