### ISSUE TITLE
Loading a pivot (not pivotUI) with Google Chart Renderer

### ISSUE THREAD

**Issue by fmfcs** [nicolaskruchten/pivottable#317]
I'm using this JS lib for 3 months, congrats to this outstanding job!

Now I'm trying to draw a pivot with a Google Chart Renderer, this is the code:

$(div).pivot($(source),
        {rows: _rows,
        cols: _cols,
        renderer: $.pivotUtilities.gchart_renderers['Bar Chart']})

Any clue?

**Comment by nicolaskruchten** [comment]
What happens when you run this code? What does it say in the javascript console?

**Comment by fmfcs** [comment]
I also try other approach but with the same outcome.

$.getJSON(_dataUrl, function(mps) {
	$('#pivotDiv').pivot(mps, {
		rows: _rows, cols: _cols,
		renderer: $.pivotUtilities.gchart_renderers['Bar Chart'] });    
});

I get this error:
TypeError: Cannot read property 'length' of undefined
    at Object.makeGoogleChart [as renderer] (gchart_renderers.coffee:41)
    at $.fn.pivot (pivot.coffee:543)
    at Object.success (VM907 Reminders.aspx:229)
    (...)

**Comment by nicolaskruchten** [comment]
There was a bug, which I just fixed. Should work for you now.

**Comment by fmfcs** [comment]
Thanks!

**Comment by fmfcs** [comment]
It's working like a charm. Thanks again!

On Mon, May 4, 2015 at 2:44 PM, Francisco Silva <francisco.correia@gmail.com
