### ISSUE TITLE
Feature Request (minor fix) : hide row filtered out by filter selection

### ISSUE THREAD

**Issue by JerYme** [nicolaskruchten/pivottable#320]
Hi,

Can you change the default behavior or add an optional parameters that allow us to hide the rows or cols where there is no data after applying the filters.

Thanks.

**Comment by nicolaskruchten** [comment]
That's already the default behaviour... can you give me an example where this doesn't happen?

**Comment by JerYme** [comment]
Doing an extraction of my data to give you a sample, i found that my data contains nullable value in my measures, that's why i had some blank lines, my mistake.

Thank you for this amazing tool.

Appreciate !
