### ISSUE TITLE
Drag and drop within column dimensions does not work correctly when starting with no column dimensions.

### ISSUE THREAD

**Issue by MaciejPendolski** [nicolaskruchten/pivottable#321]
Steps to reproduce:
1. open http://nicolas.kruchten.com/pivottable/examples/mps.html
2. drag and drop the elements to column dimensions
3. change the order of the column dimensions

Result:
Dimensions can only be dropped in some places and the drop locations sometimes do not match the cursor position.

Expected result:
http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html
Here even when all the elements are moved back to the top bar the operation is correct.

Tested on: 
Firefox 37.0.1, Chrome 41.0.2272.118.
Linux Mint 17, Windows 8.1.

**Comment by nicolaskruchten** [comment]
That's kind of weird indeed. I'll try to dig into it a bit more when I have a sec.

**Comment by nicolaskruchten** [comment]
Thanks for the bug report :)

**Comment by nicolaskruchten** [comment]
This appears to go away if I upgrade jQuery and jQueryUI, so I'm tempted to call it an upstream bug...

**Comment by nicolaskruchten** [comment]
OK, I've upgraded jquery and I can no longer reproduce this bug, so I'm closing the issue. Feel free to reopen if it's still around or appears on other platforms than what I tested (Chrome/Safari/Firefox on OSX)
