### ISSUE TITLE
Passing additional aggregation parameters to options

### ISSUE THREAD

**Issue by kdkade** [nicolaskruchten/pivottable#322]
Hi,

I'm using pivotUI to show different scenarios in my app, and a while ago client demanded snapshots of the pivot table with specific settings. So I came up with a way to read all dropdown/column/row values that are a part of the PivotUI and store them in the database. Now I want to pass it to the options, and for the most part there's no problem with that, besides one detail.

When you choose aggregators like Sum over Sum or List Unique Values,  another dropdown comes up (or dropdowns) with all the attributes as options. Is there a way to preset that/those with values I already know?

Alternatively, I can set that with jQuery selectors (.val()), but the data does not refresh like when I change it with a click. Is there a way to force refresh of data on pivotUI upon changing dropdown value without click event?

**Comment by nicolaskruchten** [comment]
Yes, you can use the `val` argument to `pivotUI` which is an array of strings. So if you wanted to show Sum A over Sum B, then `aggregatorName` is `"Sum over Sum"` and `val` is `["A","B"]`

**Comment by kdkade** [comment]
Thanks! I somehow thought that val argument is for something else after reading the documentation on parameters.
