### ISSUE TITLE
Unable to resize the table using CSS

### ISSUE THREAD

**Issue by saurabhsonu** [nicolaskruchten/pivottable#325]
I have tried resizing the table and gCharts by altering the pivot.css files. But that doesn't seem to do the trick. The original size remains intact no matter how do you alter the css. Also few classes added in js files can't be found in .css file (for ex-  pvtRenderer could not be found in pivot.css). Any ideas on fixing this.

**Comment by nicolaskruchten** [comment]
What kind of resizing are you looking for? You want the table to fit within a particular bounding rectangle? If so, how would you expect the pivottable to scale? 

Regarding the classes with no CSS definition, it's possible that those classes are there just to facilitate selection via jQuery rather than to apply CSS styles.

**Comment by saurabhsonu** [comment]
Hi Nicolas,
What I am trying to achieve is to use your pivottable.js in a responsive website. So when the website is displayed on a mobile (or the browser is sinked to mobile size), the pivot table still displays properly. For this, I was looking to adjust the table size using css for different view-port using media queries (you know it all). But this trick do not seem to work as the table size still remains the same as is displayed in standard browser size.
I even posted this on SA (http://stackoverflow.com/questions/29802658/adding-responsiveness-to-pivottable) but it didn't fetch any answer.  I am really stuck here. Please do guide me if I am going wrong here. Your help will be highly appreciated.

**Comment by nicolaskruchten** [comment]
The ultimate size of the table is basically determined by the data and the text size, and the only reliable way to shrink things would be to shrink the font size. If you try to just change the external dimensions, there is nowhere for the text in the tables to go so it will not change much.

**Comment by saurabhsonu** [comment]
So that means we can't even shrink the <td> and <tr> size. If this is the case, I still owe you a thanks, for now I won't be looking for css fixes as earlier. But can you suggest how the size is determined by the content or is there any spot in the .js where this size can be handled. I have tried a lot to alter the js but couldn't find proper place to start for this change

**Comment by nicolaskruchten** [comment]
Like I said, the size is determined by the content: if your table has 100 rows and 100 columns, there's nothing you can do to shrink that...

**Comment by saurabhsonu** [comment]
Its clear that table size is determined by rows and cols, and for 100 rows and cols obviously the size will be large. But for small sizes, say 7 rows and 7 cols, can't we somehow reduce the table size so that it still contains 7 rows and 7 cols on a smaller scale (obviously the width of each row and col in this case will be so small that the user will have to zoom in.)

**Comment by nicolaskruchten** [comment]
The way to do that is to reduce the font size of the text in the cell. You can't force the font to shrink by shrinking the containing element, that's not how HTML/CSS work :)

**Comment by mehradtv** [comment]
I have somewhat similar issue. Basically, I want the AxisContainer for the Unused attributes to have overflow-y=scroll type of behavior with a max height of an arbitrary size. I have tried messing around with the CSS, however, no luck with lowering the maximum height. What is your suggestion for achieving this?

**Comment by andineck** [comment]
I ran into the same issue. display: block; solved it for me. Here's the CSS Snippet:

```css
.pvtUi {
    display: block;
    width: 100%;
    overflow: auto;
}
```

**Comment by simplysuvi** [comment]
The font size doesn't change when CSS is applied in external css file

**Comment by igmer** [comment]
I'm trying to fix the select with class pvtDropdown
![imagen](https://user-images.githubusercontent.com/34310302/128772644-a8689cc5-5f98-4924-a598-c5080a37fdc6.png)

I have tried
.pvtDropdown{
        width: 200px !important;
    }

**Comment by filemakerunkind825** [comment]
> The way to do that is to reduce the font size of the text in the cell. You can't force the font to shrink by shrinking the containing element, that's not how HTML/CSS work :)





https://psychoanalyst4.github.io/AkDAYwe7G9yVCSPxdx054qGc/
