### ISSUE TITLE
When too much items, filters positionning breaks

### ISSUE THREAD

**Issue by T0RAT0RA** [nicolaskruchten/pivottable#326]
If the length of the filter becomes to big, the filters are not put on the same row as the table type select.
See http://jsfiddle.net/bkr1fofw/1/

**Comment by T0RAT0RA** [comment]
Well, I found the undocumented option: "unusedAttrsVertical: false".
That solved my issue.

**Comment by nicolaskruchten** [comment]
It's documented :)
