### ISSUE TITLE
Is this possible | Multiple Aggregations

### ISSUE THREAD

**Issue by dapinder-dhillon** [nicolaskruchten/pivottable#327]
![pivot js](https://cloud.githubusercontent.com/assets/12184239/7410881/9b6e669c-ef3b-11e4-81f1-0f3c0f029eac.png)

Please reply since this is critical for the project.
<<Code>>
$.get("http://localhost:6900/CROAMIS_Prototype_Site/pivotexamples/report_1_Plan_C.csv", function(report_1_Plan_C) {
                $("#output").pivotUI($.csv.toArrays(report_1_Plan_C), {
					aggregators: {
							"Sum of Rvsd - Charge Weight":
                            function() { return tpl.sum()(["Rvsd_Charge_Weight"])},
							 //successRate
							"Charge Weight Var":
							function() { return tpl.sum()(["Charge_Weight_Var"])}
                            //function() { return successRate},
							
                    },
                     derivedAttributes: {
                        "Charge_Weight_Var":    function(record) {
						  return record.Rvsd_Charge_Weight - record.Org_Charge_Weight;
						}
                    },
					hiddenAttributes: ["Budget Station","MONTH"],
                    rows: ["COMMODITY_TYPE"],
                    cols: [""]
					
                });
            });

**Comment by nicolaskruchten** [comment]
Unfortunately not. More details are in the FAQ here: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multiple-aggregators-in-the-ui-and-renderers
