### ISSUE TITLE
Pivot.js how to use aggregators as calculation of two aggregators?

### ISSUE THREAD

**Issue by Gulikoza007** [nicolaskruchten/pivottable#328]
I am using Pivot.js , which is great but having problem with calculation of two aggregators. How do I make "calculated" aggregator based on already defined two aggregators?

    $(function (){
        var derivers = $.pivotUtilities.derivers;
        var aggregators = $.pivotUtilities.aggregators;
        var aggTemplates = $.pivotUtilities.aggregatorTemplates;
        $("#output").pivotUI(JSON_data, {

            aggregators: {                  
                "Number": function() { return aggTemplates.sum(0,1)(["Number"])},
                "Amount": function() { return aggTemplates.sum(0,1)(["Amount"])},
  *******     "Calculated":  ???? "Number" / "Amount" ???? - help in this line    
            },

            cols:["year"], rows: ["age"],

        }, true);

    });

**Comment by nicolaskruchten** [comment]
If you want an aggregator that shows sum(Number)/sum(Amount) then you can use the builtin `sumOverSum` aggregator: `"Calculated": function() { return sumOverSum()(["Number", "Amount"]); }`

There is no way to combine aggregators in the way you are trying to without building your own aggregator from scratch as listed here: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators

**Comment by Gulikoza007** [comment]
Thank you! Exactly what I need it!
