### ISSUE TITLE
Different ways to implement Agerages

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolaskruchten/pivottable#329]
I got "surprising" results out of the pivottable averages.

Let me explain.  
![screen shot 2015-05-05 at 19 28 35](https://cloud.githubusercontent.com/assets/3786727/7482285/38c428b0-f36e-11e4-8425-7711a33a7fca.png)
The above is a "simple" pivottable where I display a set of values.  The actual values in the row are "silently" computed, then the Sum is made as per result.

What happens if I would like to do the average of the values across the months?

My expectation would be to see a "simple" average calculated as:
 (5330+4565+8990)/12 = 1573.75

On the other hand this is not how the pivottable calculates averages:
![screen shot 2015-05-05 at 19 29 31](https://cloud.githubusercontent.com/assets/3786727/7482341/a8722612-f36e-11e4-8e06-98b6b5b17287.png)

What has happened?  The pivottable has first averaged each column, even if it wasn't explicitly displayed, then averaged the result: a sort of double average.

I haven't checked this behaviour on other products (e.g. Excel), but I'm tempted to say that there should be two types of averages:

- One that only averages the "visible" data (accepting that any "silent" calculation is by definition a sum).
- One that calculates the average "of everything"

**Comment by nicolaskruchten** [comment]
This is pretty much how all pivot tables work, including Excel... For each cell, including the row/col/grand-totals, first the matching values are found, then the aggregator is applied. In your second example, the grand total is not the average of averages, it's the average of all values, just like in your first example, the grand total isn't the sum of sums, it's the sum of all values (which happens to be equal to a sum of sums).

To be honest, though, I'm not sure how you're generating the output in your examples: you should not be able to render empty columns like this :)
