### ISSUE TITLE
Drill-through/Output data from Pivot table entry: "pivot filtering"

### ISSUE THREAD

**Issue by samuelleach** [nicolaskruchten/pivottable#33]
I'm wondering if it's possible to output the records that have been binned into a given pivot table entry.

The use case is the following:
- I have set up a pivot table, for instance with heatmap colouring.
- I now want to click on a given pivot table entry of interest in order to filter on/ inspect / output those records, creating a filtered view of the initial input records.

i.e. I want to answer the question "Which records contribute to this pivot table entry?", and make use of them elsewhere in coordinated views.

Another approach would be to output the necessary row and column data that describes the pivot table entry in order to perform filtering externally (perhaps with crossfilter.js).

I have not looked into the source code to see how to approach this. It would be great to hear from you to know the difficultly level of this enhancement.

**Comment by fleipold** [comment]
@nicolaskruchten is there a plan to add a callback, so that one wouldn't have to patch the renderer to get access to the records underneath the aggregates?

**Comment by nicolaskruchten** [comment]
I'm looking at merging #557 or something like it.

**Comment by nicolaskruchten** [comment]
functionality for this is now in master!
