### ISSUE TITLE
Best way to drag-and-drop dimensions on touch/mobile devices? 

### ISSUE THREAD

**Issue by thatpaulschofield** [nicolaskruchten/pivottable#330]
What is the recommend way to get drag-and-drop on the dimensions/axes on touch devices (mobile phones/tablets)?

**Comment by nicolaskruchten** [comment]
If you check out this example: http://nicolas.kruchten.com/pivottable/examples/fully_loaded.html on a mobile device, it should work. All that I did there was add a reference to jQuery UI Touch Punch (http://touchpunch.furf.com/) with this line: 

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
```

**Comment by thatpaulschofield** [comment]
Thanks Nicolas, I will check them out.
