### ISSUE TITLE
How would I go about adding a "percent" column? 

### ISSUE THREAD

**Issue by marks** [nicolaskruchten/pivottable#331]
Screenshot attached. Maybe it's easier to keep it in the same cell and create some custom format or rendered? I really don't know and could use some pointers.

![pivot_demo](https://cloud.githubusercontent.com/assets/34566/7668112/ea7b34d4-fbf4-11e4-98f0-0e0f7a9ebec5.png)

**Comment by nicolaskruchten** [comment]
Try the "count as fraction of total" aggregator to see if that meets your needs?

**Comment by marks** [comment]
Have an example of using that by any chance? Thanks!

**Comment by marks** [comment]
Nevermind - I got it. Any way to have two aggregations show in a single view though? have totals and %s at once?

**Comment by nicolaskruchten** [comment]
You can only use one aggregator at a time (FAQ: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multiple-aggregators-in-the-ui-and-renderers) but you can always create a new aggregator which shows, say "<total> (<total_pct>%)" or something like that, based on the "Count as fraction of <x>" family of aggregators...

**Comment by marks** [comment]
OK, Thanks so much @nicolaskruchten !
