### ISSUE TITLE
Display a multiple data on time

### ISSUE THREAD

**Issue by zuk38** [nicolaskruchten/pivottable#332]
Hello. 

I traied to make grid with present a multiple field/data at one time.

Like that:
http://docs.webix.com/media/pivot/pivot_dtable.png

What I can do that?

**Comment by nicolaskruchten** [comment]
Unfortunately this is not possible... FAQ: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multiple-aggregators-in-the-ui-and-renderers
