### ISSUE TITLE
Round outputs with SUM aggregator

### ISSUE THREAD

**Issue by fmfcs** [nicolaskruchten/pivottable#334]
Hi!

Is this possible?

pivotUI always generates number with 2 decimals, is it possible to round outputs?

**Comment by nicolaskruchten** [comment]
1. There is the "Integer Sum" aggregator which rounds
1. You can customize the number formatting by creating your own aggregators with a different number formatter. One way to do this would be to create a "locale" file: https://github.com/nicolaskruchten/pivottable/wiki/Localization

**Comment by fmfcs** [comment]
Perfect :)
