### ISSUE TITLE
Row header with HTML doesn't get evaluated in C3

### ISSUE THREAD

**Issue by deecay** [nicolaskruchten/pivottable#335]
When a data value contains HTML tag, C3 renderer's row header does not evaluate the data value.

Legends and tooltips do evaluate the HTML value so they appear as links if the values contain a-tags.

**Comment by nicolaskruchten** [comment]
That's true, but I'm not sure what I can do about it, it seems to be a particularity of C3...

**Comment by deecay** [comment]
Thank you for the reply. I'll try to come up with some workaround.

**Comment by deecay** [comment]
Do you feel it is sensible to do something like this in c3_renderers.js?
    rowHeader = rowKey.join("-").replace(/(<([^>]+)>)/ig,"");

**Comment by nicolaskruchten** [comment]
I don't think I would want to modify `c3_renderers.coffee` in that way, no, but as a workaround, you could do that within a Derived Attribute and make your graph with that... https://github.com/nicolaskruchten/pivottable/wiki/Derived-Attributes

**Comment by deecay** [comment]
Thank you for your suggestion. I will try to come up with something.
