### ISSUE TITLE
Values permanently showing using annotations in gchart barcharts.

### ISSUE THREAD

**Issue by abanaik** [nicolaskruchten/pivottable#336]
Could you tell me how to get values permanently over the bars in barcharts, either by using annotations or any other method.

![capture](https://cloud.githubusercontent.com/assets/11008498/7830810/4df6766e-046e-11e5-9eeb-15333169f6cf.PNG)

Scroll to "Labelling Bars" in the following link.

https://google-developers.appspot.com/chart/interactive/docs/gallery/barchart

**Comment by philliproso** [comment]
You will need to modify the gchart renderer. I think you can get away with just passing extra options into the barchart, line 110. 

 https://github.com/nicolaskruchten/pivottable/blob/master/gchart_renderers.coffee

**Comment by abanaik** [comment]
@philliproso : I am unable to find where exactly to pass the annotations. As you can see in the example in the link i shared above, it is done for a very sinple chart with hard coded data. I am lost in the code when I try to implement it here. Plus, Chartwrapper is not used in the example in the link.

Here is a JSfiddle of what I am trying to achieve:
http://jsfiddle.net/asgallant/QjQNX/

This example uses the simple chart.draw function, while the plugin here uses chartwrapper to draw. I am unable to find where to put the addColumn as present in the example, in this plugin.

Any help would be appreciated.

**Comment by abanaik** [comment]
So far I have added the following piece of code:

wrapper.setView({
         columns: ([0,1,
                        { calc: "stringify",
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                    2,
                    { calc: "stringify",
                         sourceColumn: 2,
                         type: "string",
                         role: "annotation" }
                   ])   
        });
          
before the  wrapper.draw(result[0]); line. This gives the solution for the example file. See the image below: 
![capture1](https://cloud.githubusercontent.com/assets/11008498/7834104/c730fe58-0489-11e5-8436-aa3506c40c66.PNG)

But the problem is I need to know the exact number of columns for this to work. It is 2 for this chart so it is working fine, but elsewhere it might not. How can I do this dynamically?

**Comment by nicolaskruchten** [comment]
You will not be able to do this without some fairly big modifications to `gchart_renderers.coffee`: there is no way to get what you want by simply passing in extra parameters.
