### ISSUE TITLE
pivot table heatmaps

### ISSUE THREAD

**Issue by jason2591** [nicolaskruchten/pivottable#338]
I need to  modify the heat maps colors for the pivot table and give a custom threshold value for the pivot table values. I have tried trolling through the pivot.js scripts but cant seem to find the function you are using to set the threshold values.

**Comment by nicolaskruchten** [comment]
The `heatmap()`function is here: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L867 but I'm not sure what you mean about "threshold" values... The system interpolates white to red between the highest and lowest values.

**Comment by nicolaskruchten** [comment]
You can now specify a custom color scale function, see the example here: http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html
