### ISSUE TITLE
override functionality about showFilterList

### ISSUE THREAD

**Issue by hoyeol** [nicolaskruchten/pivottable#339]
there "showFilterList" function using e.pageX, e.pageY for decide popup location.
but e.pageX, e.pageY returns position relative to the left edge of the document..
that's a problem when i using pivottable with "nested" div structure.
with "nested" div structure, e.pageX/e.pageY popup location is too far from click point.

so i modified code & using like this.
```javascript
// in showFilterList function..
var offset = $(e.currentTarget).position();
var top = offset.top + 10;
var left = offset.left + 10;
valueList.css({
  left: left,
  top: top
}).toggle();
```
if provide override "showFilterList" function, does not need to modify there pivot source code

**Comment by nicolaskruchten** [comment]
Can you provide an example of the 'nested div' structure which poses a problem? I have been unable to replicate this issue...

**Comment by hoyeol** [comment]
here is the sample. https://gist.github.com/hoyeol/a049a90c524273d19c45

**Comment by nicolaskruchten** [comment]
Super, thanks! I'll take a look :)

**Comment by nicolaskruchten** [comment]
Thanks for this test case. I've actually just implemented your change and it looks like it works :)
