### ISSUE TITLE
Is it possible to populate values in the pivot table only on selecting aggregator ?  

### ISSUE THREAD

**Issue by MPrash** [nicolaskruchten/pivottable#340]
First of all thank you for having such a great plugin for pivotTable.

I am newbie and using Pivot.js , which is great but I want to populate my values in the cell only when we input the aggregator option.
I am using pivot() method for populating pivotTable and by default it takes Count as aggregator.

Is it possible to populate the pivotTable only if we have aggregator parameter in option object while calling pivot() method.

**Comment by nicolaskruchten** [comment]
I don't really understand what you're asking... Can you try to rephrase please? What would you like to have happen if you call `pivot()` without an `aggregator` parameter?
