### ISSUE TITLE
Pivot Table Issue for setting as Static Values .

### ISSUE THREAD

**Issue by alikhan12121** [nicolaskruchten/pivottable#341]
Dear Nicolas Kruchten,

I am using Dynamic Drag and Drop option of Pivot table from your free download basic Example. But i want to fix the values according to my need .. want to fix Row and Column values . But i am not able to fix this . please help me this is Urgent Sir.

**Comment by nicolaskruchten** [comment]
I'm having trouble understanding your request but it sounds like you want to use the `pivot()` function which creates a static table rather than `pivotUI()` which creates a dynamic one...

**Comment by alikhan12121** [comment]
thanks for your prompt reply, I guess you have got my point I am working on your pivot table, what I am doing with it is getting values from Mysql in it and want to fix few values in upper row and few values in left column (as currently it is drag able), each time when we open the page it rearranges all values and I just want to fix each value in it's static place.

**Comment by nicolaskruchten** [comment]
OK, well just use `pivot()` instead of `pivotUI()` then :)

**Comment by alikhan12121** [comment]
Ok will check it

**Comment by alikhan12121** [comment]
I did it but it fixed everything in it and also removed the DropDown Menues .. Please Tell me how to fix it in Horizontal and Vertical Boxes with Menue Drop Downs ...

**Comment by alikhan12121** [comment]
Thanks Nichole Krutchen for your Support i fix that .. But i need last thing to fix which is Price and Total Value against every Agent in table ... As in the following picture P(Price ) and T(total). 
![sample232](https://cloud.githubusercontent.com/assets/12734331/7983728/d8234e1a-0adc-11e5-8a6a-4475b54b9f0e.PNG)

**Comment by nicolaskruchten** [comment]
That's not possible with this library, sorry. See: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi
