### ISSUE TITLE
Custom pivotUI droppable options container

### ISSUE THREAD

**Issue by pjgoncalves** [nicolaskruchten/pivottable#342]
Hey, need to implement something really similar with what pivottable already does, but is there any way i could render the pivotUI() elements in another container? e.g. have the draggable items on my footer but keep the table in my main-content section. basically i want the table and the pivotUI() options in separated containers but still interacting.
ive been playing around with jquery's .clone() but this solution requires alot of bug/error control
![preview](http://i.imgur.com/QWfELvA.png)

**Comment by nicolaskruchten** [comment]
You could hack the `pivot()` function so that it doesn't operate on `this` but instead operates on some other DOM element...
