### ISSUE TITLE
i18n of extra renderers' name such as C3:Line Chart

### ISSUE THREAD

**Issue by deecay** [nicolaskruchten/pivottable#346]
Hi Nicolas,

I think renderers in inputOpts should respect locale parameter passed to pivotUI().

pivotUI()
      if ((existingOpts == null) || overwrite) {
        opts = $.extend(defaults, inputOpts);
      }

In other words, if "ja" is passed to pivotUI as a locale, renderers' name of the renderers passed in as inputOpts should be converted to Japanese. Otherwise adding renderers will always result in English renderer names, regardless of the locale parameter.

Does this make sense to you?

**Comment by nicolaskruchten** [comment]
The renderer (and aggregator) names do respect the `locale` parameter, if the 'language pack' file provides a `renderers` (and `aggregators`) object. See this example: http://nicolas.kruchten.com/pivottable/examples/mps_fr.html

More details on localization can be found here https://github.com/nicolaskruchten/pivottable/wiki/Localization and an example 'language pack' is here: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.fr.coffee

**Comment by deecay** [comment]
Sorry, I should have been more specific. Can you show me how to localize renderers for c3.html demo in French? I do understand that default renderers respect the `locale` parameter, but I couldn't get the manually added ones to be localized.

**Comment by nicolaskruchten** [comment]
If you pass in your own set of renderers, you'll need to make sure the keys of the `renderers` object are in the language you want, as that is what is used in the UI.

**Comment by deecay** [comment]
Thank you. Understood.

**Comment by nicolaskruchten** [comment]
Happy to help!
