### ISSUE TITLE
Custom Tooltip

### ISSUE THREAD

**Issue by sms16** [nicolaskruchten/pivottable#347]
I have used this successfully for my data visualization. Am using the d3 Visualization, but I cannot figure out how to edit the tooltips. Basically I want to have extra information on the tooltip which should be derived from the data I have in other columns of the csv which are not being displayed.  Is there a way to do that?

**Comment by nicolaskruchten** [comment]
Are you using the d3 treemap visualization?

**Comment by sms16** [comment]
I am using d3 Stacked Bar Chart visualization

**Comment by nicolaskruchten** [comment]
You mean C3 Stacked Bar Chart? I just need to know which specific thing is being used before being able to help :)

**Comment by sms16** [comment]
Ah.. my mistake when I said D3. It's actually Google Chart Renderers, as per the example here: http://nicolas.kruchten.com/pivottable/examples/gchart.html . I am using Stacked Bar Chart and regular Bar Chart and wanted to see if I can have custom tool tips here.

**Comment by nicolaskruchten** [comment]
OK. I don't think this will be very easy, but you should refer to the Google Chart documentation to see if they allow you to inject a function as a tooltip handler, and go from there.

**Comment by sms16** [comment]
Hmm ok thanks .. I will dig into it to see if I can find something
