### ISSUE TITLE
pivotUI is not a function

### ISSUE THREAD

**Issue by simonjcarr** [nicolaskruchten/pivottable#348]
I have just downloaded the latest version of this script and linked to pivot.js and pivot.css 

I get the error below, for both .pivot and .pivotUI.

When I run the basic shape/color code, I get the javascript error

Uncaught TypeError: $(...).pivotUI is not a function(anonymous function) 
@ pivottables:161m.Callbacks.j 
@ jquery.min.js:2m.Callbacks.k.fireWith 
@ jquery.min.js:2m.extend.ready 
@ jquery.min.js:2J
@ jquery.min.js:2

**Comment by simonjcarr** [comment]
Sorry,  I had my js imports in the wrong order.

**Comment by MorlaRamakrishna** [comment]
Hi,

What is the correct order for js imports
