### ISSUE TITLE
Date Aggregator

### ISSUE THREAD

**Issue by hissingpanda** [nicolaskruchten/pivottable#349]
Hi, thanks for the great tool!

I was wondering how I could create a custom aggregator that was simply the date from my json file -- so that the day of year would appear as the Y-axis. For instance instead of counting the number of occurrences of an event it would just indicate when an event occurred. Similar to this, without the slope line (although perhaps a separate aggregator to compute the slope):
![chart](https://cloud.githubusercontent.com/assets/7660115/8347598/4624143a-1acd-11e5-8e2c-6e34f76a5f02.png)

I feel like this is simple to do, but can't seem to wrap my head around it.

**Comment by nicolaskruchten** [comment]
If your dataset contains `year`, `county`, `day of year`, `sighting` then you could make this chart with the aggregator = `min(day of year)`, columns = `year`, rows = `county`.

**Comment by hissingpanda** [comment]
Oh that worked great!! Don't know why I didn't think of that... Thanks for the quick reply
