### ISSUE TITLE
Sorters on aggregators

### ISSUE THREAD

**Issue by sms16** [nicolaskruchten/pivottable#350]
Hi Nicholas, I have a google chart renders using PivotUI and I wanted to use sorters as explained here https://github.com/nicolaskruchten/pivottable/wiki/Parameters but such that sorting should happen on the aggregator for the stacked bar chart. 

So, for a stacked bar chart,  if I am aggregating on count of X, then sorting should happen on Count of X. Is there a way or example to do this?

**Comment by nicolaskruchten** [comment]
Unfortunately sorting post-aggregation is not supported at the moment... The `sorters` system is used to set an ordering for attribute values statically, before aggregation/rendering happens.

**Comment by sms16** [comment]
That's unfortunate. Is this something that will be supported in the future or would you recommend using some other rendering instead?

**Comment by nicolaskruchten** [comment]
I don't see this being implemented in the near-future, given the challenges involved in implementing it such that it works efficiently in most use-cases. If you absolutely need this, my recommendation would be for you to make a modified version of the `gchart_renderers` which implements the logic you would like to see.
