### ISSUE TITLE
Unable to store the pivotUIOptions in Cookies

### ISSUE THREAD

**Issue by ramasamynk** [nicolaskruchten/pivottable#351]
hi,
I have used the below code to save the cols and row of pivot table, but it not working for me.

$.getJSON("mps.json", function(mps) {
$("#output").pivotUI(mps, {
derivedAttributes: {
"Age Bin": derivers.bin("Age", 10),
"Gender Imbalance": function(mp) {
return mp["Gender"] == "Male" ? 1 : -1;
}
},
onRefresh: function (pivotUIOptions)
{
createCookie( "pivotcols" , pivotUIOptions["cols"] , 50);
createCookie( "pivotrows" , pivotUIOptions["rows"] , 50);
},
rows: readCookie("pivotrows"),
cols: readCookie("pivotcols")

});
});

thanks

**Comment by nicolaskruchten** [comment]
Can you expand on "it's not working for me"? What are you expecting to have happen, what does happen?
