### ISSUE TITLE
Small typo in docs

### ISSUE THREAD

**Issue by pflans** [nicolaskruchten/pivottable#353]
https://github.com/nicolaskruchten/pivottable/wiki/Parameters

Under "PivotUI" and the key "renderers", the link to the docs has a typo:
https://githubom/nicolaskruchten/pivottable/wiki/Renderers
should be **github.com**

Great library!

**Comment by nicolaskruchten** [comment]
thanks! somehow at some point a whole bunch of two-character sequences got deleted from that file and I don't know how :(
