### ISSUE TITLE
C3 charts do no respect number format

### ISSUE THREAD

**Issue by levmanuel** [nicolaskruchten/pivottable#354]
Hi

Like everyone else here, I love the library : It's so useful on the day-to-day basis.
My question is : the C3 charts (even the Google ones actually) do not respect the numberFormat() format implemented in the pivot.js. I tested it in my computer & [here](http://nicolas.kruchten.com/pivottable/examples/local.html) and thats' all the same.

Do you have any idea where it can be fixed/setup ?

Have a nice day, thanks again for your work.

**Comment by nicolaskruchten** [comment]
Yes, this is problem, and I don't really have a good solution for it at the moment. 

The challenge is that these are external charting libraries with their own number formatting system, and I'm not even sure they support localization at all. PivotTable.js just passes in numerical data and the external charting libraries take it from there and reformat it as they like...

**Comment by levmanuel** [comment]
Up !

It seems it found a way. Basically we must respect the d3.format() https://github.com/mbostock/d3/wiki/Formatting

I passed the modification to the c3_renderers.js file. For instance :

For instance line 111: i modified 

       axis: {
            y: {
              label: vAxisTitle,
              tick:{
                format: d3.format('s')
              }
            },

and for the tooltip box i changed

          tooltip: {
            grouped: false,
            format:{
              value: d3.format(',.7r')
            }

*** you can test your own format number here : http://bl.ocks.org/zanarmstrong/05c1e95bf7aa16c4768e

**Comment by nicolaskruchten** [comment]
OK. There's no need to modify c3_renderers.coffee or c3_renderers.js, as you can pass in these options via the `rendererOptions` parameter to `pivot()` and `pivotUI()`
