### ISSUE TITLE
Force refresh from outside the pivot table

### ISSUE THREAD

**Issue by samuoses** [nicolaskruchten/pivottable#356]
Hi,

First of all I think this component is amazing and I would like to congrats the contributors.

I would like to connect the pivot table with an external filter (ex. month) to select the month outside the component and override the inclusions parameter, the problem is that i don´t know how to force the refresh of the pivot table after do this. Is there a way to do this?

Thank you

**Comment by nicolaskruchten** [comment]
Hi,

There is no way to force a refresh on the pivot table, you can only do a full rerender by calling `pivot()` or `pivotUI()` again with new parameters...

Nicolas
