### ISSUE TITLE
Styling with Bootstrap

### ISSUE THREAD

**Issue by shahbour** [nicolaskruchten/pivottable#357]
I want to style the pivot and pivotUI using bootstrap but where ever i tried to add bootstrap styles for example 'table table-striped table-bordered table-hover' , the table just got corrupted .

Is their any document that we can use to do that ?

**Comment by shahbour** [comment]
Hello

I noticed that it is the same as https://github.com/nicolaskruchten/pivottable/issues/149 , so every thign is good except is their any onRefresh or onRender event or function for pivot and not pivotUI ?

Could not confirm that ?

**Comment by nicolaskruchten** [comment]
There is no `onRefresh()` callback for `pivot()` because `pivot()` renders just once, synchronously and never changes thereafter, so you can just call whatever function you like right after `pivot()` returns and you'll get the same effect.

**Comment by prernadubey** [comment]
Hello

 I am trying to add bootstrap styles for example ' table-hover', but it's not working.

Below is what I tried. 

**onRefresh: function() {
		$('.pvtTable').addClass('table-hover');
}**

Let me know if doing anything wrong!

**Comment by nicolaskruchten** [comment]
@prernadubey please open a new issue rather than commenting on a closed one...

Please include an explanation of what you expected to happen and what does happen as "it's not working" is not clear enough for me to help you.

**Comment by prernadubey** [comment]
Thanks Nicolas. Issue #701 is raised for the same.
