### ISSUE TITLE
Is it possible to format negative values with a () instead of -

### ISSUE THREAD

**Issue by AlicePain** [nicolaskruchten/pivottable#359]
Awesome control, thank you for putting this out.
Running into an issue, it's not a bug, I just can't figure out how to make this work.  

In the Cells and totals I'd like to show negative values with () instead of the default -
Example: (20,000.00) instead of -20,000.00

Here's the code I'm using 

 var createPivot = function (data) {
            $(function () {
                var sum = $.pivotUtilities.aggregatorTemplates.sum;
                var numberFormat = $.pivotUtilities.numberFormat;
                var currencyFormat = numberFormat({ digitsAfterDecimal: 2 });

                $("#pivotSummary").pivot(
                    JSON.parse(data.data),
                    {
                        cols: data.columns,
                        rows: data.rows,
                        aggregator: sum(currencyFormat)(data.matrix)
                    }
                );
            });
        }

**Comment by nicolaskruchten** [comment]
It is possible, but you will have to write your own number formatter (perhaps one that wraps `currencyFormat`) to accomplish this.
