### ISSUE TITLE
Data source size

### ISSUE THREAD

**Issue by projecthate** [nicolaskruchten/pivottable#36]
Hi, I'm having trouble implementing a rather large data source through the pivot table. The source is currently about 300,000 rows with 12 columns.

As I begin to increase the number of rows I'm selecting, it gets slower and slower, eventually not loading at all. I mean, the data is returned from the server, but the page is just blank. Here are some numbers:
1,000 1.12MB 581ms
10,000 2.4MB 939ms
15,000 3.6MB 1.46s
50,000 12.0MB 4.76s

This is # of records, size of response and response time in Chrome x64.

Anything after 15,000 does not render a chart or table at all. 

I see someone posted in https://github.com/nicolaskruchten/pivottable/issues/29 a similar issue and he said that he resolved it by breaking his ajax requests apart. But I'm not really sure how to do this. I can't find anything in the documentation that lets data be loaded in piecemeal, after the initial instantiation of the table. Is this possible?

**Comment by gibito** [comment]
Hi @nicolaskruchten 
After extensive testing, cardinality is definitely the culprit here. You can have 1,000,000 rows with recurrent items and all is fine. When you have even only 500 rows and each row has a different item, then we hang and crash the browser. Could you show us the points where we can insert defensive coding preventing this? Thanks.

**Comment by nicolaskruchten** [comment]
I would be very interested in seeing a 500-row input which will cause this to hang! Can you share it please?

**Comment by gibito** [comment]
Simply construct an array like:

 [
        {color: "color1", shape: "shape1", owner: "owner1", ....},
....
        {color: "color500", shape: "shape500", owner: "owner500", ....}
 ]

This does not allow any grouping and table buildup/DOM nodes become the bottlenecks.

**Comment by nicolaskruchten** [comment]
Ah OK if you actually try to build a 10M-cell table, yeah, rendering will be a problem. But the initial parse of the data and default render (i.e. one cell containing the counts) will work etc.

**Comment by gibito** [comment]
Yes, parsing is no the issue. HTML table build up and rendering are.

Have you considered using alternative to HTML table that use virtual rendering of the viewport? (e.g., Slickgrid)

Or any other architectural strategy you can recommend to prevent the browser from hanging?

**Comment by nicolaskruchten** [comment]
Certainly one could write a new Renderer which uses a different strategy than DOM operations to build a table. That said, I'm not sure how useful it is to be able to render tables that big and sparse, from a UI point of view, so I have not put any effort into solving this problem... :)

**Comment by gibito** [comment]
Fully agree that it is not useful. It is important to prevent user from hanging the browser by mistake (e.g., automatic projections of rows in a spreadsheet). I am talking about defensive coding.

It would be great if you could point us to a place in the code where we can stop DOM operations in case of high cardinality. Thanks.

**Comment by nicolaskruchten** [comment]
Sorry for the long delay in answering here.... You could stop DOM operations in the TableRenderer based on the number of rows/cols.

**Comment by yolnda** [comment]
Hi Nicolas,

how about get data from url ?

**Comment by nicolaskruchten** [comment]
@yolnda please don't comment on old, closed issues. Please create a new issue with a clearer description of your question.
