### ISSUE TITLE
Request for new built-in dateFormat in deriver

### ISSUE THREAD

**Issue by deecay** [nicolaskruchten/pivottable#360]
Hi, I propose adding week-number as a built-in helper for deriver's dateFormat.

case "W":
   var firstJan = new Date(date.getFullYear(),0,1);
   return Math.ceil((((date - firstJan) / 86400000) + firstJan.getDay()+1)/7);

It goes very nicely with scatter plot, and other time series analysis.

**Comment by nicolaskruchten** [comment]
Thanks for your proposal :)

I've discussed this in the past here https://github.com/nicolaskruchten/pivottable/pull/77 and concluded against including it, given the wide variety of different ways to compute the "week number".

**Comment by deecay** [comment]
Understood. Thanks.
