### ISSUE TITLE
Maximum/Minimum aggregator with a DATE

### ISSUE THREAD

**Issue by LukePivot** [nicolaskruchten/pivottable#362]
Hi Nicolas,

I'm hoping it's something basic like date formatting that I'm doing wrong (or maybe some setting that can be tweaked somewhere), but I stumbled upon an issuer earlier today.

When using the maximum/minimum aggregator with a DATE, it looks like it treats the date as a decimal and doesn't display a date.

I tried two different formats:  yyyy-mm-dd and mm/dd/yyyy and the max/min aggregators appear to chop the first section of the date off and display that on the output.

For example, a row with a max date of 12/15/2014 shows 12.00 and 2014-12-15 shows 2014.00

Do you have any tips on getting a date to show in there?  

For comparison (and I know it's not apples/apples), if you do the same in Excel and do max/min with the date field, it displays a date.  There's one app we built where this max/min functionality would be perfect, but having the date show on there is key to it.

Thanks a ton for any info/help!

**Comment by nicolaskruchten** [comment]
The min/max aggregators just treat everything as a number I believe so that's why they just look at the first number in your date string. You will likely have to copy and modify the min/max aggregators to become date-aware. Take a look at the code for them and let me know if you need a hand :)

**Comment by nicolaskruchten** [comment]
18 months later... The min/max operators now work on things other than just numbers, so out of the box they work with ISO-formatted dates (YYYY-MM-DD) and the `sorters` mechanism can be used to get it to handle arbitrarily-formatted dates.
