### ISSUE TITLE
how to disable drag and drop panels?

### ISSUE THREAD

**Issue by tiny-byte** [nicolaskruchten/pivottable#363]
Hi there
thank you for this greate tool!
I would like to generate a "pivotUI" with prefilled data.but I don't want to let user play around with it.
for example if I created with ("rendererName": "Heatmap"), I don't want user to be able to change it, and also I would like to disable dragging of the items and moving it between columns and rows.
how can I do that?

**Comment by nicolaskruchten** [comment]
Have you considered using `pivot()` instead of `pivotUI()`? This will generate just the table but not the UI around it.

**Comment by tiny-byte** [comment]
I thought of that but then it was not capable of rendering charts and other advance stuff.but I did get around this problem by setting style of that parts

.myContainer .pvtUi tr:first-child , .myContainer  .pvtAxisContainer {
        display: none;
    }

but I don't feel that's a good way to handle this.what do you think?

**Comment by nicolaskruchten** [comment]
Everything that works with pivotUI() should work with pivot()... Can you give me an example of charting that doesn't work with pivot() ?

**Comment by tiny-byte** [comment]
sorry I can't find time to make an example right now, but I will get back to you on this.
btw I got some other issue, should I post another thread or here?
I get requests to pivot.js.map, d3_renderers.js.map , ... all javascript files for pivot, but I don't have any errors in console, how can I inspect this further?

**Comment by nicolaskruchten** [comment]
Please do create a new issue for each question :)

I encourage you to google 'JavaScript source maps' for more info on the .js.map files...

**Comment by ayozebarrera** [comment]
Hi, I want to use pivotUI but without dragging cols and rows, I just need the filter options! Any advice?

Thanks

**Comment by nicolaskruchten** [comment]
@ayozebarrera this will not be possible without hacking the library itself.

**Comment by ayozebarrera** [comment]
I see, thankyou!

Just as feedback... that filter options (or charts display...) are great but it would be nice if we can achieve a pivotUI mode with some restrictions like disable dragging...

Why?
Because If I need to disable draggings and I need filters, I has to use pivotTable (not UI) and create buttons (out of the pivottable) to make filters.

Maybe I'm wrong!

thanks for the reply

**Comment by primobotas** [comment]
Hi Nicolas
I'm a biologist. This is my first attempt using javascript. I have some background using Perl
I've been playing around with Pivot.js and it's a great tool and a fun way to learn js! Thanks!!

As @tiny-byte and @ayozebarrera I would also like to restrict users form dragging cols and rows but retain the ability to select and unselect options in the filter boxes.
This could make the UI more friendly and intuitive for unprepared users.

> to use pivotTable (not UI) and create buttons (out of the pivottable) to make filters.
Could be an option. I'm am trying the filter function in pivot()

Sorry if I'm not following the github ettiquette (I'm a newbie!): I also vote this enhancement

**Comment by FloPrey** [comment]
Hi.
I know normally you should not comment under a closed issue but I ran into the same problem.

A config providing the functionality as described by @primobotas and @ayozebarrera would be awesome.
Till this I created a workaround with CSS if someone runs in the same issue.
I don't like it, but it's better than nothing.
`pivotElement.find('.pvtVertList').css('display', 'none');
pivotElement.find('.pvtHorizList').css('display', 'none');
pivotElement.find('.pvtRows').css('display', 'none');
pivotElement.find('.pvtRendererArea').attr('colspan', '2');`

But a configuration doing this without CSS would be appreciated.
Cheers.

**Comment by nicolaskruchten** [comment]
@FloPrey have you tried using `pivot()` instead of `pivotUI()` ?

**Comment by abhikvnair** [comment]
Hi,
How can i include close button in FilterBox / close FilterBox when i click outside. Any advice ?
Thanks

**Comment by abhikvnair** [comment]
when we use minimal items in filterbox cancel button can't see properly

**Comment by nicolaskruchten** [comment]
@abhikvnair this issue is closed, please create a new one rather than commenting on old, closed issues.
