### ISSUE TITLE
Prevent filtering out pre-defined objects

### ISSUE THREAD

**Issue by jacquesdev** [nicolaskruchten/pivottable#364]
I have a number of custom (and blank) records in my dataset that exist for the purposes of aggregating. In other words, the only value they have which is populated, is the field that is being aggregated on. I would like the data to appear, but to disable the option of filtering them out, since as soon as you filter it out, it breaks the dataset that I want to display.

I have had a look at exclusions, but it seems that an exclusion merely unfilters the record on initial load, perhaps I am mistaken. I would guess Filters filter out the data, which is also not exactly what I need. 

Could you perhaps suggest something I could use?

**Comment by nicolaskruchten** [comment]
I'm not sure I understand what you're doing here... Can you give me a concrete example?
