### ISSUE TITLE
Fixed Columns and headers. Scroll table data only

### ISSUE THREAD

**Issue by Khush-Gill92** [nicolaskruchten/pivottable#365]
Hello,

I was wondering if someone could point me in the right direction for making fixed rows and column headers. I only want to scroll through the data horizontally and vertically. I want the drag and drop headers in the x and y axis of the table to remain fixed.

I have unsuccessfully tried to access and manipulate elements of the table via html and css.

**Comment by nicolaskruchten** [comment]
You will have to either create a new Renderer based on the default Table one that works the way you want it to, or you will have to let the default Renderer render and then modify its HTML/CSS via Javascript calls (similar to how the Heatmap Renderers work)
