### ISSUE TITLE
Sorting the Pivot Table

### ISSUE THREAD

**Issue by wreiske** [nicolaskruchten/pivottable#366]
Is it planned to support sorting in the Pivot Table?

**Comment by ZokiA** [comment]
You can try 'NReco extensions for PivotTable.js' at http://www.nrecosite.com/pivot_table_aspnet.aspx

**Comment by nicolaskruchten** [comment]
I don't have any concrete plans to implement sorting by value, no... 

See also the FAQ here: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#sorting-in-built-in-table-renderer
