### ISSUE TITLE
save options after initialization 

### ISSUE THREAD

**Issue by shahbour** [nicolaskruchten/pivottable#367]
First , i would like to thank you for the great project , it was very handy and gave great result .

I am looking to allow user to save different templates (he create them through pivotUI) , so is it possible to export the current options (after user drag drop some columns ... ) .

I saw that the options are already saved per issue #13 #14 but i want to save them into database so i can retrieve them later and share them between different users .

BR
Shahbour

**Comment by shahbour** [comment]
I think in found it , we can use the onRefresh function to do that 

thanks

**Comment by nicolaskruchten** [comment]
Great, glad you found your way to a solution :)
