### ISSUE TITLE
Uncaught TypeError: Cannot set property 'c3_renderers' of undefined

### ISSUE THREAD

**Issue by srini-raju** [nicolaskruchten/pivottable#368]
Hi,
I am trying pivot table in single page app with Angular and i keep running into this error. Some times it goes away and i can see the graph but i get this error a lot of times. I am using jquery 2.11, if that is causing this issue. Appreciate any help.

Thanks,
Srini

**Comment by srini-raju** [comment]
Nicolas, great project. I was using lazy loading and something was clashing with other scripts. Loading the js and css in the main page solved the problem.

**Comment by lcustodio** [comment]
If someone end up here like me, make sure that the `c3_renderers` is loaded just after `pivot.min.js`
