### ISSUE TITLE
How to override col and row names.

### ISSUE THREAD

**Issue by kitta5** [nicolaskruchten/pivottable#37]
I would like to override the col and row names for displaying.

For Example:
{color: "blue", shape: "circle"},
 {color: "red", shape: "triangle"}

The above json column value is color and row value is shape. But i want to display instead of color as "Background Color" and shape as "Graph Shape".

Currently i am returning the json from java object.

Can you help me on this.

**Comment by scottward** [comment]
A workaround would be to create derived attributes. I did:

          derivedAttributes: {
              "Quarter": function(record) {
                  return record["quarter_name"];
              }
          }

**Comment by meenakshijha** [comment]
@scottward Thanks for this code snippet. It helped! Next I want the names (like Quarter in the above example)to be assigned dynamically upon what the user chooses. Any idea how that can be achieved?

Thanks

**Comment by scottward** [comment]
Yeah, not sure about that...

**Comment by steveweiwang** [comment]
I do think labels are needed for attributes. I am developing for Chinese and I believe Asian and many other languages cannot be directly used as keys or variable names in coding languages.
