### ISSUE TITLE
loading new parameters and refreshing

### ISSUE THREAD

**Issue by ousemag** [nicolaskruchten/pivottable#370]
Hello Nicolas!

I am web developer and I found your JQuery Pivot Table. First of all, let me tell you that this stuff is brilliant!!!!!

I use it and implemented data to have a play with it. It bring my website to another level that users really enjoy!

I have a question about the screen below. 
http://nicolas.kruchten.com/pivottable/examples/onrefresh.html

I am not an expert at all in javascript, I still managed to store a configuration in a txt file locally for users but I struggle to load it and implement it in the pivot table it is already 2 days I am trying to do it, it frustrates me.

Would you have an example of implementation of the code on loading of configuration from a file or another external source? You help would be so grateful for me!

I also forward you what I built (it can look very dirty and basic but it's all I can do at my level ;) )
<script type="text/javascript">
            $(function()
            {
                $("#fileLoad").bind("change", function(event)
                {
                    var reader = new FileReader();
                    reader.onload = function(theFile) 
                    { 
                        try 
                        {
                            var NewConf = theFile.target.result;
                        }
                        catch(e) 
                        { 
                            alert("Txt File error.");
                            return; 
                        }
                        $(function(){
                            
                            var derivers = $.pivotUtilities.derivers;
                            
                            $.get("../../PivotTables/ActionCQs-PN-12-Jun-23-Jun.csv", function(mps) {
                                var renderers = $.extend(
                                        $.pivotUtilities.renderers, 
                                        $.pivotUtilities.c3_renderers, 
                                        $.pivotUtilities.d3_renderers,
                                        $.pivotUtilities.export_renderers
                                        );

                                $("#output").pivotUI($.csv.toArrays(mps), NewConf ,true); //This is not working I suppose it is because the variable content is a string and should be another type to be read properly but I have no idea how to do it
                            });
                         });
                    }
                    reader.readAsText(event.target.files[0]);
                });  
            });                    
            </script>

Thank you

Magalie

**Comment by nicolaskruchten** [comment]
Hi Magalie,

I'm sorry I haven't gotten back to you more quickly. I'm afraid I'm not sure I understand what you're trying to do, so please do forward me what you've built and I'll try to help you debug it.

**Comment by ousemag** [comment]
Hi Nicolas, 

I am using a .csv file loaded of data coming from another database in Oracle (I also use coldfusion code for it). The csv file is created and overwrite almost time, on each load of the page. I try to allow the use to save a configuration for the pivot table tools, to be able to reload it  quickly for a future use. I started from your "onRefresh" option to build a text file when users want to save their current display. I managed then to load the configuration from the text file using the code JSON.parse(#content of my text file#). This part took me a while because my skills in javascript are less than basic. However now I am still stuck. I can load a configuration without having to reload the whole page but I lose the "onRefresh" option. Users can't also load their own display of the pivot table to rework it and resave it. I am back to load the whole page to be able to use the "onRefresh" option and allow them to still save their own configuration. 

Thank you for your help

My code:
<script type="text/javascript">
            $(function()
            {
                $("#fileLoad").bind("change", function(event)
                {
                    var reader = new FileReader();
                    reader.onload = function(theFile)
                    {
                        try
                        {
                            var NewConf = theFile.target.result;
                        }
                        catch(e)
                        {
                            alert("Txt File error.");
                            return;
                        }
                        $(function(){
                           
                            var derivers = $.pivotUtilities.derivers;
                           
                            $.get("../../PivotTables/ActionCQs-PN-12-Jun-23-Jun.csv", function(mps) {
                                var renderers = $.extend(
                                        $.pivotUtilities.renderers,
                                        $.pivotUtilities.c3_renderers,
                                        $.pivotUtilities.d3_renderers,
                                        $.pivotUtilities.export_renderers
                                        );
                                $("#output").pivotUI($.csv.toArrays(mps), JSON.parse(NewConf) ,true);
                            });
                         });
                    }
                    reader.readAsText(event.target.files[0]);
                }); 
            });                   
</script>

**Comment by nicolaskruchten** [comment]
You could just add your `onRefresh` callback to the output of `JSON.parse` before passing it in to `pivotUI` I think

**Comment by thovo** [comment]
First of all, your library is awesome :+1: 
Second, come back to this issue, I want to do the same like @ousemag and I don't understand how would I do it follows your suggestion.

My situation: I already have my data available in screen, I allow the user can modify the column list, the aggregation...and he/she can save it in a template so when switching between template, he would see the pivot change accordingly.I think it would be nice if I can target the pivot as an object and send to it the configuration I want. I really don't want to call the data again and append new config because my data is quite big, around 100k-150k lines.

My sample code here:
http://codepaste.net/9huq2i

**Comment by subotin94** [comment]
How can i export table to pdf on Node.js using JSDOM, expecting the same output as browser's feature pring would do with it?
