### ISSUE TITLE
Charts title

### ISSUE THREAD

**Issue by grzegorz-pierzakowski** [nicolaskruchten/pivottable#371]
Hi Nicolas,
Could you add an option for a title, that if set would be shown in the GCharts or d3Charts as the chart title, please.
{
.....
chartTitle: "some string",
...
}
if set to false would disable the title.
if undefined the title would be calculated as is.
Thank you.
Cheers Grzegorz

**Comment by nicolaskruchten** [comment]
This doesn't make a lot of sense in the context of `pivotUI()` given that the chart contents are user-controllable...

**Comment by lbk3918** [comment]
Agreed not relevant for pivotUI(), however it would be useful for pivot().
The title for gcharts is always Count vs x by y, even if you are aggregating using a sumOverSum.

**Comment by nicolaskruchten** [comment]
Sorry for the long delay on this issue. You need to specify the `aggregatorName` parameter in `pivot()` to get an appropriate title.
