### ISSUE TITLE
Add "customClass" to options to style the pivotTable

### ISSUE THREAD

**Issue by Novitoll** [nicolaskruchten/pivottable#374]
Pivottable renders `<table>` with already *pvtUi* table class. [Link](https://github.com/nicolaskruchten/pivottable/blob/master/dist/pivot.js#L1039). Let's set this class as a default, and allow to have an "customClass" as an option

**Comment by nicolaskruchten** [comment]
If you really need to add custom classes, I recommend doing it via jQuery in an `onRefresh` callback.
