### ISSUE TITLE
Changing pivotUI setting

### ISSUE THREAD

**Issue by gsimenel** [nicolaskruchten/pivottable#375]
Hi,

I'm trying to build an AngularJS directive for pivotUI that provides 2 ways data binding for the configuration (the objective is to have buttons that fire predefined configurations and also to save the configuration as it is changed). 

It seems that when I already have a pivotUI element and launch another pivotUI with a different configuration, the onRefresh function is called with the earlier config not the later. I have no experience with jQuery, and I fear I might be missing out an instruction. If not is that a desired behavior ? 

Thanks a lot.
Guillaume

**Comment by nicolaskruchten** [comment]
I'm not sure I understand what you are describing... Are you able to point me to an example?

**Comment by gsimenel** [comment]
Hi,
(Sorry for the delay answering).
Here is a fiddle : http://jsfiddle.net/0fxogxuj/1/ 
When you look at the console, the table sets up just fine. Then click on the button, it calls a function that changes the $scope.conf variable. This is watched by the angular directive, so it starts the changeConf function (you see in the console that the conf variable is indeed resetted). Then pivotUI calls it refresh function and here you see that the conf is the old one... 
Is this any clearer ? 
Thanks for the help.
G

**Comment by nicolaskruchten** [comment]
I'm sorry that I never responded to this issue... Is it still current/do you still need an answer?

**Comment by gsimenel** [comment]
Hi Nicolas,
Yes I still need an answer. BTW I tried to update the fiddle with 2.0.2 but
the behavior is the same.

**Comment by nicolaskruchten** [comment]
OK, I will try to learn a bit about AngularJS to make this work :)

**Comment by gsimenel** [comment]
Let me know if I can help. I'm not a super expert in AngularJS but if I can
give it a shot.
