### ISSUE TITLE
Is Clearing Browser History Mandatory?

### ISSUE THREAD

**Issue by AmitGoutham** [nicolaskruchten/pivottable#376]
Hi,
When using pivot.js, it works fine when i clear browser history(from beginning of time).But, it does not work when i don't clear browser history.
In either case, i'm getting 
"Uncaught TypeError: Cannot read property '0' of undefined(anonymous function) @ pivot.js:1322Q.extend.each @ sap-ui-core.js:16Q.fn.Q.each @ sap-ui-core.js:16(anonymous function) @ pivot.js:1319" error.
Any help will be appreciated.Thanks!

**Comment by SachinSinghGusain** [comment]
Hi Amit,

Even I am facing the same issue.
Please let me know if you find any solution.

**Comment by nicolaskruchten** [comment]
Clearing history is absolutely not required! All of the examples work just fine without this: http://nicolas.kruchten.com/pivottable/examples

Based on your stack trace, there are other scripts from `sap-ui-core.js` which are likely interfering with the proper functioning of PivotTable.js...
