### ISSUE TITLE
How do I suppress the "Totals" column?

### ISSUE THREAD

**Issue by holstius** [nicolaskruchten/pivottable#382]
I'm using your (awesome) library via the [rpivotTable](https://github.com/smartinsightsfromdata/rpivotTable) wrapper, but am guessing that this is the right place to ask the question:

Q: How do I suppress the "Totals" column? 

Didn't find an answer in the FAQ. Many apologies if I missed it in there or elsewhere in the docs!

**Comment by nicolaskruchten** [comment]
There is no option to hide the totals, unfortunately. More generally, there is no UI for renderer options at all.

The only way to do what you seek would be to hide it via CSS, which might be tricky if you're using it through R...

**Comment by holstius** [comment]
Oh well. Thanks anyway --- the R package is great! Turned some heads with a demo at work today. Many thanks for your fine contributions!

**Comment by nicolaskruchten** [comment]
I'm glad it's a useful tool! :)
