### ISSUE TITLE
Feature request: error bars (averages and std. dev.)

### ISSUE THREAD

**Issue by ykil** [nicolaskruchten/pivottable#383]
Awesome work! This tool has been quite helpful.  I was wondering if there's a way to manage replicates.  That is, same experiments are measured many times.  We then want to see the average and errors. Is there a way to do this now or any plans for this for later?

As example, the flat table input can be:
```
sample, replicate, measure1, measure2
A, 1, 0.5, 0.4
A, 2, 0.6, 0.3
A, 3, 0.4, 0.5
B, 1, 0.2, 0.31
B, 2, 0.3, 0.32
B, 3, 0.1, 0.33
```
In the above example, we have two samples (A and B), which were measured 3 times (replicate 1,2,3).

We want pivot table to show:
```
      Measure1 (avg), Measure1 (std.dev.), Measure2 (avg), Measure2 (std.dev.), 
Sample A 0.5, 0.1, 0.3, 0.1
Sample B 0.2, 0.1, 0.3, 0.01
```

The actual organization of the table is not critical, but we'd want to pass this to plotting as well to look like, e.g.:
https://www.google.com/search?q=error+bars&es_sm=93&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIyrvogtjRxwIVgb-ACh3zRwel&biw=1280&bih=637

Thanks in advance.

**Comment by nicolaskruchten** [comment]
This is a good idea, but unfortunately I don't think it will ever be possible with this library. Essentially it boils down to a custom display for multiple aggregators, which is a frequently-requested but architecturally-incompatible change.

**Comment by ykil** [comment]
Thanks for the quick reply.  Here's a proposed workaround.  Could you let me know what you think?  

The idea is to wrap your pivot table function.  I would manually split the input flat table per replicate and call your pivot table and then use those pivot tables results to create averages and std.dev, per cell.

I don't think these rendering libs provide error bar rendering.  I suppose I'll need to customize plots to accept error bars.

**Comment by nicolaskruchten** [comment]
I'm not sure I follow what you're proposing...

**Comment by ykil** [comment]
I've edited my previous comment.  Let me know if it clearer now. Thanks.

**Comment by nicolaskruchten** [comment]
OK. If this will do what you're looking for, great, but I'm not sure how much value PivotTable.js is bringing you here :)

**Comment by ykil** [comment]
I think this will let me continue to use your user interface and pivot table algorithm.  I'm open to other suggestions if you have any.  Thanks.

**Comment by nicolaskruchten** [comment]
If you reshaped your input to look like this...

```
sample, replicate, measure_name, measure2
A, 1, 0.5, measure1
A, 2, 0.6, measure1
A, 3, 0.4, measure1
B, 1, 0.2, measure1
B, 2, 0.3, measure1
B, 3, 0.1, measure1
A, 1, 0.4, measure2
A, 2, 0.3, measure2
A, 3, 0.5, measure2
B, 1, 0.31, measure2
B, 2, 0.32, measure2
B, 3, 0.33, measure2
```

... and you added a standard deviation Aggregator, then you could load the input once and generate just two tables: one for average and one for standard deviation. This would scale better to large numbers of replicates.

**Comment by ykil** [comment]
Thanks for letting me know (just noticed there was a response).  I'll definitely look into this.  One question.    If I have two tables, is there a good way to pass the information to make plots with error bars (assuming we have such rendering plots).

**Comment by nicolaskruchten** [comment]
There is no easy way, you'd have to hack something together...

**Comment by ykil** [comment]
OK.  I'll think about it and let you know if I have additional solutions.
