### ISSUE TITLE
crossfilter backend

### ISSUE THREAD

**Issue by declann** [nicolaskruchten/pivottable#384]
Hi,

I'm building a project for financial projection modelling and hooked my output both into crossfilter with coordinated views and pivottable. Both tools are clearly really capable to deal with tens of thousands of records and ample columns/dimensions (though I will need to scale this well up).

So is a suggestion to create a crossfilter backend for the pivottable UI (which is really great) a fair or a redundant suggestion? Will the current backend scale just as well/better? Have you already considered what Crossfilter has to offer? Are different methodologies *appropriate*? (Crossfilter incremental filtering focused, pivottable summarising focused) - if so this is a terrible idea.

If there is value to it, it might be sensible for me to try to work on and share - I prefer one copy of my data/dimensions in memory and not 2. Right now its early days for my experience in both tools so I'm hoping someone more expert can put my thinking in line. If you feel so inclined feel free to tear my thinking apart :)

Thanks
Declan

**Comment by m1sta** [comment]
+1

**Comment by nicolaskruchten** [comment]
Unfortunately, this library and Crossfilter solve different problems in incompatible ways... The [main Crossfilter page](http://square.github.io/crossfilter/) sums it up pretty well: 

*Since most interactions only involve a single dimension, and then only small adjustments are made to the filter values, incremental filtering and reducing is significantly faster than starting from scratch. Crossfilter uses sorted indexes (and a few bit-twiddling hacks) to make this possible, dramatically increasing the perfor­mance of live histograms and top-K lists.*

PivotTable.js actually recomputes and rerenders the output on every change in the UI, because most changes (other than those involving the dropdown menu for filtering) require it: changing aggregators, columns, rows, values, etc.

The best way to use Crossfilter with PivotTable.js would be to build a renderer which uses Crossfilter.

**Comment by declann** [comment]
Thank you for that Nicolas.

Therefore, there is a place for both in one project.

My next problem is the realisation that my project ultimitely won't /fully/ scale under either of these tools! v(I can scale back in a big way - but I'm researching the ambitious plan before I give up!)

I came to think about making PivotTable.js work with an OLAP backend as a potential solution on that end, and that could be a seperate feature request. But I went searching for alternatives. I came across something you wrote a while back - https://news.ycombinator.com/item?id=5938744

"We routinely use this tool [PivotTable.js] to summarize datasets which are, at their most disaggregated, hundreds of millions of rows. We have a server-side process which rolls those up into hundreds of thousands of rows, which are then fed to the browser via a query interface which tends to send only a few thousand at a time, which is easily handled by this tool.

Each step in this pipeline 'summarizes' to an extent, and the last mile is this interactive client-side tool, which would be less responsive if it were server-side."

This is nice.

Fair enough if your backend process is propietary, but to bring my project all the way I would need a substitute to fill my gap, something that works easily with Node. Cube [https://github.com/square/cube] built on MongoDB was a good starting point but no longer maintained. This might be a place for me to pick up, but not something practical for me in the near future.

Mondrian can work, but a bit on the convoluted side to integrate with Node.js, (and it's Java and does nothing for me right now when I try to run it - maybe my attitude here needs to change) http://highscalability.com/blog/2013/11/11/ask-hs-what-is-a-good-olap-database-choice-with-nodejs.html

It will take me a while to move on from any of this as I am still developing on a small scale. A lot of the information I've found from searching about this problem is very old. Do you know any other relevant starting point for what you have here? I'm surprised that/if nothing's come in to fill the gap left by Cube.

Perhaps I will suck it up and go with querying a propietary cube from Node, if that's possible, and pumping results to PivotTable.js.

Do you want me to setup a new issue to feature request operating with OLAP cubes? (which I can at least use to document my findings, when I look into this further myself)

**Comment by nicolaskruchten** [comment]
Seems like you're on your way! If you have any problems or requests for PivotTable.js, feel free to create individual Github issues for them.
