### ISSUE TITLE
Display Derived Attribute by Default

### ISSUE THREAD

**Issue by AmitGoutham** [nicolaskruchten/pivottable#385]
Hi Nicolas,
In my customizaton, i'm showing "Sum" aggregation by default. As a result it loads as follows :

![1](https://cloud.githubusercontent.com/assets/8773462/10011139/ede16fb0-6113-11e5-8f91-ac0e5c37771c.PNG)

The derived attribute needs to be selected after the load.
But, i require one of the derived attributes to be selected by default as below : 

![2](https://cloud.githubusercontent.com/assets/8773462/10011158/15fdc53e-6114-11e5-8c2f-3c8ab3dbeb15.PNG)

Any help will be appreciated!
Thanks!!

**Comment by nicolaskruchten** [comment]
Try the `vals` parameter set to `["Age"]`.

**Comment by AmitGoutham** [comment]
Cracked this!appended a blank value to the derived attribute list and called refresh()

**Comment by nicolaskruchten** [comment]
OK :)
