### ISSUE TITLE
Two column for TOTAL.

### ISSUE THREAD

**Issue by hazwanfowzi** [nicolaskruchten/pivottable#387]
is it possible to add 1 new column for Total?
Thanks in advance :)

**Comment by nicolaskruchten** [comment]
I don't understand the question... Where/why would you like a second totals column?

**Comment by hazwanfowzi** [comment]
sorry late reply, i actually i have 2 measurement to count in the pivot-table (as image attached).
![solve](https://cloud.githubusercontent.com/assets/13723729/10655043/94420ac6-78a3-11e5-90af-a09777814a5f.png)

I already solve the problem..
Thanks with the greate pivot-table :+1:

**Comment by chyasif** [comment]
> sorry late reply, i actually i have 2 measurement to count in the pivot-table (as image attached).
> ![solve](https://cloud.githubusercontent.com/assets/13723729/10655043/94420ac6-78a3-11e5-90af-a09777814a5f.png)
> 
> I already solve the problem..
> Thanks for the nice pivot-table 👍

Would you please share the solution ?
