### ISSUE TITLE
Clear Filter 

### ISSUE THREAD

**Issue by sourabhtiwari** [nicolaskruchten/pivottable#388]
Hi.

Great Work Sir 

I am very happy with your tool.I am customizing it according to my need.But having some of my issues.

I need a Clear Filter option on fields and column and row selections.Can you please help me on implementing that.

**Comment by sourabhtiwari** [comment]
Help Guys I have time restriction to complete project.any help appreciated

**Comment by nicolaskruchten** [comment]
There is no such feature, and it would be quite involved to build. Your best bet is to just rerender the pivot table by calling `pivotUI()` again.

**Comment by sourabhtiwari** [comment]
I have tried calling pivotUI again but it loads data with applied filters, columns and rows.it does not reinitializes pivot from very begining

**Comment by nicolaskruchten** [comment]
OK, you'll have to use the `overwrite` parameter set to `true` to get what you're looking for, as per https://github.com/nicolaskruchten/pivottable/wiki/Parameters#pivotuiinput-options-overwrite-locale

**Comment by sourabhtiwari** [comment]
THANKS FOR QUICK REPLY BUT I AM NOT GETTING IT PROPERLY..HERE IS WHAT I HAVE CODED FOR NOW

 $("#output").pivotUI(data, {
                             "hiddenAttributes" : ["DEAL VERSION DETAIL ID","CURRENCY NAME1","DEAL QUALITY NAME1"],                             
                             "renderers": renderers,  
                             "cols": [""], "rows": [""],
                             "aggregatorName": "Sum",
                             "autoSortUnusedAttrs" : true,
                             "menuLimit" :5,
                             "unusedAttrsVertical" :true,
                             "rendererName": "Table",
                             "unusedAttrsVertical": true,
                              onRefresh: function(config) {
                                var config_copy = JSON.parse(JSON.stringify(config));
                                // console.log(config_copy);
                                //delete some values which are functions
                                var mypivot_exclusions;
                                mypivot_exclusions = config["exclusions"];
                                //  console.log(mypivot_exclusions);
                                delete config_copy["aggregators"];
                                delete config_copy["hiddenAttributes"];
                                delete config_copy["renderers"];
                                delete config_copy["cols"];
                                delete config_copy["rows"];
                                delete config_copy["derivedAttributes"]
                                 // console.log(config_copy);
                                //delete some bulky default values
                                delete config_copy["rendererOptions"];
                                delete config_copy["localeStrings"];
                                var abc = JSON.stringify(config_copy, undefined, 2);
                                console.log(config);
                            $("#config_json").val(abc);
                        }  
                         });

**Comment by nicolaskruchten** [comment]
Right at the very end, before the ");" you need to put ", true".

**Comment by sourabhtiwari** [comment]
THANK YOU SIR...IT SOLVED MY ISSUE...THANKS A TON

**Comment by sourabhtiwari** [comment]
I NEED A CLEAR FILTER OPTION AS WELL TO RESET ONLY FILTERED VALUES...

**Comment by nicolaskruchten** [comment]
There's no straightforward way to do that, you'll have to regenerate the table again, resubmitting the configuration minus the filter exclusions/inclusions.

**Comment by sourabhtiwari** [comment]
I tried to reconfigure it by saving old configuration in a input box..but it still not taking data  from that inputs.is there any way to hold configuration properly to apply in new initialization.

**Comment by nicolaskruchten** [comment]
It's definitely possible but a little bit beyond the kind of support I have the time to provide for this library. Perhaps someone at StackOverflow.com will have some more time to help you out?

**Comment by sourabhtiwari** [comment]
ofcourse..Thanks for all the help.

On Wed, Oct 14, 2015 at 4:44 PM, Nicolas Kruchten <notifications@github.com>
wrote:

> It's definitely possible but a little bit beyond the kind of support I
> have the time to provide for this library. Perhaps someone at
> StackOverflow.com will have some more time to help you out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaskruchten/pivottable/issues/388#issuecomment-148020845>
> .
>



-- 
Sourabh Tiwari
Abhanpur cyber cafe & game zone
h/w , n/w & s/w works.............
9993841586
block colony abhanpur.

**Comment by VarelaIT** [comment]
> OK, you'll have to use the `overwrite` parameter set to `true` to get what you're looking for, as per https://github.com/nicolaskruchten/pivottable/wiki/Parameters#pivotuiinput-options-overwrite-locale

This is very helpful!
