### ISSUE TITLE
Multiple aggregators at the same time

### ISSUE THREAD

**Issue by samighawi** [nicolaskruchten/pivottable#389]
Hello,

Does PivotUI support multiple aggregators at the same time?
For example, we would like to have "Maximum by Sales", "Maximum by Expenses" and "Maximum by Profit" at the same Google chart graph.
Please refer to this link for the requested graph:

https://google-developers.appspot.com/chart/interactive/docs/gallery/columnchart#creating-material-column-charts

Generating this graph would require multiple Y-axis data as follows:
['Year', 'Sales', 'Expenses', 'Profit'],
['2014', 1000, 400, 200],
['2015', 1170, 460, 250],
['2016', 660, 1120, 300],
['2017', 1030, 540, 350]

Can we define an aggregator that returns 2 or three data instead of one in order to generate such a graph?

Thanks

**Comment by nicolaskruchten** [comment]
This is not possible, unfortunately: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi

**Comment by nicolaskruchten** [comment]
That said, if you have a field called "type" which contains one of sales/expenses/profit then you could make such a graph, with a single aggregator.

**Comment by samighawi** [comment]
Thanks for the details. I will take a look at  issue #30 to see if it is possible to use our own custom renderers to solve this limitation.
