### ISSUE TITLE
Spot to adjust decimal places in aggregator section?

### ISSUE THREAD

**Issue by LukePivot** [nicolaskruchten/pivottable#390]
Hi Nicolas,

Do you have any guidance on dynamically changing decimal places on the aggregator section?  We are adding in an input where the user can adjust decimal places, but we just want to make sure we're adjusting it in the right spot.  Do you happen to know the best spot where we can add that?

Thanks a ton for any info,

Luke

**Comment by nicolaskruchten** [comment]
Hi Luke,

Can you explain a bit more what you're trying to do? I don't understand what you mean by "dynamically changing decimal places" :)

**Comment by LukePivot** [comment]
Thanks for the super quick reply, Nicolas.

All I meant was that we are planning on adding a dropdown with values 1 through 6.

Let's say I have a Sum that shows "0.00" (ie. two decimals), even though the raw data has "0.002345".

If the user then sets the aforementioned dropdown to "4", the Sum would then be re-displayed as 4 decimals:  0.0023

Does that answer it?

**Comment by nicolaskruchten** [comment]
OK, I understand. In that case, you can create a set of aggregators which use a custom number formatting function which renders differently based on the value of your dropdown.

**Comment by LukePivot** [comment]
Awesome, thanks for the help!  We nailed it.

**Comment by nicolaskruchten** [comment]
Great :)
