### ISSUE TITLE
Row and column labels of data cell intersection

### ISSUE THREAD

**Issue by tozjerimiah** [nicolaskruchten/pivottable#391]
While I appreciate that it is not possible to drill down into the data aggregated in the pivot table, it would be very useful if there was some way to derive the row and colum labels which intersect an aggregate value - perhaps with information regarding the aggregator used and other data about the configuration of the table such as that supplied via onRefresh.

Is there any easy way of doing this? Would it be a time consuming development matter?

Thanks

**Comment by nicolaskruchten** [comment]
There's probably a reasonable way to do this. You're wanting to derive the row/col values in something like an onClick handler?

**Comment by tozjerimiah** [comment]
Exactly, yes.

I had meant to say - excellent project by the way!

Thanks

**Comment by guyclairbois** [comment]
Very interested in this as well. Would be a killer feature!

**Comment by ZokiA** [comment]
I think that 'PivotTable.js NReco Extensions FREE pack' have already covered what jou are looking for.
*http://www.nrecosite.com/pivot_table_aspnet.aspx*

**Comment by tozjerimiah** [comment]
Hmm I'm not really looking to get the aggregated data details due to the fact that there is a great deal of aggregation going on server side - I would like to get the row and col labels from an onClick event in a cell representing aggregated data.

**Comment by ZokiA** [comment]
If you use code snipet below it is just what you are looking for. object 'dataFilter' has all labels from columns and rows for that cell.

```javascript
        var nrecoPivotExt = new NRecoPivotTableExtensions({
            drillDownHandler: function (dataFilter) {
                console.log(dataFilter);
            }
        });
		var stdRendererNames = ["Table","Table Barchart","Heatmap","Row Heatmap","Col Heatmap"];
        var wrappedRenderers = $.extend( {}, $.pivotUtilities.renderers);
        $.each(stdRendererNames, function() {
            var rName = this;
            wrappedRenderers[rName] = nrecoPivotExt.wrapTableRenderer(wrappedRenderers[rName]);
        });
		
		var Options = {
            renderers: wrappedRenderers,
			...
		};
		
		...
```

**Comment by guyclairbois** [comment]
That's very nice. Will be trying it out soon. I didn't know the NReco extension. Might be worth mentioning  it on the pivottable.js docs...
