### ISSUE TITLE
How To Custimaze pivotUI ToolTip in googleChart,

### ISSUE THREAD

**Issue by hasanjaafreh** [nicolaskruchten/pivottable#392]
Hello,

when i use pivot Ui for render google chart, i need to customize the tooltip shown in chart,
i search in google chart and i see that you can send the tooltip with the datatable to chart.

my question is how to customize the plugin to send the tooltips to chart.??

i see that you send the tooltips only for ScatterChart. 

How to do that for every chart?

Thanks

**Comment by nicolaskruchten** [comment]
Sorry for the long delay in answering: this would be fairly challenging without hacking the gcharts_renderers code.
