### ISSUE TITLE
Creating views - apply new pivots without reloading the data

### ISSUE THREAD

**Issue by flotrek** [nicolaskruchten/pivottable#394]
Hello,
loving the pivottable so far, thanks for your work.
I'd like to apply a "view" to my loaded pivot table.
I understand I might have to re-render the whole thing.
But Isn't there a way to simulate an UI actions programmatically and then trigger the refresh ? (changing the pivots).
How would you proceed to build these "views", especially with bigger data sets (that take time to reload) ?

**Comment by nicolaskruchten** [comment]
There is no way to do this without re-rendering everything, unfortunately.
