### ISSUE TITLE
Can we have Row Total for numeric fields.

### ISSUE THREAD

**Issue by sourabhtiwari** [nicolaskruchten/pivottable#396]
Hi sir

I have a requirement of showing Available inventory,Used Inventory and Remaining inventory.In that case i have total of remaining inventory.but i need some of other fields as well.

![abv](https://github-cloud.s3.amazonaws.com/assets/13868381/10566187/7672e1bc-75fd-11e5-9bc6-48ec071b694c.png)

**Comment by nicolaskruchten** [comment]
This is not possible, unfortunately.
