### ISSUE TITLE
Filter Dialog position

### ISSUE THREAD

**Issue by fmfcs** [nicolaskruchten/pivottable#398]
Hi there!

A have a page with 3 pivots that has vertical scroll. If I scroll down to find an option and click it to filter, that popup will show in the wrong position.

What could it be the problem?

**Comment by nicolaskruchten** [comment]
Can you provide a link to an example of the problem so I can dig into it?

**Comment by fmfcs** [comment]
The project is private, i'll send you a private email with one URL.

**Comment by wdog** [comment]
I've the same problem. did you find any solution?

**Comment by nicolaskruchten** [comment]
@fmfcs could you post a hint as to what the CSS-related issue was?

**Comment by fmfcs** [comment]
I've added "position: relative;" to the main table.

Did it help?

**Comment by wdog** [comment]
yes :dancer:

**Comment by fmfcs** [comment]
Great :)

**Comment by nicolaskruchten** [comment]
Awesome!
