### ISSUE TITLE
pivot table not working when using astechdev latest release to enable datatables

### ISSUE THREAD

**Issue by eliesalame** [nicolaskruchten/pivottable#400]
Hello @nicolaskruchten,
I tried using the newest release presented by astechdev (https://github.com/astechdev/pivottable.git) in order to enable datatables with the pivot table.
When I downloaded the zip file and launched the examples, the pivot table won't even work.
![pivot_table_not_working](https://cloud.githubusercontent.com/assets/13767596/10823700/866587bc-7e65-11e5-9f86-f1eca90b76dd.jpg)

Were you able to find any new solution in order to enable the sorting by data?

Thanks,
Elie

**Comment by nicolaskruchten** [comment]
Unfortunately, I can't really provide support for forks of this library, so you'll have to ask @astechdev for help if their version is broken... If you really require interactive sorting for this library, you may have some luck with the extension here: http://www.nrecosite.com/pivot_table_aspnet.aspx

**Comment by eliesalame** [comment]
Thanks @nicolaskruchten , the library you provided sorts the values in the table, but I'm actually looking to sort the attribute headers.
This is why the plugin developed by astechdev suits me better.

@astechdev, will you be able to provide support and fix the version?

**Comment by astechdev** [comment]
@eliesalame did you try the dist/datatables_renderers.min.js on the datatablesRenderersDevBranch?  I have been using that in development for some time now and it works flawlessly. I have been meaning to send @nicolaskruchten a PR but haven't had the time...

**Comment by eliesalame** [comment]
Thanks for your reply @astechdev, but I used pivot_table_aspnet.aspx which @nicolaskruchten  suggested and it worked fine.
