### ISSUE TITLE
PivotUI with Chart Only

### ISSUE THREAD

**Issue by vjkr14** [nicolaskruchten/pivottable#402]
Hello Nicolas,

Can we display c3 chart (Responsive) without other columns i.e. aggregator area, drag and drop area etc.

Reason : In some scenarios we have to display only bar chart with sum without having users to change any field or summary values. 

Thanks in Advance.

Need your urgent help.

**Comment by vjkr14** [comment]
Nobody is using this plugin?. 
am I doing any thing wrong by using this. 
Anybody please reply.

**Comment by nicolaskruchten** [comment]
You should use the `pivot()` function instead of `pivotUI()` to display just the renderer area without the drag'n'drop UI.

**Comment by vjkr14** [comment]
Thanks Nicolas,
But I need to display bar char for my monthly hits. since its pivot functionality is excellent I wanted to use this. however please see if you can help me getting pivot output in a variable.
like var result = pivot(); instead of drawing on a div/table.

**Comment by hamtaroapoil** [comment]
Hey,

I need show a same result for pivot() & pivotUI(), but it's  don't same params. 

How should I do it?

**Comment by nicolaskruchten** [comment]
It's true they don't have the same parameters, but they're not that different. You'll have to build a bit of adapter code.

**Comment by hamtaroapoil** [comment]
ok thx for you reply
