### ISSUE TITLE
Hide attributes, but not for aggregators

### ISSUE THREAD

**Issue by langusta** [nicolaskruchten/pivottable#403]
Hi,
Thank you for this super convenient pivot tables library! It does wonders.
Let's say that I have 30 attributes, but 20 of them are useless to group by and I would only use them as arguments to aggregators. Is it possible to hide them from the attribute list, but leave them in the drop down list of aggregator attributes? I've seen that there is `hiddenAttributes` parameter, but it hides the attributes also for aggregators :(

**Comment by ZokiA** [comment]
Hi, 
I am also looking forward for these option.

**Comment by nicolaskruchten** [comment]
There is currently no way to do what you're looking for, sorry. I guess the way to do this would be to add two new fields to control which attributes can show up where in the UI, and then have `hiddenAttributes` override those for backwards-compatibility. Something like `hiddenAttributesFromAggregators` and `hiddenAttributesFromDragDrop` (although those names are very long)

**Comment by langusta** [comment]
Are you saying that I could add those fields? I don't know javascript (I'm using this package via R - rpivotTable), but the code doesn't look too complicated. I can try :)
Maybe following names would be (slightly) better?:
* `hiddenFromAggregators`
* `hiddenFromDragDrop`

**Comment by nicolaskruchten** [comment]
Yes, if you want to send me a pull-request that implements the code to add these two options, I would be happy to work with you to integrate it, and then we could get that upstreamed into rPivotTable :)

**Comment by MarcinKosinski** [comment]
+1

**Comment by langusta** [comment]
Ok, then I will try to do this this or next weekend.

**Comment by nicolaskruchten** [comment]
Fixed with v2.15.0 !
