### ISSUE TITLE
Force trigger onRefresh for pivotUI

### ISSUE THREAD

**Issue by eliesalame** [nicolaskruchten/pivottable#404]
I've been able to change attributes programmatically using JQuery to change cols/rows without the need of reloading data.
But once i do so, i need to do something to trigger the onRefresh so the table refreshes and actually adds the data of newly added column/row.

![2015-11-05_114447](https://cloud.githubusercontent.com/assets/13767596/10964972/a8275004-83b2-11e5-9f6d-9d382f2ea8b7.jpg)

@nicolaskruchten is there a way to force a refresh on the table?

**Comment by eliesalame** [comment]
@nicolaskruchten did you have time to check?
It's blocking my current project :).

**Comment by nicolaskruchten** [comment]
There is no way to trigger a refresh. Instead of using jQuery to change the UI and then trying to trigger a refresh, just rerender the whole table with whichever options you need.
