### ISSUE TITLE
Multiple Vals

### ISSUE THREAD

**Issue by bharatathota** [nicolaskruchten/pivottable#406]
Hi nicolaskruchten, i have a requirement of showing two vals in pivot table but need to use 'Sum' aggregator  on one of those values.For example i need to show currency codes and amount in same table cell like '$412.26' and i need to use 'Sum' aggregator on amount.How is it possible ? Thanks in Advance :)

**Comment by nicolaskruchten** [comment]
This is not possible at all, unfortunately.
