### ISSUE TITLE
Truncation issue on the y axis label

### ISSUE THREAD

**Issue by the8thavatar** [nicolaskruchten/pivottable#407]
Observable in the Firefox(38.3.0) and Internet Explorer(11.0.9600) browsers using your C3 example at http://nicolas.kruchten.com/pivottable/examples/c3.html, if you open that page and then pick 'Sum over Sum' for example then the y axis label no longer displays completely.
![pic1](https://cloud.githubusercontent.com/assets/15814140/11115249/17619db6-8922-11e5-87d3-7e2b1203ec15.png)

**Comment by nicolaskruchten** [comment]
Thanks for flagging that!

This is essentially a temporary state until both arguments are selected: if you then put "Age" in the first dropdown and "Gender Imbalance" in the second dropdown you'll see that rendering is back to normal. I'm not sure what C3 is doing there but it seems like a fairly minor issue.

**Comment by the8thavatar** [comment]
What appears to happen is that some selections cause more space to be allocated to allow for y axis labels. If no values are found, not enough space is allocated for the rendering of the label. I agree that since you would have no graph if there were no y axis values this is a minor issue.,
