### ISSUE TITLE
bower dependency on jqueryui should be jquery-ui

### ISSUE THREAD

**Issue by sebheitzmann** [nicolaskruchten/pivottable#409]
the correct syntax is jquery-ui

I have a lot of other dependencies and this one install a second version of jquery-ui for my project.

Please correct this type.

Thanks

**Comment by nicolaskruchten** [comment]
Why do you say that the "correct" syntax is `jquery-ui`? I can't find any kind of official statement to that effect, and `jqueryui` seems to work fine for most people...

**Comment by sebheitzmann** [comment]
https://github.com/components/jqueryui/blob/master/bower.json

it's the syntax in the original jqueryui.

maybe you should remove the dependency ? I don't know.

**Comment by sebheitzmann** [comment]
and here in an other library :
https://github.com/gustavohenke/jquery-ui-bootstrap/blob/master/component.json

**Comment by nicolaskruchten** [comment]
Fixed in [Version 2.0.0](https://github.com/nicolaskruchten/pivottable/releases/tag/v2.0.0) by removing this (technically-optional) dependency altogether :)

**Comment by sebheitzmann** [comment]
thanks
