### ISSUE TITLE
Sub aggregates

### ISSUE THREAD

**Issue by ykil** [nicolaskruchten/pivottable#411]
This is an alternative solution to [issues 383](https://github.com/nicolaskruchten/pivottable/issues/383).  There's a way to do sub-aggregates, which can show averages,min/max,etc... as shown in this [file](https://dl.dropboxusercontent.com/u/50487486/github/nicolaskruchten/ExampleReplicateForErrorBars.PMI.xlsx).

If I had a pivot table like this, I can get these values to generate error plots.  Is sub-aggregates a consideration?  Thanks.

**Comment by nicolaskruchten** [comment]
It is not a consideration, unfortunately, see the related [FAQ question](https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi)
