### ISSUE TITLE
Handsontable and highcharts renderers

### ISSUE THREAD

**Issue by fbrussa** [nicolaskruchten/pivottable#412]
Hi. If someone needs, I developed a plugin that adds some renderers (handsontable and highcharts renderers).

https://github.com/fbrussa/NovixPivotJS

Good luck!

**Comment by palvors** [comment]
Hi, do you know if is possible to put horizontal scrollbar and vertical ?

**Comment by nicolaskruchten** [comment]
This is very cool, thanks for submitting it!
