### ISSUE TITLE
Formatting neg values with () instead of -

### ISSUE THREAD

**Issue by AlicePain** [nicolaskruchten/pivottable#415]
This isn't a bug, but it would be super helpful to format negative values with brackets instead of a -.
Brackets are much easier to read and used for accounting purposes.  The following code could be added to the numberFormat function.

        if (x < 0 && opts.negAccountingFormat) {
          result = "(" + result.replace("-", "") + ")";
        }

You'd also have to add negAccountingFormat to opts.

**Comment by nicolaskruchten** [comment]
Agreed, but given that someone would have to build their own locale file to use this new `negAccountingFormat` option, I'm inclined to leave it out and let people add that logic into their locale file themselves...

**Comment by SAMJN** [comment]
Hi @nicolaskruchten, I have created a separate formatter in existing pivot.js for negative number. It adds () where numbers are negative.
