### ISSUE TITLE
C3 charts does not render with pivot()

### ISSUE THREAD

**Issue by atulbanwar** [nicolaskruchten/pivottable#419]
I am trying to use c3 charts with PivotTable. I am passing following renderer as I saw in one of the example:
var renderers = $.extend($.pivotUtilities.renderers, $.pivotUtilities.c3_renderers);

It works fine when I use it with pivotUI method. I can see the rendered chart.
But it does not work with pivot method. In this case it draws table only.
Could someone please tell me if I need to pass something else also to make it work with pivot method.

**Comment by nicolaskruchten** [comment]
The way you call `pivot()` and `pivotUI()` is fairly different... If you look at the documentation here https://github.com/nicolaskruchten/pivottable/wiki/Parameters you will see that `pivot()` does not take a `renderers` parameter which is a dictionary, you will need to pick a single renderer and pass it in as the `renderer` parameter.

**Comment by atulbanwar** [comment]
ohhh!!! I missed that one, thanks a lot Nicolas
