### ISSUE TITLE
format decimal 

### ISSUE THREAD

**Issue by efinten** [nicolaskruchten/pivottable#420]
nicolas hola foremost thanks for the contribution of this component, is very good, now my question is, would need to format a decimal value that I have a json, this is my scrip .ajax

$ .ajax ({
            url: 'T.aspx/Getdatos'
            type: 'POST'
            contentType: "application / json; charset = utf-8"
            Error: function (data, textStatus) {
                alert ("Error could not load the data. ');
            },
            success: function (data, st) {
                if (st == 'success') {                          
                    derivers var = $ .pivotUtilities.derivers;
                    var = $ .extend renderers (
                            $ .pivotUtilities.renderers,
                            $ .pivotUtilities.c3_renderers,
                            $ .pivotUtilities.d3_renderers,
                            $ .pivotUtilities.export_renderers
                            );
                   
                    $ ("# Output") pivotUI (jQuery.parseJSON (data.d) {renderers: renderers}, false, "es");
                
                }

            }
        });

**Comment by nicolaskruchten** [comment]
I'm not sure what your question is... Can you describe what you are getting and what you are hoping to get?

**Comment by efinten** [comment]
Nicolas hello, thanks for the reply, I need is to format a number that
bring a json, the question is how I can make the separation of decimals.
attached a picture of the data as it comes. there functions to format the
number


[image: Imágenes integradas 1]


2016-01-09 2:34 GMT-03:00 Nicolas Kruchten <notifications@github.com>:

> I'm not sure what your question is... Can you describe what you are
> getting and what you are hoping to get?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaskruchten/pivottable/issues/420#issuecomment-170199672>
> .
>



-- 
Atte,
David Esteban Finten.-

**Comment by nicolaskruchten** [comment]
I'm sorry, the image did not come through, and I still don't understand your question. There is a `numberFormat()` function within `$.pivotUtilities` but without more context I will not be able to help you use it...

**Comment by efinten** [comment]
nicolas, sorry for not being as clear in my query, in my json I get the
numerical data unformatted eg (*317 473 000,00*), I would need to see such
data *317,473,000.00* separate points and decimals a comma.
I do not know yet how serious the correct syntax


$.ajax({
            url: 'Tablero.aspx/Getdatos',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            error: function (data, textStatus) {
                alert('Error.');
            },
            success: function (data, st) {
                if (st == 'success') {

                    var derivers = $.pivotUtilities.derivers;

                    var renderers = $.extend(
                            $.pivotUtilities.renderers,

                            $.pivotUtilities.c3_renderers,
                            $.pivotUtilities.d3_renderers

                            );


                    $("#output").pivotUI(jQuery.parseJSON(data.d), {
renderers: renderers }, false, "es");

                }

            }
        });

I hope to be clear


Thanks for taking the time to answer

2016-01-12 17:01 GMT-03:00 Nicolas Kruchten <notifications@github.com>:

> I'm sorry, the image did not come through, and I still don't understand
> your question. There is a numberFormat() function within $.pivotUtilities
> but without more context I will not be able to help you use it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaskruchten/pivottable/issues/420#issuecomment-171036312>
> .
>



-- 
Atte,
David Esteban Finten.-

**Comment by nicolaskruchten** [comment]
OK so first you have a parsing problem right? You have numbers coming in as strings with spaces for thousands-separators/commas for decimal-separators and you want them to be parsed into numbers and then displayed with commas as thousands-separators/dots as decimal-separators?
