### ISSUE TITLE
Provide API to load information dynamically

### ISSUE THREAD

**Issue by Vineeth-Mohan** [nicolaskruchten/pivottable#421]
Often its not possible to offload the entire data set to the client side.
In such cases , if we could first offload meta information ( Like row names ) and then offload the actual data whenever required ( Like when a element is added to column or row ) , that would be great.

To facilitate this , can we have a API , which can be used to perform this.
For eg:

pivotTableAPI.onParameterChange(callBack Function That Renders UI in State Of Loading and from background loads ajax data);
pivotTableAPI.updateData(data from ajax in CSV format)

With this , we can integrate pivot table with any backend frame work.

**Comment by nicolaskruchten** [comment]
This would be neat but the changes required to this library to support such an API would be way too big, so I don't think I will ever do this. The big problem is that this library is synchronous right now but it would need to be rearchitected to be asynchronous to work within the browser's HTTP request model.

**Comment by sibelius** [comment]
any plans to support this?
