### ISSUE TITLE
Does pivot table support multiple measures in olap terms 

### ISSUE THREAD

**Issue by neelshah12** [nicolaskruchten/pivottable#422]
My data contains dimensions "D1,D2,D3" and multiple measures "m1,m2,m3,m4".I want the pivot table to include all the measure every time. I counldn't find any example that support it.The closest one is putting measures as aggregators as given in example http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html but it only shoes one measure at a time.

**Comment by nicolaskruchten** [comment]
As per the FAQ, there is no support for multiple measures. https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions
