### ISSUE TITLE
How about the dynamic change the rows and cols fields sorting value?

### ISSUE THREAD

**Issue by it4u** [nicolaskruchten/pivottable#423]
Hi Sir, I just ask would pivotUI can do it ? I have defined in the main program, then I want to dynamiclly to modify the rows and cols fileds sorting, can it do that ? thanks !

**Comment by nicolaskruchten** [comment]
You cannot dynamically change anything programatically, you can just re-render the full output. With respect to sorting, you can control the sort order of rows and columns with the `sorters` parameter, but note that this sorts by row/column header value, not by cell value.

**Comment by it4u** [comment]
OK. Thanks Sir. I use another method to got the result... use POST get the parameters to dynamiclly change sort fields with SQL command...

**Comment by it4u** [comment]
Forget to close, Thanks !
