### ISSUE TITLE
Get Controll of Pivot Table Size

### ISSUE THREAD

**Issue by midriss** [nicolaskruchten/pivottable#424]
I want to use PivotTable.js  on mobile device which have a fixed width

I do not want the Pivot Table with class pvtUi to extend the maximum width of the browser or the maximum width of the div element

How can I do that ?

**Comment by nicolaskruchten** [comment]
You can constraint the container's width with CSS but ultimately, it's very hard to constrain table widths: the contents can only be squeezed so much.
