### ISSUE TITLE
Turning cells into buttons or links?

### ISSUE THREAD

**Issue by jdlam** [nicolaskruchten/pivottable#425]
I'm having a lot of issues trying to turn specific cells of a data set into buttons or links.

I've been trying to use the derivedAttributes to insert html tags around the cell's value, but they are just rendered as text. When I try to use JS to create an element, they produce an error, since the derivedAttributes seem to be expecting strings or numbers.

I thought about using onRefresh, with a function that goes through every cell and determines whether or not it needs a link, but I couldn't differentiate between cells of a different category than the one I'm interested in.

Does anyone have any recommendations? I'm pretty stuck on this, and I can't find a way to accomplish what I want yet.

**Comment by nicolaskruchten** [comment]
Your best bet will be to put some Javascript into the `onRefresh` callback for sure. In terms of finding the right cells, there might not be enough information in the `class` attributes to easily find what you need but maybe I can help you figure it out... For which cells do you want buttons?

**Comment by jdlam** [comment]
Thanks, I appreciate it a lot. Also PivotTable.js has been great to work with so far.

So I just want to be able to add buttons to cells of a particular attribute. Let's say I had Name, Version, and Service Pack all on the left hand side, so they're grouped by rows, I just want to  alter the cells within the Names column. I've been able to set up my own onRefresh function that color codes any dates, but those had a specific format I could identify and parse through. In this instance, I can only think of checking the cell's value with an array of all unique values of Names...
