### ISSUE TITLE
 How make somes filters ?

### ISSUE THREAD

**Issue by palvors** [nicolaskruchten/pivottable#426]
Hi,

        if I have 2 fields and I want make some filter by filter. How I do that ? I thought that I just delcare 2 variables with my filter value like. but  

var province ={FilterField:"Province",filterValue:["Quebec","Ontario"]}
var activity ={FilterField:"Activity",filterValue:["Run","swim","Climb"]}

...
filter:function(row){

 if(row["Province"])
   // check if value is contain in the list
   // yes continue
   // no, return false

if (row["Activity"])
// check if value is contain in the list
   // yes continue
   // no, return false

}

is it like that I must apply filter ?

**Comment by palvors** [comment]
or if I wish not get the data that contains "-" in theprovince field....is it possible ? and not pass by inclusion and exclusions ?

**Comment by nicolaskruchten** [comment]
I'm afraid I don't really understand what you are trying to do... Can you give me a concrete example of the input you have and the output you'd like to see?

**Comment by palvors** [comment]
ohhh, sorry Forget. I just want make some filter, but i find  found how to make with your example http://nicolas.kruchten.com/pivottable/examples/onrefresh.html   with your attirbut "exclusions" "inclusions". but just a question about that... why we must put same informations in "inclusions" and "inclusionsInfo" ?

here when i put "province" with filter 

{
  "derivedAttributes": {},
  "hiddenAttributes": [],
  "menuLimit": 200,
  "cols": [],
  "rows": [
    "Province"
  ],
  "vals": [],
  "exclusions": {
    "Province": [
      "Alberta"
    ]
  },
  "inclusions": {
    "Province": [
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Nova Scotia",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Territories"
    ]
  },
  "unusedAttrsVertical": 85,
  "autoSortUnusedAttrs": false,
  "inclusionsInfo": {
    "Province": [
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Nova Scotia",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Territories"
    ]
  },
  "aggregatorName": "Count",
  "rendererName": "Table"
}

**Comment by nicolaskruchten** [comment]
You only need to pass either `exclusions` or `inclusions` or both, but `inclusionsInfo` is part of the `onRefresh` output for legacy compatibility reasons.
