### ISSUE TITLE
Changing the color of the dark grey Table Barcharts in the cells

### ISSUE THREAD

**Issue by kaf3773** [nicolaskruchten/pivottable#427]
Great job Nicolas!

This is my first time of using this and its absolutely great.

When i use Table Barchart the barcharts are in dark grey. Is there a way to change the color to something else? 

Secondly changing the light grey color for the header and column where the row and column labels go?

I tried changing some of the colors in the pivot.css but that did not help.

Help on the above two will be very much appreciated.

As a suggestion or an enhancement will be the ability to change the Table Barcharts to different colors based on the values in the cells. Just like the heat map but instead of shades of one color different colors instead.

Thanks

**Comment by nicolaskruchten** [comment]
Glad you like this library, and sorry I didn't reply to this sooner!

There is no way to change the colour of the bars in the Table Barchart renderer at the moment without modifying the code, although the header and column colours should be easy to change in pivot.css on lines 10 and 55.
