### ISSUE TITLE
Allow settings to the saved and reloaded

### ISSUE THREAD

**Issue by jiteshvassa** [nicolaskruchten/pivottable#428]
After a user has manually configured a pivot, it would be great if the settings of the pivot/chart could be extracted so that they could be persisted and then reloaded at a later time.  Essentially allows for pre-canned reports to be created using a UI.

**Comment by nicolaskruchten** [comment]
They can be: http://nicolas.kruchten.com/pivottable/examples/onrefresh.html

**Comment by jiteshvassa** [comment]
Thank you, that's exactly what I was after.
