### ISSUE TITLE
Number of data in set

### ISSUE THREAD

**Issue by EmilMoe** [nicolaskruchten/pivottable#431]
I need to pull information about how many data is in the current subset. How is this best archived? 

I tried to make some counts in about line 755, but it doesn't seem to do what I want. I want the number of participants who are calculated when the rows and cols are chosen.

~~~~
      switch (pivotData.aggregatorName)
      {
        case "List Unique Values":
        case "Count Unique Values":
          sum = pivotData.allTotal.uniq.length;
          break;

        case "Count":
          sum = pivotData.allTotal.count;
          break;

        default:
          sum = pivotData.allTotal.sum;
      }
~~~~

**Comment by nicolaskruchten** [comment]
I'm confused... You want the count to appear in the UI or you want programmatic access to it?

**Comment by EmilMoe** [comment]
I want to only show an output if the data that is being measured on (dataset?) is 5 participants or more. Otherwise I want to display some kind of text.

But I'm not sure my approach is correct. I think I should check somewhere in the beginning of the script, how many records are for calculation?

**Comment by nicolaskruchten** [comment]
So you want to [build an aggregator](https://github.com/nicolaskruchten/pivottable/wiki/Aggregators) which displays a special value when it is aggregating fewer than 5 values? Your aggregator will have to keep a count of how many times its `push` method has been called, and use that number as a switch for its `value` function.

Something like:

```
var count = function(data, rowKey, colKey) {
  return {
    count: 0,
    push: function(record) { this.count++; },
    value: function() { return this.count < 5 ? "fewer than 5!" : this.count; },
    format: function(x) { return x; },
 };
};
```

**Comment by EmilMoe** [comment]
I'm not sure. This leaves out data if the value in the cell is less than 5.

I want to not display anything, but only if the complete set is based on less than 5 observations. I think it's the Totals / Totals count that is in my concern only, right?

**Comment by nicolaskruchten** [comment]
Hmm ok then I don't understand what you are looking for. Could you post some sample data and the sample output you seek so I can better answer your question?

**Comment by EmilMoe** [comment]
My problem is that I don't have the sample data yet.

But if we say that a dataset is a set of observations. One dataset might be 100 observations, that means the table is based on 100 peoples preferences. If this is not 100 but 5 or less, then I don't want the display the table at all, but only in the case that the filtered data is based on 5 or less.

Maybe the filtration should be in the very initialization?

**Comment by nicolaskruchten** [comment]
Both renderers and aggregators get access to an instance of the `PivotData` class, which on its own is not aware of how many data points went into it. You could build a special aggregator which would do this counting, and query its grand total value from the renderer to prevent table display if the count is less than 5. Is that what you mean?
