### ISSUE TITLE
can't understand sumOverSumBound80 function

### ISSUE THREAD

**Issue by zhoulvjun** [nicolaskruchten/pivottable#432]
Could you please explain sumOverSumBound80 function in detail?

I can't understand the formula:
(0.821187207574908 / this.sumDenom + this.sumNum / this.sumDenom + 1.2815515655446004 * sign * Math.sqrt(0.410593603787454 / (this.sumDenom * this.sumDenom) + (this.sumNum * (1 - this.sumNum / this.sumDenom)) / (this.sumDenom * this.sumDenom))) / (1 + 1.642374415149816 / this.sumDenom)

How to use plain language to explain the statistics generated by this funcition in the cells?
thanks!

**Comment by nicolaskruchten** [comment]
This fomula basically computes the 80% confidence interval upper and lower bound according to the Wilson formula for a given number of trials and successes: https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Wilson_score_interval

**Comment by zhoulvjun** [comment]
got it!

Thanks a lot!
