### ISSUE TITLE
Element Layout for Export

### ISSUE THREAD

**Issue by LukeBrumfield** [nicolaskruchten/pivottable#435]
I am using this library for reporting and will be using the tableExport jquery plugin. The layout for the tables generated by pivottable is visually great, but libraries that parse tables for output to PDF or excel expect certain elements (thead, tbody) for the export. I am going to write some code that will change the layout of the "table.pvtTable" to something easier to pass into tableExport.

If you look at the structure of these two tables, you'll see the difference. Its more than moving the "pvtAxisLabel".

Edit:less ambiguous goal
I am going to change how this output from pivottable is generated:

<table class="pvtTable" data-numrows="2" data-numcols="3"><tr><th colspan="1" rowspan="1"></th><th class="pvtAxisLabel">ethn</th><th class="pvtColLabel" colspan="1" rowspan="2">black</th><th class="pvtColLabel" colspan="1" rowspan="2">hisp</th><th class="pvtColLabel" colspan="1" rowspan="2">other</th><th class="pvtTotalLabel" rowspan="2">Totals</th></tr><tr><th class="pvtAxisLabel">union</th><th></th></tr><tr><th class="pvtRowLabel" rowspan="1" colspan="2">no</th><td class="pvtVal row0 col0" data-value="317">317</td><td class="pvtVal row0 col1" data-value="494">494</td><td class="pvtVal row0 col2" data-value="2485">2,485</td><td class="pvtTotal rowTotal" data-value="3296" data-for="row0">3,296</td></tr><tr><th class="pvtRowLabel" rowspan="1" colspan="2">yes</th><td class="pvtVal row1 col0" data-value="187">187</td><td class="pvtVal row1 col1" data-value="186">186</td><td class="pvtVal row1 col2" data-value="691">691</td><td class="pvtTotal rowTotal" data-value="1064" data-for="row1">1,064</td></tr><tr><th class="pvtTotalLabel" colspan="2">Totals</th><td class="pvtTotal colTotal" data-value="504" data-for="col0">504</td><td class="pvtTotal colTotal" data-value="680" data-for="col1">680</td><td class="pvtTotal colTotal" data-value="3176" data-for="col2">3,176</td><td class="pvtGrandTotal" data-value="4360">4,360</td></tr></table>

Into a format which that matches what I need to deliver:

This p will not be generated by pivottable, but can be extracted from the col and row labels
<p>Workers by union and eth</p>

<table class="pvtTable, report" data-numrows="2" data-numcols="3">
    <thead>
      <tr>
        <th>union</th>
        <th class="pvtColLabel">black</th>
        <th class="pvtColLabel">hisp</th>
        <th class="pvtColLabel">other</th>
        <th class="pvtTotalLabel">Totals</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="pvtRowLabel">no</td>
        <td class="pvtVal row0 col0" data-value="317">317</td>
        <td class="pvtVal row0 col1" data-value="494">494</td>
        <td class="pvtVal row0 col2" data-value="2485">2,485</td>
        <td class="pvtTotal rowTotal" data-value="3296" data-for="row0">3,296</td>
      </tr>
      <tr>
        <td class="pvtRowLabel">yes</td>
        <td class="pvtVal row1 col0" data-value="187">187</td>
        <td class="pvtVal row1 col1" data-value="186">186</td>
        <td class="pvtVal row1 col2" data-value="691">691</td>
        <td class="pvtTotal rowTotal" data-value="1064" data-for="row1">1,064</td>
      </tr>
      <tr>
        <td class="pvtTotalLabel">Totals</td>
        <td class="pvtTotal colTotal" data-value="504" data-for="col0">504</td>
        <td class="pvtTotal colTotal" data-value="680" data-for="col1">680</td>
        <td class="pvtTotal colTotal" data-value="3176" data-for="col2">3,176</td>
        <td class="pvtGrandTotal" data-value="4360">4,360</td>
      </tr>
    </tbody>
  </table>

And the the tableExport library can push it to pdf, excel, and a few other formats that I do not plan on personally using. I will be removing the pvtAxisLabel and putting those into a different field at the top of the report.

**Comment by nicolaskruchten** [comment]
If you need a particular format of output, you may be better off copying/modifying the actual Table Tenderer code instead of reprocessing its output...

**Comment by LukeBrumfield** [comment]
That is what I meant, and I now see that I didn't quite say that. Either way, my fork that builds the table the way I was wanting. I will continue working on tableExport integration in my project and put up some examples.

**Comment by zachcowell** [comment]
Hi @LukeBrumfield, did you complete your tableExport renderer? I would be very interested in this.
