### ISSUE TITLE
Filter API

### ISSUE THREAD

**Issue by gobezu** [nicolaskruchten/pivottable#436]
Dear dev, what a great piece of software. Discovered it last night, already have it up and running to visualize stock status in an application I am developing. Thank you!
Now, I would need to use a date widget to filter on start and end date and is wondering:
1. Is it possible to kick the filter on my [transaction date] attribute from an external widget? If so, how please?
2. Is there a way other than hiding with css a certain attribute?
3. At a more general level though, is there API documentation?
Thanks!

**Comment by nicolaskruchten** [comment]
Hi there,

Glad you like this library!

1. This is not possible at the moment
2. Yes, with the `hiddenAttributes` parameter
3. Yes of course, in the wiki: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by gobezu** [comment]
Okay then, thanks for replying quickly.
I am now pulling together 2 tables with one starting at a date where the other ends.
I did some hack and it works well.
