### ISSUE TITLE
Logarithmic scale in charts

### ISSUE THREAD

**Issue by thosil** [nicolaskruchten/pivottable#438]
Hi,
Do you think it would be hard to implement a logarithmic scale for a given attribute?
Maybe you have some advice on how I can implement it (and make a pull request when it's done)?

Thanks,
Thomas

**Comment by nicolaskruchten** [comment]
Hi Thomas, 

Sorry I never answered this! It doesn't seem like C3.js supports this so it's likely not possible.

Nicolas
