### ISSUE TITLE
Example basic with json 

### ISSUE THREAD

**Issue by lucianojls** [nicolaskruchten/pivottable#439]
Could you help me, for you will be easy.
I am trying to use your basic example would send data via json with PHP. Example:
 
$ ( "# Output"). Pivot ( 

        Data: "dados.php" --This returns one json like this in exemplo--
         [
             {Color: "blue" shape "circle"},

             {Color: "red" shape "triangle"}

         ]

it is possible to do this in basic example, it is what I need.

Thank you.

**Comment by nicolaskruchten** [comment]
This library is a client-side library only, without functionality specific to any given server-side technology like PHP... I'm not really set up to help you with PHP examples, sorry.

**Comment by lucianojls** [comment]
With php no,  but the return em json.

**Comment by nicolaskruchten** [comment]
This example shows how to load data from a JSON file: http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html
