### ISSUE TITLE
Defaults PivotUI() How to set up? PivotTable

### ISSUE THREAD

**Issue by johnleta** [nicolaskruchten/pivottable#440]
I am using pivotUI() to display a table of data and would like to know how to code the default render (current is "table") and change the aggregator default from "count" to "sum as a fraction of total" on a field.  I cannot seem to find an example.  Thanks for any assistance.

**Comment by nicolaskruchten** [comment]
This example shows what you're looking for: http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html

Check out the usage of the `rendererName` and `aggregatorName` parameters.

**Comment by johnleta** [comment]
Thank you it worked perfect.  One more question is it possible in the UI to have the user be able to sort the table?  If so, how? If Not, can it be added?

**Comment by nicolaskruchten** [comment]
Unfortunately this is not supported, see https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#sorting-in-built-in-table-renderer

**Comment by johnleta** [comment]
I am getting this error only on IE (v8 and 11).  The UI comes up with no data.

Any suggestions?

pivottable.js d3 is undefined d3.renderers.js


[cid:image001.png@01D18016.494ACDD0]



[cid:image002.png@01D18016.494ACDD0]

**Comment by nicolaskruchten** [comment]
It looks like D3 isn't loading correctly.
