### ISSUE TITLE
Is it possible to hide the Totals rows/columns?

### ISSUE THREAD

**Issue by benharrell** [nicolaskruchten/pivottable#445]
Just want to programmatically hide these as I don't need them.

**Comment by nicolaskruchten** [comment]
You can only do this in CSS.

**Comment by benharrell** [comment]
no prob, should be easy enough!

**Comment by hectorcaban** [comment]
what class/css did you use ?

**Comment by XavierFlo** [comment]
Try :

$("#OutputFollow").pivotUI({
.
.
onRefresh: function(config) {
                $("#output").find('select').addClass('hidden');
                $("#output").find('.rowTotal').addClass('hidden');
                $("#output").find('.colTotal').addClass('hidden');
                $("#output").find('.pvtGrandTotal').addClass('hidden');
                $("#output").find('.pvtTotalLabel').addClass('hidden');
            },

**Comment by amit509** [comment]
Hi Benharrel/XavierFlo/Nicolaskruchten,

Can you guys help me in pivottable in angular2.

Am facing issues while integrating in angular2.

It would be a great help :)

**Comment by benharrell** [comment]
i used css for this

**Comment by nicolaskruchten** [comment]
@amit509 as per the [Contribution Guidelines](https://github.com/nicolaskruchten/pivottable/blob/master/CONTRIBUTING.md):

* Please do not add a comment to an existing issue to ask an unrelated question, especially if it's already closed. Instead, create a new issue instead and reference the older one.

That said, there has already been some discussion of Angular in issue #208 which might be of help to you...

**Comment by amit509** [comment]
sorry for that @nicolaskruchten 
I have created a new issue #628.
In issue #208 is different case.
my issue is to integrate using angular2.

@benharrell could you please share code or an example, as Am unable to integrate, facing issues like undefined tipsData, undefined renderer, pivotUI, aggregator, etc..

please respond to #628 

I would be a great help.
