### ISSUE TITLE
aggregatorName issue with pivot() vs pivotUI()

### ISSUE THREAD

**Issue by benharrell** [nicolaskruchten/pivottable#446]
I have a string value in my value column such as 'Y' or 'N' when I call pivotUI() then I see the values correctly in each cell as Y or N.  However, when I call pivot() the values always show as 1 (count?) instead of the Y or N value.

**Comment by benharrell** [comment]
actually I see now that aggregatorName is not supported for pivot() and I should set the aggregator value...thx! sorry :)

**Comment by PhantomYdn** [comment]
Looks related to #451. It would be great if config prepared by pivotUI can be used as is for pivot().

**Comment by nicolaskruchten** [comment]
This is by design: these two functions have different behaviours and different parameters.
