### ISSUE TITLE
using pivot() but change aggregator at runtime?

### ISSUE THREAD

**Issue by benharrell** [nicolaskruchten/pivottable#447]
is it possible to have my own menu to change the aggregator function?  would prefer to just set the aggregatorName like the "ui" version, is that possible?

**Comment by nicolaskruchten** [comment]
There's nothing built-in for that, but you can easily wrap `pivot()` just like `pivotUI()` does, with a simpler interface like a single dropdown for aggregators :)

**Comment by benharrell** [comment]
thx will consider it!
