### ISSUE TITLE
Get current Row / Column in customer Aggregators

### ISSUE THREAD

**Issue by Dave3of5** [nicolaskruchten/pivottable#448]
Does anyone know if it's possible to get the current row / column in a custom aggregator ?

I'm trying to add a different type of calculation as an aggregation function.

**Comment by brylie** [comment]
What do you get when you `console.log(this)`?

**Comment by Dave3of5** [comment]
Ok bit more info If I try this example:

```
var successRate = function() {
  return function() {
    return {
      sumSuccesses: 0,
      sumTrials: 0,
      push: function(record) {
        if (!isNaN(parseFloat(record.successes))) {
          this.sumSuccesses += parseFloat(record.successes);
        }
        if (!isNaN(parseFloat(record[denom]))) {
          return this.sumTrials += parseFloat(record.trials);
        }
      },
      value: function() { return this.sumSuccesses / this.sumTrials; },
      format: function(x) { return x; },
      numInputs: 0
    };
  };
};
```

The value function doesn't seem to be able to get the current record only the aggregator function.

Btw returning this on the example listed  would just return the object with  sumSuccesses: 0,sumTrials: 0

**Comment by brylie** [comment]
Does the value function provide any arguments that you can catch?

**Comment by Dave3of5** [comment]
Tried that and I get nothing :-(

**Comment by brylie** [comment]
OK, hm. I am trying to find the documentation.

**Comment by brylie** [comment]
The docs saty:
> Aggregator functions receive 3 parameters: a PivotData object, a rowKey and a colKey

Can you use the row key to access the row from the data object in the parent scope?

**Comment by brylie** [comment]
I.e. you might catch all three parameters as described, and do something like `data[rowKey]` from within the `value` function.

**Comment by Dave3of5** [comment]
My function is defined like:

```
                    value: function (data, rowKey, colKey) {
                        debugger;
                        return 0; },
```

And in the debugger I get:

`data = undefined, rowKey = undefined, colKey = undefined`

**Comment by brylie** [comment]
Hm, right. Seems contrary to the documentation.

**Comment by Dave3of5** [comment]
I think the function def would look like:

> var countUnique = function(attributeArray) {
>   var attribute = attributeArray[0];
>   return function(data, rowKey, colKey) {
>     return {
>       uniq: [],
>       push: function(record) {
>         var _ref;
>         if (_ref = record[attribute], __indexOf.call(this.uniq, _ref) &lt; 0) {
>           this.uniq.push(record[attribute]);
>         }
>       },
>       value: function() { return this.uniq.length; },
>       format: function(x) { return x; },
>       numInputs: 1
>     };
>   };
> }

but as you can see the value function still doesn't get passed those vars :-(

**Comment by brylie** [comment]
Ah, make sure you are passing in the attribute array.

**Comment by Dave3of5** [comment]
Sorry I don't understand.

**Comment by brylie** [comment]
You also might need to pass in the data, rowKey, and colKey arguments to the return function.

**Comment by Dave3of5** [comment]
Could you show an example ?

**Comment by brylie** [comment]
```
var successRate = function() {
  return function(data, rowKey, colKey) { // These arguments may be necessary
    return {
      sumSuccesses: 0,
      sumTrials: 0,
      push: function(record) {
        if (!isNaN(parseFloat(record.successes))) {
          this.sumSuccesses += parseFloat(record.successes);
        }
        if (!isNaN(parseFloat(record[denom]))) {
          return this.sumTrials += parseFloat(record.trials);
        }
      },
      value: function() { return this.sumSuccesses / this.sumTrials; },
      format: function(x) { return x; },
      numInputs: 0
    };
  };
};
```

**Comment by brylie** [comment]
I have posted some example code.

**Comment by Dave3of5** [comment]
Thanks !

**Comment by Dave3of5** [comment]
Bah rowKey and colKey are empty arrays !

**Comment by Dave3of5** [comment]
Ah it's because I'm adding them as a closure so those vars only reference the on startup...

**Comment by brylie** [comment]
Right, I was thinking something like that was the case. Closures are confusing :-)

**Comment by Dave3of5** [comment]
Yeah :-( looks like there is no way to find anything about the current record you are on when creating an aggregator function :-(.

**Comment by philliproso** [comment]
rowKey and colKey are empty arrays when you fetch the grand total aggregator. Else they are a list of the values of the properties of the group by statements in the rows and cols. 

To do what you want to do you need to dig a little deeper into pivotData data-structure. 
Each cell in the pivottable is aggregator object that can be fetched via data.getAggregator(colKey,rowKey).  The cells that are empty have no aggregregator.  This should help.

```
var successRate = function(attributeArray) {
  var attribute = attributeArray[0];
  return function(data, rowKey, colKey) { // These arguments may be necessary
    return {
      sumSuccesses: 0,
      sumTrials: 0,
      push: function(record) {
        if (!isNaN(parseFloat(record.successes))) {
          this.sumSuccesses += parseFloat(record.successes);
        }
        if (!isNaN(parseFloat(record[denom]))) {
          return this.sumTrials += parseFloat(record.trials);
        }
      },
      value: function (data, rowKey, colKey) { // remember to handle them here too
      //get all possible columns for this dataset. 
        var colkeys = data.getColKeys();
        var allRows =[];
        
        //loop through all possible columns
        colKeys.forEach(function(newColKey){
               var row_agg = data.getAggregator(rowKey,newColKey)
               if (row_agg.hasOwnProperty('value')){
               allRows.push(agg.value())
                } else {
                  allRows.push('Some sane default')
                  }
             })
       //Use the values in allRows in a calculation
        return this.sumSuccesses / this.sumTrials; 
      },
      format: function(x) { return x; },
      numInputs: 0
    };
  };
};
```

**Comment by Dave3of5** [comment]
Just tried this and I get:

Cannot read property 'getColKeys' of undefined.

**Comment by nicolaskruchten** [comment]
Indeed the way to do this is via the `data, rowKey, colKey` parameters, which you need to capture in a closure.

The only built-in aggregator which uses this is the `fractionOf` aggregator and it's a bit of a mind-bender because it wraps other aggregators.

The key to making this work is *not* to have `data, rowKey, colKey` as parameters to the `value` function, so that the body of the `value` function access the objects in the closure.

**Comment by Dave3of5** [comment]
But then they don't get updated.

**Comment by nicolaskruchten** [comment]
I don't follow... There is one aggregator for each cell in the table, so they never get updated.

**Comment by nicolaskruchten** [comment]
Oh, and value is only called once per aggregator.

**Comment by Dave3of5** [comment]
What I mean is these values:

 rowKey, colKey

are always empty arrays regardless of if I use a closure or not.

**Comment by nicolaskruchten** [comment]
Yes, for the Grand Total aggregator, but not for the other ones.

**Comment by Dave3of5** [comment]
Can you show an example? I'm always getting empty array.

**Comment by nicolaskruchten** [comment]
Can you post an example of what you're trying so I can copy it and edit it?

**Comment by Dave3of5** [comment]
Thank you for the help. I've managed to create my calculation without needing access to the current cell so I'll just leave it as is. Maybe just close this issue now.

**Comment by Dave3of5** [comment]
Closing.,

**Comment by nicolaskruchten** [comment]
OK. Well here's an example of it working ... just look in the console: https://jsfiddle.net/spd346y8/
