### ISSUE TITLE
Heatmap custom colors

### ISSUE THREAD

**Issue by Dave3of5** [nicolaskruchten/pivottable#449]
Anyone know if there is an easy way to define custom colors for the heatmap render?

I've never used d3 / c3 unfortunately.

**Comment by nicolaskruchten** [comment]
There is no particularly easy way other than editing the heatmap function at the bottom of pivot.coffee

**Comment by nicolaskruchten** [comment]
(which is not written in c3/d3, but rather jQuery)

**Comment by Dave3of5** [comment]
Ok thanks I see this now :-).

**Comment by nicolaskruchten** [comment]
You can now specify a custom color scale function, see the example here: http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html
