### ISSUE TITLE
OnClick event

### ISSUE THREAD

**Issue by caracal7** [nicolaskruchten/pivottable#45]
It's very important to have ability to click on cell and get array of aggregated values...
Without this it's very difficult to integrate pivottable in the any serious project...
Usualy OLAP-table is something like a filter to details table...

P.S. Good work. Best javascript pivot table! )

Sorry for my very bad english((

**Comment by nicolaskruchten** [comment]
this functionality is now in master as of 87c2e3da58b60c672bee8fe612a8b63a3a217c47
