### ISSUE TITLE
pivot() doesn't support rendererName

### ISSUE THREAD

**Issue by PhantomYdn** [nicolaskruchten/pivottable#451]
It looks strange that pivotUI() do support rendererName as parameter, but pivot() do not. So prepared configuration from pivotUI() can't be used for pivot()

**Comment by nicolaskruchten** [comment]
This is by design: these two functions have different behaviours and different parameters.

**Comment by PhantomYdn** [comment]
I see. I work-arounded that by this: https://github.com/OrienteerDW/Orienteer/blob/master/orienteer-pivottable/src/main/resources/org/orienteer/pivottable/component/pivottable.tmpl.js

I understand that you want to keep functionality wide, but from user perspective it might look strange, because pivotUI() can be used as editor for configuration which then should be used by pivot().
Example of usage: http://demo.orienteer.org/browse/DemoPivotTable
Just click small cogwheel on right-top side.

**Comment by nicolaskruchten** [comment]
The way you've implemented it is pretty much the way I would do it :)
