### ISSUE TITLE
PivotUI() showing error on the same data where pivot() is OK

### ISSUE THREAD

**Issue by PhantomYdn** [nicolaskruchten/pivottable#452]
Please see demo: https://jsfiddle.net/phantomydn/an2ayxbh/

**Comment by nicolaskruchten** [comment]
Your input is malformed, and so the behaviour is undefined: every object in the array must have the same keys...

**Comment by PhantomYdn** [comment]
Yes. That's right. But it's pretty common for rest json just skip field.

So we at [Orienteer](http://orienteer.org) will be happy if either this input can be valid or library will allow to specify explicit set of fields. And, btw, if it will allow to specify more human readable(localized for example) names for fields from json - that will be perfect!
Thanks for such brilliant library!

**Comment by nicolaskruchten** [comment]
Thanks for the feedback!

**Comment by PhantomYdn** [comment]
Welcome! So: are you saying that it's ok that pivot() renders a data, but pivotUI() doesn't for the same data? If data is wrong, pivot() should fail as well. From my perspective there is some issue about that just in pivotUI() code. 

According to [source code](https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee)
it should be easy to fix. I'm not expert of Coffee, but, please, take a look:

```cofee
tblCols = (k for own k of input[0])
tblCols.push c for own c of opts.derivedAttributes when (c not in tblCols)

#figure out the cardinality and some stats
axisValues = {}
axisValues[x] = {} for x in tblCols

PivotData.forEachRecord input, opts.derivedAttributes, (record) ->
for own k, v of record when opts.filter(record)
        v ?= "null"
        axisValues[k][v] ?= 0  # LINE A
        axisValues[k][v]++
```

Error is happining at line A, because axisValues doesn't have value for key "k".
Probably something like the following should be added just before LINE A

(sorry for javascript!)
```javascript
if(!axisValues[k]) {
   tblCols.push(k);
   axisValues[k] = {};
}
```

**Comment by nicolaskruchten** [comment]
For the input given, are you expecting the `c` attribute to be included in the output, such that we treat the input as having the union of the attribute of all record? Or are you expecting that the attributes be only the ones present in the first record?

**Comment by PhantomYdn** [comment]
I would expect that 'c' will be added into output.

Original problem is that REST/JSON databases can omit some data if it's null. For example that's the case for OrientDB. So first row might have not all required columns.
And there I see 2 options:
1) Library will adjust automatically set of columns during going through data and finding new columns (preferred option)
2) Or library can allow to specify set of columns which should be used (good option, but it will be nice to have it in addition to p.1)

**Comment by nicolaskruchten** [comment]
The current state of things is that point 2 can be emulated by ensuring that the first row has entries for all desired columns or by using the function input method instead of passing in an array of heterogeneous objects. I'll think about the changes required for point 1.

**Comment by PhantomYdn** [comment]
Thanks! The point is that sometimes there is no way to influence to a way how data returned by some DB. So to insure that first column has everything might be problematic.

**Comment by nicolaskruchten** [comment]
I have a PR open #600 which I believe addresses this issue... Could you take a look and let me know if it meets your needs?

**Comment by PhantomYdn** [comment]
@nicolaskruchten , PR looks good for me!:) Thank you!

**Comment by nicolaskruchten** [comment]
OK, merged and released, I'm closing out this issue :)
