### ISSUE TITLE
Freeze option for pivot table

### ISSUE THREAD

**Issue by krishnathumma** [nicolaskruchten/pivottable#454]
Hi Nicolas,

Is it possible add freeze option  in pivot table like in excel sheet on scrolling time?
Cell/Row headers to be fixed when we scrolling. 
Please help me.

Thanks,
Krishna.

**Comment by nicolaskruchten** [comment]
This is not a supported feature at this time, sorry.

**Comment by Dams591** [comment]
Any clues how I could do that ?
