### ISSUE TITLE
"rendererName" does not work with fixed pivots

### ISSUE THREAD

**Issue by jiteshvassa** [nicolaskruchten/pivottable#455]
The property "rendererName" does not appear to work when using non editable pivots, i.e. pivot(...).  It does however work on pivotUI(...).

See example here: https://jsfiddle.net/vqkk7kh5/1/

In the example if you change pivot(...) to pivotUI(...) you see that the heat map is shown.

**Comment by nicolaskruchten** [comment]
Please see [this FAQ entry](../wiki/Frequently-Asked-Questions#params).
