### ISSUE TITLE
"aggregatorName" does not work with fixed pivots

### ISSUE THREAD

**Issue by jiteshvassa** [nicolaskruchten/pivottable#456]
The property "aggregatorName" does not appear to work when using non-editable pivots, i.e. pivot(...). It does however work on pivotUI(...).

See example here: https://jsfiddle.net/vqkk7kh5/2/

In the example if you change pivot(...) to pivotUI(...) you see that the defined aggregator is used.

**Comment by nicolaskruchten** [comment]
This is by design: `pivot()` and `pivotUI()` accept different parameters. Please check the documentation.

**Comment by jiteshvassa** [comment]
I had a quick look at the docs here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

Both Pivot and PivotUI appear to accept "aggregatorName".

**Comment by nicolaskruchten** [comment]
Yes but if you read closely they do different things.
