### ISSUE TITLE
Pie Chart Integration into pivot tables

### ISSUE THREAD

**Issue by krishnathumma** [nicolaskruchten/pivottable#457]
Hi  Nicolaskruchten,

How can i get the pie chart option into pivot table.

**Comment by nicolaskruchten** [comment]
This is not supported, please see https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#pie-charts-in-the-chart-renderers

**Comment by krishnathumma** [comment]
Hi Nicolaskruchten,

I solve this one. just added the pie chart code in renders page

**Comment by kumarabrol** [comment]
Hi Krishna,
Please share the code what has been added for rendering pie chart in pivotUI.

**Comment by nicolaskruchten** [comment]
Pie charts are now built in :)
