### ISSUE TITLE
Pivot table is available in angulerJs? 

### ISSUE THREAD

**Issue by krishnathumma** [nicolaskruchten/pivottable#458]
Hi Nicolas,

now this thing is working with jquery fine, i need this in angulerjs is it possible?

**Comment by nicolaskruchten** [comment]
I don't have any experience with angular JS myself so I won't be able to help you with that.

**Comment by jupe** [comment]
@krishnathumma check this one: https://github.com/nicolaskruchten/pivottable/issues/208

**Comment by benharrell** [comment]
I was able to easily wrap this in Angular 2, should be trivial in angular 1

**Comment by maciej-karpus** [comment]
@benharrell Hi Ben, I would be eternally grateful if you could share your wrapper for Angular 2.
