### ISSUE TITLE
Combining columns, or rendering multiple tables

### ISSUE THREAD

**Issue by LukeBrumfield** [nicolaskruchten/pivottable#460]
I'm working with the "Males" dataset, http://nicolas.kruchten.com/pivottable/examples/rcsvs.html
I could then use the dynamic filtering to sort out rows based on year, location, etc. This is the important part, as I want to use the same data for each table.

If I look health on the rows, I get this table:

<table class="pvtTable" data-numrows="2" data-numcols="0"><tr><th class="pvtAxisLabel">health</th><th class="pvtTotalLabel">Totals</th></tr><tr><th class="pvtRowLabel" rowspan="1">no</th><td class="pvtTotal rowTotal" data-value="4286" data-for="row0">4,286</td></tr><tr><th class="pvtRowLabel" rowspan="1">yes</th><td class="pvtTotal rowTotal" data-value="74" data-for="row1">74</td></tr><tr><th class="pvtTotalLabel" colspan="1">Totals</th><td class="pvtGrandTotal" data-value="4360">4,360</td></tr></table>

What I am looking to do is change heath from "yes" and "no" to 0/1 and then do a count, and get something like this (disabling totals also)

<table class="pvtTable" data-numrows="2" data-numcols="0">
  <tr>
    <th class="pvtAxisLabel">health</th>
    <td class="pvtTotal rowTotal" data-value="74" data-for="row1">74</td>
  </tr>
</table>

This can be done with hiding rows and totals, but where I might have to add some code is if I want to add other labels without having to combine them. Someone would either have a 0 or 1 for things like married, health, union etc
I would want to have a table like this generated from the males dataset:

<table class="pvtTable" data-numrows="2" data-numcols="0">
  <tr>
    <th class="pvtAxisLabel">health</th>
    <td class="pvtTotal rowTotal" data-value="74" data-for="row1">74</td>
  </tr>
  <tr>
    <th class="pvtAxisLabel">married</th>
    <td class="pvtTotal rowTotal" data-value="1914" data-for="row1">1,914</td>
  </tr>
  <tr>
    <th class="pvtAxisLabel">union</th>
    <td class="pvtTotal rowTotal" data-value="1064" data-for="row1">1,064</td>
  </tr>
</table>

This can be generated by rendering multiple tables and then combining the `<tr>` elements. This would get sort of messy, but I think it could be done. Does anyone have any suggestions?

**Comment by nicolaskruchten** [comment]
I think at this point you're pushing this library a bit past its design goals :)
