### ISSUE TITLE
Enhance PivotData.processRecord to provide subtotals

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [nicolaskruchten/pivottable#461]
@nicolaskruchten w.r.t. Issues #25 and #26 enhancing `PivotData.processRecord` to provide subtotal values is a necessity to build renderers with subtotal features. I am creating this issue so that we track this and close this core dependency first so that new renderers can be built later on top of this enhancement. The code currently that works but may not be good in performing faster is given below:

    processKey: (record, totals, keys, attrs, f) ->
        key = []
        addKey = false
        for attr in attrs
            key.push record[attr] ? "null" 
            flatKey = key.join(String.fromCharCode(0))
            if not totals[flatKey]
                totals[flatKey] = f(key)
                addKey = true
            totals[flatKey].push record
        if addKey
            keys.push key
        return key

    processRecord: (record) -> #this code is called in a tight loop
        @allTotal.push record
        rowKey = @processKey record, @rowTotals, @rowKeys, @rowAttrs, (key) =>
                return @aggregator(this, key, [])            
        colKey = @processKey record, @colTotals, @colKeys, @colAttrs, (key) =>
                return @aggregator(this, [], key)
        m = rowKey.length-1
        n = colKey.length-1            
        if m < 0 or n < 0
            return
        for i in [0..m]
            flatRowKey = rowKey.slice(0, i+1).join(String.fromCharCode(0))
            if not @tree[flatRowKey]
                @tree[flatRowKey] = {}
            for j in [0..n]
                flatColKey = colKey.slice(0, j+1).join(String.fromCharCode(0))
                if not @tree[flatRowKey][flatColKey]
                    @tree[flatRowKey][flatColKey] = @aggregator(this, rowKey, colKey)
                @tree[flatRowKey][flatColKey].push record

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten I have added an option called `processor` for the developer to choose the record processing method of their choice. This will avoid any changes to the existing core and simple data processing method (`processRecord`) and provide ability to configure new data processing method if a user desires to. I have added `subtotal_processor` and used it in the demo **pivotUI() with subtotal rows and columns** 

I plan to push this change alone as a PR. Please let me know your feedback before I send the PR.

Please check the changes at: [Subtotals branch here...](https://github.com/nagarajanchinnasamy/pivottable/tree/SubTotals)

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten  the above code is updated with fix for issues in **Fraction of Rows** and **Fraction of Columns**. Now, cloning the key array before sending it to create aggregator.

    callWithJQuery = (pivotModule) ->
    if typeof exports is "object" and typeof module is "object" # CommonJS
        pivotModule require("jquery")
    else if typeof define is "function" and define.amd # AMD
        define ["jquery"], pivotModule
    # Plain browser env
    else
        pivotModule jQuery
        
    callWithJQuery ($) ->

    subtotalProcessor = (opts) ->
        colAttrs = opts.cols
        rowAttrs = opts.rows

        processKey = (record, totals, keys, attrs, f) ->
            key = []
            addKey = false
            for attr in attrs
                key.push record[attr] ? "null" 
                flatKey = key.join(String.fromCharCode(0))
                if not totals[flatKey]
                    totals[flatKey] = f(key.slice())
                    addKey = true
                totals[flatKey].push record
            if addKey
                keys.push key
            return key
  
        (pivotData, record) -> #this code is called in a tight loop
            tree = pivotData.tree
            rowKeys = pivotData.rowKeys
            colKeys = pivotData.colKeys
            rowTotals = pivotData.rowTotals
            colTotals = pivotData.colTotals
            allTotal = pivotData.allTotal
            aggregator = pivotData.aggregator

            allTotal.push record
            rowKey = processKey record, rowTotals, rowKeys, rowAttrs, (key) =>
                    return aggregator(this, key, [])
            colKey = processKey record, colTotals, colKeys, colAttrs, (key) =>
                    return aggregator(this, [], key)
            m = rowKey.length-1
            n = colKey.length-1            
            if m < 0 or n < 0
                return
            for i in [0..m]
                fRowKey = rowKey.slice(0, i+1)
                flatRowKey = fRowKey.join(String.fromCharCode(0))
                if not @tree[flatRowKey]
                    tree[flatRowKey] = {}
                for j in [0..n]
                    fColKey = colKey.slice(0, j+1)
                    flatColKey = fColKey.join(String.fromCharCode(0))
                    if not tree[flatRowKey][flatColKey]
                        tree[flatRowKey][flatColKey] = aggregator(this, fRowKey, fColKey)
                    tree[flatRowKey][flatColKey].push record

    $.pivotUtilities.subtotal_processor = (opts) -> subtotalProcessor(opts)

**Comment by nicolaskruchten** [comment]
OK, I will take a look to see if I can merge the two processors. I don't like the idea of forcing the developer to override the processor for a specific renderer.

What's the performance difference between the two processors in your experience so far?

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten Looks like subtotal processor takes double the time of default processor. if I consider mps.html (`pivotUI() with derived attributes`) with

                rows: ["Gender", "Province", "Party"],
                cols: ["Age Bin"],

On my system:

**Default processor** most of the times took: **4 milliseconds** and **TableRenderer** most of the times  took: **12 milliseconds**.

**Subtotal processor** most of the times took: **8 milliseconds** and **SubtotalRenderer** most of the time took: **16 milliseconds**

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten , fine with merging the processors. However, I suggest to keep the `processor` option. This helps in trying out any new experimental/custom processing logic without touching the existing built-in processor. We can ensure that there is always only one processor in-built while retaining the ability to configure a custom processor if the developer wishes.

**Comment by nicolaskruchten** [comment]
Sorry, I should have made my previous comment here instead... My proposal is that instead of allowing the overriding of the "processor" we allow the overriding of the entire `PivotData` class, which allows for more flexibility in implementing different "processors" and less coupling. Thoughts?

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten Thanks for your response. Ability to override entire `PivotData` class is a good idea.... Agree... That will give more flexibility... just wondering whether `overriding-PivotData` will be expected to adhere to a minimal, agreed upon interface contract!!!???

**Comment by nicolaskruchten** [comment]
Yes, any replacement would need to have very similar external behaviour... I suppose this would mean I would have to document this class' interface a bit more :)

In you case, however, you would just subclass the PivotData class and override the one method so it's fairly easy/low-risk!

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten, I think the ability to replace gives more flexibility than inheritance... Also one can write a new-PivotData in JavaScript and replace the default one! That will bring in more contribution from JavaScript-only developers too...

as you said, replacement opens up the possibility of writing different kinds of PivotData... Will wait for the replacement option :-)

**Comment by nicolaskruchten** [comment]
OK, I've pushed a branch called `configurable_pivotdata` which contains the changes (in commit eeec720a17fd7). There is a new parameter called `dataClass` for both `pivot()` and `pivotUI()`.

Please let me know if you can work with this and I'll merge into master, otherwise we'll iterate :)

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten, as u had suggested, I've created `SubtotalPivotData` class that extends `PivotData`. Overridden `ProcessRecord` function. Introduced a link in `index.html` to the example `subtotal.html`.

Submitted PR #506. Please review and let me know of your feedback.

**Comment by nicolaskruchten** [comment]
Whoops, sorry about the triangle character breakage... I'll revert that change!

**Comment by nicolaskruchten** [comment]
`dataClass` change has been merged to master.
