### ISSUE TITLE
Initializing pivot with some saved state and get the updated state after some modifications?

### ISSUE THREAD

**Issue by rameshgorantla** [nicolaskruchten/pivottable#462]
I saved a state and reinitialized pivot with that, now i want to save that state also. Is that possible?
I tried passing three parameters to pivotUI, data, state, and onrefresh method but its not working, it either updates pivot with saved state or uses onrefresh function but not both.

**Comment by nicolaskruchten** [comment]
This is definitely possible. You pass in whatever state you like and every time the `onRefresh` callback is called, it's called with the latest state. You can then save that state and pass it back into another call.

Can you describe in more detail what you say is "not working" ?

**Comment by rameshgorantla** [comment]
This is how i'm passing the parameters.

$(".pivotOutput").pivotUI(input,state,{onRefresh: function(config) {
        	
           var config_copy = JSON.parse(JSON.stringify(config));
            //delete some values which are functions
            delete config_copy["aggregators"];
            delete config_copy["renderers"];
            //delete some bulky default values
            delete config_copy["rendererOptions"];
            delete config_copy["localeStrings"];
           
            $("#pivotState").text(JSON.stringify(config_copy, undefined, 2));
            
	}}
	);

The state variable has the previously saved state. Above code is populating the pivot table with passed state, but onrefresh is not being called. Whenever i do some changes in the UI  onrefresh callback is not called.

**Comment by nicolaskruchten** [comment]
If you look at the example here http://nicolas.kruchten.com/pivottable/examples/onrefresh.html you'll see that the `onRefresh` function needs to be passed in as part of the params (i.e. what you have called the `state` object) and not as a third argument to `pivotUI()`.

**Comment by rameshgorantla** [comment]
$(".pivotOutput").pivotUI(input,{onRefresh: function(config)}});

I tried the above code but its still not working. config variable has the previously saved state.

**Comment by nicolaskruchten** [comment]
You're going to have to add the onRefresh callback to the state before passing it in.

**Comment by rameshgorantla** [comment]
I called the on refresh as second parameter as you mentioned in earlier comments passing the state to it. Is what i have done wrong? If yes, how do i do that correctly.

**Comment by nicolaskruchten** [comment]
What is it exactly you are trying to do? Where are you wanting to save the state?

**Comment by rameshgorantla** [comment]
I have a previously saved state as an object, i want to initialize a new pivot with that state and i also want to capture the changes on that.

**Comment by nicolaskruchten** [comment]
Where is the state saved and how are you wanting to "capture" the state?

The way `pivotUI()` works is that it initializes itself with the parameters you pass in, and if you pass in an `onRefresh` function in the parameters, then every time there is a change, PivotTable.js will call that function, with the current state as input.

**Comment by rameshgorantla** [comment]
I'm saving the state in a file and when user reloads the page i will get it from that file and want to show the pivot with that state, now if users modifies it again i want to capture that as well.

So its like i want a pivot with predefined state as well as onrefresh.

**Comment by nicolaskruchten** [comment]
OK, then you need to do something like this:

1. get your `state` object from storage
2. define a function which takes a `state` object and saves it
3. add that function to your `state` object under the key `onRefresh`
4. call `pivotUI()` with your `state` object

**Comment by rameshgorantla** [comment]
I will try that, thanks.

**Comment by ashbike** [comment]
This will work.

```
    var renderers = $.extend($.pivotUtilities.renderers, $.pivotUtilities.c3_renderers, $.pivotUtilities.export_renderers); // Typical pivottable init stuff...
    
    var data = <LOAD DATA>; // Load the data from wherever you want...
    
    // We store the state against key 'pivotdatakey'
    // here we are getting saved state from LocalStorage... 
    var config = localStorage.getItem('pivotdatakey'); 
    
    if (config) { // If a saved state found in LocalStorage, then load it
        var configobject = JSON.parse(config); // Make it an object
        configobject.onRefresh = saveState; // Add callback function for onRefresh

        $("#timelog_renderer").pivotUI( // Load with saved state
                data, configobject
                );
    } else { // State not found in LocalStorage. So create without a saved state
        $("#timelog_renderer").pivotUI(
                data,
                {
                    renderers: renderers,
                    rows: ["Project"],
                    cols: ["Who"],
                    aggregatorName: 'Sum',
                    vals: ["Effort in Hours"],
                    onRefresh: saveState // Add the same callback function here.
                }
        );
    }
    
    // This function stores PivotTable config to LocalStorage.
    function saveState(config) {
        var config_copy = JSON.parse(JSON.stringify(config));
        //delete some values which are functions
        delete config_copy["aggregators"];
        delete config_copy["renderers"];
        //delete some bulky default values
        delete config_copy["rendererOptions"];
        delete config_copy["localeStrings"];
        localStorage.setItem('pivotdatakey', JSON.stringify(config_copy, undefined, 2));
    }

```

**Comment by IrinaShirinsky** [comment]
I have a similar issue. 
I have a selection dropdown box with predefined configurations and want to update pivot table on selection change.
This is onchange function
```
         $("#selectconfig").change(function() {
		showTable(jsonData, this.value);
         });
```
showTable function
```
       var showTable = function(data, config) {
              $("#output").pivotUI(data, configs[config]);
        }
```

where configs is predefined object:
`      var configs = {"config1": config1, "config2": config2};`

It loads the correct selected configuration at the first time. Any selection in selection box do not reload the pivot table. Sometimes it flashes but still show the old configuration.

**What should I do to force pivot table update?**

Thanks

**Comment by IrinaShirinsky** [comment]
The problem is solved by using `overwrite ` parameter.
This works:
```
       var showTable = function(data, config) {
              $("#output").pivotUI(data, configs[config], true);
        }
```

**Comment by nicolaskruchten** [comment]
For reference, here is an example with saving/restoring to cookies: http://nicolas.kruchten.com/pivottable/examples/save_restore.html

**Comment by misteliy** [comment]
How would I add back the aggregaros and renderers?
