### ISSUE TITLE
Plugin for atom editor

### ISSUE THREAD

**Issue by y-takey** [nicolaskruchten/pivottable#464]
Dear @nicolaskruchten,

Thanks for awesome a javascript library!
I made a [plugin](https://github.com/y-takey/atom-pivottable) for atom editor. Please add the plugin to [page Used by ](https://github.com/nicolaskruchten/pivottable/wiki/Used-By) if you'd like.

**Comment by nicolaskruchten** [comment]
Wow, this is great, thanks for the heads-up! I've added it to the Used By page :)

**Comment by y-takey** [comment]
Thanks so much for the quick response. :)

**Comment by brylie** [comment]
I just tested the plugin and get an error about `missing jQuery`. I opened an [issue](https://github.com/y-takey/atom-pivottable/issues/1).
