### ISSUE TITLE
Pivot table hangs while load 7k+ data at a time

### ISSUE THREAD

**Issue by erashu212** [nicolaskruchten/pivottable#465]
Hi @nicolaskruchten ,

It seems this pivot table is working smoothly if the data count is below 1000. But it starts behaving unexpected if i load 7000+ data.

What could be the reason and what should i do?

Thanks,

**Comment by nicolaskruchten** [comment]
What are the specs of he machine you're running it on, what is the browser/os combination? Those will have an impact.

Beyond that, I will need to see a data sample to be able to help more...

**Comment by erashu212** [comment]
Hi @nicolaskruchten ,

Please find the details here.

Server Machine configuration (Where application hosted) :-

Windows 2008R2, 
2GB Ram,
Intel Xenon CPU 2.18Ghz,
64 Bit

Client Machine :-

Mac OS X EI Campitan
2.5 Ghz, Core i5,
8 GB Ram
Chrome

And the dataset are as follows.

{"status":"Success","data":[{"ID":9,"NAME":"2533TX"},{"ID":4,"NAME":"CA"},{"ID":8,"NAME":"CAN  Toronto"},{"ID":2,"NAME":"DACTION"},{"ID":5,"NAME":"GA"},{"ID":6,"NAME":"IN"},{"ID":7,"NAME":"MD"},{"ID":11,"NAME":"TAOMOTOR CA"},{"ID":10,"NAME":"TAOMOTOR TX"},{"ID":3,"NAME":"TAOTAOUSA"}]}

Thanks

**Comment by erashu212** [comment]
Hi @nicolaskruchten ,

Is there any way to implement paging to enhance performance.

Thanks,
Ashutosh

**Comment by nicolaskruchten** [comment]
OK, so the hardware and browser look fine.

For the input data, I assume you're only passing in the array under the `data` key, correct? Performance on a dataset like this should be good up to around 100k rows.

What does your output table look like? i.e. what attributes are you putting in rows and columns?

Regarding paging, there is no such feature in any builtin PivotTable.js renderer.

**Comment by erashu212** [comment]
Hi @nicolaskruchten ,

Here is the configuration object.

`var options = {
      rows: ["Customer"],
      cols: [
        'ProductName',
        'Description',
        'Qty',
        'TotalSales',
        'SalesResp'
      ]
    }`

Please correct me I am doing anything wrong.

**Comment by nicolaskruchten** [comment]
That looks reasonable. How many different combinations of `[ 'ProductName', 'Description', 'Qty', 'TotalSales', 'SalesResp' ]` are there? If you have dozens of customers and hundreds of combinations of those columns, performance will suffer greatly as you are trying to render a giant table.

**Comment by erashu212** [comment]
Hi @nicolaskruchten,

You are right. What should I do in this case?

**Comment by nicolaskruchten** [comment]
There's not a lot you can do to render giant tables faster. You mentioned paging earlier, and that might be your best bet: you could implement your own renderer which supports paging.

**Comment by srgcrafty** [comment]
Is there a way to set filters on certain attributes in the pivot table without completely calling pivotUI() again and re-rendering the table? I am also working on a large data set, and filtering within the table is snappy enough, but I also want to be able to set these from outside the table in code. Re-rendering the table passing in these attributes is the only method I've found so far, but is unacceptably resource-consuming. Any suggestion on how to go about doing this?

**Comment by nicolaskruchten** [comment]
@srgcrafty I'm not sure what you're trying to do here but can you please open a new issue which describes it and I can try to help you?
