### ISSUE TITLE
About Server Side Processing via Ajax

### ISSUE THREAD

**Issue by phanijapps** [nicolaskruchten/pivottable#466]
Firstly I would like to thank for creating a clean understandable code. I would like to know how to extend and generate pivot data on server side so that this solution will work for any number of rows.

eg: Oracle 11g has a pivot function that can get the Pivot Data for a larger data sample if needed.

**Comment by nicolaskruchten** [comment]
Please see [this FAQ entry](../wiki/Frequently-Asked-Questions#server-side-integration).
