### ISSUE TITLE
Problem displaying links

### ISSUE THREAD

**Issue by meleysk** [nicolaskruchten/pivottable#469]
We are trying to use your library to display a table that contains a column of clickable numbers. I am using a decoder to display the link HTML. The decoder works fine on the original grid view, it displays the Tkt# column contents as clickable numbers. However, when I apply the pivotUI, the contents of the column get displayed as regular numbers and are not clickable. 
Below is a screenshot of the two outputs. The first is the grid view, you can see the blue numbers (clickable links). Whereas in the second picture, the same numbers are displayed as regular numbers.
I have attached screenshots of the two different outputs and portion of my code for your reference. Please let me know if you need additional information.

![outputwithoutpivott](https://cloud.githubusercontent.com/assets/12005162/14186602/2e0b3ef2-f74d-11e5-9534-26eb631f6d6f.png)
![outputofpivottable](https://cloud.githubusercontent.com/assets/12005162/14186638/4aa95e7c-f74d-11e5-994a-59c2589f0781.png)
![pivottable](https://cloud.githubusercontent.com/assets/12005162/14186655/61b94f32-f74d-11e5-848f-2e23ea22b2f7.png)
![decodercode](https://cloud.githubusercontent.com/assets/12005162/14186662/6d9fa594-f74d-11e5-871f-359583ff70b5.png)

**Comment by meleysk** [comment]
@nicolaskruchten  any suggestions would be appreciated. Thanks.

**Comment by nicolaskruchten** [comment]
Apologies for the delay.

I have no real suggestion for you unfortunately... The table renderer outputs text, not HTML, so there is no way to make it display links. The only thing I can think of would be for you to write some jQuery code that would execute after every refresh (i.e. in the `onRefresh` callback) which would edit the DOM of the output of the table renderer to add the links back in.

**Comment by deecay** [comment]
Hi nicolas,

Any chance of implementing the following feature from the [older discussion] ?(https://github.com/nicolaskruchten/pivottable/pull/401)

> If the larger scope was to allow HTML content for headings, then I would suggest an opt-in flag to add support for that. Most templating languages will escape content by default and then have a feature (e.g.  {{{  for handlebars,  !=  for Jade) that allows for outputting unescaped content.

Can you consider implementing something like AllowHTML or AllowedHTMLTags option?

**Comment by nicolaskruchten** [comment]
@deecay I don't think I want to go down that road again, no, it opens up too much complexity, and is only applicable to the table renderers and not the charts. I really think that just post-processing the table is the best option here.

**Comment by deecay** [comment]
Nicolas,

OK. Thank you for sharing your overall idea on this.
