### ISSUE TITLE
Add new renderer 

### ISSUE THREAD

**Issue by thovo** [nicolaskruchten/pivottable#471]
Is it possible to add new renderer inside of built-in renderer? I read the FAQ and other documents but I am sorry if I didn't see how to do it.

I want to add new renderer's name "Grid" would display different background-color for `tr:nth-child(2n+1)`. I saw the example of adding c3 chart renderer, I thought I needed to do the same approach, didn't I? Could you please give an example?

And many thank for a very awesome library :+1:

**Comment by nagarajanchinnasamy** [comment]
@thovo you can also check **subtotal_renderers.coffee** at [Subtotals Branch](https://github.com/nagarajanchinnasamy/pivottable/tree/SubTotals) for an example of adding a new renderer. It offers sub-totals and collapse-and-expand features.

**Comment by nicolaskruchten** [comment]
If all you want to do is add row-level color striping you can do this with plain CSS, no need for a new renderer.

**Comment by thovo** [comment]
@nicolaskruchten : I think it should be a renderer, as the user will not always want to display the stripping rows, add it just as an option to let the user can choose how to display.

I manually did add the renderer by jQuery but I thought it is not a good and manly way to add a renderer .

**Comment by nicolaskruchten** [comment]
I think that's a fine way to do it :) I don't want to add too many options and bells and whistles to the renderers.

**Comment by thovo** [comment]
May you consider to add these features in the next release? I think it would be best if we can manually add some new renderer?

**Comment by nicolaskruchten** [comment]
As I said, this is not a feature i would add to this library, no, sorry.
