### ISSUE TITLE
Hide and show attributes

### ISSUE THREAD

**Issue by thovo** [nicolaskruchten/pivottable#472]
I read this article about [Derived Attributes](https://github.com/nicolaskruchten/pivottable/wiki/Derived-Attributes) and I think in other case may I hide or show specific attributes? Does the library already provide function to do it or I need to hide and show manually by targeting the attributes by name and hiding them?

I am very sorry if I missed this information anywhere, please give me the article if you have!

And many thanks for a great library :+1:

**Comment by nagarajanchinnasamy** [comment]
@thovo issues #403 and #408 may be of use here...

**Comment by nagarajanchinnasamy** [comment]
@thovo also check `hiddenAttributes` option explained in [Parameters Documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters)
