### ISSUE TITLE
Localize Totals

### ISSUE THREAD

**Issue by ayozebarrera** [nicolaskruchten/pivottable#473]
Hi

Great job first at all

I'm using the table and I applied the 'es' language but totals is not translating. Why?

I tried the following:

like your fr example
```js
$("#output").pivotUI(mps, 
                { rows: ["Provincia"], cols: ["Party"] }, 
                false, "es"
            );
```

and passing the following localeStrings directly
```js
localeStrings: {
        renderError: "Ocurri&oacute; un error durante la interpretaci&oacute;n de la tabla din&acute;mica.",
        computeError: "Ocurri&oacute; un error durante el c&acute;lculo de la tabla din&acute;mica.",
        uiRenderError: "Ocurri&oacute; un error durante el dibujado de la tabla din&acute;mica.",
        selectAll: "Seleccionar todo",
        selectNone: "Deseleccionar todo",
        tooMany: "(demasiados valores)",
        filterResults: "Filtrar resultados",
        totals: "Totales",
        vs: "vs",
        by: "por"
      }
```

So... what's wrong with this? Thankyou!

**Comment by nagarajanchinnasamy** [comment]
Following code works for me:


    <!DOCTYPE html>
    <html>
    <head>
        <title>Pivot Demo</title>
        
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

        
        <link rel="stylesheet" type="text/css" href="../dist/pivot.css">
        <script type="text/javascript" src="../dist/pivot.js"></script>
        <script type="text/javascript" src="../dist/pivot.es.js"></script>
        <style>
            body {font-family: Verdana;}
        </style>
        
        
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
        
        
        <script type="text/javascript" src="show_code.js"></script>
    </head>
    <body>
        <script type="text/javascript">
    // This example shows French localization
    // using the "Canadian Parliament 2012" dataset.

    $(function(){
        $.getJSON("mps.json", function(mps) {
            $("#output").pivotUI(mps, {
                    rows: ["Province"],
                    cols: ["Party"],
                    localeStrings: {
                        renderError: "Ocurri&oacute; un error durante la interpretaci&oacute;n de la tabla din&acute;mica.",
                        computeError: "Ocurri&oacute; un error durante el c&acute;lculo de la tabla din&acute;mica.",
                        uiRenderError: "Ocurri&oacute; un error durante el dibujado de la tabla din&acute;mica.",
                        selectAll: "Seleccionar todo",
                        selectNone: "Deseleccionar todo",
                        tooMany: "(demasiados valores)",
                        filterResults: "Filtrar resultados",
                        totals: "Totales",
                        vs: "vs",
                        by: "por"
                    }
                }, false, "es"
            );
        });
     });
        </script>

        <p><a href="index.html">&laquo; back to examples</a></p>
        
        <div id="output" style="margin: 30px;"></div>

    </body>
    </html>

![image](https://cloud.githubusercontent.com/assets/1784880/14380680/79a46652-fd9e-11e5-944e-8492baeb1464.png)

**Comment by ayozebarrera** [comment]
Oh thanks, I'll try.
I forgot include pivot.es.js file but I thought the localeStrings should work... all the others words are translated! I know totals is the only one word inside the table so it's okay

Closing issue!
