### ISSUE TITLE
value pass to sum aggregators 

### ISSUE THREAD

**Issue by krishnathumma** [nicolaskruchten/pivottable#474]
Hi Nicolas,
I want to pass the variable to sum aggregation on onclick event, every click it will be new value is sending to aggregation function.

**Comment by nicolaskruchten** [comment]
I'm sorry, I don't understand what you're looking for...

**Comment by krishnathumma** [comment]
Hi Nicols,
Is it possible to creates Mathematical functions with selected data.
I mean to say like https://www.tableau.com.
