### ISSUE TITLE
Unable to pass array data

### ISSUE THREAD

**Issue by vshankaa** [nicolaskruchten/pivottable#475]
I am trying to pass an array with my data to the pivot, but it's not working. What am I doing wrong here?

var dataPivot = [{"Name": "ABC", "Type":"Tall"},{"Name":"BDF", "Type":"Short"}];

$(function(){
        $("#pivDT").pivotUI(
                dataPivot
        );
     });

**Comment by nagarajanchinnasamy** [comment]
Please try mentioning `rows` and `cols` options as shown in [Simple UI example](http://nicolas.kruchten.com/pivottable/examples/simple_ui.html)

       $(function(){
        $("#output").pivotUI(
            [ 
                {color: "blue", shape: "circle"}, 
                {color: "red", shape: "triangle"}
            ], 
            { 
                rows: ["color"], 
                cols: ["shape"] 
            }
        );
     });

**Comment by nicolaskruchten** [comment]
When you say "it's not working" can you elaborate? Is there a javascript error in the console?
