### ISSUE TITLE
adding pagination in pivottable

### ISSUE THREAD

**Issue by waleedarafa** [nicolaskruchten/pivottable#476]
please i need your help in how can i add pagination in my pivot table ?

**Comment by nicolaskruchten** [comment]
I'm sorry, but that is not a supported feature.

**Comment by waleedarafa** [comment]
thanks for your reply , 
when i tried to get any other pagination jquery library and assign it to the table , the pivot table disappear , can you help me in how can i add external pagination library ?  i already added method to extract excel sheet but i couldn't do the same for the pagination

**Comment by nicolaskruchten** [comment]
I'm sorry, but I can't really help you with external libraries here...
