### ISSUE TITLE
Pagination in pivottable

### ISSUE THREAD

**Issue by kumarabrol** [nicolaskruchten/pivottable#477]
Is there a provision to include pagination in pivottable?
Should i send only that much data what needs to be displayed ? or is there a provision to add some parameter which can do pagination in pivottable?

**Comment by nicolaskruchten** [comment]
There is no pagination feature at the moment and I have no real plans to add one... Sorry!

**Comment by kumarabrol** [comment]
No problem.I am planning to handle it with sending limited set of data to pivot for respective page.Do you see any con in it?

**Comment by kumarabrol** [comment]
I was able to solve this by passing selected set of data to pivot.

**Comment by kumarabrol** [comment]
I was able to solve this by passing selected set of data to pivot
