### ISSUE TITLE
C3 Visualization selection issue when specifying rendererOptions

### ISSUE THREAD

**Issue by nels-o** [nicolaskruchten/pivottable#478]
When rendererOptions are specified for the c3 renderer, the params passed through makeC3Chart seem to get overwritten with the c3 options. Regardless of which c3 visualization is selected in the pivotUI, if you add these rendererOptions, the visualization is always the default line chart.

````
{ // options...
    rendererOptions: {
        c3: {
            data: {
                onclick: function(d, element) {
                    console.log('Clicked on', d, element);
                }
            }
        }
    }
}
````

Stepping through the source it appears to happen [here](https://github.com/nicolaskruchten/pivottable/blob/master/c3_renderers.coffee#L114). Should this be a deep copy?

**Comment by nicolaskruchten** [comment]
This could indeed be a problem! I'll try to take a closer look when I have some time. Thanks for the bug report and the pointer to the source of the problem!

**Comment by nicolaskruchten** [comment]
Sorry for the delay in addressing this, it's now fixed, as per your suggestion :)
