### ISSUE TITLE
How can i align a specific column to right?

### ISSUE THREAD

**Issue by ahiezerr** [nicolaskruchten/pivottable#479]
success: function (msg) {
                datos = msg.d;

                var sortAs = $.pivotUtilities.sortAs;
                var sum = $.pivotUtilities.aggregatorTemplates.sum;
                var numberFormat = $.pivotUtilities.numberFormat;
                var tresDecimales = numberFormat({ thousandsSep: ",", decimalSep: ".", digitsAfterDecimal: 3 });
                var totalTons = function () { return sum(tresDecimales)(["Quantity"]); };

                $("#divDatos").pivotUI(
                    datos,
                    {
                        rows: ["CardName", "DocNum", "DocDate", "DocDueDate", "ItemCode", "ItemName", "ShipToCode", "Quantity", "Retraso"],
                        cols: [],
                        vals: ["Familia", "ItemName", "WhsCode", "CardCode", "SlpCode", "City", "State", "Country", "Pedido", "Grupo", "PackQty", "OpenQty", "OpenPackQty", "SlpName", "CardName", "DocNum", "DocDate", "DocDueDate", "ItemCode", "ItemName", "ShipToCode", "Quantity", "Retraso", "Mes"],
                        rendererName: "Tabla",
                        hiddenAttributes: ["Block", "__type", "SalPackUn", "StreetNo", "Street", "ObjType"],
                        aggregators: { "Total Tons.": totalTons },
                        sorters: function (attr) {
                            if (attr == "Mes") {
                                return sortAs(["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"]);
                            }
                        }
                    }, false, "es"
                );
                $("#divLoading").hide();
            }

**Comment by nicolaskruchten** [comment]
I don't understand the question.

**Comment by ahiezerr** [comment]
i wanna text align in some column, how could i do?

**Comment by nicolaskruchten** [comment]
You'd have to use CSS

**Comment by ahiezerr** [comment]
ok thank's. I really hope some config help but i still reading the code and it is some limited for some funcs.

I solved modifying the code but fot time reasons, i didn't in generic way, but else in some preformater data.

Regards.
