### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by tgabrielle** [nicolaskruchten/pivottable#48]
it would be useful to be able to sort the output table columns (A-Z, Z-A) such that the end result is something like 'top 10 provinces who voted NDP' or similar result.

**Comment by astechdev** [comment]
@nicolaskruchten I submitted a PR https://github.com/nicolaskruchten/pivottable/pull/369 which enhances the pivot table html table element to be well formed. I was thinking this would then allow that table element to be enhanced with http://datatables.net/ which would then provide all sorts of goodness like sorting, re-ordering, etc. What do you think?

**Comment by joankent** [comment]
@nicolaskruchten how can I sort the result by the column value? without an aggregator Templates, simply by order direction asc or desc, thanks.

**Comment by nicolaskruchten** [comment]
@joankent you can't do this at the moment: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#sorting-in-built-in-table-renderer

**Comment by nicolaskruchten** [comment]
I'm closing this issue, as the FAQ addresses it fairly well.
