### ISSUE TITLE
Decimal places

### ISSUE THREAD

**Issue by ToniVeintimilla** [nicolaskruchten/pivottable#481]
Good Morning.

How I can define 0 decimals for values in rows? Default I are leaving 2 decimals. In the JSON file that receives comes formated without decimals.

$("#output").pivotUI(
				vDatos,
				{
					rows: ["PROVINCIA","MUNICIPIO"],
					cols: ["MERCADO"],
					digitsAfterDecimal: 0,
					aggregatorName: "Suma",
                	vals: ["OBJETIVOS_MUNICIPIOS"]
                	//aggregator: sum(intFormat)(["OBJETIVOS_MUNICIPIOS"])
				},
				false,
				"es"
			);

Thank you very much.

**Comment by nicolaskruchten** [comment]
The formatting is a function of the aggregators, which you either provide yourself directly or via a locale file. If you want control over the number formatting, you will have to essentially create your own locale file.
