### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by brunoqueiros** [nicolaskruchten/pivottable#484]
Is it possible to create a custom template for the filters, without using `onRefresh`? Instead of have 2 buttons 'Select All' and 'Select None' I would like to have a checkbox.

**Comment by nicolaskruchten** [comment]
This isn't a feature at the moment, no.

**Comment by brunoqueiros** [comment]
Have you plan to have this feature?

**Comment by nicolaskruchten** [comment]
Not really, no. This seems like just a different UI...
