### ISSUE TITLE
Height of Charts

### ISSUE THREAD

**Issue by kumarabrol** [nicolaskruchten/pivottable#487]
Please inform how should we control the height of charts.
 $("#pivotTableOutput").pivotUI(chartData, {
                aggregators: $.extend($.pivotUtilities.aggregators),
                renderers: $.extend($.pivotUtilities.c3_renderers, $.pivotUtilities.renderers),
                rows: rowDim,
                cols: colDim,
                vals: metricsAggregators,
                rendererOptions:{
                  height:200
                }
            },true);

I tried using rendererOptions but it does not seem to work.
Please advice.

**Comment by nicolaskruchten** [comment]
You should be able to use `rendererOptions.c3.size.width` and `rendererOptions.c3.size.height`.

**Comment by kumarabrol** [comment]
Thanks for your response.
This configuration  helps us to control the width and height of the charts.
Are there an option where we can control the width and height of the pivottable also??

**Comment by nicolaskruchten** [comment]
Unfortunately not. The output will scale with the size of the table. You
can always wrap the table in a div with overflow: scroll if you need to
constrain the dimensions.

**Comment by matmass** [comment]
Please how do you code in jquery the rendererOptions.c3.size.height in the renderoptions => rendererOptions:{
Thanks.

**Comment by nicolaskruchten** [comment]
@matmass can you clarify your question please?

**Comment by matmass** [comment]
For example if we use the older sample and if we try to put the variable c3.size.height:200 in the renderoptions, it doesn't work. It's the same if I put rendererOptions.c3.size.height:200

$("#pivotTableOutput").pivotUI(chartData, {
aggregators: $.extend($.pivotUtilities.aggregators),
renderers: $.extend($.pivotUtilities.c3_renderers, $.pivotUtilities.renderers),
rows: rowDim,
cols: colDim,
vals: metricsAggregators,
rendererOptions:{
c3.size.height:200
}
},true);

**Comment by nicolaskruchten** [comment]
@matmass ah I see the confusion.

You need to use:

```
rendererOptions: {
   c3: {
      size: { height:200, width:200}
   }
}
```

The `rendererOptions.c3.size.height` was meant to denote a path through the object hierarchy.

**Comment by matmass** [comment]
Thanks, it works.
