### ISSUE TITLE
Initialize pvtAttrDropdown with a value when use aggregatorName option

### ISSUE THREAD

**Issue by marcosesperon** [nicolaskruchten/pivottable#488]
Hi Nicolas,

Is it posible to include a new option to the $.fn.pivot function to set the default pvtAttrDropdown value.
Now you can use aggregatorName parameter to set something diferent to Count by default, but if I want to set Sum to the aggregator I would like to set also the column to use in the sum and render the pivot table with that options.

Something like this after load the values for the dropdown:

```
if (opts.attrDropdownName != null) {
  _this.find(".pvtAttrDropdown").val(opts.attrDropdownName);
  refresh();
}
```

Thank you for your time,

Regards

**Comment by nicolaskruchten** [comment]
I'm pretty sure sure that the 'vals' parameter is the one you're looking for, no?

**Comment by marcosesperon** [comment]
Oh!!

I thought that vars array limits the columns in the dropdown, but no, it loads all of them and selects the one you send in vars.

Thanks and sorry!!

**Comment by nicolaskruchten** [comment]
No worries! It's not a great name for a parameter, sorry ;)
