### ISSUE TITLE
Use multiple filters in a single pivot

### ISSUE THREAD

**Issue by BenLloydPearson** [nicolaskruchten/pivottable#489]
First of all, I want to thank you for this wonderful library, I've found it to be extremely useful.

I'm trying to use multiple filters in a single pivot, and I so far have been unable to get it to work. For example, my columns show the date, and my rows show entries for specific people. I want to filter the columns to only show entries from 2016 and also exclude a specific row from the table.

I've tried adding these two lines inside the same pivot():
```
filter: function(row){return row["Example Row"] != "Excluded Row"},
filter: function(col){return col["Year"] == "2016"},
```

The problem is that only the last filter in the code is run, and the first is not (i.e, in this example the year filter works fine, but the row exclusion does not, if I reverse the order the row exclusion works, but the year filter does not). Each filter works fine by themselves, but when I try to use both, only one ends up running on the output. Is it possible to do this?

**Comment by nicolaskruchten** [comment]
Glad you like the library :)

You can't have the same key (e.g. `filter`) twice in the same object, so the second one always overwrites the first in your case, explaining the behaviour you're seeing.

To do what you want you'll have to do something like:

```
filter: function(row) { return row["Example Row"] != "Excluded Row" and row["Year"] == "2016"; }
```
