### ISSUE TITLE
Changing the text in legend, but keep numerical sorting

### ISSUE THREAD

**Issue by DonofGor1** [nicolaskruchten/pivottable#493]
Probably a really quick question to answer. I want to sort by year, month, day (in the format yyyy, mm, dd numerically) but rather than displaying 2015-5-18 I would like the legend to display a format chosen but the user. Say for example:

If the user has chosen the format to display e.g. dd mmm yyyy ( displayed like 23 Oct 2015 ) can the legend say 18 May 2015 and keep the real date dorting in place i.e. Dec values would not come before May due to textual sorting.

Do I create a custom filter/sorter to do this. Not sure. If this is the way to submit a question like this, so thanks for patience with me, regards.

![what i want](https://cloud.githubusercontent.com/assets/15350925/15391085/35aed3c2-1db7-11e6-8e6f-b6c4610297e4.jpg)

**Comment by nicolaskruchten** [comment]
Hi there,

Unfortunately, this is not possible. The data is displayed based on a naive natural sort algorithm which is unaware that "2016-5-9" is a date, it just knows that it's a string which sorts before the "2016-6-2" string. If you represent dates in anything other than YMD order, the data will be plotted out of order, and there is no way to change the display after sorting/displaying.

Sorry,
Nicolas

**Comment by DonofGor1** [comment]
Hi Nicolas, thank you for your speedy response. No probs about this. Would've been cool but it's no show stopper.  Still using this great software. Well done on a great job!

**Comment by nicolaskruchten** [comment]
ok!
