### ISSUE TITLE
how to provide relative path for pivot table when we providing csv file name

### ISSUE THREAD

**Issue by rockymenezes** [nicolaskruchten/pivottable#494]
<script type="text/javascript">
       
            $(function(){
            	
            	
            	$.get("xyz.csv", function(theFile) {
            		
                    var input = $.csv.toArrays(theFile);
                    
						
                        var renderers = $.extend(
                        		
                            $.pivotUtilities.renderers, 
                            $.pivotUtilities.c3_renderers, 
                            $.pivotUtilities.d3_renderers,
                            $.pivotUtilities.export_renderers
                            );
						
                        $("#output").pivotUI( input, { renderers: renderers }, true);
                        jQuery('#output').css("display","block");
                 
                    //reader.readAsText(event.target.files[0]);
                });  
             });
        </script>

instead of xyz.csv I need to give path that is c:/csv/xyz.csv

**Comment by nicolaskruchten** [comment]
Relative paths should just work wherever absolute paths do... Can you point me to an example of what you're doing that doesn't work?

**Comment by rockymenezes** [comment]
Nicolas yes it works fine I was giving path as ../x/y/z.csv I changed it to x/y/z.csv and it works fine. Thanks for the great code. But I need one more help want to take data from database and provide it as  input to pivot table

**Comment by nicolaskruchten** [comment]
You'll have to serve up your database results in JSON or CSV using some server-side code and call PivotTable.js on the client side as usual.

**Comment by rockymenezes** [comment]
Thanks Nicolas
