### ISSUE TITLE
Conditional Formatting in Heatmap

### ISSUE THREAD

**Issue by tchakravarty** [nicolaskruchten/pivottable#496]
Nicolas, thanks so much for the wonderful library. I wanted to ask if there is a simple way to use conditional formatting rather than a continuous palette for the heatmap renderer? For example: 

- green if value between [a, b)
- yellow if value between [b, c)
- red if value between [c, d]

Thanks.

**Comment by nicolaskruchten** [comment]
There's no built-in way of doing that but by copying and modifying the heatmap code it should be pretty trivial :)

**Comment by tchakravarty** [comment]
Thanks for the reply @nicolaskruchten. I did try to take a look at your code to see if I could adapt it, but I gave up when I realized it was CoffeeScript. :-) Instead, I wrote up some pretty hacky looking DOM manipulations on top of the `Table` renderer, which seems to be holding for now. Can I request that there be a conditional formatting renderer in the next release? Great library, much appreciated.

**Comment by nicolaskruchten** [comment]
OK. CoffeeScript is fully compatible with Javascript, and if you're more comfortable with Javascript you could modify the compiled CoffeeScript output... As to your request, it's noted, but the best kind of request is a Pull Request ;)

**Comment by nicolaskruchten** [comment]
You can now specify a custom color scale function, see the example here: http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html
