### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by ericremoreynolds** [nicolaskruchten/pivottable#497]
Hello,

Is there any way to use the data column label as a breakdown field?

I.e. say I have this data

    Category    Value1     Value2
    A           2          1
    A           3          0
    B           5          7
    B           6          2
    B           7          1

and I want to show a table like this

    Category    Value1     Value2
    A           5          1
    B           12         10

intuitively I'd use "category" as the row breakdown, "field" as the column breakdown and "sum" as the aggregator.

I have seen this kind of thing implemented in some software packages that provide pivot-table like functionality.

Is this possible with pivottable.js?

Best,

Eric

**Comment by nicolaskruchten** [comment]
You can't do this without unpivoting/melting your data to look like this:

```
Category    Field       Value    
A           Value1        2          
A           Value1        3          
B           Value1        5          
B           Value1        6          
B           Value1        7          
A           Value2        1
A           Value2        0
B           Value2        7
B           Value2        2
B           Value2        1
```

**Comment by ericremoreynolds** [comment]
Right sure but then that means you can't do it interactively, which is what I'm looking for. Thanks for your reply however!

**Comment by nicolaskruchten** [comment]
OK.
