### ISSUE TITLE
Unicode char in aggregator name shown as escaped in C3 chart title

### ISSUE THREAD

**Issue by deecay** [nicolaskruchten/pivottable#499]
Hi Nicolas,

Currently, title text and vAxisTitle showes numeric reference escaped character.
For example, in lang "tr", the title of c3 charts look like the following.

> Say&amp;#305; vs Durum by Hedef Sürüm-Atanan

instead of 

> Sayı vs Durum by Hedef Sürüm-Atanan

I think this can be fixed with un-escaping pivotData.aggregatorName or hAxisTitle/titleText in c3_renderers.js. I tried un-escaping with

`vAxisTitle = $("<textarea/>").html(vAxisTitle).text();`

and it worked, but there can be better ways to handle this.

Cheers,

**Comment by nicolaskruchten** [comment]
Have you tried just specifying the title as Unicode without the HTML entity escape?

**Comment by deecay** [comment]
Hi,

If I alter pivot.tr.js with raw Unicode character, it works. Do you want to leave it as is? Maybe change the contribution guideline and advice not to use HTML escape?

**Comment by nicolaskruchten** [comment]
Hmm OK, I think I will need to convert all of the locale files to unicode after all.

**Comment by deecay** [comment]
Understood.

**Comment by nicolaskruchten** [comment]
ok, all done!
