### ISSUE TITLE
Hide Column and Row Totals

### ISSUE THREAD

**Issue by riaano** [nicolaskruchten/pivottable#500]
Can I request that we add functionality to allow us to either hide the right column total or the bottom row total or both.

I have a scenario where I'm showing data over months and for reporting don't need the column to the right

**Comment by XavierFlo** [comment]
I used this to hide totals
```
$("#Output").pivotUI({
.
.
onRefresh: function(config) {
//$("#output").find('select').addClass('hidden');
$("#output").find('.rowTotal').addClass('hidden');
$("#output").find('.colTotal').addClass('hidden');
$("#output").find('.pvtGrandTotal').addClass('hidden');
$("#output").find('.pvtTotalLabel').addClass('hidden');
},
.
.
});
```

**Comment by nicolaskruchten** [comment]
Here's the official answer: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#totals :)

**Comment by riaano** [comment]
This works if you want to hide all the totals, but does not work if you want to only hide the column totals and its header. It will hide the total, but not the header and if you want to hide the headerLabel it hides the Label for the bottom (row) as well.

Can a different solution be provided

**Comment by nicolaskruchten** [comment]
@riaano have you checked the answer in the FAQ?

**Comment by riaano** [comment]
Yes the answer in the FAQ does not work for this scenario I mentioned. This is why I made the comment earlier.

**Comment by nicolaskruchten** [comment]
@riaano can you please create a new issue for this indicating your desired output and I'll try to help?

**Comment by riaano** [comment]
Hide Column and Row Totals #538

**Comment by anu87** [comment]
How can I do this R Shiny? I am not sure how I can access the CSS file for my app? Or do I create one?

**Comment by nicolaskruchten** [comment]
@anu87 the R integration to this Javascript library is mediated by another package (https://github.com/smartinsightsfromdata/rpivotTable) so you would have to direct your question to the maintainer of that package...

**Comment by anu87** [comment]
Thanks!

**Comment by smartinsightsfromdata** [comment]
@XavierFlo I tried your method but it didn't work for me.  

Would you mind to publish a `jfiddle` for it?

I'm trying to see if `rpivotTable` could handle this programmatically, to address @anu87 request.

**Comment by tsando** [comment]
@nicolaskruchten Can you please put an example on how to do this using the 'official solution'? I couldn't do this using jQuery and css. I could only get it to work using the solution from @XavierFlo above. Thanks!

**Comment by nicolaskruchten** [comment]
@tsando the official solution is in the FAQ here: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#totals

if that's not working for you, please create a new issue describing what you want to do rather than posting on an old, closed one :)

**Comment by tsando** [comment]
@nicolaskruchten can you please show how the official solution would be written inside the `$(target).pivotUI(...)` function? i.e without editing my .css file? The official solution says with the following css  `.pvtTotal, .pvtTotalLabel, .pvtGrandTotal {display: none}` but how would this be passed into the `$(target).pivotUI(...)` function? Thanks.
