### ISSUE TITLE
Multiple data columns

### ISSUE THREAD

**Issue by marcosesperon** [nicolaskruchten/pivottable#501]
Hi Nicolas,

Do you think it would be possible to change the library to include the possibility of append more than one column of results?

For example, if you have a report with serveral units, show the sum of one value and the average of another at the same time.

Maybe, instead with a select input to set the column data and another to the aggregator, make like a draggable area where you can drop the columns and for each one select the function...

<img width="217" alt="pivot-1" src="https://cloud.githubusercontent.com/assets/1691866/15990516/09fb7096-3095-11e6-8680-59c83c9629da.png">
<img width="320" alt="pivot-2" src="https://cloud.githubusercontent.com/assets/1691866/15990517/09ff6386-3095-11e6-9a88-8e679d273170.png">

I know it's a big request, but I think it will take the library to the next level.

Thanks for your time,

Regards

**Comment by nicolaskruchten** [comment]
Thanks for the feedback! This is an oft-requested feature but it really is a big change and I'm not planning on implementing it any time soon :)
