### ISSUE TITLE
Unable to display data in the cells

### ISSUE THREAD

**Issue by meenakshijha** [nicolaskruchten/pivottable#502]
Hi,

I am using this wonderful library just for displaying the data. All my pivot aggregations are done on the server side as the data is huge and can't be done on the client side. I get my data in json format and I only want to display the data but by default the COUNT aggregation is being done by the library and the actual data is never shown. 

I tried commenting aggregators from the pivot.js file but then it throws errors. Can anyone please help?
I have looked all the examples and can't figure this out.

Here is a sample of what my data looks like with about 10K records!
{
col1:"ALTIMA"
col2:"VA"
col3:15337.85
},
{
col1:"HONDA"
col2:"IA"
col3:12343.3
},

This is how I am trying to render on screen-

 $("#output").pivotUI($scope.schemaData1, {  		 	    
  		 	            rows: [$scope.schemaData1.col2],
  		 	            cols: [$scope.schemaData1.col1],
  		});

Please help!

**Comment by meenakshijha** [comment]
@nicolaskruchten  Can you pls help?

**Comment by nicolaskruchten** [comment]
This example will show you want you need: http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html

Note the `aggregatorName` and `vals` parameters. You can get their definitions here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by meenakshijha** [comment]
Thanks solved it using the list unique values option.
