### ISSUE TITLE
Custom aggregation filter box totals differ from graph

### ISSUE THREAD

**Issue by DonofGor1** [nicolaskruchten/pivottable#503]
Hi Nicolas,

I have created a custom aggregator:

            var countRate = function(){
                return function(){
                    return {
                        counter: 0,
                        push: function(record){
                            if (!isNaN(parseFloat(record.count))) {
                                this.counter += parseFloat(record.count);
                            }
                        },
                        value: function() { return this.counter; },
                        format: function(x) { return x; },
                        label: "Count"
                    };
                };
            };

which will sum a specific column from my query. For example the data returned from the query is: **select some-data, _count(data-id) as count_ from some-table INNER JOIN another-table where xxx is True GROUP BY some-group-stuff;** which returns values the count is the number of matching

some-data   ,   count
xxx         ,         5
yyy         ,        3
(2 rows)

Now the graph is reporting back correct values so the aggregator is pulling out a total of '8' however the pivot filter box is showing 

xxx 1
yyy 1

totalling 2 (I believe the number of rows it returned.) Graph is correct but the filter box should be:

xxx 5
yyy 3

Any suggestions?

**Comment by DonofGor1** [comment]
An example of what I get...
![what i get](https://cloud.githubusercontent.com/assets/15350925/16192994/77515764-36e4-11e6-8758-a59e5e358e78.jpg)

**Comment by nicolaskruchten** [comment]
The filter box is not meant to be linked to the aggregator i.e. it is not meant to show a 'total'. Indeed it is meant to always just show the number of records in the input which have the given value of the given attribute.
