### ISSUE TITLE
No example provided for fractionOf aggregator

### ISSUE THREAD

**Issue by zachcowell** [nicolaskruchten/pivottable#504]
Hi, I am trying to use the `fractionOf` aggregator for `cols` (or `rows`) in a pivot table. I need to do this without pivotUI and just use the `pivot` version. From the documentation, I have found how I can programmatically build a simple `sum` aggregator like I have done in the fiddle/code snippet below. Can you please advise me how I can modify this to work with the `fractionOf` with the required arguments? I tried looking at the source and got lost because it looks pretty complex ;)

```
var sum = $.pivotUtilities.aggregatorTemplates.sum;
var numberFormat = $.pivotUtilities.numberFormat;
var floatFormat = numberFormat({digitsAfterDecimal: 2});
var sumAggregator = sum(floatFormat)(['tip'])

$("#output").pivot(
  $.pivotUtilities.tipsData, {
    rows: ["sex", "smoker"],
    cols: ["day", "time"],
    vals: ["tip", "total_bill"],
    aggregator: sumAggregator
  });
```

[Relevant fiddle](https://jsfiddle.net/w86bgq9o/183/)

**Comment by nicolaskruchten** [comment]
Here are some examples of where this is used: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L145

**Comment by zachcowell** [comment]
I tried adding in a template in that matter and it didn't quite work. I'm getting a `TypeError: this.allTotal.push is not a function`

```
var sum = $.pivotUtilities.aggregatorTemplates.sum;
var numberFormat = $.pivotUtilities.numberFormat;
var usFmtPct = numberFormat({ digitsAfterDecimal:1, scaler: 100, suffix: "%" })
var fractionOf = $.pivotUtilities.aggregatorTemplates.fractionOf(sum(), 'row', usFmtPct)

$("#output").pivot(
  $.pivotUtilities.tipsData, {
    rows: ["sex", "smoker"],
    cols: ["day", "time"],
    vals: ["tip", "total_bill"],
    aggregator: fractionOf
  });
```

[Fiddle](https://jsfiddle.net/w86bgq9o/185/)

**Comment by nicolaskruchten** [comment]
OK so the issue is that you're mixing up the call semantics of `pivot()` and `pivotUI()`... The `vals` parameter is used by `pivotUI()` but not `pivot()`.

The following will work (note that I removed `vals` and called the aggregator with a field to compute over):

```javascript
var sum = $.pivotUtilities.aggregatorTemplates.sum;
var numberFormat = $.pivotUtilities.numberFormat;
var usFmtPct = numberFormat({ digitsAfterDecimal:1, scaler: 100, suffix: "%" })
var fractionOfRowSum = $.pivotUtilities.aggregatorTemplates.fractionOf(sum(), 'row', usFmtPct)

$("#output").pivot(
  $.pivotUtilities.tipsData, {
    rows: ["sex", "smoker"],
    cols: ["day", "time"],
    aggregator: fractionOfRowSum(["tip"])
  });
```

**Comment by zachcowell** [comment]
Fantastic! Thank you.

Also, thank you very much for this excellent library. I have been using it on a few different projects now.

**Comment by nicolaskruchten** [comment]
You're welcome, and I'm glad you like it!
