### ISSUE TITLE
Column Area box and C3 Stacked Bar Chart break out of div container when number of data fields is larger

### ISSUE THREAD

**Issue by w5m** [nicolaskruchten/pivottable#505]
Hi Nicolas,

Firstly, can I say a massive thank you for creating this incredibly powerful PivotTable component - it was exactly what I was looking for.

I have an issue that I thought you might be interested in, as I think it's more to do with the PivotTable interface than the C3 chart. 

When I provide a JSON data source that has only 5 data fields, all of the data fields fit neatly within the grey horizontal "attributes" box (to the right of the "renderer" drop-down box).

When I provide a JSON data source that has 15 data fields, they exceed the width of this horizontal "attributes" box and instead appear in a new grey vertical box (directly below the chart type drop-down box). This is clearly a good way to accommodate a larger number of data fields.

However, in this latter scenario, the horizontal "column area" box (and the C3 chart below it) breaks out of the div container that houses the PivotTable component, presumably pushed across by the addition of the vertical "attributes" box.

Is the behaviour I described above intentional? Or is there a way to resize the PivotTable interface (specifically the "column area" and chart) to fit within the div container?

Any assistance or advice would be much appreciated.

Many thanks,
Clive

**Comment by w5m** [comment]
Thanks for such a quick response - much appreciated.

I'm using Windows 7 and the issue consistently occurs in Chrome, Firefox and IE11 (I've not tried in any other versions of IE).

Attached are two example HTML files; one which loads a JSON dataset consisting of 5 fields and one which is identical apart from loading a JSON dataset consisting of 15 fields. The first example fits the parent div neatly, the second example breaks out of the right side of the parent div.

Hope that clarifies my previous post.

[pivottable_issue_505_examples.zip](https://github.com/nicolaskruchten/pivottable/files/330682/pivottable_issue_505_examples.zip)

**Comment by nicolaskruchten** [comment]
OK, that definitely helps illustrate the issue, thanks! So the issue actually shows up on both your examples, if you shrink the width of your window enough... Basically the `#output` div isn't stretching to accomodate its contents. I was able to fix this on OSX/Chrome by adding `display: inline-block;` to the `#output` div as per http://stackoverflow.com/questions/1161166/how-can-i-ensure-a-div-stretches-to-fit-its-contents.

**Comment by w5m** [comment]
Many thanks Nicolas - that's sorted it.

**Comment by nicolaskruchten** [comment]
Happy to help!
