### ISSUE TITLE
Wrap default renderers tables with thead and tbody tags

### ISSUE THREAD

**Issue by yannouchou** [nicolaskruchten/pivottable#508]
It would make the tables more compatible with some third-party plugins (such as http://mkoryak.github.io/floatThead/) to wrap the headers and body of the main rendered table in thead/tbody tags.

**Comment by nicolaskruchten** [comment]
I find that most third-party plugins that rely on `thead`/`tbody` don't really deal well with multi-row/`colspan`ed column headers, not to mention the fact that they usually ignore the row headers altogether :) 

I'll take a look at just supporting these directly in the table renderer.

**Comment by nicolaskruchten** [comment]
Oh, I see that your PR does exactly this. I'll test it and merge it this week if I don't see any problems :)

thanks!

**Comment by nicolaskruchten** [comment]
merged!
