### ISSUE TITLE
"Select All" and "Select None" button filter label empty

### ISSUE THREAD

**Issue by fmfcs** [nicolaskruchten/pivottable#510]
Hi,

I don't have any javascript errors but this two labels are empty.

Any clue how to debug this?

Here it's ok:
![capture_ok](https://cloud.githubusercontent.com/assets/11777343/16422038/df8f77be-3d4e-11e6-991f-2b6ebd45735e.JPG)

In this example, they're empty:
![capture_empty](https://cloud.githubusercontent.com/assets/11777343/16422037/df8f35d8-3d4e-11e6-8b31-5a4d91d8f133.JPG)

Cheers,
Francisco

**Comment by nicolaskruchten** [comment]
That's very strange. Are you able to share a link to a case where this is happening, or to replicate it on JSFiddle or something?

**Comment by fmfcs** [comment]
Here's a link:
http://tst.gaps.pt/Gauto_UI/Test.aspx

The first pivot is OK but if you press "OpenPoup" button at the top of the page, a new pivot will be loaded with this error.

Thanks for your quick reply :)

**Comment by nicolaskruchten** [comment]
Ok I'll take a closer look when I'm on my computer but at first glance it seems like a localization problem: are you passing in localized strings for those buttons?

**Comment by fmfcs** [comment]
I'm not but the two pivots have the same configuration, the difference is
that the one in the pop-up has this problem.

**Comment by nicolaskruchten** [comment]
Oh for me the problem appears on both.

**Comment by nicolaskruchten** [comment]
Looking at the source of your page, it looks like you're overriding the `localeStrings` but not providing all of them, so the missing ones are being dropped. You will need to provide all the strings listed here: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L164

**Comment by fmfcs** [comment]
Thanks!

All the localeStrings has to be defined :)

```
localeStrings: {
        'totals':'Totais',
        'renderError': 'An error occurred rendering the PivotTable results.',
        'computeError' : 'An error occurred computing the PivotTable results.',
        'uiRenderError' : 'An error occurred rendering the PivotTable UI.',
        'selectAll' : 'Todas',
        'selectNone' : 'Nenhum',
        'tooMany' : '(too many to list)',
        'filterResults' : 'Filter results',
        'vs' : 'vs',
        'by' : 'by'
    }
```

I was induced in error because the problem was only happening when loading a pivot inside a popup.

Thanks for your quick help.

Cheers,
Francisco

**Comment by nicolaskruchten** [comment]
Happy it's sorted out!
