### ISSUE TITLE
Change color of Area Chart or any Charts' co-ordinates

### ISSUE THREAD

**Issue by guptavaibhav92** [nicolaskruchten/pivottable#511]
How to change color of any charts' co-ordinates i.e. `.c3 text` ?

**Comment by nicolaskruchten** [comment]
You want to change the colour of the text or of the bars or...? You can use CSS to control some of the C3 formatting and you can also pass options directly to C3 via the rendererOptions parameter.

**Comment by guptavaibhav92** [comment]
To clarify, I want to the change the colors of the text selected in RED in the attached image. I tried doing it using CSS in `.c3 text ` but it didn't work. Please let me know how to do the same.
![attach](https://cloud.githubusercontent.com/assets/3329044/16459281/e8bc2354-3e3f-11e6-93c8-ad804478464a.jpg)

**Comment by nicolaskruchten** [comment]
You can indeed use `.c3 text` but the CSS here applies to SVG elements rather than HTML elements so this is how you make the text blue:

```css
.c3 text { fill: blue; }
```

**Comment by guptavaibhav92** [comment]
Thanks for letting me know. It worked. Great Plugin.

**Comment by nicolaskruchten** [comment]
Happy to help!
