### ISSUE TITLE
How to add a new column to capture header total

### ISSUE THREAD

**Issue by hsultanali** [nicolaskruchten/pivottable#512]
Hi, I need to add additional columns to capture each Month's total as represented by the red lines. Can I please get some help on how I can do that with some sample code?

![1](https://cloud.githubusercontent.com/assets/6496665/16508544/be5689b6-3ee8-11e6-8816-a48f8dfccbed.PNG)

**Comment by nicolaskruchten** [comment]
It sounds like you want Subtotal support, which isn't supported at the moment but people are working on it... See issue #26

**Comment by nagarajanchinnasamy** [comment]
@nicolaskruchten , @hsultanali and friends, happy to inform you that [Subtotal.js](http://nagarajanchinnasamy.com/subtotal) is available for download as an NPM module or Bower component.

[Subtotal.js](http://nagarajanchinnasamy.com/subtotal) is hosted in GitHub as [pivottable-subtotal-renderer](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer.git)

@nicolaskruchten , In setting up [Subtotal.js](http://nagarajanchinnasamy.com/subtotal), I have shamelessly copied the structure, style and some portions of text and code as is from Pivottable.js repository. Hope you don't mind.

Thanks again to all of you for your feedback and support :+1:

**Comment by nicolaskruchten** [comment]
Fantastic @nagarajanchinnasamy, thanks :)
