### ISSUE TITLE
Adding a % Suffix

### ISSUE THREAD

**Issue by simonpervaiz** [nicolaskruchten/pivottable#513]
Hi table is not loading at all after adding the custom suffix code below.
$(function(){
				$.get("realcsv2.csv", function(mps) {
					var input = $.csv.toArrays(mps);
					var sumOverSum = $.pivotUtilities.aggregators;
					var sumOverSum = $.pivotUtilities.aggregatorTemplates.sumOverSum;
					var numberFormat = $.pivotUtilities.numberFormat;
                    var intFormat = numberFormat({digitsAfterDecimal: 1,  scaler: 100,   suffix: "%"}); 
					$("#output").pivotUI(input, {
						cols: ["Category"],
						rows: ["Supervisor", "Salesman (Dry)"],
						//vals: ["Must Have Available", "Must Have Target"],
						//aggregatorName: "Sum over Sum",
						aggregators: {
                    "Custom Agg":      function() { return sumOverSum(intFormat)(["Must Have Available", "Salesman (Dry)"]); },
                }
					});
				});
			 });

**Comment by nicolaskruchten** [comment]
Does it work if you just remove the `, suffix: "%"` part?

**Comment by simonpervaiz** [comment]
Thanks Nicolas,

I fixed it, the problem was coming my columns i was using wrong columns.

**Comment by simonpervaiz** [comment]
The values are showing in percentage on table view but in graphs if we mouse hover on bars the tooltip value is not in percentage. please see the screenshots links below.

Percentage values: https://nimbus.everhelper.me/client/notes/share/519704/lb7w1kwt1mwzgz023svz
Not Percentage values: https://nimbus.everhelper.me/client/notes/share/519709/np578e8iouam83nl33i4

**Comment by nicolaskruchten** [comment]
Yes, this is a limitation of the C3js integration, and I don't know of a good workaround. Basically C3 just receives the underlying number (i.e. 0.52) and displays it directly. To fix this you may need to pass additional options to the C3 renderer.
