### ISSUE TITLE
Preselected Filter results

### ISSUE THREAD

**Issue by JIJOSEPH** [nicolaskruchten/pivottable#514]
Hi Nicolas,

Thanks for this great tool. I would like to filter a column (prepopulate it) with some selected options from a list  eg  When the pivot table first loads it lists all the weeks from the database. I would like it to select  4 weeks and a year by default. As shown in screenshot, the four weeks (field called assessment_wk_no)  value should be 25,24, 23, 22 and the year  (field called assessment_yr) value should be 2016.  I can't seem to get any info on inclusions (I believe that is the option I should use).

        <script type="text/javascript">
    // This example has all the renderers loaded, 
    // and should work with touch devices.

    $(function(){
        var derivers = $.pivotUtilities.derivers;

        var renderers = $.extend(
            $.pivotUtilities.renderers, 
            $.pivotUtilities.c3_renderers, 
            $.pivotUtilities.d3_renderers, 
            $.pivotUtilities.export_renderers
            );

        $.getJSON("cronshaw.json", function(mps) {
            $("#output").pivotUI(mps, {
                renderers: renderers,
                derivedAttributes: {
                    "Week No": derivers.bin("assessment_wk_no", 1),
                },
                cols:["bsd_agri_region_id"], rows:  ["Week No","assessment_yr"],"vals": ["cronshaw_reading"],"aggregatorName": "Average",
                rendererName: "Bar Chart",
                rendererOptions: {
                    heatmap: {
                        colorScaleGenerator: function(values) {
                            return d3.scale.linear()
                                .domain([d3.min(values), 2, d3.max(values)])
                                .range(["green", "yellow", "red"])
                        }
                    }
                }
            });
        });
     });

        </script>

Regards

Jim

![image](https://cloud.githubusercontent.com/assets/1042916/16609456/5b7c06fc-4322-11e6-8d05-0a109ba39627.png)

![image](https://cloud.githubusercontent.com/assets/1042916/16609429/35ce0b4e-4322-11e6-94f1-47b9c15ee9d7.png)

**Comment by nicolaskruchten** [comment]
You're right that `inclusions` is the right parameter... The following should be what you need: 

```json
"inclusions": {
    "assessment_yr": ["2016"], 
    "assessment_wk_no": ["22","23","24","25"]
} 
```

**Comment by JIJOSEPH** [comment]
Thank you Nicolas. I approach this so much.  Keep up the good work.

Jim

**Comment by nicolaskruchten** [comment]
Happy to help!

**Comment by JIJOSEPH** [comment]
Dear Nicholas;

I have to questions that I am sure that that you can answer.

1)  In one of my charts I have a line which shows a fixed value of 9 to
show the threshold of some products. How do I represent this in my data or
chart as show in the image below.

2) How do I change the default title for my chart (it currently makes it up
based on the selection. I would like to put some more user friendly option.

Thanks.

JIm



[image: Inline image 1]

**Comment by nicolaskruchten** [comment]
Sorry, but your image didn't come through... Can you upload it via the Github UI instead of attaching it to an email?

**Comment by JIJOSEPH** [comment]
Ok will do. Thanks for the speedy response.

Jim

**Comment by JIJOSEPH** [comment]
Thank I posted it in Git Hub

**Comment by JIJOSEPH** [comment]
https://github.com/nicolaskruchten/pivottable/issues/517
