### ISSUE TITLE
Making init robust to missing fields.

### ISSUE THREAD

**Issue by chr15m** [nicolaskruchten/pivottable#515]
Hi,

I have a dataset where not all fields are always present:

[1171.json.zip](https://github.com/nicolaskruchten/pivottable/files/351502/1171.json.zip)

Because not all fields are present in every structure, this was throwing an error. I managed to fix it by changing the Javascript code as follows:

```
            if (axisValues[k] == undefined) {
              axisValues[k] = {};
            }
```

On line 1040 before the structure that is there now.

If I knew coffeescript I'd submit a pull-request.

**Comment by nicolaskruchten** [comment]
I'll take a look at the overall impact of such a change, thanks!

**Comment by nicolaskruchten** [comment]
PR #600 should address this.

**Comment by nicolaskruchten** [comment]
PR #600 was merged :)
