### ISSUE TITLE
Chart Title And Fixed Value Line Chart

### ISSUE THREAD

**Issue by JIJOSEPH** [nicolaskruchten/pivottable#517]
Dear Nicholas;

I have to questions that I am sure that that you can answer.

1)  In one of my charts I have a line which shows a fixed value of 9 to
show the threshold of some products. How do I represent this in my data or
chart as show in the image below.

2) How do I change the default title for my chart (it currently makes it up
based on the selection. I would like to put some more user friendly option.

Thanks.

JIm

![mean_yls](https://cloud.githubusercontent.com/assets/1042916/16790304/aa344e0c-4882-11e6-8f96-c246490a758c.jpg)

**Comment by nicolaskruchten** [comment]
For these types of modifications, you will need to look at the [C3.js documentation](http://c3js.org/) and pass those parameters directly into the c3 renderer as in this example: http://nicolas.kruchten.com/pivottable/examples/scatter.html (in the example only width and height are passed in to C3).

**Comment by JIJOSEPH** [comment]
Thanks Nicolas. Your assistance is so appreciated.  Great stuff. Blessings.

Regards
Jim
