### ISSUE TITLE
Question:  How can i create action links or buttons as a derived field?

### ISSUE THREAD

**Issue by ajaneesh** [nicolaskruchten/pivottable#518]
How can i create action links or buttons as a derived field?

I want to introduce either tooltips or action links/buttons on a derived column to lazy load additional information from a backend.  Any HTML i generate using a deriver function seems to be getting encoded and showing up as-is on the column.

how can i achieve this?  Do i have to create a custom renderer and if yes, can i see an example for a jump start?

EDIT: for now i have hacked pivot.js so that 
th.textContent = txt;
conditionally becomes
th.innerHTML = txt.html();

works but breaks my build as im using grunt/bower and i have changed in bower_components which is not a version controlled folder.

EDIT2: could not make this work in the above stated method as im using these actions with an angular controller.  So i was forced to make 2 changes.. 

my derivedAttribute function has to pass the jquery object through a $compile pipe to bind ng-click

$compile($("<input type='button' ng-click='doSomething("fooBar")' />")) 

in pivot.js, 

angular.element(th).append(txt); // instead of th.textContent = txt; approx line 850

While all of this works, it takes much longer for my pivot table to load.  My intention is to load modal dialogs on click...  

any suggestions on how best to deal with this?  is there an easier/cleaner way of accomplishing this without impacting performance?

**Comment by nicolaskruchten** [comment]
My recommendation would be to decorate the table output using jQuery and the `onRefresh` callback.

**Comment by ajaneesh** [comment]
I sorted out this issue with a slightly different approach.  i removed $compile and created some indirection.. instead of ng-click i simply called onclick and forward request to controller using a scope handle..

**Comment by nicolaskruchten** [comment]
Great!
