### ISSUE TITLE
Events in PivotTableJs

### ISSUE THREAD

**Issue by VinaykumarNM** [nicolaskruchten/pivottable#519]
Hi,
Is there any events raised after completing rendering. I want to execute some logic after completing rendering on any change in table or graph.

Please let me know if there is any such event and the place where i can get the documentation for the same.

Thanks
Vinay

**Comment by nicolaskruchten** [comment]
Check out the `onRefresh` parameter.

**Comment by nicolaskruchten** [comment]
Documentation here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

Example here: http://nicolas.kruchten.com/pivottable/examples/onrefresh.html

**Comment by BoudaSolution** [comment]
When setting the config programtically the onRefresh is not called/fired. It is only called if the user sets the configuration from the pivot UI.
what is the solution in this case?

**Comment by nicolaskruchten** [comment]
It should be fired, so long as the callback is always in the config being set programatically... You can't just set it once.
