### ISSUE TITLE
JSON sub objects

### ISSUE THREAD

**Issue by jamesecker** [nicolaskruchten/pivottable#520]
I have given some of the JSON objects sub objects. Does this application support sub objects, if so how can I define the sub objects so that they appear correctly? 

I am trying to make the data appear like the following:

        Question        Type A                Type B              Type C
    Date            Lvl01	Lvl02    Lvl01  Lvl02  Lvl03  Lvl04
    May-2016         1        7        5      2       8     5        2
    June-2016        1        7        5      2       8     5        2
    July-2016        1        7        5      2       8     5        2
    Aug-2016         1        7        5      2       8     5        2

Thank you for everyone's help.
James

**Comment by nicolaskruchten** [comment]
Unfortunately sub-objects are not supported. You can get the output format you're looking for with a flat input with fields Type, Level and Date by setting `cols` to `["Type", "Level"]` and `rows` to `["Date"]`.

Hope this helps!
Nick

**Comment by jamesecker** [comment]
Nick,
This definitely gives me hope. Are there any examples I can look at? 

Thank you again,
James

**Comment by jamesecker** [comment]
Nick,
Thank you for your help. I just realized exactly how to complete what you mentioned. 

Thank you, thank you.

James

**Comment by nicolaskruchten** [comment]
Great!
