### ISSUE TITLE
Question: programmatic change of cols and rows.

### ISSUE THREAD

**Issue by ajaneesh** [nicolaskruchten/pivottable#521]
How do i change the overall pivot table configuration programmatically.  instead of exposing the drag drop functionality, i prefer to hide that and instead provide 5-10 predetermined configurations as toolbar buttons..  i tried calling the pivotUI() function again and it simpy renders the old data...  is there a refresh/reload/repaint kind of option?

**Comment by enisnazif** [comment]
I would also be interested in knowing how to do this! at the moment i'm trying to edit the cols attribute passed to pivotUI and then call `$('.pivot-root').pivotUI(this.props.data, options);` again (i'm using pivottable within a react app), but this just renders the same data

**Comment by nicolaskruchten** [comment]
Have you tried setting the override parameter to true?

**Comment by enisnazif** [comment]
thanks! that did the trick (I probably should read the documentation more thoroughly...)

**Comment by ajaneesh** [comment]
I'll try this .  Thanks

**Comment by nicolaskruchten** [comment]
This example shows how to overwrite the config from outside: http://nicolas.kruchten.com/pivottable/examples/save_restore.html
