### ISSUE TITLE
Question: filter on a column

### ISSUE THREAD

**Issue by ajaneesh** [nicolaskruchten/pivottable#522]
how do i sort on a column?  right now i have counts on columns for one of my fields.. say.  distribution of choices of users against three colours.. RED, BLUE & GREEN.  i want to filter down the final outcome such that i want to just hide all rows where column RED has a blank or zero against it...

**Comment by nicolaskruchten** [comment]
I'm not sure I follow what you're trying to do here, can you elaborate please? Are you wanting to sort or filter or hide or...?

**Comment by ajaneesh** [comment]
Want to hide row based on aggregated value .  Let's say I have three fields , Dept , employee name, gender.  I'll use Dept as my row and gender as my column which will give me count of males and females against each Dept

From this result I want to filter down the table by some aggregated outcome.  As a HR I want to list out only Depts that have zero count of women. or any other specific value , say Depts with exactly 5 women.  And I also want to know male headcount of such Depts.  It's almost as if, I first render the pivot table and then do a second run and knock of certain rows based on what I see such that I can deal with a much smaller aggregated result that is of concern to me.

**Comment by ajaneesh** [comment]
And I really appreciate your follow-up on this!  What you have developed is a wonderful thing.  It made my life so much easier.  Very impressed .  Thanks.

**Comment by nicolaskruchten** [comment]
OK, I understand. There are no built-in features for this, but you could do exactly what you describe: after the table is rendered, do a second pass with some jQuery calls and edit the table output. You could do this in an `onRefresh` call or by wrapping the `TableRenderer`.

**Comment by ajaneesh** [comment]
I have achieved this as you described. But I could not achieve this by manipulating the rendered table because in my case there are actually multiple row fields and not just one , which means they go through grouping and consequently row spanning.  My initial idea was to simply delete <tr> s but rowspanning makes this an impossible task.  So what I've has to do is use simple jquery to get me a list of Dept ids that I don't want using a filter on tr.col0.text() === 'soemthing' and get the id to be removed using .prev().text().  I then actually make a new dataset with this is array and rerender with this new dataset. So Im not able to accomplish this without either discarding or losing required data or replicating and consuming more browser memory.  Just letting you know how I went about this.  Not complaining...

**Comment by ajaneesh** [comment]
Sorry, smartphone keyboard is messing up things a bit but I have more to add.   My first attempt at second pass was to simply use exclusions.  That did not work somehow.  What I noticed is that, that particular field's filtering pop-up does not allow filtering and says list is too big to be displayed and I was wondering if somehow the lack of foreground filtering also blocks background filtering.  That they are somehow tied up.  Hope that was clear
