### ISSUE TITLE
How can I change average calculation + mps_csv does not work with offline jquery

### ISSUE THREAD

**Issue by Koras1** [nicolaskruchten/pivottable#525]

**Comment by nicolaskruchten** [comment]
Can you please elaborate on this?

**Comment by Koras1** [comment]
I'm really sorry for not putting my question in a understandable manner, anyways I have figured out it was not a mistake with the average calculation, I just had to enable showZero > true.

**Comment by Koras1** [comment]
I have now ran into a new problem, I'm trying to get average of HH:MM:SS  (for ex: 25:55:45) , How could I make the pivot get the average of this format

**Comment by nicolaskruchten** [comment]
That's not going to be possible with anything built in: you will have to represent your data numerically and then display it in this format, which will take a custom aggregator.

**Comment by Koras1** [comment]
Got it, thanks for the quick reply
