### ISSUE TITLE
Question: How to save customized google chart editor 

### ISSUE THREAD

**Issue by focusspan** [nicolaskruchten/pivottable#527]
I used pivot UI with google charts renders. I click to google chart to pop up Chart Editor and switch to Customize tab. Is there a way to save config which i edited such as title font size, title color, background color? I want to save the config to the database and use it to load the chart in edit mode with saved config. 
![chart_editor_customize](https://cloud.githubusercontent.com/assets/14815415/17083861/1a844d12-51d7-11e6-9ef7-d8fcfbf9c2ed.PNG)

Thanks.

**Comment by nicolaskruchten** [comment]
Unfortunately not. If you read the Google Charts documentation you should be able to recreate any configuration in code, though, and pass it in via the `rendererOptions` through to the Google Chart Renderer.
