### ISSUE TITLE
Default formatter in en locale not working

### ISSUE THREAD

**Issue by enisnazif** [nicolaskruchten/pivottable#528]
Hello,

I am calling pivotUI using the default set of aggregators and the default locale of en, but no formatting is being applied to my numerical data and instead they are being displayed as the raw values in the data. E.g, values are not being formatted using the thousands comma separator, and values are not being truncated to two numbers after the decimal point.

Could anyone possibly advise as to why this is?

Thanks

**Comment by nicolaskruchten** [comment]
Can you provide an example of this happening, say on JSFiddle or something, so I can take a look? 

What OS/Browser are you using? 

Does this page display correctly-formatted numbers? http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html

**Comment by enisnazif** [comment]
I think i've figured out the problem - I didn't realise that the nice formatting for numbers is only applied to the aggregation rows / columns and not the raw data itself. i.e [https://jsfiddle.net/w14L7yrn/](url)

Here, the income column (the raw data) is not formatted nicely. I realise that this probably isn't what the formatter is intended for, but is there a way in which I could use the built in number formatters to format the data in this scenario?

Thanks!

**Comment by enisnazif** [comment]
I've found a solution; I just passed all numeric data through the default numberFormatter when the rows are rendered in the pivotTableRender
