### ISSUE TITLE
Pivotttable sorting columns and rows

### ISSUE THREAD

**Issue by dbzsoft** [nicolaskruchten/pivottable#533]
Pivotttable, always order name column or rows, how i can to make the columns are not sort alphabetically or ascending...
 if i have a-t-g, i dont want pivottable show me a-g-t

**Comment by ahmad003** [comment]
Example with month :

add variable
`var allMonths = ["Jan","Feb","Mar","Apr", "May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];`

in script bellow 

`$("#output").pivot( [datasets], {`

add sorting script
`
                sorters: function(attr) {
                    if(attr == "month_data") {
                        return sortAs(allMonths);
                    }
                }
`

then the variable like columns, rows, renderers, and aggregator

then the month will sort according to variable allMonths
