### ISSUE TITLE
Sort pivot pvt unused element

### ISSUE THREAD

**Issue by sisodiasidh** [nicolaskruchten/pivottable#535]
how can i sort the only columns name  in the pivot table .

For eg : when we load the pivot table that time all the  element which are placed in the pvtUnused class these element should be in ascending order.
![demo](https://cloud.githubusercontent.com/assets/16410034/17516435/ec6dfa22-5e5b-11e6-85ba-8b92d2065874.jpg)

**Comment by nicolaskruchten** [comment]
Try the `autoSortUnusedAttrs` parameter :)

https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by sisodiasidh** [comment]
Thanks you..

**Comment by sisodiasidh** [comment]
Hi Nicolaskruchten,

I have implemented this pivot table in angular.js project but we are not getting C3 chart.  

We have configure the pivot table by the following command :

Step 1. install D3 chart-
            Bower install d3-angular --save

Step 2. install C3 chart-
             Bower install d3-angular --save

And we have install all the required jar for the pivot table. Please find attachment . 

we are getting only few of option as default in renderer but need to implement c3 charts in pivot table .
![pivot](https://cloud.githubusercontent.com/assets/16410034/17544393/8a932fe0-5ef4-11e6-959b-f02bdca038fe.png)
![pivot output](https://cloud.githubusercontent.com/assets/16410034/17544394/8a9344ee-5ef4-11e6-960d-7bb06b694a3b.png)

**Comment by nicolaskruchten** [comment]
I need to see your code, not just screenshots of your IDE :)

Also, please note that you need to actually pass in the c3 renderers to the `pivotUI()` call, not just load them. See this example: https://jsfiddle.net/nicolaskruchten/gq6w05j8/
