### ISSUE TITLE
Display both Table and Bar Chart at once

### ISSUE THREAD

**Issue by koppireddy** [nicolaskruchten/pivottable#537]
Display both Table and Bar Chart at once by using two objects. I have used  onRefresh and saved the config to a variable and  $("#income").pivotUI(JsonData, rkTest.replace('"Table"','"Bar Chart"'));
But this is not working.

            $("#output2").pivotUI(JsonData, {
                onRefresh: function(config) {
                    var config_copy = JSON.parse(JSON.stringify(config));
                    //delete some values which are functions
                    delete config_copy["aggregators"];
                    delete config_copy["renderers"];

                    delete config_copy["rendererOptions"];
                    delete config_copy["localeStrings"];
                    rkTest= JSON.stringify(config_copy, undefined, 2);
                    $("#output").text(JSON.stringify(config_copy, undefined, 2));
                     $("#income").pivotUI(JsonData, rkTest.replace('"Table"','"Bar Chart"'));
                }
            });

**Comment by nicolaskruchten** [comment]
When you say it is "not working" what do you mean? What happens?

**Comment by koppireddy** [comment]
The second div is not refreshing with bar chart.
$("#income").pivotUI(JsonData, rkTest.replace('"Table"','"Bar Chart"')); 
The above line is not displaying anything 

![image](https://cloud.githubusercontent.com/assets/8700118/17666232/e0cd6640-62c4-11e6-93e7-a96156775545.png)

**Comment by koppireddy** [comment]
https://jsfiddle.net/kn381h7s/352/

This is the sample file that i am working on. Hope this will be helpful to understand my problem

Thanks

**Comment by nicolaskruchten** [comment]
Thanks for the JSFiddle, that makes things easier!

Instead of:

```javascript
rkTest= JSON.stringify(config_copy, undefined, 2);
$("#output").text(JSON.stringify(config_copy, undefined, 2));
$("#output3").pivotUI(JsonData, rkTest.replace('"Table"','"Bar Chart"'));
```

you should use:

```javascript
$("#output").text(JSON.stringify(config_copy, undefined, 2));
config_copy["aggregatorName"] = config_copy["aggregatorName"].replace('Table','Bar Chart')
$("#output3").pivotUI(JsonData, config_copy,  true);
```

Note the differences:

1. You were passing in a *string* as the second parameter, but this parameter expects an *object*
2. To 'remote control' a pivot table like this you need to set the third parameter (`overwrite`) to `true`

**Comment by koppireddy** [comment]
Thanks it is working. Final working copy.
https://jsfiddle.net/kn381h7s/360/

I have hidden the graph UI features. I really appreciate your help.
