### ISSUE TITLE
Hide Column and Row Totals

### ISSUE THREAD

**Issue by riaano** [nicolaskruchten/pivottable#538]
There is a solution to hide all totals, but there is no solution to hide only the column totals and its header.

Currently if you use the same example as the FAQ explains then you get the following. It will hide the total, but not the header and if you want to hide the headerLabel it hides the Label for the bottom (row) as well.

Can a different solution be provided

**Comment by nicolaskruchten** [comment]
So you want to hide the bottom-most row: the header cell, the column totals and the grand total?

**Comment by riaano** [comment]
I have two scenarios:

1. Hide the Column Total on the right of the table, with its header and grand total
2. Hide the row Total at the bottom

**Comment by nicolaskruchten** [comment]
This is going to just be a variation on the CSS for hiding all totals, with a child selector for thead vs tbody for the label.

**Comment by riaano** [comment]
Thanks. Can you send me the code on how to.

**Comment by nicolaskruchten** [comment]
`thead > tr > th.pvtTotalLabel, .rowTotal, .pvtGrandTotal { display: none; }`

and

`tbody > tr > th.pvtTotalLabel, .colTotal, .pvtGrandTotal { display: none; }`

**Comment by riaano** [comment]
I tested both of the lines provided and got the following results. The rows or columns total gets hidden but the header still persists. See attached image showing the header still present.

`<style>thead > tr > th.pvtTotalLabel, .rowTotal, .pvtGrandTotal { display: none; }</style>`

![totals-hidden-without-totals-header](https://cloud.githubusercontent.com/assets/8228092/17802316/d1b264b6-65ef-11e6-88a3-98cac0d9fd46.png)

`<style>tbody > tr > th.pvtTotalLabel, .colTotal, .pvtGrandTotal { display: none; }</style>`

![totals-hidden-without-totals-header-column](https://cloud.githubusercontent.com/assets/8228092/17802411/6ee2881a-65f0-11e6-940f-813bb7bd4d3c.png)


Setup of Table
```
// Pivot Table Setup
var tpl = $.pivotUtilities.aggregatorTemplates;
var sortAs = $.pivotUtilities.sortAs;
var numberFormat = $.pivotUtilities.numberFormat;
var intFormat = numberFormat ({digitsAfterDecimal: 0});

$("#SummarySectionCrossTable").pivotUI
	(
		reportData,
		{
			// aggregators - Specifies the aggregators that is used and shown
			aggregators:
				{
					"Sum": function() { return tpl.sum (intFormat)(["TotalMessages","ActionType"]) },
				},
			// sorters - specifies how to sort each item for the attribute that is specified
			sorters: function (attr)
				{
					if (attr == "Period")
					{
						return sortAs (sortPeriod);
					}
				},

			// hiddenAttributes - hides the attributes from the change able filter options
			hiddenAttributes: ["TotalMessages"],
			// inclusions - has all the months, but only shows the months provided
			inclusions:
				{
					'Period': viewPeriod,
				},

			rows: ["MessageCategory", "MessageSubCategory"],
			cols: ["Period", "ActionType"],
			vals: ["TotalMessages"],
			aggregatorName: "Sum",
			rendererName: "Table",
			hideTotals: true
		}
	);
```

**Comment by nicolaskruchten** [comment]
Are you using the latest version of the PivotTable.js code?

**Comment by riaano** [comment]
Updated the pivot to the new release and it works. Thanks

**Comment by nicolaskruchten** [comment]
There's no feature for this, no. Also: please don't comment on old, closed issues to bring up new ones: instead please create new issues.
