### ISSUE TITLE
Average function

### ISSUE THREAD

**Issue by ousemag** [nicolaskruchten/pivottable#540]
Hello,

I have difficulties with the average function. I am running a dataset containing a Total production from an Hour /Type of Product/Machine etc... up to a Month of production data. I am using the following code to elaborate my average aggregator:
,aggregators: {"Daily Production": function() { return tpl.sum()(["Total"])},
                     "Aver. Hourly Prod": function() {return tpl.average()(["Total"])}}

However, I was hoping my average function would pick on a Daily average or Hourly average depending on my selected columns/lines but it remains at the Hourly level, whatever filter /display I apply in Pivot Table. How can I be that flexible? 
Should I have 2 average aggregator, Aver. Hourly Prod/ Aver. Daily Prod?

**Comment by nicolaskruchten** [comment]
The aggregators operate on the raw data, so if the raw data is hourly, you will always get averages of hourly data. Does that make sense or have I misunderstood your question?

**Comment by ousemag** [comment]
Is there any way to set it based on a different scale or would it require an evolution of the system? Thank you for your answer, well understood.

**Comment by nicolaskruchten** [comment]
This would basically be a large-scale change, unfortunately.
