### ISSUE TITLE
Column counts above each Stacked Bar Chart

### ISSUE THREAD

**Issue by PPTim** [nicolaskruchten/pivottable#541]
Is there a way to display a count above each column of a stacked bar chart? I am displaying some Counts per Month for different data, and would like to be able to display a total numerical Count above each column, like so:

![stackoverflow](https://cloud.githubusercontent.com/assets/20221605/17753366/6550b87a-6484-11e6-9595-4db707d252e6.png)

Thank you

**Comment by nicolaskruchten** [comment]
I don't believe that C3 can do this automatically, no.

**Comment by oscardcs** [comment]
http://c3js.org/samples/data_label.html

Maybe this can help

**Comment by oscardcs** [comment]
In file c3_renderers.js
add labels true in params lines 150+-

params = {
          axis: {
            y: {
              label: ''
            },
            x: {
              label: '',
              tick: {
                rotate: rotationAngle,
                multiline: false
              }
            }
          },
          data: {
            type: chartOpts.type,
            labels: true
          },
          tooltip: {
            grouped: false
          },
          color: {
            pattern: ["#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477", "#66aa00", "#b82e2e", "#316395", "#994499", "#22aa99", "#aaaa11", "#6633cc", "#e67300", "#8b0707", "#651067", "#329262", "#5574a6", "#3b3eac"]
          }
        };


![seleccion_024](https://cloud.githubusercontent.com/assets/24301219/20833399/46589cd8-b86e-11e6-854c-814aeb98a942.png)

**Comment by nicolaskruchten** [comment]
Great, if C3 can do it then you should use the `rendererOptions` mechanism instead of editing the library files :)

See http://nicolas.kruchten.com/pivottable/examples/scatter.html for an example of passing options directly to C3 via the `rendererOptions` mechanism.
