### ISSUE TITLE
show  the value of the rest fields displayed under the columns not just one fields

### ISSUE THREAD

**Issue by leochenchn** [nicolaskruchten/pivottable#543]
Suppose I have seven fields {A,B,C,D,E,F,G},A would be the rows,and B,C,D would be the cols,
the rest of the fields would be the vals :
              rows: ["A"],
                cols: ["B","C","D"],  
                vals: ["E","F","G"]
If i wrtite like this ,just the value of E show under the column,Now I want  the   the value of the rest fields displayed under the columns not just one fields,how could I do that?

**Comment by nicolaskruchten** [comment]
This is not supported at the moment, sorry.
