### ISSUE TITLE
Question: Access data currently used in result

### ISSUE THREAD

**Issue by xirevinian** [nicolaskruchten/pivottable#544]
Hello Nicolas, 

First of all, thanks for creating such great tool! It is really cool ;-)

I have one question - is there a way to access data "currently" used in pivot calculations? Let say there is initial data set which have X columns and N rows. For that data I have defined 3 additional derived attributes, so there is N rows and X+3 columns in total.

End user creates pivot table based on that data and sets some filters up in the pivot. This action limits number of rows from initial N to M rows. I would like to reach that filtered "source" data; M rows of X+3 columns in order to use it in further processing (creating export file, display in table, other calculations).  Is is possible?

Regards.

**Comment by nicolaskruchten** [comment]
Glad you like it!

This data is kind of an intermediary dataset which is hard to access but by wrapping the `PivotData` object you might be able to intercept it... Honestly it feels like a stretch, though.
