### ISSUE TITLE
OnRefresh not called when the configuration is set programmatically.

### ISSUE THREAD

**Issue by BoudaSolution** [nicolaskruchten/pivottable#545]
I am using the onRefresh parameter for accessing the pivot table options and state, which is working perfectly when the user sets it form the UI, but however the user can click on restore configuration button and I will set the configuration programmatically and the problem is that onRefresh is not fired in that case and any changes the user does after that is again won't call the onRefresh function.
How should I solve this?
Thank you

**Comment by nicolaskruchten** [comment]
Hi Natalie,

Sorry for the long delay in responding. I'm not sure I understand the problem you're seeing. Can you provide some code or a JSFiddle or something? Are you working on something similar to this example? http://nicolas.kruchten.com/pivottable/examples/save_restore.html

**Comment by BoudaSolution** [comment]
Thanks for your response.
The problem is I have a function:
`$("#output2").pivotUI(mps,
         {onRefresh: function(config) {	
          //some code here
	 console.log('test refresh');
         }
});`
Which supposed to be called when the user drags and drops fields.
This works perfectly until this part of the code is executed before dragging and dropping the fields.
`$("#output2").pivotUI(mps, JSON.parse($.cookie("pivotConfig")), true);`
This is the link to a simple [page](http://dev.countingopinions.com/nb/pivotSave.html) where you can see that "test refresh" doesn't appear in the console if Restore button is clicked first.
Thanks

**Comment by nicolaskruchten** [comment]
The problem is that the second time you call it, you are not including the `onRefresh` function as part of the config... You will need to store the output of `JSON.parse()` in a variable, and add the `onRefresh` parameter to it before calling `pivotUI()` again. In fact you will need to do this for every function contained in the serialized config, as functions cannot be serialized/deserialized to/from JSON strings.

**Comment by BoudaSolution** [comment]
`var parsedJSON=JSON.parse($.cookie("pivotConfig"));
parsedJSON.onRefresh=function(config) {// your code here};
$("#output2").pivotUI(mps,parsedJSON,true);`
I added these this part as you said and it is working.
Thank you, Nicolas.

**Comment by nicolaskruchten** [comment]
great!
