### ISSUE TITLE
Adding additional sorter parameter to config loaded from cookie

### ISSUE THREAD

**Issue by PPTim** [nicolaskruchten/pivottable#546]
Hi,

 I was following the example in http://nicolas.kruchten.com/pivottable/examples/save_restore.html . My data before saving includes a sorter config parameter, like so:

```
                            `sorters: function(attr) {
                                    if(attr == "Month") {
                                        return sortAs(["January","February","March","April", "May",
                                            "June","July","August","September","October","November","December"]);
                                    }
                                }`
```

But this parameter is not saved, and so when loaded, the months are displayed in natural sort (backwards). Is it possible to append a sorter into the config loaded from JSON?

$("#outputTestBed").pivotUI(parsed_data,JSON.parse($.cookie("pivotConfig")), true); //Add sorter: parameter?

Thanks

**Comment by nicolaskruchten** [comment]
Yes, you'll have to store the output of `JSON.parse` into a variable, then set the `sorters` key of that object...

**Comment by nicolaskruchten** [comment]
Here's an example which might help you: http://nicolas.kruchten.com/pivottable/examples/text_config.html
