### ISSUE TITLE
Arrays inside data object

### ISSUE THREAD

**Issue by kingwillowviii** [nicolaskruchten/pivottable#547]
Hi,

Firstly great plugin ;-)

I was wondering if this was even feasible / have the potential in the futurn to split pivot on mutlivalue fields inside a single object?

So a basic example is:

`$("#output").pivotUI(
    [
        {color: "blue", shape: "circle"},
        {color: "red", shape: ["triangle", "square"]}
    ],
    {
        rows: ["color"],
        cols: ["shape"]
    }
);`

As you can see below, the array is just concatenate into one, is there a way to split this even further so triangle and square are in seperate cells.

![capture](https://cloud.githubusercontent.com/assets/5303184/17971803/3f6f035e-6ad4-11e6-8a77-4c7ed217d81d.PNG)

Many thanks in advance.

**Comment by nicolaskruchten** [comment]
This is not part of the supported data model, no.
