### ISSUE TITLE
Custom Aggregator - Integer Sum

### ISSUE THREAD

**Issue by lfried-ndd** [nicolaskruchten/pivottable#548]
I've been all over this Git and unable to figure out my issue. Using pivotUI, I only want to see "Integer Sum" similar-output (I named it "# Produced"), but using the following shows 2 decimal places:
`$(function(){
            var sum = $.pivotUtilities.aggregatorTemplates.sum;
        Papa.parse("/pivottable/data.csv", {
            download: true,
            complete: function(parsed){
                $("#output").pivotUI(parsed.data, {
                    rows: ["Year"], 
                    cols: ["Model"],
                    vals: ["Count"],
                    aggregators: {"# Produced": function() { return sum()(["Count"])}},
                    renderer: "Table"
                    });
                }
            });
        });;`

Now, I've tried the following which gives me the correct list of aggregators, but a blank table:
`$(function(){
            var sum = $.pivotUtilities.aggregatorTemplates.sum;
            var numberFormat = $.pivotUtilities.numberFormat;
            var intFormat = numberFormat({digitsAfterDecimal: 0});
            var sumInt = sum(intFormat);
        Papa.parse("/pivottable/data.csv", {
            download: true,
            complete: function(parsed){
                $("#output").pivotUI(parsed.data, {
                    rows: ["Year"], 
                    cols: ["Model"],
                    vals: ["Count"],
                    aggregators: {"# Produced": function() { return sumInt()(["Count"])}},
                    renderer: "Table"
                    });
                }
            });
        });`

I realize I could just use
'aggregatorName: "Integer Sum"'
but then I have all the other aggregators that I don't want to see.

What am I doing wrong?

-EDIT-
I don't know why the code is entering as a continuous line. Even typing it in from scratch (as opposed to copy/paste from NetBeans) it still does it. I feel stupid.

**Comment by lfried-ndd** [comment]
Shortly after this posting, I went into the pivot.js and merely changed the value there for digitsAfterDecimal from 2 to 0. Problem solved.

It would still be nice to know how to do it within the HTML instead of changing the hard code.

**Comment by nicolaskruchten** [comment]
In order to control the display of numbers without altering the core library, you would need to create a custom language-pack/locale file: https://github.com/nicolaskruchten/pivottable/wiki/Localization
