### ISSUE TITLE
Too wide

### ISSUE THREAD

**Issue by EmilMoe** [nicolaskruchten/pivottable#549]
This element

~~~~html
<td class="pvtAxisContainer pvtUnused pvtHorizList ui-sortable">
~~~~

Becomes too wide because all options are on same line, how do I enforce line wrap?

**Comment by EmilMoe** [comment]
No solutions to this?

**Comment by nicolaskruchten** [comment]
Have you tried the 'unusedAttrsVertical' parameter set to true?

**Comment by EmilMoe** [comment]
Not exactly, but I can overwrite this `.pvtHorizList li` to be `inline-block`, which might be better as default too.

**Comment by nicolaskruchten** [comment]
ok!
