### ISSUE TITLE
Hide rows or columnss with EMPTY values

### ISSUE THREAD

**Issue by delnei123** [nicolaskruchten/pivottable#550]
Are comming all combinations of elements from rows or columns, even there aren't in the data.
Such as MDX, is possible to hide members (ex: lines) with empty values (empty measure values) ?

**Comment by nicolaskruchten** [comment]
Only rows and columns with data are shown, however by default the value `0` is not displayed, so in some cases you can end up with all-empty rows or columns. You can control this via a custom locale, with your own number formatting.

**Comment by delnei123** [comment]
I have filtered my mdx query to remove zeros and it worked like you said.

I suggest let by default zero in results, in some cases zero has a meaning diferente of empty, example: temperature (celsius).

Finally, pivottable is a great job.

Thanks for your reply.

**Comment by nicolaskruchten** [comment]
Updating an old issue: this aesthetic choice has been reversed, and zeros are always displayed now when there is data in the cell (i.e. 'count' will never show zero because there is nothing to count).
