### ISSUE TITLE
Add this behavior to readme.md

### ISSUE THREAD

**Issue by Scot3004** [nicolaskruchten/pivottable#551]
Grettings and thanks by your good plugin.

Trying to show a data, the generated html was malformed
the pvtUnused appears on left instead of top as show in the following image. 
![captura de pantalla 2016-09-16 a las 6 19 58 p m](https://cloud.githubusercontent.com/assets/1175402/18603799/3f0034d4-7c3a-11e6-895f-c4556c181298.png)
this happens because was generated 2 rows instead of 3.
I put this the code jsfiddle to check the result.
these have 2 variables data which have the case and a basic control data.
https://jsfiddle.net/scot3004/jh3hLq6d/1/

**Comment by nicolaskruchten** [comment]
This is a feature, not a bug. If there are many attributes, the unused attributes are laid out to the left instead of top. Check out the `unusedAttrsVertical` parameter to control this behaviour.

**Comment by Scot3004** [comment]
Ok that is fine, thanks for your attention, well its a documentation issue #553

**Comment by Scot3004** [comment]
Can be added on this section
https://github.com/nicolaskruchten/pivottable#what-does-it-do
