### ISSUE TITLE
How can I prepopulate and still have options?

### ISSUE THREAD

**Issue by EmilMoe** [nicolaskruchten/pivottable#552]
It seems unclear how you would prepopulate from config and maintain the configurations?

``` javascript
$('#pivot').pivotUI(pivotData, JSON.parse(_global.user.pivot_config), {
    derivedAttributes: {
        "Hours Bin": derivers.bin("Hours", 50)
    },
    unusedAttrsVertical: false
});
```

Here the configs are ignored. At least the unusedAttrsVertical. I also have issues with onRefresh.

**Comment by nicolaskruchten** [comment]
In the code above, you are passing data as the first argument, config as the second argument, and config again as the third argument... The third argument is meant to be a boolean, so this is not going to work... https://github.com/nicolaskruchten/pivottable/wiki/Parameters

I'm unclear about what specifically you're trying to do here, so I'm not sure what more constructive advice I can give :)

**Comment by EmilMoe** [comment]
Ah yes, sorry. What I want is to pass the data, then some preselection stored in the database (`_global.user.pivot_config`) and then the configurations. I can be blind but I'm haven't found the way to do that.

**Comment by nicolaskruchten** [comment]
Sounds like you need to merge the objects before passing them into `pivotUI()`, yes. Be careful with the deep/copy behaviour of `$.extend()` though... read the docs to make sure you know what you're doing, as I've been very surprised in the past by what gets mutated by that function!

**Comment by nicolaskruchten** [comment]
Here is an example which shows this in action: http://nicolas.kruchten.com/pivottable/examples/text_config.html
