### ISSUE TITLE
Link wiki page from main page

### ISSUE THREAD

**Issue by Scot3004** [nicolaskruchten/pivottable#553]

**Comment by nicolaskruchten** [comment]
Hmmm I'm not sure about this. It's a very minor feature that is already documented in the full documentation. It doesn't seem notable enough to be in the readme

**Comment by Scot3004** [comment]
Sorry, that is found here https://github.com/nicolaskruchten/pivottable/wiki/Parameters
The page on github repo http://nicolas.kruchten.com/pivottable the main page is redirected to http://nicolas.kruchten.com/pivottable/examples/ which haven't references to wiki, that have the full documentation.

**Comment by Scot3004** [comment]
Anyways, this hidden feature, is minimal but have a big visual impact. at least a reference on this page can be good https://github.com/nicolaskruchten/pivottable#what-does-it-do

**Comment by nicolaskruchten** [comment]
I added a link to the wiki from `examples/index.html`.
