### ISSUE TITLE
 Several Summation columns

### ISSUE THREAD

**Issue by diegosliver** [nicolaskruchten/pivottable#555]
Hello!

My Name is Diego, I am from Brazil, 
I'm from Brazil , and I really liked your library!

I want to know if it is possible to include several columns to perform summations ?, Today only the TOTAL column is the sum of the number of records .

I want for example to have a salary column and be able to view the sum of the salary column , and the sum of the number of records

I also want for example to have the column Salario , number of children , and display the sum of the two columns in the same view .

**Comment by nicolaskruchten** [comment]
Hi Diego! If I understand correctly what you're trying to do, the answer is unfortunately that this is not supported... You can only apply aggregators to fixed input attributes, and then generate columns based on other attribute values. See also this FAQ entry: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi

**Comment by diegosliver** [comment]
OK Nicolas!

thank you!
