### ISSUE TITLE
can't show data

### ISSUE THREAD

**Issue by yolnda** [nicolaskruchten/pivottable#561]
hi @nicolaskruchten,

i make pivottable.js in laravel and can't show data like this
![image](https://cloud.githubusercontent.com/assets/22439577/18899712/369d54aa-8565-11e6-892c-cd566bc93eac.png)

thanks before

regards,
nada

**Comment by nicolaskruchten** [comment]
Ok. I will need to see your code, as this is really not enough information to help you!

**Comment by yolnda** [comment]
I've been able

thanks nicolas
