### ISSUE TITLE
how to add new chart

### ISSUE THREAD

**Issue by yolnda** [nicolaskruchten/pivottable#562]
hi nicolas,

![screenshot_3](https://cloud.githubusercontent.com/assets/22439577/19031379/15dd62f6-897e-11e6-87d3-723d5b05dccf.jpg)

regards, 
yolnda

**Comment by nicolaskruchten** [comment]
That dropdown allows you to specify which Renderer should be used to display information. If you want to add a new chart type, you will need to create a new Renderer.

Here is the Renderer documentation: https://github.com/nicolaskruchten/pivottable/wiki/Renderers and here is the Optional Renderer documentation: https://github.com/nicolaskruchten/pivottable/wiki/Optional-Extra-Renderers

**Comment by yolnda** [comment]
ok, thank you nicolas
