### ISSUE TITLE
How to destroy a pivottable and reclaim all memory used?

### ISSUE THREAD

**Issue by mreishus** [nicolaskruchten/pivottable#563]
If I `$("#pivot").pivotUI(....)`, then later `$("#pivot").html('')` and `$("#pivot").remove('')`, I think I am reclaiming some memory, but not all.   Is there a better way to destroy a pivottable and not leave any references to the data?

**Comment by nicolaskruchten** [comment]
What leads you to believe that you're leaking memory?

**Comment by arturgspb** [comment]
@nicolaskruchten , I have this trouble.
Example: https://jsfiddle.net/z8aep77v/7/

I think onclick and other events leaking on remove element.

**Comment by mreishus** [comment]
I'm not sure that it is leaking.  When using the chrome timeline tab to look at the JS heap size, it seems that after GC kicks in, it returns to baseline memory usage.

![chrome_2017-07-10_08-01-46](https://user-images.githubusercontent.com/937354/28019365-59870fda-6546-11e7-85a6-73e7074c25a1.png)

**Comment by arturgspb** [comment]
@mreishus, I'm not sure too ) You may run GB manually and GB not clear all memory.
I detect memory usage in OS and Chrome Task Manager.

![2017-07-10 16 10 50](https://user-images.githubusercontent.com/1708175/28019717-8c993094-658a-11e7-8e54-9a5987cae6d9.png)
