### ISSUE TITLE
Tree structure

### ISSUE THREAD

**Issue by Alekonm** [nicolaskruchten/pivottable#564]
Hi! How i can create tree structure in rows like that?
![tree](https://cloud.githubusercontent.com/assets/21244784/19118328/bfa15570-8b24-11e6-880c-986995d7c932.jpg)

**Comment by nicolaskruchten** [comment]
Maybe Subtotal.js would meet your needs? http://nagarajanchinnasamy.com/subtotal/examples/

**Comment by Alekonm** [comment]
No. I need something like webix trrtable but free or recommendation how create module.... Maby I can try create my own renderer...
Sory for my english...

**Comment by nicolaskruchten** [comment]
OK. Subtotal.js is about the closest you're going to get with this library...

**Comment by Alekonm** [comment]
Thank you.

**Comment by arturgspb** [comment]
@nicolaskruchten hi! 
I need one tree dimension too.
