### ISSUE TITLE
define attributes even if not present in the data

### ISSUE THREAD

**Issue by AlanBell** [nicolaskruchten/pivottable#565]
I have a scenario where I have data with a "week commencing" attribute, and for most weeks there is at least one data row. However, I want to ensure that the cross tab includes every week, even ones that will have a blank column. Is there a way to specify a list of attributes that must be used?

**Comment by AlanBell** [comment]
I think I mean attribute values rather than attributes. I am thinking of something like the inclusions parameter, but that actually includes values not necessarily present in the data.

**Comment by nicolaskruchten** [comment]
This is not possible at the moment, no. The only rows and columns that get displayed are the ones which contain at least one matching cell in the input. If you want to force columns or rows to appear, you must have some kind of dummy row in the input.
