### ISSUE TITLE
Zeros not shown in cells if sum or integer sum

### ISSUE THREAD

**Issue by OpenDGPS** [nicolaskruchten/pivottable#567]
Currently I'm building an pivottale.js frontend against spark/pyspark (github release will follow). One target is at least to resolve the #565 issue. I'm sure pivottable.js is the best choice to dive in to huge data sources.

![pivattable](https://cloud.githubusercontent.com/assets/7815263/19268986/0712ed00-8fb8-11e6-9513-d6a6968330b3.png)

If I fill a list with missing combinations (*'b' and 'B' in the sample*), both the original cell and the total cell is empty instead of showing '0' or '0.0'. 

I've tried to find the reason, but failed. There is no error in the console. I can only imagine, the strange behavior of JS in handling with 0 and/or null is behind it.

**Comment by jandrei** [comment]
In pivot.js(line 45) there to showZero option: false, just change the showZero: false to showZero: true

**Comment by nicolaskruchten** [comment]
The non-display of zeros by default is indeed a feature, and can be controlled by creating a new locale with different number formatting options.

**Comment by nicolaskruchten** [comment]
Updating an old issue: this aesthetic choice has been reversed, and zeros are always displayed now when there is data in the cell (i.e. 'count' will never show zero because there is nothing to count).
