### ISSUE TITLE
Used By: http://cloudcharts.io

### ISSUE THREAD

**Issue by yannouchou** [nicolaskruchten/pivottable#568]
Hi!
I've been using pivottable for a simple self-service data analytics tool at http://cloudcharts.io
Feel free to add it to your page.
Note that I'm using a customized version that uses:
- The cell click callbacks I implemented in #557 
- A custom renderer for the excellent [Plot.ly](http://plot.ly/javascript/) charting library - which I might share if I get the time to separate it from my app's code a bit better :)

**Comment by nicolaskruchten** [comment]
Thanks for the heads-up, I've added you to https://github.com/nicolaskruchten/pivottable/wiki/Used-By
