### ISSUE TITLE
Just shwo data with aggregators

### ISSUE THREAD

**Issue by ybarbaria** [nicolaskruchten/pivottable#571]
Hello, 

I try to show the values of the some data in my pivot. 
Folowing this code i whant to show for each counterpart the value of "courbe" by "pasHoraire" 

```javascript
     const values = [
            { counterpart: "toto", pasHoraire: "16/12/2015 05:00:00", courbe: "265000,000 KW 25°C" },
            { counterpart: "toto", pasHoraire: "16/12/2015 06:00:00", courbe: "265000,000 KW 25°C" },
            { counterpart: "toto", pasHoraire: "16/12/2015 07:00:00", courbe: "2648745,000 KW 25°C" },
            { counterpart: "toto", pasHoraire: "16/12/2015 08:00:00", courbe: "5674,000 KW 25°C" },
            { counterpart: "toto", pasHoraire: "16/12/2015 09:00:00", courbe: "15487,000 KW 25°C" },
            { counterpart: "toto", pasHoraire: "16/12/2015 10:00:00", courbe: "2548,000 KW 25°C" },
            { counterpart: "toto", pasHoraire: "16/12/2015 11:00:00", courbe: "654545,000 KW 25°C" },
            { counterpart: "tata", pasHoraire: "16/12/2015 05:00:00", courbe: "654887,000 KW 25°C" },
            { counterpart: "tata", pasHoraire: "16/12/2015 06:00:00", courbe: "51548,000 KW 25°C" },
            { counterpart: "tata", pasHoraire: "16/12/2015 07:00:00", courbe: "51484,000 KW 25°C" },
            { counterpart: "tatae", pasHoraire: "16/12/2015 08:00:00", courbe: "55454,000 KW 25°C" },
            { counterpart: "tata", pasHoraire: "16/12/2015 09:00:00", courbe: "354543,000 KW 25°C" },
            { counterpart: "tata", pasHoraire: "16/12/2015 10:00:00", courbe: "12322,000 KW 25°C" },
            { counterpart: "tata", pasHoraire: "16/12/2015 11:00:00", courbe: "1321311,000 KW 25°C" }
        ];
```

I don't know what I have to write in aggregators ? 

```javascript
 pivot.pivotUI(
            values,
            {
                rows: ["pasHoraire"],
                cols: ["counterpart"],
                aggregators: {
                    "Power by pas horaire": () => {
                      ?????
                    }
                }
            });
```

![pivottable](https://cloud.githubusercontent.com/assets/5574663/20000462/d795154e-a277-11e6-9ef3-4da329c3ef6d.PNG)

**Comment by chapt0011** [comment]
Il faut que tu mettes courbe

**Comment by ybarbaria** [comment]
@chapt0011  Merci, mais peux tu me donner plus d'info? 
 
J'ai essayé ça mais sans succès : 

`pivot.pivotUI(values, { rows: ["pasHoraire"], cols: ["counterpart"], aggregators: { "Power by pas horaire": () => { "courbe" } } });`

**Comment by chapt0011** [comment]
Ok j'ai lu un peu trop vite.
En fait il te manque pas mal de chose un "agrégateurs" est une fonction qui réalise un calcul (Somme, Moyenne, ...) sur un champ donné.
Mais en réalité tes données sont mal formatées.
Il va falloir que tu sépare les KW des degrés. (si c'est toujours 25°C inutile de le mettre)

regarde [cet exemple](https://jsfiddle.net/w86bgq9o/357/)
ca ne donne rien de très bon...

Le code correspondant:
`pivot.pivotUI(
 [ { counterpart: "toto", pasHoraire: "16/12/2015 05:00:00", courbe: "265000,000 KW 25°C" }, { counterpart: "toto", pasHoraire: "16/12/2015 06:00:00", courbe: "265000,000 KW 25°C" }, { counterpart: "toto", pasHoraire: "16/12/2015 07:00:00", courbe: "2648745,000 KW 25°C" }, { counterpart: "toto", pasHoraire: "16/12/2015 08:00:00", courbe: "5674,000 KW 25°C" }, { counterpart: "toto", pasHoraire: "16/12/2015 09:00:00", courbe: "15487,000 KW 25°C" }, { counterpart: "toto", pasHoraire: "16/12/2015 10:00:00", courbe: "2548,000 KW 25°C" }, { counterpart: "toto", pasHoraire: "16/12/2015 11:00:00", courbe: "654545,000 KW 25°C" }, { counterpart: "tata", pasHoraire: "16/12/2015 05:00:00", courbe: "654887,000 KW 25°C" }, { counterpart: "tata", pasHoraire: "16/12/2015 06:00:00", courbe: "51548,000 KW 25°C" }, { counterpart: "tata", pasHoraire: "16/12/2015 07:00:00", courbe: "51484,000 KW 25°C" }, { counterpart: "tatae", pasHoraire: "16/12/2015 08:00:00", courbe: "55454,000 KW 25°C" }, { counterpart: "tata", pasHoraire: "16/12/2015 09:00:00", courbe: "354543,000 KW 25°C" }, { counterpart: "tata", pasHoraire: "16/12/2015 10:00:00", courbe: "12322,000 KW 25°C" }, { counterpart: "tata", pasHoraire: "16/12/2015 11:00:00", courbe: "1321311,000 KW 25°C" } ],
  {
    rows: ["pasHoraire"],
    cols: ["counterpart"],
    vals: ["courbe"],
    aggregatorName: "Sum",
    rendererName: "Table"
  });
`

**Comment by chapt0011** [comment]
![image](https://cloud.githubusercontent.com/assets/22372495/20007183/6854025c-a29b-11e6-91cc-0bbe4f19c598.png)

**Comment by nicolaskruchten** [comment]
Ça depends de ce que tu cherche comme output... Quelque-chose du genre pourrait marcher:

```javascript
pivot.pivotUI( values, 
{ 
    rows: ["pasHoraire"], 
    cols: ["counterpart"], 
    vals: ["courbe"],
    aggregatorName: "List Unique Values"
}
);
```

En general, la doc des aggregators est ici: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators
