### ISSUE TITLE
pivottablejs requirements

### ISSUE THREAD

**Issue by Chandlerwu007** [nicolaskruchten/pivottable#572]
os:win7 32bit
browser : chrome
ide: Jupyter notebook

Nothing shows up after I employed pivot_ui 

thanks in advance

**Comment by nicolaskruchten** [comment]
Are you using this library directly in Javascript or are you using it via the Python module? If it's the Python module, please submit this issue in that project's repo which is here: https://github.com/nicolaskruchten/jupyter_pivottablejs

Thanks!
