### ISSUE TITLE
pivot table not grouping values correctly

### ISSUE THREAD

**Issue by janscas** [nicolaskruchten/pivottable#573]
I don't know what's causing this.
Using the csv import example is not working also (http://nicolas.kruchten.com/pivottable/examples/local.html)

As you can see SEVILLA (and others) are not grouped together.

![error](https://cloud.githubusercontent.com/assets/7224106/20026547/93274942-a2fc-11e6-8689-82b3bdd38375.png)

**Comment by nicolaskruchten** [comment]
Not that the the `local.html` example does not do case correction or whitespace chomping on the input data... Most likely there are multiple variations on `"SEVILLA"` like `"SEVILLA "` or `" SEVILLA"` etc which are showing up differently.

**Comment by janscas** [comment]
That's not the case. All values are stripped from leading and trailing spaces. I double check it. For sure "Sevilla" will not match "SEVILLA" but I expect all "SEVILLA"'s to group together and that's not the case.

I paste here the csv (in a zip) i have used.
You can check it by yourself in the example page.

[IMPORTAR prueba.zip](https://github.com/nicolaskruchten/pivottable/files/573671/IMPORTAR.prueba.zip)

**Comment by janscas** [comment]
Btw you need to add '<meta charset="utf-8"/>' to the example pages to avoid the � chars.

**Comment by nicolaskruchten** [comment]
Interesting. It looks like maybe the sorting function I'm using is case-insensitive but the grouping function is case-sensitive. Thanks for the bug report, I'll try to fix it.

**Comment by nicolaskruchten** [comment]
Yeah, that's definitely the problem, and it's easy to fix. I'll have to do some more checking to ensure that such a change doesn't break anything else though.

**Comment by janscas** [comment]
Thanks!

**Comment by nicolaskruchten** [comment]
This should now be fixed in master. Sorry for the delay and thanks for the bug report!

**Comment by janscas** [comment]
Awesome! Thanks!

**Comment by nicolaskruchten** [comment]
Can you confirm that this fixes your issue, and if so I can do a release?

**Comment by nicolaskruchten** [comment]
(sorry, I shouldn't have closed this issue so quickly)

**Comment by janscas** [comment]
Sure, but i'm out for a week. I'll try and come back with the result.

Thanks

**Comment by nicolaskruchten** [comment]
OK, I've done the release and tested it with the file you provided and it looks good to me :)
