### ISSUE TITLE
Allow disabling hasOwnProperty check.

### ISSUE THREAD

**Issue by SamMousa** [nicolaskruchten/pivottable#575]
Possibly related to https://github.com/nicolaskruchten/pivottable/issues/288.

When using native javascript getters added to the prototype using `Object.defineProperty(Myclass.prototype...` these are not usable by the pivottable library.

Especially when dealing with large number of objects, adding these custom properties to the prototype is a lot more efficient.

I think making this optional would be an improvement.

Side note, the libraries extending native objects should mark those properties as non-enumerable instead...

**Comment by SamMousa** [comment]
For reference, I have an array of around 25000 objects with ~ 50 properties. If I add 50 properties defineProperties` on the prototype it takes ~1 msec. If I do it on each object it takes ~3.6 seconds..

**Comment by nicolaskruchten** [comment]
It would be difficult to make this optional, given that this line is output by the CoffeeScript compiler...

**Comment by SamMousa** [comment]
I think you have both kinds in coffee script.
````
For own key in object

For key in object
````

**Comment by nicolaskruchten** [comment]
Oh I know, and I had to change from the latter form to the former for correctness reasons. You're telling me that this change causes performance issues, but unfortunately correctness trumps performance.

Can you tell me more about your use-case? I'm not sure I understand the upstream code you're using which needs to define properties on a prototype etc. Is this on the input dataset? This library basically assumes that the input is set of 'plain' objects, likely the result of `JSON.parse` or something like that. You're doing something different I take it?

**Comment by SamMousa** [comment]
Yes I'm doing something different; I am using this in an angular 2 project with typescript "classes".
The advantage of adding a getter to the prototype is performance; consider having 1000+ objects like these:
````
{ first: "Jane", last: "Doe" }
````
Then adding a getter / function `fullName() { this.first + ' ' + this.last; } to all those objects will be slow, but adding to the prototype of say `Person` is a lot faster.

I'm not sure what correctness you're referring to, let me look in the issue archive :)

**Comment by nicolaskruchten** [comment]
OK, but passing in an object with a `fullname()` method as input to this library doesn't make a lot of sense... It doesn't call methods on objects, it reads fields.

**Comment by nicolaskruchten** [comment]
WRT correctness, you can see in issue #288 that you mentioned that without this own-prop check, in certain cases it would throw exceptions.

**Comment by SamMousa** [comment]
Fullname as a letter I meant https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Defining_a_getter_on_new_objects_in_object_initializers

**Comment by nicolaskruchten** [comment]
Ok. Basically the short answer is that getters are not supported by this library at this time :)

**Comment by nicolaskruchten** [comment]
But if you give me a bit more context about what you're trying to do I might be able to suggest some things... maybe using a function as input instead of an array, to speed things up :)
