### ISSUE TITLE
How to sort filter ?

### ISSUE THREAD

**Issue by fbobo** [nicolaskruchten/pivottable#576]
Hello everybody,

I integrate "pivottable" in a dashboard.

But, I have a problem with the "DATE" filter. He's not sorted decreasing.

Can you help me ?

Thanks

![image](https://cloud.githubusercontent.com/assets/23505892/20357264/87b796c8-ac27-11e6-85b5-1cecc94578b4.png)

**Comment by nicolaskruchten** [comment]
It actually is sorted: 03, 07, 10 etc... The sorter has no way of knowing this is a date and that the year is on the right. To get sorted dates you will need to use ISO-formatted dates: YYYY-MM-DD eg 2016-10-03.

**Comment by fbobo** [comment]
Hello Nicolas,

Thanks for the response.

So, i used the ISO-formatted dates: YYYY-MM-DD. It's works! 

But now how I reverse the sense of sorts ? 

Regards,

**Comment by fbobo** [comment]
up please :)

**Comment by nicolaskruchten** [comment]
Check out the `sorters` parameter: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

There's an example here: http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html

You might actually even be able to use it to sort dates formatted the way you originally had them, if you want, come to think of it, without formatting them in ISO.

**Comment by fbobo** [comment]
Hello Nicolas,
Thanks for the response.

This date format suits me.

I would just sort the date from the newest to the oldest dynamically without having to enter them by hand in the "`sorters`" function.

Do you understand my request? I am not a Javascript specialist.
![image](https://cloud.githubusercontent.com/assets/23505892/20568398/b3978788-b19c-11e6-9044-37834d8b2f7c.png)

Regards,

**Comment by nicolaskruchten** [comment]
You can do it with the `sorters` functionality without enumerating all the dates by passing an appropriate comparison function. Here's some documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by nicolaskruchten** [comment]
Here's a new version of an old example, which now includes two ways of sorting things: http://nicolas.kruchten.com/pivottable/examples/mps_agg.html
