### ISSUE TITLE
Can renderer be made an instance with public API?

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [nicolaskruchten/pivottable#577]
Hi @nicolaskruchten 

Want to know if there is a way to expose the renderer instance and let applications use the APIs exposed by the renderer???!!!! Would be nice if this is documented.

Thanks :)

**Comment by nicolaskruchten** [comment]
There is no renderer instance or API, actually, the renderer is just a function, as you know :)

There is, however, the `rendererOptions` parameter, which a renderer could use to communicate with the outside world: the renderer could call a callback function in the options which would allow it to pass back a communication object.

**Comment by nagarajanchinnasamy** [comment]
I am not ashamed to confess that am an author of a renderer without even realizing that renderer is a function and not an instance!! Its you who should be blamed for it.... to have made things so simple for us.... Thanks :)

Why is renderer a function that just returns a DOM? Instead, can we make it an instance of a class with some standard contractual-APIst that can be invoked to render --- as in MVC pattern? Sorry if I have asked a lame question again!!!

**Comment by nicolaskruchten** [comment]
Well, the whole library is built with functional principles in mind: everything is a function and the only state being stored is in the DOM, so I would not be in favour of changing things just for renderers and not for, say, aggregators, etc.

**Comment by nagarajanchinnasamy** [comment]
Thanks. Am learning :). I will keep this in mind when making any changes/enhancements to subtotal.js renderer.
