### ISSUE TITLE
pivottable and d3 version 4.2.7

### ISSUE THREAD

**Issue by Bigot** [nicolaskruchten/pivottable#579]
Hi
If I try to use d3 renderer example with the latest version of d3 (Version 4.2.7) I get an an error "An error occurred rendering the PivotTable results."

console gives: 
$.pivotUtilities.d3_renderers.Treemap@file:///D:/Documents%20and%20Settings/Owner/My%20Documents/pivottable-master/dist/d3_renderers.js:71:9
$.fn.pivot@file:///D:/Documents%20and%20Settings/Owner/My%20Documents/pivottable-master/dist/pivot.js:938:20
$.fn.pivotUI/refreshDelayed</<@file:///D:/Documents%20and%20Settings/Owner/My%20Documents/pivottable-master/dist/pivot.js:1323:13

As I already use v4.2.7 in my project, is there a way to solve this issue ?

Thanks a lot, Jeff

**Comment by nicolaskruchten** [comment]
I must admit I have not tested this code with D3 version 4, so I'm not sure what the incompatibilities are... I'm not even sure how well C3 works with D3 version 4 actually.

**Comment by timelyportfolio** [comment]
Here is the issue https://github.com/c3js/c3/issues/1648 tracking c3 and d3v4.

**Comment by nicolaskruchten** [comment]
D3 v4+ is now supported by C3 v0.5+ so you should use that combination if you need a more recent version of D3. Please note that most of my efforts are going into Plotly support rather than C3 support at this point :)
