### ISSUE TITLE
Export 

### ISSUE THREAD

**Issue by ghost** [nicolaskruchten/pivottable#58]
Hi there. I'm sorry if I'm writing this at the wrong place, but I was wondering if there's already something implemented to export the pivot table as an Excel file or anything like that. It doesn't have to be fancy or anything. Just the raw data used to form the current pivot table.

Thanks in advance!

**Comment by brianalu** [comment]
I'm currently trying to export using PHP to be 1 worksheet in a much larger report. Was wondering if this was ever completely implemented? :)

-Brian

**Comment by nicolaskruchten** [comment]
This is a client-side only library, so the backend technology (i.e. PHP) does not really come into play... Does the `export_renderers` functionality meet your needs? If not, what more would you need?

**Comment by brianalu** [comment]
Is there any way to get the output of the table pivot into a string or something that I could easily pass to PHP or a file? Similar to the export method in the branch  @ashesnz made
https://github.com/ashesnz/pivottable/tree/ExportToCSV

**Comment by nicolaskruchten** [comment]
Yes, with the `export_renderers`... have you tried to see if this can meet your needs?

**Comment by LukeBrumfield** [comment]
I've been using this library on a reporting project, and I have something that might help out anyone wanting to export to PDF. This example uses jspdf, and should warn about  "pvtAxisLabel" causing some problems if you do not exclude them
This uses jspdf: https://github.com/MrRio/jsPDF

```
<script src="javascripts/pivot.js"></script>
<script src="javascripts/jsPDF/dist/jspdf.debug.js"></script>
<script src="javascripts/jsPDF/dist/jspdf.min.js">

var genPDF = function() {
  var pdf = new jsPDF('p', 'pt', 'letter');
  source = $(".pvtTable")[0].outerHTML; //pvtTable is the default element class
  pdf.fromHTML(source);
  pdf.save('Test.pdf');
};
```

**Comment by nicolaskruchten** [comment]
Thanks @LukeBrumfield !

**Comment by GauravP77** [comment]
@LukeBrumfield @nicolaskruchten thanks for the above snippet for export to pdf. It worked but had challenges with css, grouping and was shrinking so made following changes which worked like charm.

   var pdf = new jsPDF('landscape');

   var specialElementHandlers =     {
							    '.pvtTable': function(element, renderer){
							        return true;
							    }
							};							
   var options = {
          pagesplit: true
     };

  pdf.addHTML($('.pvtTable')[0], 15, 30, {
      'elementHandlers': specialElementHandlers,
    }, function() {
        pdf.save('Test.pdf');
   });

**Comment by meghbrume** [comment]
Hi, I am also struggling with the same problem. But I only want to download the output generated after selecting all the renderers and aggregators. How can I solve it?

Thanks in advance :)

**Comment by nicolaskruchten** [comment]
I'm marking this as closed, given that the FAQ addresses it quite well: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#exporting-renderer-output-to-excel-or-images

**Comment by Bill-VA** [comment]
romulosilvacardoso, thanks for the code snippets.  Instead of editing the pivottable.js file (using CDN), I just did this:  `$('.pvtTable').attr('id', 'testTable');`

To remove the totals columns and bottom row, I did this:

```
$('#testTable thead tr:first').find('th:last').remove();
$('#testTable tr').find('td:last').remove();
$('#testTable').find('tr:last').remove();
```

**Comment by ShravanaCool** [comment]
Sir,
 
How can i do excel export of particular cell data in this

**Comment by susandotmark** [comment]
tried romulosilvacardoso solution via typescript, hits the function all codes are executed, no erros but nothing happens, can someone please guide me through this

**Comment by PRINCEHR** [comment]
### **Guys, You can try this code** 
// In body

<button onclick="exportTableToExcel('testTable', 'pivot_table')">Export Table Data To Excel File</button>


```
<script type="text/javascript">
  function exportTableToExcel(tableID, filename = ''){
var downloadLink;
var dataType = 'application/vnd.ms-excel';
var tableSelect = document.getElementById(tableID);
var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');

filename = filename?filename+'.xls':'excel_data.xls';
downloadLink = document.createElement("a");

document.body.appendChild(downloadLink);

if(navigator.msSaveOrOpenBlob){
var blob = new Blob(['\ufeff', tableHTML], {
  type: dataType
});
navigator.msSaveOrOpenBlob( blob, filename);
}else{

downloadLink.href = 'data:' + dataType + ', ' + tableHTML;

downloadLink.download = filename;

downloadLink.click();
}
}
  </script>

```

### **//In pivot.js** 

pivot.js link in which can be used in which modification is already made
[modified pivot js](https://github.com/PRINCEHR/Pivot-.JS-with-Excel-Output/blob/master/dist/pivot.js)
After Inline  No:955
`result.setAttribute("id", "testTable");
`

**Comment by andreczip** [comment]
I would like to get the data output values from the Pivot component, which I believe is in json format. Has anyone done this?

**Comment by eusebiomarquesbenitez** [comment]
This export to Excel work fine.

Adding the Javascript function:

```
function TableToExcel(filename = ''){
        var downloadLink;
        var dataType = 'application/vnd.ms-excel';
        var tableHTML = $(".pvtTable")[0].outerHTML.replace(/ /g, '%20');
        
        filename = filename?filename+'.xls':'excel_data.xls';
        downloadLink = document.createElement("a");
        document.body.appendChild(downloadLink);
        
        if(navigator.msSaveOrOpenBlob){
            var blob = new Blob(['\ufeff', tableHTML], {
                type: dataType
            });
            navigator.msSaveOrOpenBlob( blob, filename);
        }else{
            downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
            downloadLink.download = filename;
            downloadLink.click();
        }
    }
```
And the Html Code

```
<input type="button" value="Exportar a Excel" onclick="TableToExcel('TablaDinamica');" id="Exportar" style="font-size: 14px;" />
```

**Comment by susandotmark** [comment]
Dear nicolaskruchten/pivottable,

This is a confirmation that we received your email and registered it as ticket #26248156. You can always reply to this email if you want to add additional information.

Kinds regards,

Team Dotmark

**Comment by AFilipchyk** [comment]
Hi!
Export to excel works, but my MS Office show me warning that it's not xls file. And it's true, there is html inside!

**Comment by susandotmark** [comment]
Dear nicolaskruchten/pivottable,

This is a confirmation that we received your email and registered it as ticket #26528206. You can always reply to this email if you want to add additional information.

Kinds regards,

Team Dotmark

**Comment by Suganya0207** [comment]
Dear eusebiomarquesbenitez,
                Export to Excel works. But i need to change the style in the excel. i.e Header portion should have different color and total portion should be different and rows/columns should be left aligned.

**Comment by susandotmark** [comment]
Dear nicolaskruchten/pivottable,

This is a confirmation that we received your email and registered it as ticket #32901886. You can always reply to this email if you want to add additional information.

Kinds regards,

Team Dotmark
