### ISSUE TITLE
Data from json objects and value filter

### ISSUE THREAD

**Issue by gargulamen** [nicolaskruchten/pivottable#580]
I have json with multiple objects but the keys aren't the same in each of them.
Let's say I have something like this.

[{ a: "foo",
   b: "bar",
   val: 20
 },
 { b: "car",
   c: "bar",
   val: 10
 }]

When it gets around the lines below, I get an error. Something about my "c" key.
if ((base = axisValues[k])[v] == null) {
      base[v] = 0;
}
      results.push(axisValues[k][v]++);

I tried to construct a json with "a", "b", "c" on every single object with null value for the ones that don't have value at all, but I can't filter the attributes rows/cols rendered with the name "null".

Any solution for this?
Thanks in advance.

**Comment by gargulamen** [comment]
Update: I want a behavior that looks like the exclusions but that removes from the list aswell.
Even with the exclusions for every key the table stops rendering results.

**Comment by nicolaskruchten** [comment]
This library doesn't deal very well with "ragged" input like this where individual rows don't have the same keys or are missing keys. I'll take a look to see how hard it is to make it work but I'm skeptical that it will be easy.

**Comment by nicolaskruchten** [comment]
OK, I have a PR open #600 which should address this, if you want to test it out.
