### ISSUE TITLE
Preselect Aggregation entities

### ISSUE THREAD

**Issue by misteliy** [nicolaskruchten/pivottable#581]
Hi,

I like pivottable very much since it gives me a nice and direct way to compare my data - thank you very much for the effort. I was wondering if it is possible to preselect the entities when I switch from count to sum in the UI that not all fields pop up but only the ones that make sense for summing?

Thanks and all the best

--yannick

**Comment by nicolaskruchten** [comment]
There's no way to do quite what you seek, but maybe a custom aggregator would go part-way?

http://nicolas.kruchten.com/pivottable/examples/mps_agg.html

**Comment by misteliy** [comment]
Yes, right. I manuelly set all the options and that works as well. thanks a lot
