### ISSUE TITLE
How can we download the PIVOT table data to excel

### ISSUE THREAD

**Issue by kavikon** [nicolaskruchten/pivottable#582]
Hi I am trying to use this wonderful javascript for doing some presentation.
However the requirement is that after the manipulations are done on the screen the users should be able to download the data.Either the picot table data or chart & chart data.

Incase this sounds like enhancement please point me to some area which can help me achieve this on my own

**Comment by misteliy** [comment]
just use the TSV option and then copy & paste

**Comment by nicolaskruchten** [comment]
Yes, right now the TSV option is the best we've got: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#exporting-renderer-output-to-excel-or-images

**Comment by oscardcs** [comment]
Hi guys, I made a function that read every row and column from a div table html by JQuery, create a JSON object and send that object to php to make an excel document.

![seleccion_022](https://cloud.githubusercontent.com/assets/24301219/20806828/2e548360-b7db-11e6-9b1b-03c7edc8c514.png)
![seleccion_023](https://cloud.githubusercontent.com/assets/24301219/20806829/2e7b46ee-b7db-11e6-8309-0f1e308f6b4c.png)

JQuery code:
$(document).on("click", 'a[id^="exportar_"]', function(){
			var nro_grafico_split = $(this).attr('id').split('_');
			var id_grafico = "#output_"+nro_grafico_split[1];

			$.each($(id_grafico+' .pvtTable'), function(key, value){
				var tabla = {};
				var cols = [];
				var i;

				var columnas = value.getAttribute('data-numcols');
				var filas = value.getAttribute('data-numrows');

				tabla.columnas = columnas;
				tabla.filas = filas;
				tabla.head = [];
				tabla.body = [];

				tabla.id_grafica = nro_grafico_split[1];

				$.each($(id_grafico+' .pvtTable thead tr'), function(key2, value2){
					i = 0;
					row = [];
					$.each($(this).find('th'), function(key3, value3){
						casilla = {};
						if(($(this).html()) !== null && ($(this).html()) !== ''){
							if($(this).attr('colspan') !== undefined){
								casilla.colspan = $(this).attr('colspan');
							}
							else{
								casilla.colspan = 0;
							}

							if($(this).attr('rowspan') !== undefined){
								casilla.rowspan = $(this).attr('rowspan');
							}
							else{
								casilla.rowspan = 0;
							}
							casilla.valor = $(this).html();

							row[i] = casilla;
							i++;
						}
						else{
							if($(this).attr('colspan') !== undefined){
								casilla.colspan = $(this).attr('colspan');
							}
							else{
								casilla.colspan = 0;
							}

							if($(this).attr('rowspan') !== undefined){
								casilla.rowspan = $(this).attr('rowspan');
							}
							else{
								casilla.rowspan = 0;
							}
							casilla.valor = '';

							row[i] = casilla;
							i++;
						}
					});
					cols.push(row);
				});
				tabla.head.push(cols);

				cols = [];
				$.each($(id_grafico+' .pvtTable tbody tr'), function(key4, value4){
					i = 0;
					row = [];
					$.each($(value4).find('th'), function(key5, value5){
						casilla = {};
						if(($(this).html()) !== null && ($(this).html()) !== ''){
							if($(this).attr('colspan') !== undefined){
								casilla.colspan = $(this).attr('colspan');
							}
							else{
								casilla.colspan = 0;
							}

							if($(this).attr('rowspan') !== undefined){
								casilla.rowspan = $(this).attr('rowspan');
							}
							else{
								casilla.rowspan = 0;
							}
							casilla.valor = $(this).html();

							row[i] = casilla;
							i++;
						}
						else{
							if($(this).attr('colspan') !== undefined){
								casilla.colspan = $(this).attr('colspan');
							}
							else{
								casilla.colspan = 0;
							}

							if($(this).attr('rowspan') !== undefined){
								casilla.rowspan = $(this).attr('rowspan');
							}
							else{
								casilla.rowspan = 0;
							}
							casilla.valor = '';

							row[i] = casilla;
							i++;
						}
					});

					$.each($(this).find('td'), function(key6, value6){
						casilla = {};
						if(($(this).html()) !== null && ($(this).html()) !== ''){
							if($(this).attr('colspan') !== undefined){
								casilla.colspan = $(this).attr('colspan');
							}
							else{
								casilla.colspan = 0;
							}

							if($(this).attr('rowspan') !== undefined){
								casilla.rowspan = $(this).attr('rowspan');
							}
							else{
								casilla.rowspan = 0;
							}
							casilla.valor = $(this).html();

							row[i] = casilla;
							i++;
						}
						else{
							if($(this).attr('colspan') !== undefined){
								casilla.colspan = $(this).attr('colspan');
							}
							else{
								casilla.colspan = 0;
							}

							if($(this).attr('rowspan') !== undefined){
								casilla.rowspan = $(this).attr('rowspan');
							}
							else{
								casilla.rowspan = 0;
							}
							casilla.valor = '';

							row[i] = casilla;
							i++;
						}
					});
					cols.push(row);

				});
				tabla.body.push(cols);

				var tabla2 = JSON.stringify(tabla);

				$("#tabla_final").val(tabla2);
				$("#form_excel").submit();
			});
		});

**Comment by smartinsightsfromdata** [comment]
For any users of rpivotTable (the R wrapper for pivottable), there is a simple example  in R + shiny [here](https://github.com/smartinsightsfromdata/rpivotTable/issues/62).

**Comment by kavikon** [comment]
Hi @oscardcs can you give the complete code would like to make use of it to export to excel

**Comment by comeback2000** [comment]
Where to copy this code for export to excel option

**Comment by abhikvnair** [comment]
hi @oscardcs  
how to implement this, please reply

**Comment by PRINCEHR** [comment]
### **Guys, You can try this code** 
// In body

<button onclick="exportTableToExcel('testTable', 'pivot_table')">Export Table Data To Excel File</button>


```
<script type="text/javascript">
  function exportTableToExcel(tableID, filename = ''){
var downloadLink;
var dataType = 'application/vnd.ms-excel';
var tableSelect = document.getElementById(tableID);
var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');

filename = filename?filename+'.xls':'excel_data.xls';
downloadLink = document.createElement("a");

document.body.appendChild(downloadLink);

if(navigator.msSaveOrOpenBlob){
var blob = new Blob(['\ufeff', tableHTML], {
  type: dataType
});
navigator.msSaveOrOpenBlob( blob, filename);
}else{

downloadLink.href = 'data:' + dataType + ', ' + tableHTML;

downloadLink.download = filename;

downloadLink.click();
}
}
  </script>

```

### **//In pivot.js** 

pivot.js link in which can be used in which modification is already made
[modified pivot js](https://github.com/PRINCEHR/Pivot-.JS-with-Excel-Output/blob/master/dist/pivot.js)
After Inline  No:955
`result.setAttribute("id", "testTable");
`
