### ISSUE TITLE
How to deal with large data set getting from server side

### ISSUE THREAD

**Issue by datnguyen0606** [nicolaskruchten/pivottable#584]
My situation is that I have more than 200k rows records which are gotten from server side. In order to use pivottable js, a client browser needs to download whole data, e.g via ajax request, it causes browser hang and not respond.

I'm thinking that instead of processing pivot table in front-end, I would do it on back-end side. However I would love to use the js library for drag&drop UI. It means that when I manipulate pivot table, it would send a request to server. Is there any way I could achieve this result?

Or any suggestion would prevent browser not respond while downloading a large data set for initializing the pivotable?

Thanks

**Comment by ilyaguy** [comment]
I'm working now on the same issue.

My idea is to load data by portions (may be 20k rows), then init pivotUI with this array.
So, it means that pivottable will not reload all data every for each drag-n-drop move.

**Comment by datnguyen0606** [comment]
@ilyaguy: yeah, that's one way I have tried, but one down side is that user needs to wait until client gets all portions. And server needs to query into database for every portion (20k rows), it will take time to load whole data.

My idea is that we only load data from database one time and store it in cache or local file. For each drag&drop move, client sends request to server, server don't need to query again, just get data from cache and process the pivot table (e.g using Pandas python library to handle it)

**Comment by chapt0011** [comment]
Hello guy's,

I'had to work on an similar issue... 
In my case, the final user has to deal with several data set
When then user logs in, for each data set he has subscribed to, i run an asynchronous ajax request
that stores the result of the sql query in php session.
During this asynchronous request, the front end shows a progressbar ( Loaded 1 of X...).
When finished, you can easily reload the full page without doing any other request on the database.
Your pivot table should easily deal with the 200k rows that are stored in the php session.

**Comment by datnguyen0606** [comment]
@chapt0011: storing data in php session means that the data is in server memory, right? If data grows up quickly, server will be out of memory. Is there any way we store data in client local storage? so we don't affect server memory.

**Comment by nagarajanchinnasamy** [comment]
I think you need to choose where the pivoting needs to happen!.

If it happens on server side, it will help reducing the amount of data to be transferred to client... But then you wouldn't need a pivot table ui on the client side (pls correct me if i am wrong)

On the othethand, if you want the user to have entire data and perform pivoting on it, then data volume to be transferred to client may go up!!!!

Good point to discuss about.... Waiting to learn from this discussion :)

**Comment by chapt0011** [comment]
@datnguyen0606 Sure, but assume data has been loaded in php session.
Render the page on the server side does'nt meen you can't unset the session variable on the server side after it has been sent to client side.

First:
While loading data into php session variable
//SQLRequest
// $_SESSION['dataset']=SQLResult json formatted
display loading progress!

On loaded
Redirect user to the following page:
```
<?php
session_start();
//if you don't use any template engine
echo '<html>
<head>[...]</head>
<body>
<script>
$(function(){
        var derivers = $.pivotUtilities.derivers;
            $("#output").pivotUI('.$_SESSION['dataset'].',
                //your pivotUI params here
            });
        });
     });
</script>
<div id="output"></div>
</body>';

//FINALLY unset the session variable which is already written!
unset($_SESSION['data']);
?>
```

**Comment by chapt0011** [comment]
Peform pivot on the server side is not a good idea.  Anytime the final user wants to change rows or cols in the table,  he will have to reload the dataset or the pivot result. 
Actually the data in pivotui is already stored on the client side.  I think you are just looking for the best way to get them as fast as possible from the server..
1st.  you need to optimize your request !  if you are using mysql you can try to use a ramdisk...
2nd. Use Ajax asynchronously to perform your request, you don t really need php sessions . This way you won t get any javascript timeout

**Comment by nicolaskruchten** [comment]
My feeling is that the architecture of this library is incompatible with a server-side integration along these lines... See #150

**Comment by nagarajanchinnasamy** [comment]
@chapt0011  yes you can bring in data in smaller chunks. But the pivot result on the client will be based on the data so far loaded on the client. And, the performance will be based on the client machine configuration!!!

@nicolaskruchten it would be nice if you can point us to references of such architectures that would address such requirements. Thanks :)

**Comment by nicolaskruchten** [comment]
https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#server-side-integration
