### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using 'Heatmap' renderer

### ISSUE THREAD

**Issue by zam6ak** [nicolaskruchten/pivottable#585]
I have a data set with approx 14,000 rows (array of arrays), each row with 5 items.
the usage is straight forward, but if I use heatmap renderer it crashes:

```
$("#pivot1").pivot(data, {
    rows: ['Facility', 'Method', 'Order Date', 'Description'],
    cols: ['Status'],
    aggregator: count()(['Order Date']),
    renderer: renderers['Heatmap'], // crashes with large data set
    //renderer: renderers['Table'], // works with same large data set
    rendererOptions: {
        heatmap: {
            colorScaleGenerator: function(values) {
                return d3.scale.linear()
                    .domain([d3.min(values), d3.mean(values), d3.max(values)])
                    .range(["white", "lightskyblue", "deepskyblue"]);
            }
        }
    }
});

```

And the error:

```
RangeError: Maximum call stack size exceeded
    at Function.ga [as find] (jquery.min.js:2)
    at r.fn.init.find (jquery.min.js:2)
    at o (pivot.coffee:898)
    at pivot.coffee:903
    at r.fn.init.t.fn.heatmap (pivot.coffee:908)
    at Object.Heatmap [as renderer] (pivot.coffee:155)
    at r.fn.init.t.fn.pivot (pivot.coffee:549)
    at HTMLDocument.<anonymous> (report:177)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```

**Comment by zam6ak** [comment]
Also, I tried removing rendererOptions completely and the error still persists....

**Comment by nicolaskruchten** [comment]
Hmm, yeah, it seems like one of the jQuery functions is having trouble running on such a large DOM. I'll have to play with it to see if I can work around it but it seems like you've bumped up against a limit of this type of in-browser approach.

**Comment by zam6ak** [comment]
I have had this error occur with as little as 9,000 rows as well.
Thanks for looking into this.

**Comment by nicolaskruchten** [comment]
Well I suspect the issue is not with the number of rows in the input, it's with the number of rows, columns and cells of the output table. I've successfully used the Heatmap renderer with 100k-row input. But if you have a fully diagonal table with a 9k-row input, then your table will have 9k^2=81M cells ;)

**Comment by zam6ak** [comment]
So there is a threshold based on number ROWs x COLUMNs .
In my case, it is breaking within 117k - 130k cells.
Only workaround I can think of right now is to choose Table renderer if the total cell count is let's say > 100k ....But our users don't like it :( (they want to see the Heatmap)

**Comment by nicolaskruchten** [comment]
My hypothesis is that there is this kind of threshold, yes, but I haven't been able to test that just yet.

**Comment by nicolaskruchten** [comment]
I'm having no issues with the heatmap renderer with 475 rows and 156 columns (=74,100 cells) but to be honest this size of table is not really meaningfully usable in my opinion given the amount of scrolling required to get it all in view.

I am able to replicate your issue with a large number of cells, but there's not much I can suggest other than that this library (and perhaps a browser in general) is not suitable for this sort of task...

**Comment by zam6ak** [comment]
I think it is more realistic to have large number of rows rather than large number of columns, is it not?
The nice thing about the pivot table in general  is that they are able to aggregate large data sets.

if this is not fixable, then so be it.
But perhaps it would be useful for others looking to use this library to know about these limits before they start their own project.

**Comment by nicolaskruchten** [comment]
Well to be clear, this library can *aggregate* large data sets, but browsers in general are not suitable for *displaying* large datasets. For example, this system will snappily generate counts for low-cardinality dimensions or tables with hundreds of cells on a underlying dataset with 50,000 rows with 10 attributes. The browser will not easily generate a 50,000-row table with 10 columns.

**Comment by ayanakshi** [comment]
I changed this piece of code:  heatmapper = (function(_this) {
        return function(scope) {
          var colorScale, forEachCell, values;
          forEachCell = function(f) {
            return _this.find(scope).each(function() {
              var x;
              x = $(this).data("value");
              if ((x != null) && isFinite(x)) {
                return f(x, $(this));
              }
            });
          };
          values = [];
          forEachCell(function(x) {
            return values.push(x);
          });
          colorScale = colorScaleGenerator(values);
          return forEachCell(function(x, elem) {
            return elem.css("background-color", colorScale(x));
          });
        };
      })(this);

With:

heatmapper = (function(_this) {
        return function(scope) {
          var colorScale, forEachCell, values;
          forEachCell = function(f) {
            return [].forEach.call(_this[0].querySelectorAll(scope), function(item) {
                   		 var x;
                            x = item.getAttribute("data-value");
                            if ((x != null) && isFinite(x)) {
                                return f(x, $(item));
                            }
                   		});
          };
          values = [];
          forEachCell(function(x) {
            return values.push(x);
          });
          colorScale = colorScaleGenerator(values);
          return forEachCell(function(x, elem) {
            return elem.css("background-color", colorScale(x));
          });
        };
      })(this);

This is working at my end. In place of jquery each function, I used the javascript querySelectorAll.
