### ISSUE TITLE
How know pivottable rendering success/complete point?

### ISSUE THREAD

**Issue by ssangdifafa** [nicolaskruchten/pivottable#586]
How know Pivottable rendering complete point?..

I want render after.. another logic add..

ex) add action or event ->grid css add ... total hide ...

**Comment by nicolaskruchten** [comment]
check out the `onRefresh` callback parameter. 

documentation: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

example: http://nicolas.kruchten.com/pivottable/examples/onrefresh.html
