### ISSUE TITLE
Initializing pivot with some saved state and get the updated state after some modifications?  #462 

### ISSUE THREAD

**Issue by misteliy** [nicolaskruchten/pivottable#587]
How can I re-add the aggregators and renderers?

https://github.com/nicolaskruchten/pivottable/issues/462#event-755599360

**Comment by ilyaguy** [comment]
For example:

```
    if (config) {
        // If a saved state found in LocalStorage, then load it
        configObject = JSON.parse(config); // Make it an object
    } else {
        // Prepare new config.
        configObject = {
            cols: ['Event Name'],
            rows: ['Traffic Source', 'Event Month', 'Event Day'],
            vals: ['eventCount'],
            autoSortUnusedAttrs: true,
            aggregatorName: 'count',
            rendererName: 'Table',
            hiddenAttributes: ['event', 'eventDate', 'trafficSourceId']
        };
    }

    // Add function calls to config object.
    configObject.onRefresh = saveState; // Add callback function for onRefresh
    configObject.dataClass = $.pivotUtilities.SubtotalPivotData;
    configObject.derivedAttributes = derivedAttributes;
    configObject.aggregators = aggregators;
    configObject.renderers = renderers;
    configObject.sorters = sorters;

    jQuery("#output").pivotUI( // Load with saved state
            dataSource, configObject, true
        );
```

**Comment by nicolaskruchten** [comment]
If you call `pivotUI()` without setting `overwrite=true` OR if your first call to `pivotUI()` is with a saved config, then you will need to make sure your saved config contains all the keys you want to configure including `aggregators` and `renderers`. You can do this explicitly as in the code above, or you can merge your saved config with a default config of your choice.

**Comment by misteliy** [comment]
Hi @ilyaguy ,
thank you very much. Finally I decided to overwrite the aggregator in the restore part (merge as nicolas suggested):
`                             $("#restore").on("click", function(){
                                    configObject = JSON.parse($.cookie("pivotConfig")); 
                                    configObject.aggregators = {
                                        "Sum": function() { return tpl.sum()(["Variable"])},
                                        "Count":      function() { return tpl.count()() },
                                        "Average": function() { return tpl.average()(["Variable"])}}
                                    $("#output").pivotUI(parsed.data, configObject, true);
                             });`

**Comment by Humano2** [comment]
Hi @misteliy , your answer was helpfull but can you help me with the same line with sorter? 

configObject.sorters = {} (i need a example)


sorters: function(attr) {
                        if(attr == "Mes Creacion") {
                            return sortAs(["Jan","Feb","Mar","Apr", "May",
                                "Jun","Jul","Aug","Sep","Oct","Nov","Dec"]);
                             }
}

**Comment by ilyaguy** [comment]
@Humano2 
```
var mySorters = function(atrr) {
   if(attr == "Mes Creacion") {
      return sortAs(["Jan","Feb","Mar","Apr", "May", "Jun","Jul","Aug","Sep","Oct","Nov","Dec"]);
   }
}

/* ... */

configObjec.sorters = mySorters; // function name from above definition.
```

**Comment by Humano2** [comment]
:( doesn't work.
@ilyaguy my global problem is when i save and restore configurations i lost sorting and derivedatributes configurations.

can you check my proyect here: http://crm.skbergechile.com/forms_anon/formulariosk/vfc/mbt2.aspx

im been trying to fix this 3 days please your help

**Comment by nicolaskruchten** [comment]
I've just added a new example which might help you, @Humano2 ... http://nicolas.kruchten.com/pivottable/examples/text_config.html

In the future, please don't comment on closed issues if you want help, just create a new issue :)

**Comment by Humano2** [comment]
Thanks a lot
