### ISSUE TITLE
Loading data error

### ISSUE THREAD

**Issue by gargulamen** [nicolaskruchten/pivottable#588]
Why can I Load the object like this?

    {
    "Somê name": null,
    "Sõme name": null,
    "Some thing": null,
    "Something": null,
    "Some, name": null,
    "Nonull": "Info info",
    "Morenull": null,
    "Metric": "Value",
    "Peri": "Tri",
    "Date": "2009-03-31",
    "Date stuff": "1 to 5",
    "Dateee": "tóo 1",
    "Info": "this",
    "Setor institucional de contraparte": "NoSame",
    "Setor institucional de referência": "Sameee",
    "NoPlace": null,
    "Place": "Country",
    "Currency": "Currencyinfo",
    "Value": 8666.707897
  },
  {
    "Somê name": null,
    "Sõme name": null,
    "Some thing": null,
    "Something": null,
    "Some, name": null,
    "NoNull": null,
    "Morenull": null,
    "Metric": "Value",
    "Peri": "Tri",
    "Date": "2009-09-30",
    "Dateee": null,
    "Info": "this",
    "A big key name with a lot of spaces": "NoSame",
    "Another big key name with thêõs": "Sameee",
    "NoPlace": "SomePlace",
    "Place": "Country",
    "Currency": "Currencyinfo",
    "Value": 68.996283
  }

The nulls on the first set show up on the render but i don't want it.
but not like this? I get an error when i try around line 1070

    {
    "Nonull": "Info info",
    "Metric": "Value",
    "Peri": "Tri",
    "Date": "2009-03-31",
    "Date stuff": "1 to 5",
    "Dateee": "tóo 1",
    "Info": "this",
    "Setor institucional de contraparte": "NoSame",
    "Setor institucional de referência": "Sameee",
    "Place": "Country",
    "Currency": "Currencyinfo",
    "Value": 8666.707897
  },
  {
    "Metric": "Value",
    "Peri": "Tri",
    "Date": "2009-09-30",
    "Info": "this",
    "A big key name with a lot of spaces": "NoSame",
    "Another big key name with thêõs": "Sameee",
    "NoPlace": "SomePlace",
    "Place": "Country",
    "Currency": "Currencyinfo",
    "Value": 68.996283
  }

**Comment by nicolaskruchten** [comment]
This library doesn't deal very well with "ragged" input like this where individual rows don't have the same keys or are missing keys. I'll take a look to see how hard it is to make it work but I'm skeptical that it will be easy.

**Comment by nicolaskruchten** [comment]
I believe that PR #600 should address this if you want to test it out.
