### ISSUE TITLE
Header fixed in multi aggregation case 

### ISSUE THREAD

**Issue by dharam1291** [nicolaskruchten/pivottable#589]
how to fixed the header in multi aggregator case. i have used necro pivotable but it works fine without multi aggregator

**Comment by nicolaskruchten** [comment]
I'm not sure I understand your question... can you clarify please?

**Comment by dharam1291** [comment]
I want to say how to fixed the header. If pivotmf.js used. Basically
pivotmf is used for multi measure.

On 05-Dec-2016 2:36 am, "Nicolas Kruchten" <notifications@github.com> wrote:

I'm not sure I understand your question... can you clarify please?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nicolaskruchten/pivottable/issues/589#issuecomment-264731162>,
or mute the thread

**Comment by nicolaskruchten** [comment]
I don't know what "pivotmf.js" is... this is not part of this library.

**Comment by dharam1291** [comment]
I mean multiple aggregator labels issue no 30.

**Comment by nicolaskruchten** [comment]
Ah, OK. I'm afraid I can't help you with that, it's sort of an unofficial patch that I don't spend any time maintaining...
