### ISSUE TITLE
Adding checkbox to pivottable rows?

### ISSUE THREAD

**Issue by ridonkz** [nicolaskruchten/pivottable#592]
Is there a way to add checkboxes to the pivot table. I am not using pivot UI.
I was wondering if I can add checkboxes as I have a export functionality, so I want to be able to export only the selected rows.

**Comment by nicolaskruchten** [comment]
There is no built-in functionality which will be helpful for this, no, sorry!

**Comment by ridonkz** [comment]
Is there a way that you can suggest this can be achieved? I am using Ruby on Rails.

**Comment by nicolaskruchten** [comment]
Not really, what you're looking for is pretty far out of scope for this library...
