### ISSUE TITLE
Simple question from a newbie re derived attributes in montreal_2014.html

### ISSUE THREAD

**Issue by astrodad1** [nicolaskruchten/pivottable#594]
Hi, I'm just getting up to speed on pivottable.js and like it a lot. I'm stuck on a relatively simple task in derived attributes. In the montreal_2014.html code, all I am trying to do is create a new variable called "Precipitation" that is the sum of Total Rain (mm) and Total Snow (cm). Once the new variable Precipitation is created in the derived attributes, I plan to also add it to the aggregators list as well. Adding two existing variables seems simple, but I have yet to get it to work and haven't found any code in the examples to help. Sorry for the newbie question. Thanks, astrodad@gmx.com

**Comment by nicolaskruchten** [comment]
What you want to do is created a "derived attribute" like "Gender Imbalance" in this example: http://nicolas.kruchten.com/pivottable/examples/mps.html

**Comment by nicolaskruchten** [comment]
Basically something like:

```javascript
"derivedAttributes": { 
    "Precipitation": function(row){return row["Total Rain (mm)"] + row["Total Snow (cm)"];} 
}
```
