### ISSUE TITLE
jasmine test

### ISSUE THREAD

**Issue by cacahuete49** [nicolaskruchten/pivottable#597]
hi,

In the test page (/tests/index.html), the link (http://coffeescript.org/extras/coffee-script.js) are broken , you can replace it with this link http://coffeescript.org/v1/browser-compiler/coffee-script.js .

soon you will have another problem with chrome, the following message came from the console :
Fetching scripts with an invalid type/language attributes is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5760718284521472 for more details.

thx for your work =)

**Comment by nicolaskruchten** [comment]
Thanks for the heads-up, all fixed!
