### ISSUE TITLE
frequently hangs the browser while manipulating pivot table when  input data is big

### ISSUE THREAD

**Issue by rKS2827** [nicolaskruchten/pivottable#599]
Hi @nicolaskruchten 
I would love to use this API  but I find it frequently hangs the browser when  input data is big.
Browser  crashes frequently(Browser started to complain it was out of memory), when manipulating pivot table, as selecting rows/columns.
For the input data, I'm only passing in the array under the data key As below.

`[{"Province": "d6880daca6180e00", "Party":"Conservative", "Age": 50,"Name": "8c9424ca352f92c7","Gender": "Male","City":"83f113b91833ae43","Country":"india","Brand":"AcnSports","Account":"Old Navy LLC","Tier 1 SC Access":"Update","Province1": "Ontario", "Party1":"Conservative1", "Age1": 50,"Name1": "Adle Mark", "Gender1": "Male","City1":"Jaipur","Country1":"india","Brand1":"AcnSports","Account1":"Old Navy LLC","Tier 1 SC Access1":"Update"}]`

**I have 5k rows which contains unique value for(Key) -Provience,Name and City ,rest all are duplicate.**
Everything seems working. Data gets rendered but it takes too much time whenever I perform any action like drag n drop.
It works fine if there is all  duplicate rows ,I have tested for 1,60000 records and it works smooth .
There is lot of  DOM manipulation happen ,when there is thousands of unique records ,that leads to browser crashes ,thats what I have understand .
Please correct me If I  am doing anything wrong. 
What should I do in this case?
Any Help will be apprecited.
[output table Snapshot](http://imgur.com/a/dLwam)
[JSONData](https://drive.google.com/file/d/0B5tB3Kj8ObvSTHNLQnp6cWwtYk0/view?usp=sharing)
**System spec's :-**  2.5 Ghz, Core i7,16 GB Ram,Chrome

Thanks,
Ravindra Solanki

**Comment by nicolaskruchten** [comment]
The issue is not with the raw number of rows, but with the cardinality of the columns: the number of unique values, because the browser has to add a large number of nodes to the DOM. For example in your data, it's very snappy to make a table with Age and Account, but slows down if you add any of the fields that you filled with hex hashes.

**Comment by nicolaskruchten** [comment]
I was only able to replicate your crashing scenario when I tried to put one of the high-cardinality attributes in the rows area and one in the columns area but this makes sense... The resulting table would have 25 million cells in it, and the browser cannot draw this. Is that what you're trying to do?

**Comment by rKS2827** [comment]
Thanks  @nicolaskruchten  for your qiwk response.
Yes, I tried to put one of the high-cardinality attributes in the rows area and one in the columns area.In this case how should I proceed?
is there any way to add pagination ?

**Comment by nicolaskruchten** [comment]
This is not really a reasonable thing to do... Think about it: a 5000x5000 table is not something a human can read... If each cell was 1 pixel by 1 pixel, you would need a grid of 3x5 HDTVs to display this many pixels!
