### ISSUE TITLE
using filtered (by Pivottable) data later?

### ISSUE THREAD

**Issue by s9908** [nicolaskruchten/pivottable#603]
Is there any way to use filtered data later? For example, to load filtered by Pivottable data array to DataTables? I do not want load pivot to Datatable, only raw data (but after filtering in Pivottable).

I am loading data using Ajax to Pivottable. When user on page will apply some filters (in Pivottable), I want to get filtered raw data array and (for exapmle) load these data to DataTable (or something other).

I am loading data using Ajax to Pivottable. When user on page will apply some filters (in Pivottable), I want to get filtered raw data array and (for exapmle) load these data to DataTable (or something other).

```javascript
var pivot;
$.ajax(
{
    "dataType": 'json',
    "url": './ajax/data.php',
    "type": 'POST',
    "data":
    {               
    },
    "success": function(result)
    {               
        pivot = $("#pivot").pivotUI(
            result,
            {
                onRefresh: function()
                {

                    //!! NEED TO GET FILTERED ARRAY HERE

                }
            }
        );
    }
});
```

**Comment by nicolaskruchten** [comment]
It kind of sounds like you want to build your own [Renderer](../wiki/Renderers) based on DataTables... If you did this you would not use the `onRefresh` callback but rather your Renderer would be called directly with a `PivotData` object that you could interrogate to display data in any format you want.

**Comment by s9908** [comment]
Thank you!
Can I access to filtered data from renderer scope? I added to my pivotUI: 

 `renderers:
						{
							'test': testRenderer
						}`

and create a new Renderer function: 

`var rendererHtml = function(d)
	{        
		console.log(d);
    }`

In browser console I can see all data ("input" array). Need I filter data myself (in my renderer code), or can access to filtered data directly?

**Comment by nicolaskruchten** [comment]
The first argument to the Renderer is a `PivotData` object which has a `forEachMatchingRecord(criteria, callback)` function. If you wanted to, say, log all filtered data to the console, you could have a renderer that looks something like this, with empty `criteria`:

```javascript

var testRenderer = function(data){
  data.forEachMatchingRecord({}, function(record){ console.log(record); })
}
```

**Comment by s9908** [comment]
It working as I wanted:)
Thank you.

**Comment by nicolaskruchten** [comment]
Happy to help!
