### ISSUE TITLE
Multiple aggregators (aka multiple measures)

### ISSUE THREAD

**Issue by numjcp** [nicolaskruchten/pivottable#608]
Is it possible to display two different aggregators in the same pivot table ?
lets say sum aggregator and count.

**Comment by nicolaskruchten** [comment]
Unfortunately not. Please see [this FAQ entry](../wiki/Frequently-Asked-Questions#multi).

**Comment by MaySahu** [comment]
Hi Nicolas,
I was working on a Qlik sense custom extension that's built upon pivottable.js that you have created.But it limits us from adding multiple measures.
Could you please guide me what changes should i make so that i'll be able to achieve my desired output ?

**Comment by nicolaskruchten** [comment]
@MaySahu unfortunately this is not possible.
