### ISSUE TITLE
Custom value for pvtColumnTotal

### ISSUE THREAD

**Issue by shruthi-venkateswaran** [nicolaskruchten/pivottable#610]
I have some dummy sample data: 
[
  {"Item Description": "abcd", "Item": "1234", "Number": "495", "Description": "something", "Name": "ABC", "Factor": "0.6", "Price": "$0.132", "value": 1},
  {"Item Description": "xyz", "Item":"654","Number": "651", "Description": "something", "Name": "XYZ", "Factor":  "0.4", "Price": "$0.16", "value": 1},
  {"Item Description": "pqr", "Item":"345","Number": "651", "Description": "something", "Name": "PQR", "Factor":  "0", "Price": "$0.43", "value": 1},
  {"Item Description": "foo", "Item":"123","Number": "652", "Description": "something", "Name": "LMN", "Factor":  "1", "Price": "$0.66", "value": 1},
]

And this produces something like: 
<img width="433" alt="screen shot 2017-01-06 at 8 56 16 pm" src="https://cloud.githubusercontent.com/assets/5776700/21739556/a2bb4b56-d452-11e6-9ec4-c8fbcb9d1245.png">

Is it possible to have a custom function for the Total value of each column. Wherever there is a 1 in that column, sum of the value = Factor*Price is computed and added to the sum as total.

**Totals	0.66	0	0.064	0.0792**

**Comment by shruthi-venkateswaran** [comment]
This is my pivot table code as it is now:

$("#content").pivot(
    utils.tipsData, {
        rows: ["Number", "Description", "Name", "Factor", "Price"],
        cols: ["Items", "Item Description"],
        aggregator: sum(intFormat)(["value"]),
        rendererName: "Table"
});

I do want to display number "1" in the cells, but total shouldn't be a plain sum of 1s

**Comment by nicolaskruchten** [comment]
Yep! Check out the documentation for Aggregators: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators

**Comment by shruthi-venkateswaran** [comment]
Aggregators are for the calculation of the individual cells (which is just number 1 in this case), but to tweak the column total calculation also can we use aggregators ?

**Comment by nicolaskruchten** [comment]
Yes, aggregators are used to compute row, column, and grand totals as well. The aggregator is called with the `rowKey` and `colKey`. When the `rowKey` is `[]` the returned value is the column total etc. What you will need is an aggregator that behaves differently when one or both of `rowKey` or `colKey` is `[]`.

**Comment by nicolaskruchten** [comment]
Sorry, I should read my own documentation :) ... You're in a total cell when `rowKey` or `colKey` is `null`, not `[]`!

**Comment by shruthi-venkateswaran** [comment]
Thanks. Is there an example doing something similar, for a plain pivot table and not pivotUI ?

**Comment by shruthi-venkateswaran** [comment]
I wasn't able to do so with an aggregator. Not sure what I am missing.

**Comment by nicolaskruchten** [comment]
Can you show me what you tried?

**Comment by shruthi-venkateswaran** [comment]
Got it working. Thanks.

**Comment by nicolaskruchten** [comment]
Ah, sorry about that! I'll have to fix the documentation and learn to use my instincts more :)
