### ISSUE TITLE
Prepending Currency Symbol

### ISSUE THREAD

**Issue by ttremblay2** [nicolaskruchten/pivottable#611]
Hi Nicolas,

Thank you for the great library.

I have a quick question.

First of all, all the data fed to the pivot table is user selected, so I don't really know in advance what will be analyzed. At run-time, I do know all attributes and their type, including if an attribute is numeric and has a currency.

In a scenario where a numeric attribute is displayed and I know that it has a currency, how could I prepend the values displayed with the currency symbol?

Thanks.

Thierry

**Comment by nicolaskruchten** [comment]
Sorry for the long delay in responding! I can't think of an easy way to get what you want, unless you use custom aggregators with specific formatting functions...

**Comment by ttremblay2** [comment]
Hi Nicolas,

I ended up doing a post Process formatting routine to prepend the currency sign when needed:

$( this.m_htmlContainer ).find('.pvtVal:not(:empty), .pvtTotal:not(:empty), .pvtGrandTotal:not(:empty)').prepend( currentValField.currency );

Works fine for my needs

**Comment by nicolaskruchten** [comment]
super!
