### ISSUE TITLE
How to display data label differents than theirs grouping key?

### ISSUE THREAD

**Issue by shascoet** [nicolaskruchten/pivottable#616]
Hello,
First, great work, it helps a lot. I just miss a fonctionnality.

```
$("#registration-pivot").pivot(
    [
        { colorKey: 1, colorLabel: "blue", shape:"circle" },
        { colorKey: 2, colorLabel: "blue", shape: "circle" },
        { colorKey: 3, colorLabel: "yellow", shape: "circle" }
    ],
    {
        rows: ["colorLabel"],
        cols: ["shape"]
    }
);
```

With this example, I get two rows: `blue/2` and `yellow/1`
I'd like to group rows by `colorKey`, while displaying `colorLabel` to get resulting rows: `blue/1`, `blue/1` and `yellow/1`

Is there a way to to that ?
Thanks.

**Comment by nicolaskruchten** [comment]
You would have to add "colorKey" at the beginning of the "rows" array to get the grouping you want but there is no way to then hide that column from the output.

**Comment by shascoet** [comment]
Ok thank you. 
My "colorKey" is in fact a Guid ... so I wanted to hide it.
I'll try to generate some discriminent less visible like "blue (1)", "blue (2)" only when having duplicated colorLabel with differents colorKey.

Thanks.
