### ISSUE TITLE
Sorting issue.

### ISSUE THREAD

**Issue by ilyaguy** [nicolaskruchten/pivottable#617]
Natural sorting for numeric values works strange:
<img width="813" alt="2017-01-17 12 46 10" src="https://cloud.githubusercontent.com/assets/6704355/22017406/f4e30b0e-dcb2-11e6-8414-64415d619deb.png">

I think values should be in order `-6 -5 -4 -1 0 1 2 3 4`

**Comment by nicolaskruchten** [comment]
Yeah, this is a problem with the natural sort function, as the dash is read as a dash and not a minus.

**Comment by nicolaskruchten** [comment]
OK, PR #652 should address this. I'll likely merge it tomorrow (and then look at your PR :)

**Comment by nicolaskruchten** [comment]
Should be resolved in v2.9.0
