### ISSUE TITLE
Need some suggestions! About PIVOT JS crosstab/gridviews..

### ISSUE THREAD

**Issue by HannahJSwystun** [nicolaskruchten/pivottable#620]
hello :)

If I may, I would like first to hear your opinion on the matter : 

![unnamed](https://cloud.githubusercontent.com/assets/20491664/22397151/f4d9f9e8-e562-11e6-98df-d2886288f776.png)

I want to transform my samples / analyzes into a crosstable or gridview or something looks like , so that users can enter results, here is an example:

My questions are in the screenshot. thank you in advance.

**Comment by nicolaskruchten** [comment]
In answer to your Question 1... PivotTable.js is a Javascript library that runs in the browser so it knows nothing about tables and joins etc. If you have tables in a database that you want to join and display using this library, you will need to make the output of the join query available to a browser in a format like CSV or JSON via some server-side technology.

In answer to your Question 2: PivotTable.js is a display library only, so there is no mechanism for anyone to enter data into it, nor any mechanism for it to transmit data anywhere, it just takes input and displays it.
