### ISSUE TITLE
How to pass google datatable as input for pivotUI function?

### ISSUE THREAD

**Issue by ssriram30** [nicolaskruchten/pivottable#621]
its render functionality is awsome for google chart. your api support array of array,array of object and csv as input for drawing pivot chart. but i want to pass google datatable as input . what can i do?

**Comment by nicolaskruchten** [comment]
I'm not sure what a "google database" is... Can you explain?

In general, the answer is that you need to convert your data from whatever format it lives in to one of the supported formats you listed.

**Comment by ssriram30** [comment]
Hi, first if i draw Google chart i need data. That data passed in datatable
or datatable  in json format.

Sample json input which i want to pass:

{
  "cols": [
        {"id":"","label":"Topping","pattern":"","type":"string"},
        {"id":"","label":"Slices","pattern":"","type":"number"}
      ],
  "rows": [
        {"c":[{"v":"Mushrooms","f":null},{"v":3,"f":null}]},
        {"c":[{"v":"Onions","f":null},{"v":1,"f":null}]},
        {"c":[{"v":"Olives","f":null},{"v":1,"f":null}]},
        {"c":[{"v":"Zucchini","f":null},{"v":1,"f":null}]},
        {"c":[{"v":"Pepperoni","f":null},{"v":2,"f":null}]}
      ]
}

**Comment by nagarajanchinnasamy** [comment]
A roundabout way is to use `dataTableToCsv()` and convert CSV to JavaScript array using d3 or other libraries.

**Comment by nicolaskruchten** [comment]
Yeah, you will have to convert from this `cols`/`rows` object into one of the supported input formats yourself, before being able to use this type of data with this library.
