### ISSUE TITLE
suitability to allow 'consumers' to interact with data; 'platform independent' alternative to power pivot.

### ISSUE THREAD

**Issue by seanv507** [nicolaskruchten/pivottable#624]
Hi
I can't think of the right terms, but I think I have a general use case.

I am looking for a 'standalone tool' that I can use to present results to 'consumers' (ie no programming experience etc).  ie I want something that I give to a customer to allow him to 'play' with specific data.

## requirements:
1) portable/no installation process [ so I don't want them to install R/python etc. start a server etc]
2) permits more than a million rows (for source data) [tried with 1.6 million].

I believe the above two are handled already.

3) allows multiple pivots/tables to be made using the same data either on the same page or on a new tab ( ie so data doesn't need to be reloaded for each pivot table)
4) allows me (developer) to program my own 'measures', eg click through rate sum(clicks)/sum(impressions)

Does pivottable.js seem the right tool for this?  Libreoffice would be an alternative (but requiring users to have it/excel installed), however it can only support ~1 million rows.

Excel power pivot has the required functionality, but is not cross platform...

**Comment by nicolaskruchten** [comment]
Interesting.

1. should be pretty easy to host this centrally
2. this will likely not work on an entirely client-side basis, as this library starts to crawl around 100k rows, however in most cases you can pre-aggregate your millions of rows on the server and ship a smaller result to the client
3. you can definitely have multiple tables per page but they will not share the memory representation of the dataset: a copy will be made for each table.
4. this is supported via Aggregators: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators
