### ISSUE TITLE
Edit Inclusions Value

### ISSUE THREAD

**Issue by reksiars** [nicolaskruchten/pivottable#625]
When i pass a new parameter using Onclick button to this function, why the inclusions doesn't change ?

function DataPerAPKS(CBD) {
        var Utils = $.pivotUtilities;
        $("#Table_Output").pivotUI(
            Utils.tipsData, {
                "cols": [
                    "Brand Name"
                ],
                "rows": [
                    "CBD Code",
                    "Title"
                ],
                "aggregatorName": "Integer Sum",
                "vals": [
                    "QTY"
                ],
                "inclusions": {
                    "CBD Code": [CBD]
                }
            }
        );
    }

**Comment by nicolaskruchten** [comment]
Try setting the `overwrite` parameter to `true`: https://github.com/nicolaskruchten/pivottable/wiki/Parameters#pivotuiinput-options-overwrite-locale

**Comment by reksiars** [comment]
Thanks nicolaskruchten, i have been solved this problem with this code:

function DataPerAPKS(CBD) {
var Utils = $.pivotUtilities;
$("#Table_Output").pivotUI(
Utils.tipsData, {
"cols": [
"Brand Name"
],
"rows": [
"CBD Code",
"Title"
],
"aggregatorName": "Integer Sum",
"vals": [
"QTY"
],
"inclusions": {
"CBD Code": [CBD]
}
}, **_true_**
);
}

**Comment by nicolaskruchten** [comment]
Great!
