### ISSUE TITLE
how can i grow the charts.

### ISSUE THREAD

**Issue by Dougwfp** [nicolaskruchten/pivottable#627]
I need to get a bigger chart because i will put a great quantity values and this make the chart really confused.

**Comment by nicolaskruchten** [comment]
You can pass in the chart size using `rendererOptions` like in the example here: http://nicolas.kruchten.com/pivottable/examples/scatter.html

**Comment by Dougwfp** [comment]
![image](https://cloud.githubusercontent.com/assets/16749751/22692307/6e835d10-ed25-11e6-83cd-49c4379205dc.png)

**Comment by Dougwfp** [comment]
thank you!!
