### ISSUE TITLE
"Single-value" filter menu for multi-value cells

### ISSUE THREAD

**Issue by co-operate** [nicolaskruchten/pivottable#630]
Hi,

The cells in some of my table rows contain multiple values which are separated by a comma (e.g. "A, D, E"; "B, D"; "B"; "A, C";  ...). I want to modify the filter menu for these attributes (and preferably only for these attributes), so that users can filter for single values, e.g. for cells containing the value "A". 

I am sure this must be possible, and probably through `inclusions`. But I'm getting nowhere ...
Can someone nudge me in the right direction, please?

**Comment by nicolaskruchten** [comment]
The `inclusions`/`exclusions` mechanism is basically a whitelist/blacklist system to set/clear the checkboxes in the UI on an enumerated, per-value basis, there is no way to pass in a function there. The `filter` mechanism is more blunt: you can pass in a function but the data is fully hidden from the UI altogether.

Your best bet would be to dynamically-generate a list of inclusions.
