### ISSUE TITLE
Subtotal Column

### ISSUE THREAD

**Issue by ccarrioncl** [nicolaskruchten/pivottable#631]
Hi Nicolas, first of all, very thank you for share your plugin, very interesting, i have a question.

Its there any way to draw a sum in pivot table on columns?

like this picture?
![pivot](https://cloud.githubusercontent.com/assets/20032026/22746494/99999590-ee02-11e6-9f73-eb0b456513e5.png)

**Comment by nicolaskruchten** [comment]
Please see this FAQ answer: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#subtotals
