### ISSUE TITLE
Remove the Renderers and Aggregators dropdown.

### ISSUE THREAD

**Issue by nithishanf** [nicolaskruchten/pivottable#633]
Hi Nic,
I have a design issue.
In my requirement I only need Renderer as Table and Aggregators as Count always. So I would like to remove the dropdown renderer and aggregator. 
I tried adding this script on my page to remove renderers.
`$('table.pvtUi > tbody > tr').eq(0).children('td').eq(0).children('select.pvtRenderer').remove();`
But its not working.How can I achieve this. 
I am also planning a Clear All Filter button. So would like to introduce this button on the above space.

**Comment by nicolaskruchten** [comment]
You're best off hiding the dropdowns in CSS.
