### ISSUE TITLE
recover

### ISSUE THREAD

**Issue by djmcit** [nicolaskruchten/pivottable#636]
Recover column to html or PHP?

**Comment by nicolaskruchten** [comment]
Can you... elaborate?

**Comment by djmcit** [comment]
I am using the google translator,

Ask 2 questions but at the moment I found the answer and put it in the same
thread of the question and so I closed it.

Sorry for the disturbances.

2017-02-09 18:13 GMT-06:00 Nicolas Kruchten <notifications@github.com>:
