### ISSUE TITLE
default count is set for pivot() function. its different from pivotUI() and pivot()

### ISSUE THREAD

**Issue by ssriram30** [nicolaskruchten/pivottable#637]
am unable to load the customize option in pivot() funtion. it can applies only on pivotUI() function.

please refer for clarification https://jsfiddle.net/2ebayd6x/

**Comment by nicolaskruchten** [comment]
Yes, `pivot()` and `pivotUI()` accept different parameters, please check the documentation: https://github.com/nicolaskruchten/pivottable/wiki/Parameters
