### ISSUE TITLE
Negative values in Table BarChart renderer.

### ISSUE THREAD

**Issue by ilyaguy** [nicolaskruchten/pivottable#644]
Table Barchart renderer works incorrect with negative values.

**Comment by nicolaskruchten** [comment]
Indeed, this renderer only makes sense in the context of positive values....

**Comment by ilyaguy** [comment]
I have some ideas how to improver renderer to work with negative values too.
I'll prepare pull request.

**Comment by nicolaskruchten** [comment]
OK, great, looking forward to it!

**Comment by ilyaguy** [comment]
I added pull-request. Could you review it?

**Comment by nicolaskruchten** [comment]
Thanks for the PR! I'll take a look when I have some time, yes :)

**Comment by mwasiluk** [comment]
+1

**Comment by nicolaskruchten** [comment]
Fixed with v2.15.0!
