### ISSUE TITLE
onRefresh method is not clearing the old Data.

### ISSUE THREAD

**Issue by nithishanf** [nicolaskruchten/pivottable#647]
Hi,

Extension of #626 
Inorder to get the filtered values, I am using inclusions of onRefresh parameter. First time, I am applying filter on "Header A, Value A",  value A gets passed into a local variable and correspondingly data is EXPORTED TO EXCEL.
Next time, I am clearing the "Header A, Value A", and applying filter "Header B, Value B". This time also, it hits onRefresh, but I find both value A and value B getting passed in corresponding variables and hence my EXPORT EXCEL is giving wrong value.

Note: The applying filter is working fine with the PIVOT TABLE. In the PIVOT TABLE, correct data is pulled and displayed. Only when I pass the string variable, I am getting this issue. 

How to refresh "inclusions" every time I apply filter.Kindly Help. I am stuck terribly.

**Comment by nicolaskruchten** [comment]
You'll have to set the `override` parameter to `true`.
