### ISSUE TITLE
Trying to add rendererOptions using onRefresh and also want to include clickCallback function and pass it to a jQuery method

### ISSUE THREAD

**Issue by Sreelakshmigc** [nicolaskruchten/pivottable#648]
I am trying to add clickCallback to the pivot table I am drawing and pass and save the JSON for next use but I am seeing below errors, 
```
"rendererOptions": {
    "localeStrings": {
      "renderError": "An error occurred rendering the PivotTable results.",
      "computeError": "An error occurred computing the PivotTable results.",
      "uiRenderError": "An error occurred rendering the PivotTable UI.",
      "selectAll": "Select All",
      "selectNone": "Select None",
      "tooMany": "(too many to list)",
      "filterResults": "Filter values",
      "apply": "Apply",
      "cancel": "Cancel",
      "totals": "Totals",
      "vs": "vs",
      "by": "by"
    }
  }
```
This is the code I am using fyi,
```
$("#divID").pivotUI(input, {
                derivers:derivers,
                rendererOptions: { table: {
                        clickCallback: function(e, value, filters, pivotData){
                            var names = [];
                            pivotData.forEachMatchingRecord(filters,
                                function(record){ names.push(record.Variable); });
                            alert(names.join("\n"));
                        }
                    }
                },
                 onRefresh: function(config) {
                    var config_copy = JSON.parse(JSON.stringify(config));
                    jQuery(window).trigger('resize');//to show the widgets
                    //delete some values which are functions
//                    delete config_copy["aggregators"];
//                    delete config_copy["renderers"];
                    //delete some bulky default values
//                    delete config_copy["rendererOptions"];
                    delete config_copy["localeStrings"];
                    $("#widgetConfigDisplay").text(JSON.stringify(config_copy, undefined, 2));
                 },
                renderers: renderers
            });
```
Please help me solve this

**Comment by nicolaskruchten** [comment]
I'm going to need a bit more context here or an input sample or a JS Fiddle or something... There is not enough info here for me to help you :)

**Comment by Sreelakshmigc** [comment]
Hi Nicolas, Thank you for the super quick response. I am new here so having little trouble in explaining the problem I am facing. Below is the code I am using to draw a set of pivotWidgets. 

function showPivotWidget(URL,dataFormat,divId,options){
        
    var derivers = $.pivotUtilities.derivers;    
    options.renderer = getRenderer(options.rendererName);//This a common function to get the correct render for pivot js
    if (options.rendererName == 'Table With Subtotal'){
        options.dataClass = $.pivotUtilities.SubtotalPivotData;
    }
    if (options.hasOwnProperty('aggregatorName')){ //difference in the way params are done in pivotUI and pivot()
         options.aggregator = $.pivotUtilities.aggregators[options.aggregatorName](options.vals); //get the function
    }
        
    $.get(URL, function(mps) {
            var input;
            if (dataFormat == 'csv')
             input = $.csv.toArrays(mps);
           else{
               input =  jQuery.parseJSON(mps);
           }
           
		if (options.hasOwnProperty('exclusions') && !_.isEmpty(options.exclusions)){ //check if a exclusion filter exists
			
			input = pivotFilter(input,options.exclusions);
		}           
		//init pivot and show table/chart
		$("#"+divId).pivot(input, options);
      
   });

}

I want to use clickCallback in the above function, I am not able to understand the way rendererOptions needs to be managed and how to call table.clickCallback from here.

Final output I am looking at is to display the records on click of the widget table cell just like your example http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html

Thanks again

**Comment by nicolaskruchten** [comment]
Just like in the example, you add a key to your `options` object like this:

```
options["rendererOptions"] = { table: { clickCallback: function(..){..} } }
```

**Comment by Sreelakshmigc** [comment]
Thank you sooooo much Nicolas it worked. Thanks again for the quick response.

**Comment by nicolaskruchten** [comment]
Great!

**Comment by Sreelakshmigc** [comment]
Hi Nicolas, I need your help yet again. 

I am trying to do the same feature for c3 charts (bar, pie, line ...). 

On click of the charts, I want to see the pivot data exactly the same as we have done for tables. Can you please help me in achieving this. Its pretty critical. Thanks
