### ISSUE TITLE
i need to show strings in the values field...

### ISSUE THREAD

**Issue by nandha128** [nicolaskruchten/pivottable#650]
i have requirement to show the string values in the data fields.currnetly using 'aggerator' and 'vals' i am able to show  only count or max or sum `only.`

we are using aggregator/vals property in pivot table.we have devloped the coding by checking your blog but we have not got the desired results yet if we bind string values like name place to it .if we use aggerators its only show 'NULL' instead of corresponding value(i.e strings,  ) and if we use 'Vals' its showing 'COUNT' instead of actual values.please help us ..we want to display strings in those value fileds...please help us!....i know aggerator property of yours only accepts integer!...but i need to make your js to accept the string in the value field..

**Comment by nicolaskruchten** [comment]
Min and Max will accept strings, and you can use the "List unique values" aggregator to show more than one string value.

**Comment by nicolaskruchten** [comment]
Sorry, Min and Max will not accept strings, but First and Last will.

**Comment by Bsidey** [comment]
@nandha128 @nicolaskruchten 
I have the same requirement. Did you figure it out?
My code is below. I want to display "clname" in the grid.
I've been trying for a while but can't get it:

var mps = [{"avail_date":"2017-03-13","avail_time":"10:00:00","avail":1,"appointmentid":1,"managebac_id":10239301,"pname":"Florence","clname":"Mona Lot","clid":52}]    

            $("#output").pivot(mps, {
                rows: ["avail_date","avail_time"],
                cols: ["pname"],
                aggregatorName: "Last",
                vals: ["clname"],
                rendererName: "List Unique Values",
                rendererOptions: {
                    table: {
                        clickCallback: function(e, value, filters, pivotData){
                            var appId = [];
                            pivotData.forEachMatchingRecord(filters,
                                function(record){ appId.push(record.appointmentid, record.avail); });
                            alert(appId.join("\n"));
                        }
                    }
                }
            });

Where am I going wrong?

**Comment by nicolaskruchten** [comment]
@Bsidey you need to use `"Table"` and the `rendererName` and `"List Unique Values"` as the `aggregatorName`.

**Comment by Bsidey** [comment]
@nicolaskruchten Thanks for the reply Nicolas. I made the changes that you suggested but unfortunately the cells are still showing the "Count" result.

**Comment by nicolaskruchten** [comment]
Oh, I see, you're using `pivot()` and not `pivotUI()`. Please note that these two functions take different arguments! In this case you should not pass in `vals`, `aggregatorName`, or `rendererName` but just use `aggregator: $.pivotUtilities.aggregatorTemplates.listUnique()(["clname"])`.

The following code does work, I just tested it:

```javascript
var mps = [{"avail_date":"2017-03-13","avail_time":"10:00:00","avail":1,"appointmentid":1,"managebac_id":10239301,"pname":"Florence","clname":"Mona Lot","clid":52}]

$("#output").pivot(mps, {
  rows: ["avail_date","avail_time"], cols: ["pname"],
  aggregator: $.pivotUtilities.aggregatorTemplates.listUnique()(["clname"]),
  rendererOptions: {
    table: {
      clickCallback: function(e, value, filters, pivotData){
        var appId = [];
        pivotData.forEachMatchingRecord(filters,
                                        function(record){ appId.push(record.appointmentid, record.avail); });
        alert(appId.join("\n"));
      }
    }
  }
});
```

**Comment by Bsidey** [comment]
Champion! 
Many thanks Nicolas. Please regard my part of the ticket as awesomely closed.

**Comment by nicolaskruchten** [comment]
Happy to help!

**Comment by rajkumar73443** [comment]
how to show string value  use   pivotUI methode  in pivot table
