### ISSUE TITLE
Saving state from PivotUI and Loading into Pivot

### ISSUE THREAD

**Issue by fmmarmello** [nicolaskruchten/pivottable#653]
Hello folk, 
awesome work you've been doing!

Really saved my life.

So.. I'm already saving my state using "onRefresh" in PivotUI,
but what I need is to build the "created" tabled in Pivot(), so that the final user can't change it.

Pivot doesn't take same instructions, right?

Thanks in advance

**Comment by nicolaskruchten** [comment]
That's right, but it's not that hard to convert from one to the other: just look up the aggregator in the list of aggregators by name, and the same for renderers :)

**Comment by fmmarmello** [comment]
Humm.. Not quite sure how to do that.
But thanks :smile: !

I'll try it!

**Comment by fmmarmello** [comment]
So..

I have this option json

{ "derivedAttributes": {}, "hiddenAttributes": [], "menuLimit": 500, "cols": [ "densidade_de_moradores_por_comodo", "existencia_de_servicos_e_bens_duraveis" ], "rows": [ "ug" ], "vals": [ "v" ], "exclusions": {}, "inclusions": {}, "unusedAttrsVertical": 85, "autoSortUnusedAttrs": false, "sorters": {}, "rendererName": "Tabela Imputável", "aggregatorName": "Sum", "inclusionsInfo": {} }

It's a PivotUI pattern.
When I use it in pivot, the table renders almost correctly, but the aggregator is "count" I need "sum" to be the default.

**Comment by fmmarmello** [comment]
Just done it!
Thanks to that!
http://nicolas.kruchten.com/pivottable/examples/simple_agg.html

Thanks!

**Comment by nicolaskruchten** [comment]
Great!

**Comment by frankernesto87** [comment]
Hi again nicolas!!
I'm facing a new problem with save and load state from pivotui , I'm saving pivot conf to DB, but when I try to restore it I'm getting this:
 "pivot.coffee:932 Uncaught TypeError: D.aggregators[u.val(...)] is not a function
    at pivot.coffee:932 (anonymous) @ pivot.coffee:932". 
My conf loads unused fields and rows , but is not able to load the data table, renderers and aggregators. For some reason I could 't upload an image but I sended it by email for yo to hace a clear vision


 any help??
regards Frank

**Comment by nicolaskruchten** [comment]
@frankernesto87 please do not comment on old, closed issues... rather create new ones.
