### ISSUE TITLE
How to update pivotui's parameter when triggering event

### ISSUE THREAD

**Issue by chuducty** [nicolaskruchten/pivottable#654]
I want to do something like. the current renderer is standard renders, and when i click a button, it will add the c3_renderers. I tried to do it, however the UI is not refreshing
`
$(function(){
        
        var model = {
          derivers: $.pivotUtilities.derivers,
          renderers : $.pivotUtilities.renderers

        }
        var init = function(){
          $("#output").html('');
          $.getJSON("mps.json", function(mps) {
              $("#output").pivotUI(mps, {
                  renderers: model.renderers

              });
          });

          }

        init();

        $('#btn').click(function(){
          $.extend(model.renderers, $.pivotUtilities.c3_renderers)
          console.log(renderers);
          init();
        })
     });

`

**Comment by nicolaskruchten** [comment]
Try the `overwrite` parameter: https://github.com/nicolaskruchten/pivottable/wiki/Parameters#pivotuiinput-options-overwrite-locale

**Comment by chuducty** [comment]
It is still not working. I'm not sure if i'm doing something wrong
`
var model = {
          derivers: $.pivotUtilities.derivers,
          renderers : $.pivotUtilities.renderers

        }
        var init = function(){
          //$("#output").html('');
          $.getJSON("mps.json", function(mps) {

              $("#output").pivotUI(mps, {
                  renderers: model.renderers

              }, true);

          });


          }

        init();

        $('#btn').click(function(){
          //$.extend(model.renderers, $.pivotUtilities.c3_renderers)
          model.renderers = $.pivotUtilities.c3_renderers;
          console.log(model.renderers);
          //init();
        })
`

**Comment by chuducty** [comment]
Fortunately, I have been able to do it. In addition to using the overwrite parameter ,you need to still call the init() on the click event.
Thank you for the great help

**Comment by nicolaskruchten** [comment]
Great!
