### ISSUE TITLE
Reset values in Ajax based result in pivottable

### ISSUE THREAD

**Issue by vinairaj** [nicolaskruchten/pivottable#656]
Hi,

I faced a problem when loads saved data.
here I give the steps exactly what i am doing.

1. I load data from database and show in the pivot tables
2. i call a json service after selecting  a drop box  value. if the result was null in that it shows blank table.
then I select another value from drop box . this service i will get the result but it stills shows blank table.

how to reset the value according to ajax call.

**Comment by nicolaskruchten** [comment]
I'm not really clear on what you're trying to do here... can you provide a bit more detail please?
