### ISSUE TITLE
How to present 2 aggregator values

### ISSUE THREAD

**Issue by nishanth919** [nicolaskruchten/pivottable#657]
Hi Guys, 

Can you guys please help me, below is my requirement screen shot. 

![image](https://cloud.githubusercontent.com/assets/20475727/23845239/f4d0030a-07ec-11e7-8920-b6535806ddf6.png)

I am not able to get two aggregators values. Below is my code.
`$("#pivotchartss").pivot(
					utils.tipsData,
					{
						rows : [ "Rule Name" ],
						cols : [ "Prod Name" ],
						aggregator : sum(intFormat)([ "Value", "Percentage" ]),
						rendererOptions : {
							table : {
								clickCallback : function(e, value, filters,
										pivotData) {
									var names = [];
									pivotData.forEachMatchingRecord(filters,
											function(record) {
												names.push(filters);
											});
								}
							}
						}
					});
		});`

My JSON
`$.pivotUtilities.tipsData = [ {
			"Rule Name" : "Production Qty",
			"Prod Name" : "PVC Pipe",
			"Value" : 2316,
			"Percentage" : 7.1
		}, {
			"Rule Name" : "Production Qty",
			"Prod Name" : "PVC Frame",
			"Value" : 29450,
			"Percentage" : 90.32
		}, {
			"Rule Name" : "Production Qty",
			"Prod Name" : "PVC Roof",
			"Value" : 840,
			"Percentage" : 2.58
		}, {
			"Rule Name" : "Machine Hours",
			"Prod Name" : "PVC Pipe",
			"Value" : 1791.75,
			"Percentage" : 49.65
		}];`

**Comment by nicolaskruchten** [comment]
Unfortunately, it is not possible to use 2 aggregators at the same time like this: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi

**Comment by nishanth919** [comment]
Hey Nicolas,

I did some work around and able to achieve to that output by modifying JSON.
Thanks for your response.
