### ISSUE TITLE
Conditional formatting?

### ISSUE THREAD

**Issue by Bsidey** [nicolaskruchten/pivottable#659]
Hi Nicolas
Are there any examples that explain how to set background colours of result cells based on data values?
(quasi code: if(a==true && b==false) {set.background-color:"red";}
I have tried playing with renderer options for heatmap but I'm "stabbing in the dark" and don't know how to upskill myself here.
Best regards and kudos on this great tool.
Brendon

**Comment by nicolaskruchten** [comment]
Glad you like the library!

Unfortunately there are no features built-in for this kind of conditional formatting. To get this kind of thing you would have to copy and modify the heatmap function more extensively than just playing with the options (which only allow you to modify the colour scale, not change the colour logic).

At a high level, what the heatmap function does is it iterates through the table cells using jQuery and adds formatting based on the relative values of the cells. What you're looking for is actually simpler, as it's cell-by-cell. 

The basic code you need is something like this, if you're writing the pivot table to a div with id `output`... you just find all the `td` tags with class `.pvtVal` and then change their format based on their contents:

```javascript
$("#output").find(".pvtVal").each(
    function(){ 
        if($(this).data("value") > 10) { 
            $(this).css("background-color", "red"); 
        } 
    }
)
```

**Comment by Bsidey** [comment]
Perfect. Thanks again.
