### ISSUE TITLE
pie charts

### ISSUE THREAD

**Issue by tgabrielle** [nicolaskruchten/pivottable#66]
i can't seem to get the Gchart pie chart to work. When I try to chose, via GChart, the pie chart, it says 'the required data format for the Pie chart doesn't match the current data'. but I think I have aligned my data correctly because a stacked bar works fine and thus so should the pie. any ideas?
![pie not working](https://f.cloud.github.com/assets/5801444/1541053/b8a10afa-4d2d-11e3-9929-127d728f50af.JPG)

**Comment by nicolaskruchten** [comment]
Pie charts are now built in to the Plotly renderers :)
