### ISSUE TITLE
Filter Limitations Remove

### ISSUE THREAD

**Issue by SethuICOMM** [nicolaskruchten/pivottable#662]
HI,

we are testing the pivot table with our requirement and met all the cases but i want to know how to remove the filter if records (employee id) goes to 14000. That time if i click the column filter system says "Filter Limitations"

# 2 I want to change the Row & Column field caption ?

Could you please guide me how to overcome this?

**Comment by nicolaskruchten** [comment]
I'm not sure I understand what you're asking here... Can you elaborate please?

**Comment by nicolaskruchten** [comment]
This is much clearer, thanks!

For question 1: you can use the `menuLimit` option to show more items in the filter dropdowns, but this will slow down performance of the initial render.

For question 2: there is no feature for this but it can be emulated like this: http://nicolas.kruchten.com/pivottable/examples/mps_rename.html
