### ISSUE TITLE
Add a "" (null) string value in exclusions always.

### ISSUE THREAD

**Issue by nithishanf** [nicolaskruchten/pivottable#663]
My Data has null values in almost every column. The PivotUI is considering them also in Filter Options. So I have overwrote the code to exclude ""(null) values from being seen in Filter Options.

Now when I apply filter, in the filter results, it is giving results without excluding the "" entries . I think since these "" values remain checkbox checked,it is not getting added to exclusions field.And hence always remain checked.

How can I add "" values for any objects by default in exclusions.
something like `opts.exclusions[attrValues][attr].push("")` . But I am not able to use it properly and donot understand where to place this code. I am newbie to coffeescript debugging

**Comment by nicolaskruchten** [comment]
Sorry to reply so late... Are you still seeking assistance with this issue?

**Comment by ravinsinghd** [comment]
@nicolaskruchten we are also seeking the same option. if we can exclude the null values globally it will be very helpful

**Comment by nicolaskruchten** [comment]
There is no way to force this as a default, but of course you can use the normal exclusions mechanism as shown above. I'm not sure what kinds of problems were encountered there.
