### ISSUE TITLE
How to configure pivot in AngularJS to sum by default

### ISSUE THREAD

**Issue by oztallguy** [nicolaskruchten/pivottable#665]
Am new to pivot.js and have read many posts on how to do a basic sum, but I am clearly doing something wrong when combining it with AngularJS 1.4.  Have integrated with https://github.com/ErickRuano/angular-pivot and here is the code:

		$scope.pivotoptions = {
			    rows: ["CREV Category"],
			    cols: ["Account Type"],
			    aggregator: jQuery.pivotUtilities.aggregatorTemplates.sum()(["Quota"]),
			    vals: ["Quota"],
                hiddenAttributes: ["CREV_CTGY_ID","ACCT_TYPE_ID"]
        };

jQuery and JQueryUI are loaded prior to AngularJS.  Invoking JQuery under AngularJS in the manner above works elsewhere in the application.
The current result is a display that counts the records.  Am hoping for help to sum by Quota.
Thanks in advance!

**Comment by nicolaskruchten** [comment]
Sorry to get back to you so late... Are you still seeking assistance with this?

**Comment by oztallguy** [comment]
No thanks I figured it out

Regards
Andrew Baines
