### ISSUE TITLE
Totals calculation

### ISSUE THREAD

**Issue by Tombeniusis** [nicolaskruchten/pivottable#666]
Is there a way to cahnge how Total are calculated?
For example a Box costs 100 EUR. When I display the box with some joint elements (lets say 2) Total sum becomes 200 EUR. How do I make Total calculation by certain onbejct?
Poor visualisation:

|Thing | Parts | Totals |
|BOX--  | Part1 | 100    |
|-------| Part2 | 100    | 
|--------Totals | 200    |

I'd like my totals to be 100.

**Comment by nicolaskruchten** [comment]
You'll have to define a custom [Aggregator](../wiki/Aggregators) for that...

**Comment by Tombeniusis** [comment]
Aha. I read this example http://nicolas.kruchten.com/pivottable/examples/mps_agg.html and wanted to ask additionaly. In the example you pass a parameter like this return tpl.average()(["Age"]). How do I make so I can chose the parameter from my data (dropdown, like ussual)?

**Comment by Tombeniusis** [comment]
So I just wrote an aggregator straight into the plugin. If anyone needs one, it looks like this: 

sumUnique: function(formatter) {
        if (formatter == null) {
          formatter = usFmt;
        }
        return function(arg) {
          var attr, uniq;
          attr = arg[0], uniq = arg[1];
          return function(data, rowKey, colKey) {
            return {
              sum: 0, 
              uniqList: [],
              push: function(record) {
              	var ref = record[uniq];
                if (indexOf.call(this.uniqList, ref) < 0 && ref != undefined) 
                {
                  this.uniqList.push(record[uniq]);
                  return this.sum += parseFloat(record[attr]);
                }
              },
              value: function() {
                return this.sum;
              },
              format: formatter,
              numInputs: (attr != null) && (uniq != null) ? 0 : 2
            };
          };
        };
      }
