### ISSUE TITLE
On click of the c3 charts, I want to see the pivot data exactly the same way a clickCallback function works

### ISSUE THREAD

**Issue by Sreelakshmigc** [nicolaskruchten/pivottable#668]
On click of the c3 charts, I want to see the pivot data exactly the same way as we have done for tables. Can you please help me in achieving this. Its pretty critical. Thanks

FYI #648

@nicolaskruchten

**Comment by nicolaskruchten** [comment]
This is a good idea but I don't have time to implement it at the moment. You may be able to accomplish this by modifying `c3_renderers.coffee` but I'm afraid I can't help you with this in the next little while...

**Comment by Sreelakshmigc** [comment]
Thank you Nicolas. Will check if something can be done.

**Comment by adrianomr** [comment]
I am working with js and i could work around this by placing changing the data config into "c3_renders.js". The edited code is here:

 data: {
            type: chartOpts.type,
            order: null,
			onclick: function(e) { alert(e.value); }
          }
