### ISSUE TITLE
Record Filtering

### ISSUE THREAD

**Issue by salmancreations** [nicolaskruchten/pivottable#669]
Is it possible that if Apply filter button is clicked then it effect all other filters and empty filters should not be visible?. Please see snapshot attached to understand what i exactly mean. In simple words, the filter column should be refreshed each time a filter is applied.
![pivotjs](https://cloud.githubusercontent.com/assets/10696759/24351207/219e438a-12e5-11e7-8b96-aa277a7df277.png)

**Comment by nicolaskruchten** [comment]
I'm not really sure what you're asking for here... can you elaborate please?

**Comment by salmancreations** [comment]
Hi Nicolas, first of all thank you for your reply. Please see snapshot above. If i click apply button then it should effect the main items on left. See arrow towards "client, Durability test, External references" etc. If for example you click apply then items on the left should be refreshed and items with empty values should not be visible. I hope it is clear. Waiting for your reply.

**Comment by nicolaskruchten** [comment]
Ah I understand now.

The idea behind the attribute bubbles is that there is always one per attribute in the dataset. I'm not in favour of changing the current behaviour, as would make the UI more confusing if things kept appearing and disappearing. If a user were to see a preconfigured pivot table and then they changed the filters, new attribute bubbles would seemingly-arbitrarily appear...
