### ISSUE TITLE
Exclusions not working for a saved widgetConfig and calling pivot() to show the same. But works when onRefresh is used while creating the same

### ISSUE THREAD

**Issue by Sreelakshmigc** [nicolaskruchten/pivottable#671]
Hi @nicolaskruchten 
I am using onRefresh to get the pivot data which has some exclusions working fine when I am creating the widget and then I save the same. Below is the widgetConfig of a saved widget. 
`"widgetConfig": {
    "derivedAttributes": [],
    "aggregators": [],
    "renderers": [],
    "hiddenAttributes": [],
    "menuLimit": 500,
    "cols": [],
    "rows": [
      "InvoiceNumber",
      "Amount",
      "AmountReceivedAtStore",
      "AmountToBeCollected",
      "PartialAmountCollected"
    ],
    "vals": [
      "AmountToBeCollected"
    ],
    "exclusions": {
      "PaymentType": [
        "Prepaid"
      ]
    },
    "inclusions": {
      "PaymentType": [
        "ODP"
      ]
    },
    "unusedAttrsVertical": 85,
    "autoSortUnusedAttrs": false,
    "derivers": [],
    "inclusionsInfo": {
      "PaymentType": [
        "COD",
        "ODP"
      ]
    },
    "aggregatorName": "Sum",
    "rendererName": "Table"
  }`

I am trying to load the same widget again using pivot(input, options), and I am not seeing any exclusions applied on the pivot table. 

Below are the snapshots of same widget for both working and not working scenarios.
![exclusionissueworkingsnapshot](https://cloud.githubusercontent.com/assets/6168602/24400124/e4725de6-13cc-11e7-9f9d-3787ce7feb29.png) Working
![exclusionissuenotworkingsnapshot](https://cloud.githubusercontent.com/assets/6168602/24400140/f1ecf382-13cc-11e7-9f2e-1246b03e8c62.png) Not Working

 This is very critical, I am not aware if I am making any mistake here. Please help.

Thanks in advance.

**Comment by nicolaskruchten** [comment]
If you check the [documentation for `pivot()`](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) you will see that it does not accept the same parameters as `pivotUI()`... specifically, it does not accept `exclusions` or `inclusions` but rather just a `filter` function parameter. Under the hood, `pivotUI()` uses the `exclusions` to build a `filter` function, you can see the code here: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L979

PS: just to be clear, noting that something is "very critical" for you comes across as quite demanding on my time, which I provide freely to support this library, and doesn't really serve to accelerate my responses...

**Comment by Sreelakshmigc** [comment]
Thank you for the quick response. This is a great library and I respect the amount of efforts you have put in. Noted your points and respect them. Thanks again

**Comment by PixelatedFigure** [comment]
Can I see an example of using such a filter? I have the same problem and I have no idea how to use the filter function

**Comment by nicolaskruchten** [comment]
@PixelatedFigure please create a new issue describing your problem and I'll try to help.
