### ISSUE TITLE
 propert vals pivotui

### ISSUE THREAD

**Issue by luanaanalist** [nicolaskruchten/pivottable#672]
Is there any way to insert more than one column of different value into this property? Usually when I put the tool does not fit or add everything. How to fix this problem?

**Comment by nicolaskruchten** [comment]
I'm having trouble understanding what you're looking for here... can you elaborate please?

**Comment by luanaanalist** [comment]
I wanted to know there is a possibility of having more than one column of values ​​that add up inside a table.
Today when I insert another column in the waltz, the n plugin creates another column for it. for example:
$("#Report-body").pivotUI(
                json, {
                    rows: ["day"],
                    cols: ["Type", "unit"],
                    aggregatorName: "Sum",
                    vals: ["Valor", "amount"],
                    rendererName: "Table",
                },
            );

**Comment by nicolaskruchten** [comment]
OK, I understand. This is not possible, no... Here is the FAQ entry: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi
