### ISSUE TITLE
Asking about implementation of attribute filtering in PivotUI

### ISSUE THREAD

**Issue by chuducty** [nicolaskruchten/pivottable#679]
I'm implementing the custom UI, which will call pivot() to render table when users give some input ( drag, drop, etc).
I want to know how to implement the attribute filter function in the PivotUI.
I think the answer is to use the parameter 'filter' in the pivot(). However, how can I know the domain/ range of each attribute from the data set.

Thank you for helping

**Comment by nicolaskruchten** [comment]
I'm afraid I don't understand what you're trying to do here, can you clarify please?

**Comment by chuducty** [comment]
I think I will try to do it in different way. Thank you very much for helping.
