### ISSUE TITLE
How to override nested data array to pivot table

### ISSUE THREAD

**Issue by nyobeentanglaud** [nicolaskruchten/pivottable#683]
// normal data [ { "Kode Observer":"1001", "Nama Surveyor":"Dina", "Status Survey":"new", "No. TPS":"TPS 38", "Kota// normal data
[

    {
        "Kode Observer":"1001",
        "Nama Surveyor":"Dina",
        "Status Survey":"new",
        "No. TPS":"TPS 38",
        "Kotamadya":"Jakarta Barat",
        "Kecamatan":"Cengkareng",
        "Kelurahan":"Cengkareng Barat",
        "Suara1":"1",
        "Suara2":"2",
        "Suara Sah":"3",
        "Suara Tidak Sah":"4",
        "Total DPT":"5",
        "Cordinate":"0, 0",
        "Tanggal Input":"2017-04-05 07:15:47"
    },
]

// data what i want
[

    {
        "Kode Observer":"1001",
        "Nama Surveyor":"Dina",
        "Status Survey":"new",
        "No. TPS":"TPS 38",
        "Kotamadya":"Jakarta Barat",
        "Kecamatan":"Cengkareng",
        "Kelurahan":"Cengkareng Barat",
        "Suara Calon":[
            {
                "Suara1":"1",
                "Suara2":"2"
            }
        ],
        "Suara Sah":"3",
        "Suara Tidak Sah":"4",
        "Total DPT":"5",
        "Cordinate":"0, 0",
        "Tanggal Input":"2017-04-05 07:15:47"
    },
    
]

can i make attribute in derivedAttributes function when i drag it, it show atribute like in "normal attribute"..??

**Comment by nicolaskruchten** [comment]
I'm not sure I understand what you're trying to do here... This library doesn't convert from one JSON representation to another.
