### ISSUE TITLE
Multiple Aggregator

### ISSUE THREAD

**Issue by SAMJN** [nicolaskruchten/pivottable#684]
Hi nicolaskruchten, this issue is related to Multiple aggregator - displaying sum/ average/ mean.....
against to entries as we can do in MS-Excel. Now this issue has been reported in #30  and #73 . But still I wanted to ask if you plan to add multiple aggregator. i tried to change parameters in Sum Over Sum, as it takes different aggregators. But as currently aggregators return only single value and not an array, Multiple aggregator is not possible. Could you help me further

**Comment by nicolaskruchten** [comment]
Implementing multiple aggregators is a major UI challenge and I don't have the time at the moment to envision when it could be done. Basically, multiple aggregators are not on the roadmap for this project.

**Comment by SAMJN** [comment]
Could you guide me whether my thinking is right or not? I will have to make changes in PivotData functions, custom aggregator, custom renderer and some in PivotUI() and Pivot().
The changes done by others involves hard coded parameters(Vals, Cols, Rows), whereas I am passing dynamic parameters (when a user change the fields, chart should again render).

**Comment by nicolaskruchten** [comment]
Yes, you will have to change pretty much every part of the system to
accommodate this feature :)

**Comment by SAMJN** [comment]
Thanks for the help. I will let you know if I touch a breakthrough.

**Comment by gzsombor** [comment]
@SAMJN : Have you been able to achieve success? I would like to have something similar ...

**Comment by SAMJN** [comment]
I tried changing function, but due to shortage of time, I didn't got any success. I am planning to work on it, and will post here as soon as I get any success.

**Comment by SAMJN** [comment]
Hi,

I have developed a solution to existing library for Multi-metric and support of Group total charts too. I will upload my solution by end of first week of December 17. Will provide the link for that too

**Comment by SAMJN** [comment]
Hi All,

[https://github.com/SAMJN/PivotTableMultiMetric]. In the file pivot.js attached in this repository, you can refer for multiple metrics support of Pivot Table. Kindly start watching the repository, I will update the library with my work of heatmap and subtotals soon.

**Comment by SuleymanS** [comment]
Nice job SAMJN. congratulations.

but I need my 3 total columns. Is this possible ?

**Comment by SAMJN** [comment]
Hi @SuleymanS , are you asking about creating separate total columns for separate metrics? I guess currently, I have provided one total column, displaying individual totals.

**Comment by pranjal-goswami** [comment]
Hi!
I have attempted to write a plugin for adding multiple aggregations on different fields and have published them here: https://github.com/pranjal-goswami/multifact-pivottable

![Multifact-pivottable](http://pranjalgoswami.in/multifact-pivottable/examples/images/multifact-pivottable-2-min.png)

Using this plugin you can : 

- Add multiple aggregations to the same pivottable: AVG(Column A), SUM(Column B)
- Add derived aggregations :
-- a = AVG(Column A)
-- b = SUM(Column B)
-- [c = b/a] as 'Success Score'

- Hide an aggregate (in case you want to use the value in derived aggregate but not show it)
- Hide an aggregate from row-totals section
- Enhance rendering of aggregations using heatmap or barchart
- Custom heatmap colors for each aggregation

A demo is available here: http://pranjalgoswami.in/multifact-pivottable/examples/

Will add detailed documentation if people find the plugin useful.

**Comment by abhikvnair** [comment]
Thank You............
It is absolutely wonderful plugin for PivotTable.js.
Please upload detailed documentation.

**Comment by abhikvnair** [comment]
While using locale error showing.Please update lib with example of locale

**Comment by prnshamahrjn** [comment]
Could there be multiple pvtTable within single initialization?

**Comment by BBBhatt** [comment]
just want to format numbers without decimal places..
what options should i Use with it?

-Thanks,
Bhavin.
