### ISSUE TITLE
Array.prototype causes issues in display format

### ISSUE THREAD

**Issue by niciliketo** [nicolaskruchten/pivottable#685]
This is a great piece of software.

I am experiencing a problem integrating it with my existing code because I use `Array.prototype` to define a new method on Arrays. This seems to interfere with how the pivot table is rendered and my function ends up in the headers.

Here is an example - https://jsfiddle.net/v3pnn8c5/

**Comment by nicolaskruchten** [comment]
Glad you like the library!

Maybe the hiddenAttributes parameter can help here...

**Comment by niciliketo** [comment]
Hi @nicolaskruchten . Thank you very much for your quick feedback.
I have spent some time trying to use hiddenAttributes to prevent this from showing up, but I have not yet had success.  It does not appear to have any effect on `pivot` and whilst it will hide other attributes on `pivotUI` I cannot find a correct way to hide the extra function. I will continue to look at this, but any further tips would be greatly appreciated.

**Comment by niciliketo** [comment]
Apologies, I have found an answer to my question in the SO answer. It seems the problem was with our existing code (unrelated to this pivottable js).

I changed the other code from:

`````
Array.prototype.last = function() {
	return this[this.length-1];
  }
`````
to
`````
Object.defineProperty(Array.prototype, 'last', {
    enumerable: false,
    value: function() {
	return this[this.length-1];  }
});
`````

Thanks again for such a useful piece of software.
