### ISSUE TITLE
does't work build with webpack

### ISSUE THREAD

**Issue by gongph** [nicolaskruchten/pivottable#686]
Hi, @nagarajanchinnasamy  @nicolaskruchten @brendtumi  ,  I had a problem when using it in webpack + vue + es6.  This my code:

As a module:
```js
function init ( selector ) {
	var dataClass = $.pivotUtilities.SubtotalPivotData;
        var renderers = $.pivotUtilities.subtotal_renderers;
	$.getJSON("../data/mps.json", function ( mps ){
		$( selector ).pivotUI( mps, {
			dataClass: dataClass,
            rows: ["Gender", "Province"],
            cols: ["Party", "Age"],
            renderer: renderers,
            rendererName: "Table With Subtotal"
		})
	})
}

module.exports = {
	init
}
```

Use in Vue components
```html
<script>
	import { init } from "./utils/utils.js"

	export default {
		created () {
			// init pivottable data
			init(".render-pivottable")
		}
	}
</script>
```

When the page is rendered， there are no icons(▶) ，i don't know what's wrong. Help!

**Comment by gongph** [comment]
However, the same code can be used in the browser.

**Comment by gongph** [comment]
Problem solved!

**Comment by frosich61** [comment]
Cancelar
Atentamente,

Frank Rosich

**Comment by ibmsoft** [comment]
@gongph
would you like share your step more detail
i just get the following error

TypeError: this.find(...).sortable is not a function
