### ISSUE TITLE
pivot table output data

### ISSUE THREAD

**Issue by habibiitdu** [nicolaskruchten/pivottable#687]
Hi nicolas,
Hope you are doing well! 

I wanna get the output data from pivot table on which the visual representation (table, bar chart etc.) is generated. How's that possible. 

Thanks in advance.

**Comment by nicolaskruchten** [comment]
Can you elaborate please? I'm not sure I understand what you're looking
for...

**Comment by habibiitdu** [comment]
Well, let me explain. 
we provide some data objects of columns and rows to pivot table to generate different types of representations like table, bar chart etc. 

Based on the provided row and column objects, pivot table calculate and render required table etc. 
my query is to get the data objects which is used to generate the table DOM. 

If I still clouldn't make you understand. please let me know. I'll try to sketch and give you a pictorial description.

**Comment by nicolaskruchten** [comment]
What do you want to do with this intermediate data object? It is passed into the Renderer layer so you can access it by writing your own Renderer: https://github.com/nicolaskruchten/pivottable/wiki/Renderers

**Comment by habibiitdu** [comment]
Actually I need to write the table in a PDF. So, I just wanna know the data format so that I can write the table somehow in the pdf. 

Btw, Thanks for your cooperation.

**Comment by nicolaskruchten** [comment]
Your best bet will be to write a renderer in this case.
