### ISSUE TITLE
Extra Header cells with code...

### ISSUE THREAD

**Issue by Rnhatch** [nicolaskruchten/pivottable#688]
I'm using pivotUI to display data coming from an array of objects.  I am getting a duplicated cell in the header for every axis header.  This cell always has the text "function (d){d=this.indexOf(d);-1!=d&&this.splice(d,1);return this}".  Its either a full repeated TR row in column headers,  or a repeated TH cell in the row headers.  

See image below. 

![screen shot 2017-04-17 at 9 09 15 am](https://cloud.githubusercontent.com/assets/630577/25089793/bd0b7eaa-234d-11e7-9125-c6c2e7801876.png)
 
Below is the guts of my pivot calling code: 
```

        $("#output").pivotUI(myData,
            {
                rows: ["Team","Employee"],
                cols: ["Work_Reporting_Category__c"],
                vals: ["Hours__c"],
                aggregatorName: "Sum",
                rendererName: "Table",
                hiddenAttributes: ["__proto__","Attributes","Id","Id15","__skuid_record__","Employee__r","Epic__r","Employee__c","Epic__c"],
                unusedAttrsVertical: false
            }
        );

```
Where the "myData" variable is the array of objects being provided from my data source.  Here is a representative object in the array: 

![screen shot 2017-04-17 at 9 14 08 am](https://cloud.githubusercontent.com/assets/630577/25089899/5039dbd6-234e-11e7-8309-6feb8f6f69a7.png)

Any thoughts?

**Comment by nullv01d** [comment]
Hi @nicolaskruchten,

I am facing the same problem, even when the data is empty:

![image](https://cloud.githubusercontent.com/assets/6281634/25172683/6e50c568-250f-11e7-80e8-3e8826a9beec.png)
![image](https://cloud.githubusercontent.com/assets/6281634/25172704/782fc93a-250f-11e7-980f-03d5b1f52afa.png)

Sample code:

```javascript
$scope.pivotData = [];

$scope.pivotConfig = {
    rows: ["Name"],
    cols: ["ProductID"],
    renderer: $.pivotUtilities.renderers["Table"]
};

$("#container").pivot($scope.pivotData, $scope.pivotConfig);
```

Could you please help?

**Comment by nullv01d** [comment]
I think I found the problem, I was adding custom functions to `Array.prototype`, which in turn is making them show up on the table.

@Rnhatch check if you're doing anything similar.

**Comment by Rnhatch** [comment]
Yes indeed.  My system was adding a custom function.  However I had excluded that attribute of the object in the configuration (added to the hiddenAttributes configuration).  So I'm surprised that its still being evaluated in some way...
