### ISSUE TITLE
How to set localeStrings ?

### ISSUE THREAD

**Issue by subo-romens** [nicolaskruchten/pivottable#690]
https://jsfiddle.net/kn381h7s/873/        I want to change totals text  but not working  please  help me

**Comment by daine** [comment]
Hi there, I had the same question as you. I was able to change the "Totals" text by setting the localeStrings inside the rendererOptions.

```javascript
rendererOptions:{
    localeStrings: {
        totals: "Totaleseee",
    }
}
```

I've updated your jsfiddle to reflect the change I made to make it work:
https://jsfiddle.net/kn381h7s/905/

**Comment by subo-romens** [comment]
Thank You
