### ISSUE TITLE
c3 rounding values with negative values

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolaskruchten/pivottable#692]
Revising some "old" `stackoverflow`  questions on `rpivotTable` I found an odd one [here ](http://stackoverflow.com/questions/38799996/r-rpivottable-bug-the-value-on-the-table-is-not-the-same-with-the-value-on-ba).

As it is possible to see from the example on `SO`, c3 `bar chart` rounds the negative numbers, and only those.

I just tested it with `pivottable` 2.11.0 and the behaviour is still there. Is this intended for some reason?

Please note it is a minor issue.  :)

**Comment by nicolaskruchten** [comment]
Unfortunately this is a C3 bug :(

**Comment by nicolaskruchten** [comment]
Update: this is not a C3 bug

**Comment by nicolaskruchten** [comment]
Sorry, hit close too early! meant to add "... and will be fixed shortly!"

**Comment by nicolaskruchten** [comment]
This is now fixed, and I recommend that `rpivotTable` be updated ASAP with the new code... sorry for the bug!
