### ISSUE TITLE
Access the UI table

### ISSUE THREAD

**Issue by zakdia** [nicolaskruchten/pivottable#694]
In the pivot.js file, I see that we are generating an html table and storing in uiTable variable. Is it possible to access the html table generated by the pivot.js outside of the JS file? I'm looking to use the dynamic table being rendered by the js file in my code.

**Comment by nicolaskruchten** [comment]
the `uiTable` variable is just a jQuery object referencing the `table` DOM node, so you can access a copy of it any time via jQuery with the proper selector...

**Comment by nicolaskruchten** [comment]
For example, if you're adding the pivot UI to a div with id `output` then the following jQuery call will get you a reference to what you're looking for: `$("#output table.pvtUi")`

**Comment by zakdia** [comment]
Thanks @nicolaskruchten 
This is exactly what I was looking for.
