### ISSUE TITLE
Can I filter and pivot data without render?

### ISSUE THREAD

**Issue by arturgspb** [nicolaskruchten/pivottable#696]
Hi,

I would like to use a direct public api for data transformation, like pandas.
Example:
var mydata = [...];
var params = {
 // group by 
 // filter
// sort (not supported yet, I know)
};
var groupedData = pivottable.transform(mydata, params);

**Comment by nicolaskruchten** [comment]
This library is not really a Javascript replacement for Pandas... It does not return any values, it writes them to the DOM.

**Comment by arturgspb** [comment]
Ok
