### ISSUE TITLE
Variance aggregator

### ISSUE THREAD

**Issue by ArktekniK** [nicolaskruchten/pivottable#697]
Hi there,  I've got a scenario where users select several date ranges to compare data. I'd like to implement an aggregator for the table that shows the variance/percentage change between the first date column and each subsequent one.

For example, given 3 columns, the second and third would show the variance compared to the first.

My questions are;
 - Does something like this already exist?
 - If not, is it possible to access values in specific columns and rows from the aggregator callback? Ideally something like a column selector for am adjacent cell on the same row.

Perhaps I'm missing something and there's a better way to do this!

Many thanks

**Comment by nicolaskruchten** [comment]
It sounds like you're asking about using multiple aggregators in the same table, which is not supported, unfortunately: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi
