### ISSUE TITLE
 Api based integration (e.g:-nodejs +Mysql)

### ISSUE THREAD

**Issue by matt212** [nicolaskruchten/pivottable#698]
hi, 
1. Spectacular library of consolidated functional mechanisms of pivot !
2. rather than issue , a question how can integrated with api based approach .
like (Api based on nodejs as server stack  with mysql as database )
Any pointers , suggestion since it would not be feasible to load humongous amount of data unto a library , curious though !
Awesome lib of well crafted Bi- tool features for client based processing !

**Comment by nicolaskruchten** [comment]
1. Glad you like it!
2. This library happily handles up to around 100k rows of input. Beyond that you will need to feed it either pre-aggregated data or pre-filtered data, as you say from an API that does this server-side, usually by interacting with a database.

**Comment by matt212** [comment]
Hi @nicolaskruchten , 

1.thanks for the clarification, Since I would be loading actually more than 300 k .

2.What, I am planning to do is build dynamic Sql statement depending upon user action of pivottable  
    and filter the statement through **sqlstring** for **sql injection**and then execute it .

Any suggestion, pointers on the same ?
Many thanks !

**Comment by nicolaskruchten** [comment]
Well, what you want to do is going to be very difficult if not impossible
due to the synchronous/asynchronous mismatch between the PivotTable library
and the way HTTP calls work in the browser, unfortunately. This is a
client-side library, and really not designed for server-side integration
in-band like you are describing...

**Comment by matt212** [comment]
Hi  @nicolaskruchten , 
Thanks again for clarification, will  architect my BI-module accordingly !

**Comment by OElesin** [comment]
Hi @matt212, how were you able to solve this?

Currently working on implementing something similar in Python.

**Comment by matt212** [comment]
Hi OElesin,
partially, since what I did was somewhat on  simple selection box as X and Y axis  without using  pivottable , further process would be to implement using Multi selection in Both X and Y axis !
Since we are build custom dynamic pivot we can implement date operation (hr, mon, yr) on any valid datetime fields !
Please refer below gif for the same 
![meh](https://user-images.githubusercontent.com/1698139/27253747-d17d48bc-5397-11e7-8eb4-7bf7c9508915.gif)
