### ISSUE TITLE
Question on Aggregator formating

### ISSUE THREAD

**Issue by datafracking** [nicolaskruchten/pivottable#699]
New to using pivotUI.   Great work btw..     Couple newbie questions:

1. If using a custom aggregator, is there a way to also enable all the default aggregators?  Or do you have to now specify all the aggregators..  Ie..  custom sumoversum.. but want count, sum, etc too.  for example, to see the count aggregator, I had to also include it with my custom one in example below.  

2. If using a custom aggregator, the default behavior of sumoversum selection allows the client user to pick the numerator and denominator columns with dropdowns.  they appear when selecting sum over sum.   If I do a custom one (in order to show the % essentially), it appears the only way is to set the columns statically.. or do a customization outside of the context of pivotUI to pass in the values as I set with numerator, denominator, etc...   Is there a way to get it to still let users set the num/denom?  

Thanks!

```
 var customsumOverSum = $.pivotUtilities.aggregatorTemplates.sumOverSum;
 var numberFormat = $.pivotUtilities.numberFormat;
 var intFormat = numberFormat({digitsAfterDecimal: 2, scaler: 100, suffix: "%"});
 //     var mysum = function() { return customsumOverSum(intFormat)(["world", "hello"]); }
 // same as above
 var tpl = $.pivotUtilities.aggregatorTemplates;
 var numerator = "world";
 var denominator = "hello";
 var mysum = function() { return tpl.sumOverSum(intFormat)([numerator, denominator]); }

       
       
$("#output").pivotUI($("#input"), {
aggregators: {
     "Cusstom Agg": mysum,
     "counterzzz" : tpl.count()
		 //"Custom Agg": function() { return sumOverSum(intFormat)(["world", "hello"]); },
 }, 
    renderers: $.extend(
    $.pivotUtilities.renderers, 
      $.pivotUtilities.c3_renderers)
 });
```

and for proper measure, here is the html used with my above example if anyone wants to create a fiddle...
```
<div id="output"></div>
<table id="input">
            <thead>
                <tr>
                    <th>name</th>
                    <th>hello</th>
                                     <th>world</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>bob</td>
                    <td>3</td>
                    <td>2</td>
                    
                </tr>
                <tr>
                    <td>george</td>
                    <td>44</td><td>2</td>
                </tr>
                <tr>
                    <td>carl</td>
                    <td>3</td><td>2</td>
                </tr>
                <tr>
                    <td>steve</td>
                    <td>7</td><td>2</td>
                </tr>
</tbody>
        </table>
```

**Comment by nicolaskruchten** [comment]
1. Yes of course, you can pass in the default aggregators using `$.extend`:

```javascript
aggregators: $.extend($.pivotUtilities.renderers, {"custom agg": <whatever> })
```

2. Yes, you can preserve the higher order behaviour by 'peeling off' a layer of functions:

```javascript
// your example
"Custom Agg": function() { return sumOverSum(intFormat)(["world", "hello"]); }

//peeling off a layer
"Custom Agg": sumOverSum(intFormat) 
```

**Comment by datafracking** [comment]
Perfect.  That works.  

FYI, you have a typo in answer for part 1.   It should be _aggregators_ not _renderers_..   

Here is the working sample of my previous example that has your fixes.   

```
 var numberFormat = $.pivotUtilities.numberFormat;
 var intFormat = numberFormat({digitsAfterDecimal: 2, scaler: 100, suffix: "%"});
 var tpl = $.pivotUtilities.aggregatorTemplates;
 var mysum =  tpl.sumOverSum(intFormat); 

$("#output").pivotUI($("#input"), {
aggregators: $.extend($.pivotUtilities.aggregators, {
     "Custom Agg": mysum
 }), 
    renderers: $.extend(
    $.pivotUtilities.renderers, 
      $.pivotUtilities.c3_renderers)
 });

```

**Comment by nicolaskruchten** [comment]
Glad that this worked for you, sorry for the typo, I'll fix it :)
