### ISSUE TITLE
Continuous column table by inserting missing dates 

### ISSUE THREAD

**Issue by zakdia** [nicolaskruchten/pivottable#700]
I have a pivot table in the below format and there are no values between the dates when the count is less than 1. 
Is it possible to insert missing dates with count as 0? (This table output feeds one of my chart and I'm trying to make that chart a continuous one.)

Date              count
2017-03-21	1
2017-03-28	2
2017-04-01	1
2017-04-16	3
2017-04-17	1

**Comment by nicolaskruchten** [comment]
There is no built-in functionality for this: the pivot table displays the data it is given, so if you want to show zeros, the data will need to contain zeros :)

**Comment by zakdia** [comment]
Thanks @nicolaskruchten for the response. Closing the ticket.
