### ISSUE TITLE
Styling pivottable with bootstrap

### ISSUE THREAD

**Issue by prernadubey** [nicolaskruchten/pivottable#701]
Hello,

I want to style pivotUI using bootstrap styles. For eg. adding bootstrap style ' _table-hover_' in pvtTable. 
I tried below code-

Code snippet-
**$("#output").pivotUI(data,  {
			 cols: ["MINBAL"],
			 rows: ["BANKNUM"],
			 aggregatorName: "Sum",
			 rendererName:"Table",
			 renderers: renderers,
			 onRefresh: function() {
				$('.pvtTable').addClass('table-hover');**

'_table-hover_' class got added to table, see below . But hover functionality is not working in my pivot table. Please let me know If doing something wrong. 

![image](https://cloud.githubusercontent.com/assets/1680828/25698914/e19c8298-308e-11e7-98eb-091f40609b6f.png)

**Comment by nicolaskruchten** [comment]
did you still want help with this?

**Comment by prernadubey** [comment]
Thanks Nicolas !
I got it how to do. Below is the code which worked for me.

onRefresh: function() {debugger;
			$('.pvtTable').addClass('table-hover');
			**$('.pvtTable tbody tr').addClass('success');**
