### ISSUE TITLE
Moving row totals and pinning columns

### ISSUE THREAD

**Issue by rsalayo** [nicolaskruchten/pivottable#704]
Hi,

Is it possible to move the "Row Total" closer to the rows instead of the last column?
Also, is it possible to pin columns so that only values scroll-able?

Thanks

**Comment by nicolaskruchten** [comment]
Neither of these is a supported feature, no.

**Comment by rsalayo** [comment]
I understand. Thanks. I think I can live without it ;)
Although there's one more thing I need... Change the class if columns contains specific word. E.g. I want to show different different color if column is Sat/Sun (Weekends). Is that doable?

**Comment by nicolaskruchten** [comment]
There's no built-in way to do this, but a little bit of `jQuery` work should do the trick here...
