### ISSUE TITLE
Thanks! And I want more

### ISSUE THREAD

**Issue by lafar6502** [nicolaskruchten/pivottable#705]
Hey, thank you for this great project, simple and clear, users like it very much
If possible, i'd like to write down some ideas for next versions 
1. Make it possible to have more than 1 measure in the grid
2. Allow for simple arithmetic operations on the values (computed values), like a - b, a * b etc - something like a computed attribute but with the option to specify in the gui

**Comment by nicolaskruchten** [comment]
Glad you like the tool!

Both of your suggestions are good, but I'll be frank and say that I'm unlikely to implement either of them... the first one is the most-requested feature but would require a major rethink of the architecture and UX, and the second one is a more power-user-oriented feature with big UX challenges (basically providing reasonable error messages for users who typo when inputting expressions).
