### ISSUE TITLE
List of JQuery UI components

### ISSUE THREAD

**Issue by akshaisarma** [nicolaskruchten/pivottable#706]
First off, thanks for the great tool! It's simple and extraordinarily functional.

I am running into plugin clashes with bootstrap and jquery-ui and was wondering if you had a list of the components (http://jqueryui.com/download/) that you use so I could just include those instead of all of jquery-ui?

I could add them in one by one and find out what breaks to fix and iterate but was hoping you had a list.

**Comment by nicolaskruchten** [comment]
It only relies on `sortable` :)

**Comment by akshaisarma** [comment]
Sweet, that makes it easy. Cheers!

**Comment by lestcape** [comment]
I have also a conflict with bootstrap. Can you drop jquery-ui in favour of a build-in functionality? Please see a full description of my issue [here](https://github.com/mistic100/jQuery-QueryBuilder/issues/71).

 I think drag and drop is also provided by jquery-ui... that is correct? I can workaround [the call of sortable](https://github.com/nicolaskruchten/pivottable/blob/master/dist/pivot.js#L1672), but if i don't include jquery-ui, i will lost the drag and drop support. If you have some against of drop the jquery-ui dependency, can you point me to the specific code that i need to replace to drop the dependency by myself?

Thanks anyway for the library is beauty to easy analyze data on fly.

**Comment by nicolaskruchten** [comment]
There's no built-in alternative to something like `jquery-ui`'s `sortable` and I'm unlikely to remove this dependency in the near future, as it's been part of this library from the beginning :)

**Comment by lestcape** [comment]
Ok thanks, I understand, i will try to drop the jquery-ui dependency by myself.
