### ISSUE TITLE
Please add www.sqlwallet.com on Used By page

### ISSUE THREAD

**Issue by Glebby** [nicolaskruchten/pivottable#709]
Thank you for the great component, I use it in SQLwallet to allow building chart/pivots directly form SQL queries.

Please add http://www.sqlwallet.com on Used By page. I credit pivottable on our FAQ page [](http://www.sqlwallet.com/faq/)  (see "What are amounts of data SQLwallet can deal with?")

**Comment by nicolaskruchten** [comment]
Done! thanks :)
