### ISSUE TITLE
How to hide tools in the pivotUI() with C3

### ISSUE THREAD

**Issue by okman1214** [nicolaskruchten/pivottable#710]
I want to keep the charts area only
Control the the paramter<rows cols..> with js function
thxs!

**Comment by nicolaskruchten** [comment]
You can use the `pivot()` function instead of `pivotUI()`

**Comment by okman1214** [comment]
Thank u for help!
but, i want to use other charts not only table   e.g. line、columns、pie...
How to function with pivot()?

**Comment by okman1214** [comment]
For example:
the "Unused" dimension tool area
<td class="pvtAxisContainer pvtUnused pvtHorizList ui-sortable"> style="
    display: none;
">...</td>

If i can only set the style of this object “display:none"? So do the others tool area?

**Comment by nicolaskruchten** [comment]
There is no API for this, but you can just use the CSS classes that are there to do it...

**Comment by okman1214** [comment]
Thank u very much!
