### ISSUE TITLE
I dont want want to merge rows, display it seprately.

### ISSUE THREAD

**Issue by riyaz1989** [nicolaskruchten/pivottable#712]
Hi Nicolas,

First of all thanks for providing great stuff.

- I am using pivot.js and pivotUI() for showing table.
- Currently  showing my rows in merged form in table, I don't want to show it in meged form, All rows will show seprately. If you did not get my point please check screen shot
![lia](https://cloud.githubusercontent.com/assets/26436818/26108150/45a25356-3a69-11e7-91b5-7b20016dd04d.png)

- As u can see in screenshot that field "Lia"  is merged for all their related rows, I want to show "Lia" for every record those are related to its separately. There are 8 records related to Lia.

**Comment by nicolaskruchten** [comment]
There's no option to control that so you'll have to fork or modify the
default renderer.
