### ISSUE TITLE
Rounding floats to int bug

### ISSUE THREAD

**Issue by babjak** [nicolaskruchten/pivottable#716]
Values in random columns of the embedded data will get rounded to integers when displayed in "Line Chart" mode, yet the same values are printed as float when selecting "Table". Other columns are plotted and printed as proper floats.

**Comment by babjak** [comment]
It seems this only happens with negative numbers, and as others have pointed out, this seems to be an issue with the c3 library, not pivottable.js. I have tested it with c3 v0.4.11, and the bug is still there. Is there a workaround for this?

**Comment by nicolaskruchten** [comment]
I haven't found a good workaround, no :(

**Comment by babjak** [comment]
A better description of the bug can be found here:
https://stackoverflow.com/questions/38799996/r-rpivottable-bug-the-value-on-the-table-is-not-the-same-with-the-value-on-ba

**Comment by nicolaskruchten** [comment]
This has now been fixed.

**Comment by babjak** [comment]
My first tests show this works as expected. Thank you!
