### ISSUE TITLE
Summing up Time and Showing values in time format

### ISSUE THREAD

**Issue by knaveenchand** [nicolaskruchten/pivottable#717]
Hi,

Great plugin!

I'd like to use it to display mysql-php output in json format. My table has data in time format (HH:MM:SS). I'd like to show these values and also sum up in the row Totals and column totals. 

If I try Sum or Count or Min or Max, it returns nothing. However, if I try "List Unique Values", it shows the values correctly. But the Row Totals and Column does not work. Here is a screenshot. Can you help me guide in the right direction to get the totals as well. 

![screen shot 2017-05-27 at 1 52 09 pm](https://cloud.githubusercontent.com/assets/3255846/26518123/54daa8ea-42e4-11e7-8c14-917dd96657f1.png)

As you see in the image above, the time is not summing up. This is the code I am trying:

```

$.getJSON("http://salesapp.matenek.com/salesmatenek/navtests/getInputForPivot.php", function(mps) {
        $("#output").pivotUI(mps, 
        {
            cols: ["report_date"],
            rows: ["rid"],
            vals: ["time_spent"]
            })
    })

```

**Comment by nicolaskruchten** [comment]
The current behaviour is explained by the fact that a string in the format "hh:mm:ss" is not a number, so is not summable, averagable, etc. "list unique values" will concatenate all unique values of the field with a comma as a divider, which is why you're seeing the output you're seeing.

In order to get the behaviour you're looking for you will either have to convert your input to numbers, and use the built-in aggregator templates with a custom number formatter, or you can roll your own aggregators which will parse "hh:mm:ss" to a number first if you really need to leave your input as-is.

**Comment by knaveenchand** [comment]
Thanks for your ideas on how to approach this problem. From your suggestion, I choose the first option of converting my input to numbers and then once pivot is generated I created a script to manipulate the format (instead of using built-in aggregator templates and custom number formatter). 

I had to take this route because of my limited abilities to understand how aggregator templates work. I would be grateful if you can post an example script. 

Meanwhile, here is my workaround - which I guess is not a professional work. 

Step 1: I wrote php to generate a json where time_spent is in Time-to-Seconds format (in other words, numbers). 

Step 2: html (note that i am hiding output initially so your script runs in background and shows only changed format after i click a button. 

```
        <button class="convert">Convert Seconds to Time</button>
        <div id="output" style="margin: 30px; display:none;"></div>
```

Step 3: script where I am calling my script on button click because I couldn't hook my functions after your function is executed. I tried a lot to do that. As I failed, this is the work around I implemented. 

```     
    // This example is the most basic usage of pivot()
            var tpl = $.pivotUtilities.aggregatorTemplates;

        $.getJSON("http://salesapp.matenek.com/salesmatenek/navtests/getInputForPivot.php", function(mps) {
            $("#output").pivotUI(mps, 
            {
                cols: ["report_date"],
                rows: ["rid"],
                vals: ["time_spent"],
                aggregators: {
                    "Time Spent":      function() { return tpl.sum()(["time_spent"]) },
                    "Number of Visits":      function() { return tpl.count()(["time_spent"]) }

                },

                })
            //console.log(mps);
     

        })
 
    $('button.convert').click(function(){
        
        
        function secondsTimeSpanToHMS(s) {
                var h = Math.floor(s/3600); //Get whole hours
                s -= h*3600;
                var m = Math.floor(s/60); //Get remaining minutes
                s -= m*60;
                return h+":"+(m < 10 ? '0'+m : m)+":"+(s < 10 ? '0'+s : s); //zero padding on minutes and seconds
            }
            
        function manipulateClass(y) {
            var divs = document.getElementsByClassName( y );
            [].slice.call( divs ).forEach(function ( div ) {
                var x = div.innerHTML; //fetch the text in the class pvtVal
                x=x.replace(/\,/g,''); // 1125, but a string, so convert it to number
                //x=parseInt(x,10);
                div.innerHTML = secondsTimeSpanToHMS(x); //send to function and get seconds converted to time
            	});
            }
            
        manipulateClass('pvtVal')
        manipulateClass('pvtTotal')
        manipulateClass('pvtGrandTotal') 
        
        $('#output').show();
    });

```

I am sure my solution is lengthy and may not be the correct one. But it is giving the desired solution although not neat. I would be grateful if you can show an example of changing format in built-in aggregator.

**Comment by nicolaskruchten** [comment]
Here is the documentation for localization, which is basically what you want to do with number formatting: https://github.com/nicolaskruchten/pivottable/wiki/Localization ... it contains a link to the aggregator/templates documentation: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators

You can avoid using a button by using the `onRefresh` callback, which is called after every refresh.

**Comment by knaveenchand** [comment]
Thank you again. onRefresh callback was very useful.
