### ISSUE TITLE
Pivot() working Fine, but pivotUI() is throwing an Error

### ISSUE THREAD

**Issue by MorlaRamakrishna** [nicolaskruchten/pivottable#719]
I have added <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
pivot() is working fine for me, but pivotUI() is not working for me.

Getting below Error:
pivot.min.js:1 TypeError: this.find(...).sortable is not a function
    at jQuery.fn.init.t.fn.pivotUI (http://localhost:9000/main.bundle.js:60979:26104)
    at TestComponent.webpackJsonp../src/main/webapp/app/test/test.component.ts.TestComponent.ngOnInit (http://localhost:9000/main.bundle.js:73446:22)

**Comment by nicolaskruchten** [comment]
The correct order is:

1. jQuery
2. (Optional for `pivot_ui` to work) jQuery-UI
3. `pivot.js`
4. (Optional for D3/C3 renderers) D3
5. (Optional for C3 renderers) C3
6. any optional renderers

You can see it working in any of the examples such as this one: http://nicolas.kruchten.com/pivottable/examples/mps.html
