### ISSUE TITLE
sort in pivot UI with Stacked bar chart

### ISSUE THREAD

**Issue by chaitanmk** [nicolaskruchten/pivottable#721]
Hi,

I want to stop natural sorting in pivot UI. I need data to shown in the same order from the input list. I've tried below code in jsfiddle, but it was not working. Can you please help me on this.

var input=	[{"Day":"2017-05-01","GearId":"1","GearVal":"20"},{"Day":"2017-05-01","GearId":"2","GearVal":"10"}];
var tpl = $.pivotUtilities.aggregatorTemplates;
var aggregatorValue = {'Gear Utilization (%)': function() {return tpl.sum()(["GearVal"])}};
$("#output").pivotUI(
input, {
rows: ["GearId"],
cols: ["Day"],
aggregators: aggregatorValue,
rendererName: "Stacked Bar Chart",
sorters: {"GearId": $.pivotUtilities.sortAs(["1","2"])},
renderers: $.extend(
$.pivotUtilities.renderers,
$.pivotUtilities.c3_renderers
)
});

i want gear ID 1 then gear ID 2 in graph. But due to natural sort gear id 2 coming in bottom then gear id 1. sorting is working if render type is table. but for stacked bar chart. its not working

 Thanks in advance.

**Comment by nicolaskruchten** [comment]
You'll have to upgrade to the newest version of this library for this to work :)

**Comment by nicolaskruchten** [comment]
I've updated the JSFiddles in the examples page to use version 2.13.0 of this library, which allows the order from `sorters` to get pass through to C3.

**Comment by chaitanmk** [comment]
Hi Nickolas,

Thank you so much. It was great help from you.

Regards,
Krishna M

**Comment by chaitanmk** [comment]
Hi, 

can you please let me know how to allow orders from sorters to get pass through c3. There were many difference between my current library and your latest library.

**Comment by nicolaskruchten** [comment]
Just use the `rowOrder` and `colOrder` parameters. Documentation is here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by chaitanmk** [comment]
Hi,

I modified code in C3.min.js to stop overriding data based on values. But in pivot.min.js it is sorting data in ascending order based on ids. Since its minified js i'm not able to figure out logic for sorting. Can you please help me how to stop natural sorting in piovt.min.js

Thanks in advance.

**Comment by nicolaskruchten** [comment]
Have you tried passing in a custom `sorter` ?

**Comment by chaitanmk** [comment]
Hi,

I modified pivot.min.js and c3.min.js to stop sorting data. So whatever
order I send data it is showing in same order. That's resolve my issue.

Regards,
Krishna M
