### ISSUE TITLE
2+ values per column/sample and percentages

### ISSUE THREAD

**Issue by gomedya** [nicolaskruchten/pivottable#722]
hi, i have a situation where i have more than one answer per question, such as 'hobby', and need to have a custom aggregator that shows percentages (cell value/total of row or column * 100) in cells. Any idea to implement both is appreciated, thanks.

**Comment by nicolaskruchten** [comment]
There is a "sum as a fraction of" aggregator built in already, does that
meet your needs?

**Comment by gomedya** [comment]
Nicolas hi, Thanks for quick answer. Count as fraction of total does work, but I don't know how to handle multiple answers per question. An example sheet can be seen at https://docs.google.com/spreadsheets/d/15OVjxsoPVZqWm49R-VpSMBInRDi_J03VI1CU9__PmQs/edit?usp=sharing
Thanks.

**Comment by nicolaskruchten** [comment]
Hmm, I'm sorry but I don't understand... Can you elaborate please?

**Comment by gomedya** [comment]
sure, in the mps example, one person can have one name, party, province, age, gender.. suppose there is a  "hobby" question and one person can give more than one answer, such as reading, swimming, etc. in the google docs example, people are asked what fruits they like and what hobbies they have, both multiple choice questions. you can see "hobby" answers as column headers, and "fruit" answers as row headers. because people can change more than one answer, results can be more than the number of people and percentages greater than 100%.

**Comment by nicolaskruchten** [comment]
Hmmm there is a problem with the math here then: even if one person can say they like both apples and bananas and video games, you don't have 133% of people liking video games :)

**Comment by gomedya** [comment]
this is how my customers expect results, total of 4 answers from 3 people/subjects resulting %133. spreadsheet is correct. i don't know if this way of calculating percentages has any value in general statistics crowd, but surveys are calculated and presented this way in turkey. going back to original question, how can we have multiple answers per column/question?

**Comment by nicolaskruchten** [comment]
OK, well you'll have to build a custom aggregator that implements something like count(x)/countUnique(y) or something like that... You can probably use the Sum over Sum one as a starting point.

**Comment by gomedya** [comment]
ok, thanks. :)
