### ISSUE TITLE
need to show total value on stacked bar

### ISSUE THREAD

**Issue by chaitanmk** [nicolaskruchten/pivottable#723]
Hi Nicolas,

i need to show total value on each bar in stacked bar chart. can you please help me on this.

```javascript
var input=	[{"Day":"2017-05-01","GearId":"1","GearVal":"20"},{"Day":"2017-05-01","GearId":"2","GearVal":"10"}];
var tpl = $.pivotUtilities.aggregatorTemplates;
var aggregatorValue = {'Gear Utilization (%)': function() {return tpl.sum()(["GearVal"])}};
$("#output").pivotUI(
input, {
rows: ["GearId"],
cols: ["Day"],
aggregators: aggregatorValue,
rendererName: "Stacked Bar Chart",
renderers: $.extend(
$.pivotUtilities.renderers,
$.pivotUtilities.c3_renderers
)
});
```

Thanks in advance.

**Comment by nicolaskruchten** [comment]
There is no built-in way to do this but you may be able to pass extra directives to C3 via `rendererOptions`...

**Comment by chaitanmk** [comment]
can you please give me some sample code.

**Comment by nicolaskruchten** [comment]
Here you can see the `size` object being passed to C3 via `rendererOptions`: http://nicolas.kruchten.com/pivottable/examples/scatter.html

**Comment by chaitanmk** [comment]
thank you.
