### ISSUE TITLE
How to when pivottable starts rendering and then finished rendering?

### ISSUE THREAD

**Issue by turnerniles** [nicolaskruchten/pivottable#725]
I know I can use the onRefresh callback parameter to check when it's finished rendering the table. Documentation: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

But is there anyway to check when it starts rendering the table? I'm only interested in when the table starts rendering not when a parameter is being dragged (unless it triggers a table re-render).

**Comment by nicolaskruchten** [comment]
There is no built-in way to do this, no, but I should mention that any change in the UI (dropdown selection, drag/drop) causes a full re-render. The only thing that doesn't is if you close a filter menu without changing anything or if you drop something to the same location it was on...

**Comment by nicolaskruchten** [comment]
I see from your profile that you're working on a React-based pivot library... If you're doing benchmarks to compare against PivotTable.js I'd love to see them, I've been pondering a React port myself :)

**Comment by turnerniles** [comment]
@nicolaskruchten haha yeah! We're working on a pivot library to try and handle large amounts of data but it still needs work and is lacking features. 

We are also using PivotTable.js and want to visually see the rendering time vs data download time. That's the immediate need. But I had thought of benchmarking the react pivot vs PivotTable.js as well ;).

Once I get further along, I will reach out. We're working on filtering right now.

**Comment by nicolaskruchten** [comment]
Cool, looking forward to seeing what you come up with!

My guess is that React will not be faster for large tables because the majority of operations require a full redraw. PivotTable.js uses raw DOM operations in its TableRenderer whereas React will also have the overhead of the virtual DOM but none of the benefits because it's a full redraw not a small diff.

**Comment by turnerniles** [comment]
@nicolaskruchten We are using virtualization so we are only rendering the visible cells using [https://github.com/bvaughn/react-virtualized](url). From my testing PivotTable.js renders only slightly slower with a large amount of data. I will update you once I do a benchmark / more detailed comparison.

**Comment by nicolaskruchten** [comment]
Ah, interesting.

My broader feeling is that huge tables are generally not a good way to look at datasets anyway, so I've never been that concerned about making them very fast ;)

**Comment by nicolaskruchten** [comment]
FYI the React port is almost done, in case you want to take a look and/or give feedback :) https://react-pivottable.js.org/

**Comment by turnerniles** [comment]
@nicolaskruchten It looks great! It feels faster than the classic version.

**Comment by turnerniles** [comment]
@nicolaskruchten do you have a roadmap for the future of development for pivottable.js and/or react-pivottable.js?

**Comment by nicolaskruchten** [comment]
@turnerniles nothing firm  or committed to or written down at the moment, no, why do you ask? Are you looking for a specific feature, or looking for a way to contribute or...?

By way of a slightly longer answer... PivotTable.js has basically been a spare-time project for the past five years for me, but I built react-pivottable while working for Plotly, so I'm more likely to add features and do new development on react-pivottable, while maintaining and back-porting features to PivotTable.js as appropriate. I'm likely to add Plotly renderers to PivotTable.js fairly soon, for example ;)

On the react-pivottable side, I'm hoping to achieve feature-parity with PivotTable.js soon (still missing area charts, localization, a few other bits and pieces) and a couple of new chart-types and interaction features. After that it'll basically be a question of what kinds of features get requested most. Plotly also does [sponsored development](https://plot.ly/products/consulting-and-oem/), so react-pivottable may end up accumulating some features/get integrated into various places that way.
