### ISSUE TITLE
Passing data in JSON format from an ExtJS grid - is this possible

### ISSUE THREAD

**Issue by jovenden** [nicolaskruchten/pivottable#726]
Hi, this project is really interesting and testing I have done using a 10,000 row CSV has been very impressive. 

We use ExtJS (3.x - not latest version) - as I understand it all the data is in the browser in JSON format. What I'd like to do is "push" the data from the page into pivottable (for example give my user a button to do this).

Should this be possible? 

Appreciate your assistance and hope this isn't a dumb question - just wanting to explore the options and I really like what you have done!

All the best
Jeremy

**Comment by nicolaskruchten** [comment]
Hi Jeremy,

This documentation page outlines all the ways to get data into the library: https://github.com/nicolaskruchten/pivottable/wiki/Input-Formats

Hope it helps!
Nicolas

**Comment by jovenden** [comment]
Hi Nicolas, amazing quick response :)  I had read that page and hoped that perhaps I was missing something. Having already built a lot of stuff round ExtJS grids and seeing what you've done it would be so great to be able to seamlessly invoke a pivot or graph from the data within the ExtJS grid.

Any tips or pointers appreciated.

all the best
Jeremy

**Comment by nicolaskruchten** [comment]
I'm afraid I'm not familiar enough with ExtJS to be able to provide any more specific advice, I'm sorry :)

**Comment by jovenden** [comment]
No problem at all – many thanks again for the rapid responses!

**Comment by jovenden** [comment]
<note to self> 
do not just hit reply to the email :)
</nts>
