### ISSUE TITLE
Unable to reset columns and rows after initial view

### ISSUE THREAD

**Issue by eformx** [nicolaskruchten/pivottable#729]
I load the pivotUI with json data and works fine.  

```
$("#chart").pivotUI(arr_found, {
            rows: ["Segmentation"],
            cols: ["Transferred"],
         });
```
I have a button and on click I want to change the layout but it doesn't clear the old view.

```
$(document).on('click', ".btn_pivot", function (e) {
//arr_found is my global json data
$("#chart").pivotUI(arr_found, {
            rows: ["Segmentation", "Transferred"]
         });

});
```
So what I would like to do is have pre-configured layouts so the pivot can be changed from buttons.  Possible?  How?

**Comment by nicolaskruchten** [comment]
This example explains how to use the `overwrite` parameter of `pivotUI()` to accomplish what you want: http://nicolas.kruchten.com/pivottable/examples/save_restore.html

**Comment by eformx** [comment]
Hi Nicolas,

Actually I don't want to save the config, I have users that don't understand pivots...so I would like 3 buttons with the 3 layouts in the click events.  Hit a button...configure the layout from the same data.  Currently the only way I have been able to get to work is using JQuery remove of the div and then append a new div and re-initalize it.  But that just doesn't seem a perfect solution?

**Comment by nicolaskruchten** [comment]
The example shows save and restore and you are describing essentially a
restore operation for configs that are defined statically, no?

**Comment by eformx** [comment]
Your solution only works if the config file can be built and stored in script; which I haven't seen...I have users across the country (Canada), so the cookie retrieval suggestion does not work.  So currently I am going for the following super simple solution:

        ```
$("#chart").remove();        
        $(".some_charts").append("<div id='chart'></div>");        
        $("#chart").pivotUI(arr_found, {
            rows: ["Segmentation"],
            cols: ["Transferred"]
        });
```

**Comment by nicolaskruchten** [comment]
I'm 99% sure you just need to do this to accomplish what you want:

```javascript
$("#chart").pivotUI(arr_found, {
            rows: ["Segmentation"],
            cols: ["Transferred"]
        },
        true // <-- this is the overwrite parameter you need to set to true!
);
```

**Comment by nicolaskruchten** [comment]
re your comment that "only works if the config file can be built and stored in script" ... in the example you gave above you have this, the config object is just `{rows: ["Segmentation"], cols: ["Transferred"]}`.

**Comment by nicolaskruchten** [comment]
Check out the documentation for the `overwrite` parameter here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters#pivotuiinput-options-overwrite-locale (note: it's not part of the config, it's a separate parameter to `pivotUI()`

**Comment by eformx** [comment]
Okay that works...I saw that; but without any implementation guidance on the site, I couldn't figure out where to put it.  So for anyone else that needs to know where it goes here it is...

```
              $("#chart").pivotUI(arr_found, {
                    rows: ["Segmentation"],
                    cols: ["Transferred"]
                }, true); 
```
