### ISSUE TITLE
C3 charts are not getting loaded

### ISSUE THREAD

**Issue by ramakrishnan26** [nicolaskruchten/pivottable#731]
Hi,
I am working on the examples from your website. I am able to load the basic pivot. But I am not able to load the C3 charts examples. I have added the C3 plug ins as you mentioned. But still I could not able to load. Can you please help me in this? 

I am attaching the source code and the html file head structure for your reference. 

![pivt js part](https://user-images.githubusercontent.com/28620061/27466725-50244fd8-57fa-11e7-9802-48d9f0c2c673.PNG)
![pivot c3 chart](https://user-images.githubusercontent.com/28620061/27466728-55322770-57fa-11e7-9455-cb9b8de856c4.PNG)

**Comment by nicolaskruchten** [comment]
In your second screenshot there are 2 issues:
1. c3 and d3 are commented out so they are not loaded
2. the load order matters, it has to be: d3, then c3, then the renderers.
