### ISSUE TITLE
Looking to render TSV in background without a refresh 

### ISSUE THREAD

**Issue by 01** [nicolaskruchten/pivottable#732]
I have modified the export_renders.js to result in a CSV format. However I am looking to have the CSV generated from a seperate button that does no refresh the render. Having little trouble following where and how the renders are from the select tags, since change results in refresh(); Any advice would be appreciated.

**Comment by nicolaskruchten** [comment]
Probably the easiest thing for you to do would be to render in an invisible element using `pivot()` rather than `pivotUI()` and grabbing the output from there...

**Comment by 01** [comment]
Thanks, worked great. However did not work with calling just pivot.  Required calling pivotUI. Due to differences in how pivot() and pivotUI() work it does not seem calling pivot with export_renders["TSV Export"] as the renderer works.

**Comment by nicolaskruchten** [comment]
Its definitely possible to do with `pivot()` but the call semantics are slightly different.

**Comment by 01** [comment]
I figured it out, I extended render: to both export and pivotJS built in renders so without stating a renderName it defaulted to table since I didnt dictate rendererName.
