### ISSUE TITLE
Refresh pivotUI on external button click

### ISSUE THREAD

**Issue by KatoWitEC** [nicolaskruchten/pivottable#736]
Hi Everyone, 
at first, Nicolas what a great library pivot.js is:) !
I have successfully understood aggregators, filters, subtotal renderers, however still have a problem with a basic issue I believe.

I have some extra buttons on page (next to the Pivot UI table). They are acting as shortcuts for some actions. For example: changing columns and their order

Problem I have is that creating pivotUI for the first works ok, howewer selecting any option for the second time does not refresh the pivot table, data structure stays the same. (I am simply reinitializing pivotUI with new parameters for columns.)

I can see it works for pivot, not pivotUI. Any hints on this one please?

**Comment by nicolaskruchten** [comment]
Glad you're liking this library!

To solve your issue, set the third parameter of `pivotUI()` (the `overwrite` parameter) to `true` as shown here: https://pivottable.js.org/examples/save_restore.html

**Comment by KatoWitEC** [comment]
Right, eveything works perfect now. Thank you!
