### ISSUE TITLE
How to keep inclusions filter selected

### ISSUE THREAD

**Issue by ape163** [nicolaskruchten/pivottable#738]
Hello,
I have to pass to a query all the selected filter with the callback.
My problem is that inside the callback I haven't the object inclusions.
I can't find a solution anywhere

**Comment by nicolaskruchten** [comment]
If you look here: https://pivottable.js.org/examples/onrefresh.html you will see the inclusions are being passed to the `onRefresh` callback...

**Comment by nicolaskruchten** [comment]
(Except in the case of everything being included.)

**Comment by ape163** [comment]
Thank you but I don't understand how to use onRefresh in the callback but I found a workaround:

var inclusions = jQuery("#output").data('pivotUIOptions').inclusions;
				                	
It seems to work, what do you think about?  :)

**Comment by nicolaskruchten** [comment]
If it works it works :)
