### ISSUE TITLE
How to use pivot_ui() via Azure Notebooks

### ISSUE THREAD

**Issue by zpencerguy** [nicolaskruchten/pivottable#739]
Trying to use the pivot_ui function inside of a notebook powered by Azure. Im assuming this has something to do with localization.. Keep getting URL not found.

**Comment by nicolaskruchten** [comment]
This issue probably belongs in the issue tracker in the repo for the Python `pivottablejs` module, no? https://github.com/nicolaskruchten/jupyter_pivottablejs

I created an Azure Notebooks account to help you debug this but was unable to install the module... how do you do it?

**Comment by zpencerguy** [comment]
Fair point, I have moved this to https://github.com/nicolaskruchten/jupyter_pivottablejs/issues/27
