### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by AykutBurak** [nicolaskruchten/pivottable#740]
```
$(function(){
  $("#output").pivotUI(
    $.pivotUtilities.tipsData, {
      rows: ["sex", "smoker"],
      cols: ["day", "time"],
      vals: ["tip", "total_bill"],    
    },false,"fr");
});
```
I've edited the code from pivotUI() example but I couldn't change the locale of the pivottable. I believe I'm doing the same thing as shown in the French locale example. What am I doing wrong?

**Comment by adityos2003** [comment]
how to change code above to link php json from mysql ? the example :
(code php encode from mysql link to file.js (above))

<?php
$conn=mysql_connect("localhost","root","");
if($conn){
mysql_select_db("test");
$sqlstr="SELECT * FROM test";
$recset=mysql_query($sqlstr,$conn);
$test=array();

while($row=mysql_fetch_assoc($recset)){
$sales_table[]=$row;
}
$sales_table=array("test"=>$test);
mysql_close($conn);
echo json_encode($test);
}else{
echo "server not connected";
}

//print json_encode($test);
?>;

**Comment by nicolaskruchten** [comment]
@AykutBurak sorry for the late reply... Did you load the `fr` locale file?

**Comment by AykutBurak** [comment]
@nicolaskruchten yeah that was the issue. Thank you for your help.
