### ISSUE TITLE
Creating derivedAttributes by Multiply two column values 

### ISSUE THREAD

**Issue by mali0811** [nicolaskruchten/pivottable#742]
Hi Nick,
Thanks for the great efforts on Pivot Tables.

1.) Is it possible to multiply two columns of a pivot table and populate the third column which is a derived Attribute?
2.) Is it possible to have custom aggregators such as weighted average with the aggregators that you have developed?

Please suggest.

**Comment by nicolaskruchten** [comment]
1. No, all columns must be computed with the same aggregator
2. Yes, you can easily create custom aggregators: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators
