### ISSUE TITLE
Pivot over nested json data

### ISSUE THREAD

**Issue by andtov** [nicolaskruchten/pivottable#743]
Hi Nicolas, I´m jusing the plugin to check compatibility issues when migrating sql server. The data comes from a json generated with a tool (Microsoft Data Migration Assistant). This json has several nested objects and I'm triying to get the total of AssessmentRecommendations per database. 

Right now just the database names  is the data I'm able to setup in the plugin, but I'm don't know how to get the count over the AssessmentRecommendations (nested json object per database) object working.

This is the current plugin setup that I'm using:

```javascript
var cnt = $.pivotUtilities.aggregatorTemplates.count;
var numberFormat = $.pivotUtilities.numberFormat;
var intFormat = numberFormat({digitsAfterDecimal: 0});

$("#output").pivotUI(
    $.pivotUtilities.tipsData[0].Databases, {
        rows: ["Name",$(this).AssessmentRecommendations],
	aggregator: cnt(intFormat)($(this).AssessmentRecommendations),
        rendererName: "Heatmap"
     }
 );
```

Thanks for your help

**Comment by jovenden** [comment]
Question actually to andtov: you're pointing to JSON data as the source for Nicolas' pivot utility? I didn't realise this format was supported and so am interested in your progress with this :)

**Comment by andtov** [comment]
Hi jovenden, yes the plugin supports JSON, but I'm not sure how much complex the json data can be. I will keep you updated on this

**Comment by nicolaskruchten** [comment]
Unfortunately while JSON is a fine way to get data into this library, it expects either array-of-(non-nested!)-objects or array-of-array as a format. Basically a table of records with named scalar attributes.

**Comment by nicolaskruchten** [comment]
I've updated the Input Formats documentation: https://github.com/nicolaskruchten/pivottable/wiki/Input-Formats

**Comment by andtov** [comment]
Ok Nicolas it's clear for me. I hope some day the plugin can work with this type of objects.

Thank you

**Comment by nicolaskruchten** [comment]
@andtov can you tell me a bit about how you would expect this to work? I'm not clear on how this library would be useful on nested data... would you expect it to flatten out all objects and generate attribute names like `a.b` ?

**Comment by andtov** [comment]
Yes Nicolas something like that, as a common json object can be acceded. I think this plugin  can be a powerful tool to analyze several data and working with json make this the first option to take.

**Comment by nicolaskruchten** [comment]
OK. Are you able to just flatten the nested JSON before handing it off to the library? Does that meet your needs?

**Comment by andtov** [comment]
Ok I will try and let you know, thank you
