### ISSUE TITLE
Rendering HTML?

### ISSUE THREAD

**Issue by qcchris** [nicolaskruchten/pivottable#745]
Is it possible to render HTML inside the cells?

I have this as my aggregator:

`aggregator: function (data, rowKey, colKey) {
                            return {
                                PostInventoryQuantity: 0,
                                Quantity: 0,
                                push: function (record) {
                                    this.PostInventoryQuantity = record.PostInventoryQuantity;
                                    this.Quantity = record.Quantity;
                                },
                                value: function () { return this.Quantity + ' - <strong>' + this.PostInventoryQuantity + '</strong>'; },
                                format: function (x) { return x; }
                            };
                        },`

...and it renders the HTML &lt;strong&gt; tag as text.

**Comment by nicolaskruchten** [comment]
This is not possible, no... It used to be but because other projects are integrating this library with potentially unsafe input, for security reasons I rolled that feature back.

**Comment by nicolaskruchten** [comment]
See #401 for the full details.

**Comment by qcchris** [comment]
Is there a way to append data to a cell that isn't visible such as an attribute to the &lt;td&gt; tag? For example, I would like to only display 'PostInventoryQuantity' but still have 'Quantity' available later on for further functionality such as displaying a menu when a user clicks on a cell.

Otherwise, could I easily change my own version of the libraries code to re-allow HTML? As my HTML will always be from hard-coded strings.

**Comment by nicolaskruchten** [comment]
You should be able to just back out the changes from PR #401 to get what you want, yes.
