### ISSUE TITLE
nicolaskruchten/pivottable sorting

### ISSUE THREAD

**Issue by frankernesto87** [nicolaskruchten/pivottable#746]
Is it possible to remove sorting of pivot table??
it alows alphabethical and it's reverse, but I'm looking for showing the data as it comes from a certain json. 
Regards.

**Comment by nicolaskruchten** [comment]
There is no way to disable sorting, no, because the output needs to be deterministic and there is no obvious way to preserve the input order within the various transformations that occur. You can provide your own sorting functions on a global or per-attribute basis, though, so you can control the order beyond just up or down. Check out the `sorters` parameter.

**Comment by frankernesto87** [comment]
Hi again nicolas!!
I'm facing a new problem with save and load state from pivotui , I'm saving
pivot conf to DB, but when I try to restore it I'm getting this:
 "pivot.coffee:932 Uncaught TypeError: D.aggregators[u.val(...)] is not a
function
    at pivot.coffee:932 (anonymous) @ pivot.coffee:932".
My conf loads unused fields and rows , but is not able to load the data
table, renderers and aggregators.


 any help??
regards Frank

2017-07-19 13:52 GMT-05:00 Nicolas Kruchten <notifications@github.com>:

**Comment by nicolaskruchten** [comment]
can you give me an example of the JSON you're passing into the `pivotUI()` call?

**Comment by frankernesto87** [comment]
Of curse , here it is:
this is configuration JSON
{"rendererOptions":{"localeStrings":{"renderError":"Ocurrió un error
durante la interpretación de la tabla dinámica.","computeError":"Ocurrió un
error durante el cálculo de la tabla dinámica.","uiRenderError":"Ocurrió un
error durante el dibujado de la tabla dinámica.","selectAll":"Seleccionar
todo","selectNone":"Deseleccionar todo","tooMany":"(demasiados
valores)","filterResults":"Filtrar
resultados","apply":"Apply","cancel":"Cancel","totals":"Totales","vs":"vs","by":"por"},"rowSubtotalDisplay":{"disableExpandCollapse":true},"colSubtotalDisplay":{"disableExpandCollapse":true}},"localeStrings":{"renderError":"Ocurrió
un error durante la interpretación de la tabla
dinámica.","computeError":"Ocurrió un error durante el cálculo de la tabla
dinámica.","uiRenderError":"Ocurrió un error durante el dibujado de la
tabla dinámica.","selectAll":"Seleccionar todo","selectNone":"Deseleccionar
todo","tooMany":"(demasiados valores)","filterResults":"Filtrar
resultados","apply":"Apply","cancel":"Cancel","totals":"Totales","vs":"vs","by":"por"},"derivedAttributes":{},"aggregators":{},"renderers":{},"hiddenAttributes":[],"menuLimit":500000,"cols":[],"rows":["Nombres","Apellidos","PlazasEnlazada","PlazasCancelada","Oficio","Jornada","Localizacion","Ejecutor","CodEmpleado","Sexo","Baja","Salario","PlazaTarifa"],"vals":[],"rowOrder":"key_a_to_z","colOrder":"key_a_to_z","exclusions":{},"inclusions":{},"unusedAttrsVertical":false,"autoSortUnusedAttrs":false,"sorters":{},"aggregatorName":"Cuenta","inclusionsInfo":{},"rendererName":"Table"}

And this is my data source:

[{"Plaza":"OPERARIO DE MANTENIMIENTO A EQUIPOS E
INSTALACIONES","EstadoPlaza":"Vacantes:    0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"JEFE
DE BRIGADA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0003086351","Nombres":"RICARDO","Apellidos":"VALDEZ
BORREGO","Sexo":"Masculino","Baja":"No","Salario":1260,"PlazaTarifa":6.05},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO CONSTRUCTIVO","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0001421817","Nombres":"JORGE
LUIS","Apellidos":"FERNANDEZ
VEGA","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO CONSTRUCTIVO","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009138766","Nombres":"LORENZO
RICARDO","Apellidos":"PESTANO
LORENZO","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"JEFE
DE BRIGADA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO CONSTRUCTIVO","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009562082","Nombres":"NOEL","Apellidos":"ZAYAS
BALTAD","Sexo":"Masculino","Baja":"No","Salario":1260,"PlazaTarifa":6.05},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO","Jornada":"JORNADA
8 H","Localizacion":"//HOTEL PARQUE CENTRAL/DIRECCION","Ejecutor":"BRIGADA
DE MANTENIMIENTO","CodEmpleado":"0003110858","Nombres":"CARLOS
ERNESTO","Apellidos":"CASTELLANOS
ESTEVEZ","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009545572","Nombres":"ADOLIS
FRANSISCO","Apellidos":"NARANJO
PEREZ","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA OPERARIOS ( 14/22)","Localizacion":"//HOTEL
PARQUE CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS
NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009556063","Nombres":"ARISTIDES","Apellidos":"LANDA
GONZALEZ","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA OPERARIOS ( 19/7)","Localizacion":"//HOTEL
PARQUE CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS
NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009130117","Nombres":"ROBERTO","Apellidos":"ALVAREZ
HERRERA","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA OPERARIOS ( 14/22)","Localizacion":"//HOTEL
PARQUE CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS
NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"59081300947","Nombres":"VICENTE","Apellidos":"BLANCO
TRIBIÑO","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"68111414946","Nombres":"RICARDO","Apellidos":"GONZALEZ
BONACHEA","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009141799","Nombres":"AGUSTIN","Apellidos":"CUELLAR
FUENTES","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009556391","Nombres":"ALFREDO","Apellidos":"GARCIA
CRESPO","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009545734","Nombres":"BONIFACIO","Apellidos":"MEJIAS
JORGE","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009546844","Nombres":"JORGE
LUIS","Apellidos":"GONZALEZ
PEREIRA","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009550821","Nombres":"LEONARDO","Apellidos":"GONZALEZ
DUARTE","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0003094340","Nombres":"LEONARDO
ALFONSO","Apellidos":"PARAPAR
VAZQUEZ","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009565149","Nombres":"PEDRO
JOSE","Apellidos":"DURAND
FERRER","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIOS
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES","EstadoPlaza":"Vacantes:
 0Ocupadas:
8","PlazasAprobadas":8,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009543076","Nombres":"YANIER
RAMON","Apellidos":"VILLAVERDE
FEBLES","Sexo":"Masculino","Baja":"No","Salario":1100,"PlazaTarifa":5.28},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES J
BRIGADA","EstadoPlaza":"Vacantes:    0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"JEFE
DE BRIGADA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009553337","Nombres":"CARLOS","Apellidos":"OTERO
VALDEZ","Sexo":"Masculino","Baja":"No","Salario":1200,"PlazaTarifa":5.76},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES J
BRIGADA","EstadoPlaza":"Vacantes:    0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"JEFE
DE BRIGADA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009546531","Nombres":"WILFREDO","Apellidos":"ACOSTA
LEYVA","Sexo":"Masculino","Baja":"No","Salario":1200,"PlazaTarifa":5.76},{"Plaza":"TECNICOS
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OPERARIO
DE HABITACIONES","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS DE
HABITACIONES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009568979","Nombres":"PABLO
LAZARO","Apellidos":"SPECHT
VIDABUR","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"TECNICOS
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0000466072","Nombres":"EYNIER","Apellidos":"FREYRE
GARCIGA","Sexo":"Masculino","Baja":"No","Salario":1220,"PlazaTarifa":5.86},{"Plaza":"TECNICOS
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
2","PlazasAprobadas":2,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0000440243","Nombres":"MIGUEL
ANGEL","Apellidos":"COBO
MONSERRAT","Sexo":"Masculino","Baja":"No","Salario":1220,"PlazaTarifa":5.86},{"Plaza":"TECNICOS
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
3","PlazasAprobadas":3,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"TECNICO","Jornada":"JORNADA
8 H","Localizacion":"//HOTEL PARQUE CENTRAL/DIRECCION","Ejecutor":"BRIGADA
DE
MANTENIMIENTO","CodEmpleado":"0009544727","Nombres":"GABRIEL","Apellidos":"CASTELLANO
CASANOVA","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"TECNICOS
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
3","PlazasAprobadas":3,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"TECNICO","Jornada":"JORNADA
8 H","Localizacion":"//HOTEL PARQUE CENTRAL/DIRECCION","Ejecutor":"BRIGADA
DE MANTENIMIENTO","CodEmpleado":"0003088254","Nombres":"OLGA
LIDIA","Apellidos":"FERNANDEZ
COLON","Sexo":"Femenino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"TECNICOS
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
3","PlazasAprobadas":3,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"TECNICO","Jornada":"JORNADA
8 H","Localizacion":"//HOTEL PARQUE CENTRAL/DIRECCION","Ejecutor":"BRIGADA
DE MANTENIMIENTO","CodEmpleado":"0009565228","Nombres":"RICARDO
SERAFIN","Apellidos":"PEREIRA
FERRO","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"ESPECIALISTA
B EN SERVICIOS TECNICOS","EstadoPlaza":"Vacantes:    0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"ESPECIALISTA
B.","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/DIRECCION","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0000448183","Nombres":"ROGELIO","Apellidos":"GARCIA
LINARES","Sexo":"Masculino","Baja":"No","Salario":1220,"PlazaTarifa":5.86},{"Plaza":"ESPECIALISTA
C EN AHORRO Y USO DE ENERGIA","EstadoPlaza":"Vacantes:    0Ocupadas:

1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"ESPECIALISTA
C.","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/DIRECCION","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0003693814","Nombres":"ANTONIO DE LA
C","Apellidos":"VIART
GALAN","Sexo":"Masculino","Baja":"No","Salario":1280,"PlazaTarifa":6.15},{"Plaza":"TECNICO
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA OPERARIOS ( 19/7)","Localizacion":"//HOTEL
PARQUE CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS
NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0000432455","Nombres":"CARLOS
MIGUEL","Apellidos":"GONZALEZ
MORENO","Sexo":"Masculino","Baja":"No","Salario":1220,"PlazaTarifa":5.86},{"Plaza":"TECNICO
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009135389","Nombres":"LUIS
MANUEL","Apellidos":"ALMAGUER
ORTA","Sexo":"Masculino","Baja":"No","Salario":1160,"PlazaTarifa":5.57},{"Plaza":"TECNICO
EN SERVICIOS TECNICOS PARA EL TURISMO","EstadoPlaza":"Vacantes:
 0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"OFICIAL
DE PRIMERA","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL PARQUE
CENTRAL/BRIGADA DE MANTENIMIENTO EN AREAS NOBLES","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"0009567426","Nombres":"SERGIO
A.","Apellidos":"FUNDORA
HERNANDEZ","Sexo":"Masculino","Baja":"No","Salario":1220,"PlazaTarifa":5.86},{"Plaza":"OPERARIO
DE MANTENIMIENTO A EQUIPOS E INSTALACIONES J
SERV.TEC","EstadoPlaza":"Vacantes:    0Ocupadas:
1","PlazasAprobadas":1,"PlazasEnlazada":true,"PlazasCancelada":0,"Oficio":"JEFE
DE SERVICIOS TECNICOS","Jornada":"JORNADA 8 H","Localizacion":"//HOTEL
PARQUE CENTRAL/DIRECCION","Ejecutor":"BRIGADA DE
MANTENIMIENTO","CodEmpleado":"581484","Nombres":"JUAN
CARLOS","Apellidos":"RUZ
ZUBIRI","Sexo":"Masculino","Baja":"No","Salario":1600,"PlazaTarifa":7.69}]

Hope this hepls


2017-08-31 9:39 GMT-05:00 Nicolas Kruchten <notifications@github.com>:

**Comment by nicolaskruchten** [comment]
the problem is that you're passing empty objects for `aggregators` and `renderers` so the default ones aren't loaded. You either need to not pass in those parameters or pass in an object of functions.

**Comment by frankernesto87** [comment]
renderers solved!!!, 
before pass my config as parameter I set it as:
var renderers = $.extend($.pivotUtilities.renderers, $.pivotUtilities.c3_renderers, $.pivotUtilities.subtotal_renderers);
conf_pivot["renderers"] = renderers;
Now , is there a way to set aggregators as well??, I think is the only one thing missing for my goal

**Comment by nicolaskruchten** [comment]
Yes, the default aggregators are available at `$.pivotUtilities.aggregators`.

**Comment by frankernesto87** [comment]
Thanks nicolas, now it works, but I have a new issue,
I was trying to save config after loading my pivot via a previous config
json, I'm using subtotals renderer .
If I load pivot normally, without a loaded config , subtotals works, but If
load it by a config , I get this error (attached pic), It only happends
with subtotals, the rest of then are ok.

This is how I'm building my config:

var renderers = $.extend($.pivotUtilities.renderers,
$.pivotUtilities.c3_renderers, $.pivotUtilities.subtotal_renderers);
var aggs = $.pivotUtilities.aggregators.Cuenta;
conf_pivot = JSON.parse(conf_pivot);
conf_pivot["renderers"] = renderers;
conf_pivot["aggregators"] = aggs;
conf_pivot.rendererOptions = {
    rowSubtotalDisplay: {
        disableExpandCollapse: true
    },
    colSubtotalDisplay: {
        disableExpandCollapse: true
    }
};
conf_pivot.onRefresh = saveState;


$('#pivot').pivotUI(origin_data, conf_pivot, true, 'es');

Thanks a lot

2017-08-31 11:26 GMT-05:00 Nicolas Kruchten <notifications@github.com>:

**Comment by nicolaskruchten** [comment]
there was no image uploaded... I should add that issues with Subtotal.js should be address to that repo, not here: https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer

**Comment by frankernesto87** [comment]
Solved!!, I was  missing dataClass parameter, sorry for the disturbs and
thanks a lot, your library 's great for our work.


---------- Forwarded message ----------

**Comment by nicolaskruchten** [comment]
awesome! glad you're all sorted out :)
