### ISSUE TITLE
Zero's getting truncated

### ISSUE THREAD

**Issue by chaitanmk** [nicolaskruchten/pivottable#751]
Hi,

in graph on mouse over it is showing GearVal as 20.5 instead of 20.50. It is truncating 0 in decimal part. can you please let me know how we can fix it.

var input=	[{"Day":"2017-05-01","GearId":"1","GearVal":"20.50"},{"Day":"2017-05-01","GearId":"2","GearVal":"10.23"}];
var tpl = $.pivotUtilities.aggregatorTemplates;
var aggregatorValue = {'Gear Utilization (%)': function() {return tpl.sum()(["GearVal"])}};
$("#output").pivotUI(
input, {
rows: ["GearId"],
cols: ["Day"],
aggregators: aggregatorValue,
rendererName: "Stacked Bar Chart",
renderers: $.extend(
$.pivotUtilities.renderers,
$.pivotUtilities.c3_renderers
)
});

thanks in adavance

**Comment by nicolaskruchten** [comment]
Unfortunately, this is an issue in the underlying charting library, which is out of my hands... Sorry.

**Comment by nicolaskruchten** [comment]
This was actually not a bug in the underlying library but rather one in this library, and which has been fixed :)

**Comment by chaitanmk** [comment]
Hi Nicolas,

Can you please let me know what changes you made to resolve it.

Thank you.

Regards,
Krishna M

**Comment by nicolaskruchten** [comment]
See this commit: 854d821b1727b0b85f65d709fd7d0ab610a4cc06

**Comment by nicolaskruchten** [comment]
Specifically line 73 of the change to `src/c3_renderers.coffee`

**Comment by chaitanmk** [comment]
Hi,

we are not using c3_renderers.coffee file. we are using c3.min.js, pivot.min.js, c3_renderers.min.js and d3.min.js files.

**Comment by nicolaskruchten** [comment]
`c3_renderers.min.js` is the compiled output of `c3_renderers.coffee`.

In any case, just upgrade to the latest version and you're good  to go.

**Comment by chaitanmk** [comment]
Hi,

I made those changes in c3_renderers.min.js. but before coming to that
isFinite condition, value is showing with truncated zeros.

Regards,
Krishna M


On Aug 3, 2017 7:31 PM, "Nicolas Kruchten" <notifications@github.com> wrote:

c3_renderers.min.js is the compiled output of c3_renderers.coffee.

In any case, just upgrade to the latest version and you're good to go.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nicolaskruchten/pivottable/issues/751#issuecomment-319977781>,
or mute the thread

**Comment by nicolaskruchten** [comment]
I recommend you just upgrade *all the files* to the latest version, including `pivot.min.js` etc. I can't provide any help if you just patch certain files and don't use the full versioned release of this library :)

**Comment by chaitanmk** [comment]
Hi Nicolas,

i taken update from your c3_renderers.min.js file and now it is showing zeros after decimal point. 

Thank you for your support :)
