### ISSUE TITLE
Pivot.js

### ISSUE THREAD

**Issue by venkateshr8849** [nicolaskruchten/pivottable#753]
Hey man,
   I have set of chart data with col set and group set in Json format. Now ,I wanna to populate chart based on my chart data...

Shall u help me...:)

**Comment by nicolaskruchten** [comment]
You're going to need to give me some more details here... what does your data look like? what kind of chart do you want? Are there any examples at https://pivottable.js.org/ which look like what you want?

**Comment by venkateshr8849** [comment]
I generate a chart in different tool.Then I take the data for a chart. 
Now I wanna to feed that data (main format) in to the pivot.js then pivot has to flat chart what i got in the another tool..

**Comment by venkateshr8849** [comment]
I I generate a chart in different tool.Then I took the data for a chart. It has group of columns  and each cell value.
Now I wanna to feed that data (json format) in to the pivot.js then pivot has to flat chart what i got in the another tool...is it possible??

**Comment by nicolaskruchten** [comment]
I don't understand, I'm sorry. Can you give me some concrete examples, like the actual data or some screenshots of the chart?

**Comment by venkateshr8849** [comment]
result : {data : {"combinedGroup":"Year of invoicedate_Month of invoicedate","chartData":[[[["2011_1",1,["2011","1"]],["2011_2",3,["2011","2"]],["2011_3",1,["2011","3"]],["2011_4",8,["2011","4"]],["2011_5",9,["2011","5"]],["2011_6",5,["2011","6"]],["2011_7",140,["2011","7"]],["2011_8",208,["2011","8"]],["2011_9",274,["2011","9"]],["2011_10",303,["2011","10"]],["2011_11",256,["2011","11"]],["2011_12",377,["2011","12"]],["2012_1",350,["2012","1"]],["2012_2",267,["2012","2"]],["2012_3",335,["2012","3"]],["2012_4",276,["2012","4"]],["2012_5",318,["2012","5"]],["2012_6",302,["2012","6"]],["2012_7",394,["2012","7"]],["2012_8",422,["2012","8"]],["2012_9",373,["2012","9"]],["2012_10",411,["2012","10"]],["2012_11",384,["2012","11"]],["2012_12",330,["2012","12"]],["2013_1",490,["2013","1"]],["2013_2",382,["2013","2"]],["2013_3",523,["2013","3"]],["2013_4",427,["2013","4"]],["2013_5",389,["2013","5"]],["2013_6",461,["2013","6"]],["2013_7",477,["2013","7"]],["2013_8",454,["2013","8"]],["2013_9",424,["2013","9"]],["2013_10",461,["2013","10"]],["2013_11",466,["2013","11"]],["2013_12",459,["2013","12"]],["2014_1",496,["2014","1"]],["2014_2",468,["2014","2"]],["2014_3",590,["2014","3"]],["2014_4",457,["2014","4"]],["2014_5",463,["2014","5"]],["2014_6",494,["2014","6"]],["2014_7",562,["2014","7"]],["2014_8",3862,["2014","8"]],["2014_9",30919,["2014","9"]],["2014_10",30547,["2014","10"]],["2014_11",29623,["2014","11"]],["2014_12",29582,["2014","12"]],["2015_1",30251,["2015","1"]],["2015_2",29810,["2015","2"]],["2015_3",30891,["2015","3"]],["2015_4",30285,["2015","4"]],["2015_5",29989,["2015","5"]],["2015_6",30056,["2015","6"]],["2015_7",30391,["2015","7"]],["2015_8",30155,["2015","8"]],["2015_9",30328,["2015","9"]],["2015_10",30550,["2015","10"]],["2015_11",30004,["2015","11"]],["2015_12",30347,["2015","12"]],["2016_1",30866,["2016","1"]],["2016_2",30410,["2016","2"]],["2016_3",31425,["2016","3"]],["2016_4",30199,["2016","4"]],["2016_5",30634,["2016","5"]],["2016_6",30506,["2016","6"]],["2016_7",30557,["2016","7"]],["2016_8",30855,["2016","8"]],["2016_9",30980,["2016","9"]],["2016_10",31314,["2016","10"]],["2016_11",31497,["2016","11"]],["2016_12",31664,["2016","12"]],["2017_1",32230,["2017","1"]],["2017_2",37971,["2017","2"]],["2017_3",40059,["2017","3"]],["2017_4",38710,["2017","4"]],["2017_5",40174,["2017","5"]],["2017_6",39636,["2017","6"]],["2017_7",28628,["2017","7"]]]],[[["2011_1",154,["2011","1"]],["2011_2",2640,["2011","2"]],["2011_3",192,["2011","3"]],["2011_4",2425,["2011","4"]],["2011_5",4627,["2011","5"]],["2011_6",3072,["2011","6"]],["2011_7",523092.01999999996,["2011","7"]],["2011_8",706467.1900000001,["2011","8"]],["2011_9",847577.7304444443,["2011","9"]],["2011_10",836550.0895555556,["2011","10"]],["2011_11",823679.5297777777,["2011","11"]],["2011_12",911302.4326666666,["2011","12"]],["2012_1",1019405.7804,["2012","1"]],["2012_2",773071.3557999999,["2012","2"]],["2012_3",1019086.4929999999,["2012","3"]],["2012_4",1033426.8980000002,["2012","4"]],["2012_5",1069905.9962,["2012","5"]],["2012_6",1131836.2185999998,["2012","6"]],["2012_7",1266591.7785999998,["2012","7"]],["2012_8",1221991.5163636364,["2012","8"]],["2012_9",1256988.6334545456,["2012","9"]],["2012_10",1355944.2835849056,["2012","10"]],["2012_11",1383766.335,["2012","11"]],["2012_12",1559867.2256880733,["2012","12"]],["2013_1",1794868.042,["2013","1"]],["2013_2",1492408.7555140187,["2013","2"]],["2013_3",1612612.9882568808,["2013","3"]],["2013_4",1699921.6261467892,["2013","4"]],["2013_5",1705731.0926605505,["2013","5"]],["2013_6",1752421.9080530973,["2013","6"]],["2013_7",1943922.441333333,["2013","7"]],["2013_8",1929301.1122295621,["2013","8"]],["2013_9",2051318.9026313385,["2013","9"]],["2013_10",2162203.521529412,["2013","10"]],["2013_11",2203062.394716001,["2013","11"]],["2013_12",2605045.034727766,["2013","12"]],["2014_1",2517501.8349571964,["2014","1"]],["2014_2",2479728.7354896907,["2014","2"]],["2014_3",2754622.9243775103,["2014","3"]],["2014_4",2712974.053573184,["2014","4"]],["2014_5",2916005.2264943672,["2014","5"]],["2014_6",2768203.946196257,["2014","6"]],["2014_7",2964245.842988448,["2014","7"]],["2014_8",3178261.6773226773,["2014","8"]],["2014_9",5602769.87958949,["2014","9"]],["2014_10",3085029.3743246794,["2014","10"]],["2014_11",3067322.3005575477,["2014","11"]],["2014_12",3905053.4399837926,["2014","12"]],["2015_1",3420767.092470119,["2015","1"]],["2015_2",3270718.738025069,["2015","2"]],["2015_3",3605728.8133526766,["2015","3"]],["2015_4",3390474.693314652,["2015","4"]],["2015_5",3503229.167649403,["2015","5"]],["2015_6",3611724.6617868347,["2015","6"]],["2015_7",3792753.2084466014,["2015","7"]],["2015_8",3780470.053878674,["2015","8"]],["2015_9",3670585.8994974643,["2015","9"]],["2015_10",3870411.911851405,["2015","10"]],["2015_11",3794798.6862957277,["2015","11"]],["2015_12",5189923.817840289,["2015","12"]],["2016_1",4438220.377717718,["2016","1"]],["2016_2",4211522.637360593,["2016","2"]],["2016_3",4421738.311254399,["2016","3"]],["2016_4",4179312.9414980602,["2016","4"]],["2016_5",4515781.9155017305,["2016","5"]],["2016_6",4337211.5457988335,["2016","6"]],["2016_7",4522762.312927191,["2016","7"]],["2016_8",4623797.467321826,["2016","8"]],["2016_9",4652384.077054078,["2016","9"]],["2016_10",4829584.989310758,["2016","10"]],["2016_11",4842570.3564605415,["2016","11"]],["2016_12",6761514.990056685,["2016","12"]],["2017_1",5053900.718343302,["2017","1"]],["2017_2",5410244.850537789,["2017","2"]],["2017_3",5554876.189886836,["2017","3"]],["2017_4",5206694.603966952,["2017","4"]],["2017_5",5442770.932535092,["2017","5"]],["2017_6",5686198.916162719,["2017","6"]],["2017_7",3827878.3740560506,["2017","7"]]]]],"sortType":0,"lensTitle":"","colSet":["Count of Rows","Sum of totalinusd"],"groupSet":["Year of invoicedate","Month of invoicedate"]},    


.........this is the json data it has the information of chart type, aggregator, and group of columns....when I feed these information to the pivot .js.. which has to give the same chart what i got in the different tool

**Comment by nicolaskruchten** [comment]
OK, now I see. The bad news is that there's no built-in way to do this, you're going to have to do a lot of parsing and transforming of this object to be able to feed it to PivotTable.js.

**Comment by venkateshr8849** [comment]
Okay thank u...:)
One more question...in your pivottable.js  ,After the aggregation which fuction is used to feed a data to the chart renders.

And how u feed data to the cells in the record..
What function u used??

**Comment by nicolaskruchten** [comment]
The charting library is http://c3js.org/ if that's what you mean...

**Comment by venkateshr8849** [comment]
Thank u!!!!


And I wanna to hide attribute value while click the small triangle button in the attribute ??

Reason is i gonna to use all the attribute values...so I don't need it to display all attribute value

Is it possible?

**Comment by nicolaskruchten** [comment]
You can't disable the triangles, no.

**Comment by venkateshr8849** [comment]
Do u have any example code for inclusions and exclusions??

**Comment by nicolaskruchten** [comment]
You can see the configuration object here: https://pivottable.js.org/examples/onrefresh.html ... try some checking/unchecking some boxes and you'll see.

The full documentation is here and it's very straightforward: https://github.com/nicolaskruchten/pivottable/wiki/Parameters#pivotuiinput-options-overwrite-locale
