### ISSUE TITLE
Constraint attributes in aggregation function

### ISSUE THREAD

**Issue by AntonPerm** [nicolaskruchten/pivottable#754]
Hello.

Is there a way to constraint attributes list that available to use as aggregation function argument. E.g in select pvtAttrDropdown, we dont want to calculate sum of field's values  "Province".
https://jsfiddle.net/dbmcnymv/

Thanks for help.

**Comment by nicolaskruchten** [comment]
There's no way to do this at the moment, no, unfortunately. Issue #191 would be a great way to do it but I haven't found a reasonable implementation yet :)

**Comment by mogliang** [comment]
by default, pivottable uses same collection to render cols/rows and aggregation list. A workaround would be set aggregation attribute list manually.

https://github.com/mogliang/pivottable/commit/b3af3341e044e798a950e41cf4a54ddc1431d56d

**Comment by nicolaskruchten** [comment]
I've just merged the changes from #408 and added the `hiddenFromAggregators` and `hiddenFromDragDrop` parameters, which may be of use here.

**Comment by AntonPerm** [comment]
Thank you for your help)
