### ISSUE TITLE
About - Writing your own aggregators

### ISSUE THREAD

**Issue by miclessepaq** [nicolaskruchten/pivottable#757]
Hello Nicolas, you have made a whole project it is truly exceptional to share it. 
I intend to implement your plugin in my APEX applications. 
The only thing I would miss is an aggregate for string values, concatenate it. 
If I write a custom function in this style,
     _function (aggStringValues, aggStringSeparetor) {
                    Return aggStringValues.join (aggStringSeparetor); Will your plugin support it?__

Should I implant it?
If I just have to do it is not so bad :-)

Exemple:
![image](https://user-images.githubusercontent.com/15946685/29005161-13ed02d2-7aa3-11e7-818b-1813e15df419.png)

Thank you

**Comment by nicolaskruchten** [comment]
Glad you like this library.

There is a built-in aggregator called "List Unique Values" which does what
you describe, although maybe you want to show duplicates, in which case you
will need to modify it slightly...

**Comment by miclessepaq** [comment]
Thanks a lot !!!! 

Envoyé de mon iPhone
