### ISSUE TITLE
Not able to restore the saved options

### ISSUE THREAD

**Issue by sujeetsks** [nicolaskruchten/pivottable#758]
I want to save and restore the options(rows, cols, vals,aggregatorname, renderername ). 
I have saved the rows, cols, vals, aggregatorname, renderername separately into the data base by separating each of them from 

```javascript
var config = $("#output").data("pivotUIOptions");
var config_copy = JSON.parse(JSON.stringify(config));
var cols = config_copy["cols"];
 var rows = config_copy["rows"];
  var vals = config_copy["vals"];
 var aggregatorName = config_copy["aggregatorName"];
 var rendererName = config_copy["rendererName"];
  var unusedattrsVertical = config_copy["unusedAttrsVertical"];
   var menuLimit = config_copy["menuLimit"];
```

Again I am able to read the mentioned options from database correctly and want to restore.
Here is my code

```javascript
       $("#output").pivotUI(
      $.pivotUtilities.tipsData, {
          rows: rows,      // saved rows from database
          cols: cols,        // saved cols from database
          aggregatorName: aggregatorName ,  //saved aggregatorName from database
          rendererName: rendererName ,      //saved rendererName  from database
          renderers: $.extend(
              $.pivotUtilities.renderers,
            $.pivotUtilities.c3_renderers
          )
      });
```

But it does not rendered, Can anyone help me regarding this if already achieved the mentioned one.

**Comment by nicolaskruchten** [comment]
When you say "does not render" what do you mean? Does it show an error or...? Please note that the dataset you're passing in is the demo "tips" dataset: `$.pivotUtilities.tipsData`, and it's only available if you load that specific JS file.

**Comment by sujeetsks** [comment]
$.pivotUtilities.tipsData is my json data Here I have assign it using the ajax call.

This now working fine for me I have added like this.

$("#output").pivotUI(
      $.pivotUtilities.tipsData, {  
          rows: [rowsname],   //saved rows from database
          cols: [colsname],     //saved cols from database
          vals: [valsname],     //saved vals from database
          aggregatorName: aggregator,
          rendererName: renderer,
          renderers: $.extend(
              $.pivotUtilities.renderers,
            $.pivotUtilities.c3_renderers
          )
      });

Thanks..

**Comment by sujeetsks** [comment]
Thanks... It Works for me..
