### ISSUE TITLE
showing functions on columns

### ISSUE THREAD

**Issue by DiogoMoreira0610** [nicolaskruchten/pivottable#759]
Hello.

Very good your control.

I'm having a problem while generating a PIVOT. The Control is displaying the Javascript functions in the columns, with a simple array in JSON.

What can I be doing wrong?

My Array:
    var dados = [
        { "RecID": 1, "ProjetoID": 11, "WbsID": 4, "Mes": 9, "Ano": 2017, "VlPlanejado": 1000.0000, "VlConfirmado": 0.0000, "Tipo": "MOB" },
        { "RecID": 2, "ProjetoID": 11, "WbsID": 4, "Mes": 9, "Ano": 2017, "VlPlanejado": 2000.0000, "VlConfirmado": 1800.0000, "Tipo": "MOB" },
        { "RecID": 3, "ProjetoID": 11, "WbsID": 4, "Mes": 8, "Ano": 2017, "VlPlanejado": 3000.0000, "VlConfirmado": 0.0000, "Tipo": "MOB" },
        { "RecID": 4, "ProjetoID": 11, "WbsID": 4, "Mes": 11, "Ano": 2017, "VlPlanejado": 5000.0000, "VlConfirmado": 0.0000, "Tipo": "MOB" },
        { "RecID": 6, "ProjetoID": 11, "WbsID": 4, "Mes": 12, "Ano": 2017, "VlPlanejado": 5000.0000, "VlConfirmado": 0.0000, "Tipo": "MOB" },
        { "RecID": 7, "ProjetoID": 11, "WbsID": 4, "Mes": 1, "Ano": 2018, "VlPlanejado": 3000.0000, "VlConfirmado": 0.0000, "Tipo": "MOB" }
    ];

My JQuery Call:
    $("#pivotFuncoes").pivot(dados,
        {
            rows: ["Tipo"],
            cols: ["Periodo"],
            vals: ["Valor"],
            aggregatorName: 'Sum',
            rendererName: 'Table'
        });

**Comment by DiogoMoreira0610** [comment]
I changed the array to:

[{"Mes":8,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"1-Planejado","Valor":3000.00,"RecID":3},{"Mes":8,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"2-Confirmado","Valor":0.00,"RecID":3},{"Mes":9,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"1-Planejado","Valor":1000.00,"RecID":1},{"Mes":9,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"1-Planejado","Valor":2000.00,"RecID":2},{"Mes":9,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"2-Confirmado","Valor":0.00,"RecID":1},{"Mes":9,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"2-Confirmado","Valor":1800.00,"RecID":2},{"Mes":11,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"1-Planejado","Valor":5000.00,"RecID":4},{"Mes":11,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"2-Confirmado","Valor":0.00,"RecID":4},{"Mes":12,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"2-Confirmado","Valor":0.00,"RecID":6},{"Mes":12,"Ano":2017,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"1-Planejado","Valor":5000.00,"RecID":6},{"Mes":1,"Ano":2018,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"1-Planejado","Valor":3000.00,"RecID":7},{"Mes":1,"Ano":2018,"WbsID":4,"WBS":"000 - PROJETO","Tipo":"2-Confirmado","Valor":0.00,"RecID":7}]

and JS to:
    $("#pivotFuncoes").pivot(dados,
        {
            rows: ["Tipo"],
            cols: ["Ano", "Mes"],
            vals: ["Valor"],
            aggregatorName: 'Sum',
            rendererName: 'Table'
        });

but have no effect.

still getting:

![image](https://user-images.githubusercontent.com/27218524/29171820-2e5d60bc-7db4-11e7-8f1d-eb91077b9d71.png)

**Comment by nicolaskruchten** [comment]
Most likely you have loaded some other library which adds functions to the `Array` prototype, which is not well-supported by this library unfortunately.

**Comment by DiogoMoreira0610** [comment]
Thanks for you help.
