### ISSUE TITLE
Could be possible to enable the sort icons of pivottablejs in Jupyer Notebook?

### ISSUE THREAD

**Issue by lgonzalezsa** [nicolaskruchten/pivottable#760]
Hello,

In first place, great tool. 
I was looking a way to enable the sort buttons/icons to sort the values in the pivot table. I create a question in StackOverflow:

Could be possible to enable the sort icons of pivottablejs in Jupyer Notebook?
https://stackoverflow.com/q/45578534/1729896?sem=2

Hope this can be done using Jupyter.

Luis

**Comment by nicolaskruchten** [comment]
Are you using the latest version of the `pivottablejs` Python module? It should support this feature now.

**Comment by lgonzalezsa** [comment]
I am using anaconda and the pivottablejs version is 2.7.0 (under py36_0).
Here an example:
![2017-08-14_9-08-27](https://user-images.githubusercontent.com/704686/29277905-57de8f28-80d0-11e7-89dd-7d3207417c1a.png)

**Comment by nicolaskruchten** [comment]
You'll have to upgrade to version 0.8.0 of the `pivottablejs` module to get this functionality.

**Comment by nicolaskruchten** [comment]
If you're installing using `conda` then unfortunately you're not using the official version of this project, but rather this one: https://github.com/ContinuumIO/pivottablejs and the maintainer is not being very cooperative with me :(

**Comment by lgonzalezsa** [comment]
Got it, but that's the beauty to have pip supported as well. Changing it to your code and works perfectly!
Thank you sir!
![2017-08-14_9-25-52](https://user-images.githubusercontent.com/704686/29278705-c519885c-80d2-11e7-975d-16c1bc91e461.png)
