### ISSUE TITLE
get data from specific element <td>

### ISSUE THREAD

**Issue by huss66n** [nicolaskruchten/pivottable#763]
I want when I click on specific element show me the data on the parent element in alert

![5005c6943aa04348acc0e0a95b6c9adf](https://user-images.githubusercontent.com/30974292/29249458-6d5a326e-8038-11e7-81a1-4da35f8ad161.png)

**Comment by nicolaskruchten** [comment]
This is not currently supported by this library, so you'll have to use jQuery to add events to the table to handle these clicks.

**Comment by nicolaskruchten** [comment]
You can probably use the `clickCallback` mechanism to do something similar to this by reading the `filter` object: https://pivottable.js.org/examples/mps_prepop.html
