### ISSUE TITLE
how to use with vue

### ISSUE THREAD

**Issue by ibmsoft** [nicolaskruchten/pivottable#764]
i use npm install jquery-ui,pivottable
then in the bootstrap.js

`

 window.$ = window.jQuery = require('jquery');
 window.$ = $.extend(require('jquery-ui'));
 window.$.pivotUI = $.extend(require('pivottable'));

`
then in the pivot.vue
`
  mounted() {
            $("#output").pivotUI(
                [
                    {color: "blue", shape: "circle"},
                    {color: "red", shape: "triangle"}
                ],
                {
                    rows: ["color"],
                    cols: ["shape"]
                }
            );
        }
`
i get the following error
TypeError: opts.filter is not a function

is there any document for the right usage with vue ? thanks

**Comment by ibmsoft** [comment]
resolved

**Comment by espositodaniele** [comment]
@ibmsoft  how did you solve this? I'm getting the same error.

**Comment by mahmutcetin** [comment]
anyone else solved the problem? I'm getting the same error.

**Comment by swuecho** [comment]
@mahmutcetin This works perfectly. I have some problem in making the plot work. Is it possible  in vue?
