### ISSUE TITLE
Overall Column total based on Column definition 

### ISSUE THREAD

**Issue by SethuICOMM** [nicolaskruchten/pivottable#765]
Hi,

I am using Pivot table Js for my project and want to show the column total (split up) based on column definition.

In my table , row is company and column is employment status and Year (which means Trainee for 2016-17 & 2017-18).
 
![1](https://user-images.githubusercontent.com/26506467/29398189-de16f086-8340-11e7-99ca-82ce6150f7dd.png)
![2](https://user-images.githubusercontent.com/26506467/29398190-de2dd422-8340-11e7-9cfc-413ad2f25e99.png)

I want total to be split into 2 (2016-17 & 2017-18).

how do i achieve this.

Regards
Sethu

**Comment by nicolaskruchten** [comment]
Unfortunately that isn't possible with this library using any built-in
functionality. If you want to use this library for a UI, you will need to
create your own Renderer, likely based on a fork of the SubTotal.js project.

**Comment by SethuICOMM** [comment]
Thank you

**Comment by SethuICOMM** [comment]
Is there any chance to help me out to achieve this. It wuld be good for my project.

Sethu

**Comment by nicolaskruchten** [comment]
I'm sorry but I don't have time, sorry :(

**Comment by SethuICOMM** [comment]
No Problem.
