### ISSUE TITLE
multiple choice survey

### ISSUE THREAD

**Issue by gomedya** [nicolaskruchten/pivottable#768]
i have an example survey with following questions:

gender (m/f) single choice
favorite color (red/blue/green/..) multiple choice
favorite animal (cat/dog/etc/..) multiple choice

how would I represent answers of this survey in code or in csv so pivottable can process it?
this format is good for single choice answers but multiple multiple choice answers seems like a challenge..
[
                {color: "blue", shape: "circle", value: 1},
                {color: "red", shape: "triangle", value: 2},
                {color: "blue", shape: "circle", value: 3},
                {color: "red", shape: "triangle", value: 4}
            ],

thanks.

**Comment by nicolaskruchten** [comment]
I think you're right that multiple-choice data is going to be hard to use with this library, unfortunately.

**Comment by gomedya** [comment]
ok, thanks
