### ISSUE TITLE
pivot save load state

### ISSUE THREAD

**Issue by frankernesto87** [nicolaskruchten/pivottable#770]
Hi again nicolas!!
I'm facing a new problem with save and load state from pivotui , I'm saving pivot conf to DB, but when I try to restore it I'm getting this:
 "pivot.coffee:932 Uncaught TypeError: D.aggregators[u.val(...)] is not a function
    at pivot.coffee:932 (anonymous) @ pivot.coffee:932". 
My conf loads unused fields and rows , but is not able to load the data table, renderers and aggregators. For some reason I could 't upload an image but I sended it by email for yo to hace a clear vision

 any help??
regards Frank

**Comment by nicolaskruchten** [comment]
OK, this is the third time you've posted the same question and I'm answering it in #746 so let's close this one.
