### ISSUE TITLE
How do i know when the pivot construction finished

### ISSUE THREAD

**Issue by beny8503** [nicolaskruchten/pivottable#771]
Hi, thanks very much for take your time to build this awesome component. 
Here's my problem: I'm trying to use a jQuery plugin to handle big sets of data (DataTables). It seems to me that with this plugin I can achieve most of the things I want to do with the pivot, such as make the data table appear in a scroll layout with fixed headers and applying bootstrap styles. Before you ask, I've tried NReco and is not working for me because scroll slow down on big set of data and I can't buy the premium version.

Thanks beforehand

**Comment by nicolaskruchten** [comment]
The `onRefresh` callback is called after every render, including the first one. Does that answer your question, or am I misunderstanding?

**Comment by beny8503** [comment]
I was trying to do it right there but is like when the onRefresh executes, the html code of the data table is still loading or something. I'm saying this based on the expected funcionality of the DataTables plugin wich is suposed to take the html table and make the necesary changes. Perhaps I really don't underestand the onRefresh option. Also, I'm using the onRefresh to change the style of the pivot to bootstrap, something like NReco does.

**Comment by nicolaskruchten** [comment]
I'm not sure what you mean by "the html code of the data table is still loading" ... can you provide some kind of example of what you're seeing?

**Comment by beny8503** [comment]
It's not what I'm seeing it's more like what I'm not seeing. Here is the thing, I'm loading a json data into the pivot, it has about 2000 records and could be more, so far could be 30 thousand and more(it also has about 17 columns), but I'm testing with 2000. When the pivot load the first time, the area of the data table remains blank for e few seconds or maybe less, and them the table shows. The problem is that is too big for the screen in my page, so I want to make it on a smaller layout like 600px height with scroll bars, that's why I told you about DataTables jQuery plugin. So, the onRefresh callback, when exactly it gets triggered?, is there something like a state of the pivot to know when it is completely showed in the screen?

**Comment by nicolaskruchten** [comment]
This system is completely synchronous, so the PivotTable calls for a render, and when the render is done, it calls `onRefresh`.

1. The renderer is called here: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L990
2. a few lines later, the `onRefresh` callback is called: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L1013

try passing in something like `onRefresh: function(){ alert('done'); }` in the parameters. The alert should appear immediately after the table appears.

**Comment by beny8503** [comment]
I did what you said, the result was that the alert shows before the data table (table.pvtTable)

**Comment by beny8503** [comment]
![pivot1](https://user-images.githubusercontent.com/31513988/29943093-1c0ce776-8e66-11e7-9011-596cccd298fb.png)
![pivot2](https://user-images.githubusercontent.com/31513988/29943094-1c2edbc4-8e66-11e7-86c6-c1996093a890.png)
Here you can see what I'm saying

**Comment by nicolaskruchten** [comment]
Well that's certainly surprising. Could it be an actual DOM-rendering delay but the DOM has been constructed? I.e. if you query the DOM from the `onRefresh` callback is the table present but just the browser hasn't drawn all the pixels yet?

**Comment by beny8503** [comment]
Mmmm, honestly I don´t know, let me do some test and I keep you posted, I'll also try a diferent aproach, but it will imply the use of a third library different from DataTables (Clusterize and Fixed-Header-Table)

**Comment by beny8503** [comment]
Here is what I did, I put this code: `if ($('table.pvtTable').length)
                    alert("the table exist");
                else
                    alert("the table does'nt exist");` in the onRefresh callback an this is what I get: 
![pivot3](https://user-images.githubusercontent.com/31513988/29972151-1620774a-8ef9-11e7-9896-3e5f4d5d0e18.png)

**Comment by nicolaskruchten** [comment]
OK, so yeah, the fact that the table doesn't actually appear on the screen shouldn't prevent you from executing further code to modify it etc from within `onRefresh`. There's a lag to actually draw the pixels but there's not much we can do about browser performance...

**Comment by beny8503** [comment]
I realize that, so I'm  trying the other solution I commented earlier. I also have another problem. it's not about this subject but here it goes: I'm trying to reduce the renderers list that are shown in the renderers select and make then appear in spanish. I already include the pivot.es.js file loading after the pivot.min.js file and the result is that the renderers' list does'nt change at all and the aggregators list change to spanish without problems

**Comment by beny8503** [comment]
Before you answer the previous question, I managed to change the elements on the renderers' list, my bad. But stil they does'nt show in spanish, also, how can I do to change the elements in the aggregators list?
By the way, thanks very much for your attention, I'm very satisfied with the support

**Comment by nicolaskruchten** [comment]
Happy to help!

Regarding the localization to spanish: if you specify a `renderers` object or an `aggregators` object, this overrides the locale file, so you'll need to provide your own keys in spanish for those objects.

**Comment by beny8503** [comment]
Oh I see, I followed your recomendation and I succesfully populate both list in spanish with the desired elements. Are you interested on knowing about my progress in the integration of the libraries I've mentioned earlier?

**Comment by nicolaskruchten** [comment]
Glad to know your issues are resolved!

I'm always happy to hear about how people are able to use this library, so feel free to let me know, yes! In the meantime I'll close this issue. Please create new issues as you hit new problems/have new questions :)
