### ISSUE TITLE
Style element of PivotUI - half way through only, help...

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#772]
Thanks Nicolas for this excellent code... I Inspect elements and then use
```
  $('.pvtAttrDropdown').addClass('Dropdownlist');
                        $('.pvtAggregator').addClass('HideIt');
                        $('axis_0 ui-sortable-handle').addClass('Dropdown2');
```
to add class so I can style the elements
The 2nd line is working and successfully added class hideit as desired
But the 1st and 3rd line of code did not append the desired classes
How should I modify the code ? Thanks

**Comment by nicolaskruchten** [comment]
I'm not sure why those lines aren't working, but the issue doesn't seem related to PivotTable.js code... 

I should also note that you can just add styles to the existing classes, you don't need to add classes to elements necessarily.

**Comment by hkbeer** [comment]
Yes I found I can style it directly in pivot.css
Great thing you have created. Very Impressive indeed.

**Comment by nicolaskruchten** [comment]
Glad you like it!
