### ISSUE TITLE
How to hide Value field from Top bar ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#778]
This is not an issue but some help needed...
My source csv is simple, only 3 columns:-
Country, Product, Revenue.
Revenue is value field and we are interested in sum of it so the default is 
Integer Sum > Revenue
The PivotUI is displaying nicely but at the same time the Revenue button also appear on top horizontal bar.
Some user drag this Revenue to side bar causing it crash on use. 
Is it possible to hide the Revenue button on top ?
I tried hiddenAttributes: ["Revenue"] it then disappear from top bar but at the same time it disappears from selection box beneath Integer Sum. 

How to only hide it from top horizontal bar ? Thanks

**Comment by nicolaskruchten** [comment]
There is no way to do this at the moment, although there is an open pull request which I may merge that does this: #408

**Comment by nicolaskruchten** [comment]
I've just merged the changes from PR #408 so you can now use `hiddenFromDragDrop` to accomplish what you're looking for, or `hiddenFromAggregators` for the opposite.

**Comment by hkbeer** [comment]
Yes this is great. Thanks... making it even more perfect now.

**Comment by nicolaskruchten** [comment]
Great. Please close this issue if you don't need any further help.
