### ISSUE TITLE
How to hide rows with zero values in all cells ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#779]
My CSV has 2 columns of values, say, Revenue and Cost. Then another 2 columns are Country and Product
In some displays, (eg UK + Apple) has Revenue but no Cost in data itself.
When displaying Integer Sum Cost in PivotUI, this UK Apple row is all zero naturally (this is not an issue with the js).

How to have PivotUI not to display this zero row at all ?

Thanks

**Comment by nicolaskruchten** [comment]
I can't think of a way to do this: this library displays output for all input, regardless of value.
