### ISSUE TITLE
How to sort without regard to upper or lower case

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#780]
The default table sorting is that

MN is sorted before
ab because seems the order is

A,B,C,D,......X,Y, Z , a, b, c, d,....z
Is there way I make it display in this order
A,a,B,b,C,c... etc without regard of lower or upper case ?

Thanks

**Comment by nicolaskruchten** [comment]
You can use a custom sorting function with the `sorters` parameter.

**Comment by hkbeer** [comment]
Thanks. I noticed this. The hardship I am facing is the data keeps changing so I cannot hard code all names in the sort code. Can I do wildcard like sorters {"A*", "a*" etc} ?

**Comment by nicolaskruchten** [comment]
You can provide a standard javascript comparison function... you can just wrap the builtin default like this: `function(a,b){ return $.pivotUtilities.naturalSort( (""+a).toLowerCase(), (""+b).toLowerCase() ); }`

**Comment by hkbeer** [comment]
Thanks a lot to inform this is doable. Great... So sorry, how to "just wrap the builtin default "
Do you have the fuller code of where I should put this code ? 

  $("#output").pivotUI(parsed.data, { sorters: { function(a,b){ 
    return $.pivotUtilities.naturalSort( (""+a).toLowerCase(), (""+b).toLowerCase() ); 
}}

is this correct ? and what  ""+a is doing ? Do I need to further customize ? Pls help with more guide. Really appreciate this.

**Comment by nicolaskruchten** [comment]
`""+a` is a hack to get a stringified version of `a` so I can call `.toLowerCase()` on it safely.

If you read the parameter documentation [here](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) you will see that `sorters` needs to be a function which returns a sorting function, so one way to use the example I gave you above is like this:

```javascript
$("#whatever").pivotUI(data, {
    sorters: function(){ 
        return function(a,b){  
            return $.pivotUtilities.naturalSort( (""+a).toLowerCase(), (""+b).toLowerCase() ); 
        }; 
    }
});
```

**Comment by hkbeer** [comment]
I just tried only the following still those lower cases falls to the bottom...

$("#output").pivotUI(parsed.data, {
 sorters: {
                            

                            function() {
                                return function (a, b) {
                                    return $.pivotUtilities.naturalSort(("" + a).toLowerCase(), ("" + b).toLowerCase());
                                    
                                };

**Comment by nicolaskruchten** [comment]
Ah, right, my simple suggestion here will not work. You'll have to find or write your own sorter function here. I don't have time to help you with this specific thing, sorry. Here is some documentation on how to write such a function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
