### ISSUE TITLE
What is the format of the codes when using Option inclusions ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#781]
I am trying to prepopulate the table as if somebody has checked 2 boxes out of 10 boxes in one of the selection.

The column header is "Name". There are 40 names: A1, A2, A3.... A40.
I wish to prepopulate so on load, only several of them are displayed but user can display/hide some more using the provided selection box.

How to code using Inclusions option to say display A17, A25 and A31 by default ?
I keep searching post and still cannot find the answers. Pls help. Thanks

**Comment by nicolaskruchten** [comment]
This example will show you the full input object for all keys for any configuration you like, so you can get a sense of what's what: https://pivottable.js.org/examples/onrefresh.html

**Comment by hkbeer** [comment]
Thanks a lot. I tried to uncheck the box and watch the code on the left. I found to enter in BOTH inclusives and exclusives ... but the data keeps adding A40, A41, A42 etc. I have to go to modify my code and add items each time the data has new Names ? Is there way to ALWAYS Exclude all and the include fixed A17, A25 and A31 ? Please help.... thanks

**Comment by nicolaskruchten** [comment]
You don't have to use both `inclusions` and `exclusions`. If you want to just have a whitelist of checked items, just use `inclusions`.

**Comment by hkbeer** [comment]
Thanks. How to do "Exclude *.*" first so the other would go away ?

**Comment by nicolaskruchten** [comment]
To exclude a value called `value` from an attribute called `attribute` use the follow configuration fragment: 

```javascript
...
"exclusions": {"attribute": ["value"] } 
...
```

**Comment by hkbeer** [comment]
Thanks. How to exclude ALL first ? As these values keep adding new values.. I cannot hard code the code each time. What can I do ? Thanks

**Comment by nicolaskruchten** [comment]
Excluding all is rarely a good idea... to do this you would use inclusions
with an empty array, meaning "include nothing".

**Comment by nicolaskruchten** [comment]
Did you figure this out? Can we close this issue?

**Comment by hkbeer** [comment]
OK I close it first... I will test it later.
Thanks
