### ISSUE TITLE
Is % after sum possible

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#784]
Thank you for this great js.

Below is not an issue but seeking a hope this is do-able..

My source file has 3 columns, 
Country, Revenue, Cost.
I need to show a report with % of Cost over Revenue (ie Cost divided by Revenue x 100%). So  some are 80% and some 40% etc....

So I add to source csv file a 4th Column called CostPcT = Cost/Revenue

What I want to achieve is , if data has only 2 rows
USA, 51, 100
USA, 49, 100
I wish to see USA row to be 50%. Now my CostPcT is giving me 100%
ie, I wish the total = (51+49)/(100+100) = 50%,  instead of (51/100)+(49/100) = 100%

Is there way to display (Sum of all row for Cost column ) / (Sum of  of all rows for Revenue column).

I am exploring the code you posted in Wiki: 
`var ageBinDeriver = function(record) { return record.Age - record.Age % 10; }`

How to add this ageBinDeriver into the PivotUI ? and how to modify the formula ?
`var CostPcT = function(record) { return record.Cost/record.Revenue % 10; }`
Is this correct ? and do I need to change the word record to something else in my case (eg into Country)?

Thanks a lot.

**Comment by WSAyan** [comment]
You have to write your own derived method. I calculated percentage of a column based on another column by adding **calculatedField** index in `derivers = {}` map in pivot.js source and  Here was my addition to pivot.js:

```
derivers = {
            calculatedField: function (firstColumn, secondColumn) {
                return function (record) {
                    return (record[firstColumn] / record[secondColumn]) *100;
                };
            }
}
```
And called it from the my js like this:

```
var customDeriverMap = {};
customDeriverMap[calculatedFieldName] = derivers.calculatedField(firstColumn, secondColumn);
$("#output").pivotUI( pivotFormat, { derivedAttributes: customDeriverMap },true); 
```

**Comment by hkbeer** [comment]
Thanks a million.... really appreciate it. I am impressed.. 
I found this section in js:-
` derivers = {
      bin: function(col, binWidth) {
        return function(record) {
          return record[col] - record[col] % binWidth;
        };`

So is it I append like this ?

` derivers = {
      bin: function(col, binWidth) {
        return function(record) {
          return record[col] - record[col] % binWidth;

calculatedField: function (firstColumn, secondColumn) {
                return function (record) {
                    return (record[firstColumn] / record[secondColumn]) *100;
                };
        };`

`var customDeriverMap = {};
customDeriverMap[calculatedFieldName] = derivers.calculatedField(Cost, Revenue);
$("#output").pivotUI( pivotFormat, { derivedAttributes: customDeriverMap },true); `

Is this correct ? I am wondering [calculatedFieldName] in my case is what ? 
Really appreciate your contributions..Thanks

**Comment by nicolaskruchten** [comment]
This is probably the wrong way to go. You can just use the builtin "Sum over Sum" aggregator in the UI for this, no need to write a deriver.

**Comment by WSAyan** [comment]
@nicolaskruchten 
He is trying to create a custom based on other columns. I am still playing and trying to fully understand pivot.js which is really wonderful. My goal is to giving users a basic interface to calculate their own columns based on other columns by writing some basic equations. For testing purpose I tried to take two columns name as input and calculated percentage of one column over another columns and it worked nicely this way. So for my purpose is this wrong way to go?

**Comment by nicolaskruchten** [comment]
The issue is that in his case, if he takes the average of your derived column, he will not get what he wants. He wants (a+b)/(c+d) but what he will get is ((a/c)+(b/d))/2.

**Comment by WSAyan** [comment]
@hkbeer 
Actually I wrote var 
```
var firstColumn = $("#firstColumn").val();
var secondColumn = $("#secondColumn").val();
var calculatedFieldName = $("#calculatedFieldName").val();
customDeriverMap = {};
customDeriverMap[calculatedFieldName] = derivers.calculatedField(firstColumn, secondColumn);
```

because I took the calculated column name from user. And passed in the into the map as an index. See you can hard code the column name just like the example stated. And of course you have to change the calculation part of the calculatedField(Cost,Revenue) method.  
`derivedAttributes: { "CostPcT": derivers.calculatedField(Cost, Revenue) }`

**Comment by WSAyan** [comment]
@nicolaskruchten 
Yes you are right. My **calculatedField** is not going calculate what he wants.

**Comment by hkbeer** [comment]
Yes Sum Over Sum works ! Previously I dunno what is that and now I know.
This tool rocks ! Thanks.

The only change I need is now the result is 0.41, 0.55 etc
How to code to make them display as percentages ?
and how to pre-populate the 2 fields used in Sum Over Sum ?

Thanks a million indeed.
