### ISSUE TITLE
Summing the values instead of count

### ISSUE THREAD

**Issue by jovenden** [nicolaskruchten/pivottable#785]
Hi, loving what has been done with this tool - really great stuff.

This must be really simple but (and apologies if it's really obvious) but does the tool as shown on say 
https://pivottable.js.org/examples/local.html
support this?

The below represents the number of server transactions performed per minute

HHMI  TXNS
08:30	944
08:29	997
08:28	1097
08:27	950
08:26	890
08:25	900
08:24	866
08:23	768
08:22	857
08:21	221

When we drop this data into PivotUI we can get for example the rows to show the time (HHMI) but the values in the table presented are 1 for every time - because that is the number of rows we have per time. I assume we can somehow get the TXNS data to be presented instead of what is of course just the record count.

![pivotui](https://user-images.githubusercontent.com/29379362/30695610-99ea7e86-9ed0-11e7-975a-82b55f3e6ca1.jpg)

If the request makes sense... is this something supported without us extending the tool?

**Comment by nicolaskruchten** [comment]
Yes, just choose something other than "count" in the second dropdown. For example "sum" and then choose NUM_TXNS in the second dropdown that appears

**Comment by jovenden** [comment]
I cannot believe I missed the “oh so obvious” answer to this…

thx!

**Comment by nicolaskruchten** [comment]
:)
