### ISSUE TITLE
Can I expand one row to Level2 but not another

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#786]
In my data source there are 2 columns. I drag them both to left panel as row fields. Say Level1 and Level2 aee headers of these 2 columns.

In Level1...items are A, B, C. etc
Level 2 are details. Eg product details...how to set the code so if items is A, H and C then preload its Level2 is expanded ...other are collapsed and Level2 is not expanded by default?
Thanks

**Comment by nicolaskruchten** [comment]
There is no way to collapse anything unfortunately.
