### ISSUE TITLE
Easy sorting possible ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#788]
I have a report with rows not to be ordered by alphabets but by a specific ordering... 
The names of these rows keep changing as new names are added but luckily there is a ID_Name which we can use to order these rows by order of ID_Name as these ID already reflect the hierarchy of the report.
Say for example
0001Apple
0002Orange
0003Pear etc

Is it possible to SORT based on this [ID+Name] above but when display on report, only
Apple, Orange etc are displayed ? other than having to create 2 fields on the report ?
ie can we sort by [ID_Name] but when displayed it is [Name] ?

**Comment by nicolaskruchten** [comment]
Not possible, no.
