### ISSUE TITLE
<select> to refresh PivotUI ... how ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#792]
I have an [input type="select"] on html so it is a dropdownlist and I wish when user immediately after select this selection box,it will refresh PivotUI ... how ?

My current html code is 

```
<input type="select">
<option value="American">American flamingo</option>
<option value="Andean">Andean flamingo</option>
etc
</input>

```
and JS is

```
 Papa.parse("Book1.csv", {
                    download: true,
                    skipEmptyLines: true,
                    complete: function (parsed) {
                        $("#output").pivotUI(parsed.data, {
```

How could I modify the code so on change of selection box then the JS is refreshed ?
Thanks

**Comment by nicolaskruchten** [comment]
I don't understand what you're trying to do, can you try to clarify please?

**Comment by hkbeer** [comment]
Sorry for unknown reason Github is not displaying < > code... I have replaced them with [ ] ... my need is when user select html selection choice, it refreshes the PivotUI...

Pls help..

**Comment by nicolaskruchten** [comment]
When posting code to GitHub you can surround it in triple-backticks to
preserve all formatting and special characters.

**Comment by hkbeer** [comment]
Thanks. I have preserved the code. How can I make html selection box onchange to fire the JS code ?

**Comment by nicolaskruchten** [comment]
Did you close this because you figured it out?
