### ISSUE TITLE
Dunno why hiddenFromDragDrop is not working...

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#793]
I have a pivotUI that is working

```
$("#output").pivotUI(parsed.data, {
hiddenFromDragDrop: ["Product"],
dataClass: dataClass,
etc etc

```

All the options are doing the effect except 
hiddenFromDragDrop: ["Product"],

The field Product still appears in the 1st top row.
Did I type the syntax wrong ?

**Comment by hkbeer** [comment]
So sorry pls close this post. I found I did not download the new js.
Now it works. This tool is perfect. Thanks

**Comment by nicolaskruchten** [comment]
Great. Please close the issue if you don't need any further help. You've
got a bunch of open ones now and I'd love it if we could close some out if
you're done with them...
