### ISSUE TITLE
How to display the row field name starting from 4th letter

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#795]
I have a field called [ProductName] and I dragged it to the left panel so in the PivotUI table they become rows.
This field has ProductNumber as first 4 letters followed by the Name, ie they are like this

```
2314Circuit
2789ScrewA
etc etc
```
How can I display in the rows only like this

```
Circuit
ScrewA
etc etc ???
```

I guess the code is adding something like

```
result = result.substring(4, result.length)
```
but dunno where in pivot.js to put it ...
I hope it can cut the first 4 letters AFTER Sorting if possible. If it works then we can have easy custom sorting.

Please help...Thanks

**Comment by nicolaskruchten** [comment]
There is no way to do this unfortunately

**Comment by hkbeer** [comment]
Thanks for the information.
