### ISSUE TITLE
pvtAggregator 

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#796]
I need to hide some items from pvtAggregator (ie Count, Integer Sum, etc).
How can I achieve this ?

Thanks

**Comment by nicolaskruchten** [comment]
You can pass in whichever aggregators you like with the `aggregators` parameter.

In general, might I recommend that you familiarize yourself with the contents of this wiki page? https://github.com/nicolaskruchten/pivottable/wiki/Parameters ... many of the questions you are asking here are answered there.

**Comment by hkbeer** [comment]
I have read the wiki already. What I need is to REMOVE some items from it...

What I am doing now is to remove those items from .js file but it is not a good way since I may need them in another html/page.

I am wonderful if there could be an option/switch to "turn on/off" just like what

hiddenFromAggregators & hiddenFromDragDrop do...

ie, any hiddenFromAggregator would be nice....

**Comment by nicolaskruchten** [comment]
The way this works is that there is a default value for `aggregators` which contains a bunch of stuff. It's available at `$.pivotUtilities.aggregators`. If you want a subset of those, then pass in the desired subset as the `aggregators` parameter, and it will use your subset instead of the defaults.

The other option is that you could create a locale file.

**Comment by hkbeer** [comment]
Thanks. When you say "It's available at $.pivotUtilities.aggregators"
Where do I need to look at ? inside pivot.js ?

**Comment by nicolaskruchten** [comment]
$.pivotUtilities.aggregators is an object where the keys are the default
aggregator names and the values are the corresponding aggregator functions.
You can inspect it just like any other object with something like
console.log($.pivotutilities.aggregators) or you can read the source code
in either original .coffee form or compiled .js form.

**Comment by hkbeer** [comment]
Yes I read the js and found "Integer Sum": tpl.sum(usFmtInt),
In Wiki
aggregators | object of functions | (common aggregators)

I just dunno how to adjust this line

var aggregators = $.pivotUtilities.aggregators;
I tried var aggregators = "sum" etc it does not work...

**Comment by nicolaskruchten** [comment]
You really seem to want to do things the hard way every time... You basically never need to modify the source library file: everything is overridable!

If you wanted to, say, use just Integer Sum and Count, here is how you might do it, without modifying the underlying library:

```javascript

var my_aggregators = {
"Integer Sum": $.pivotUtilities.aggregators["Integer Sum"],
"Count": $.pivotUtilities.aggregators["Count"]
};

$("#whatever").pivotUI(my_data, {aggregators: my_aggregators});
```

**Comment by hkbeer** [comment]
It works. Thanks. I dunno it can be used this way. I will study more.
