### ISSUE TITLE
Cascading/Dependent Filters?

### ISSUE THREAD

**Issue by tableaukun** [nicolaskruchten/pivottable#797]
Is it possible to have filters be dependent on other selected filters?

For example, looking at https://pivottable.js.org/examples/onrefresh.html, if we put Province in the rows shelf and Party in the columns shelf, we see that British Columbia has one record in the Green Party.

If we filter out British Columbia from Province, Green is still an option to filter by in Party, even though there is no longer data.

Is there a setting to enable cascading/dependent filters? 

Thanks!

**Comment by nicolaskruchten** [comment]
There is no setting for this, no, and I don't think I would be inclined to add it, as I believe it would cause more confusion that the current situation.
