### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by toocold** [nicolaskruchten/pivottable#798]
Hi,

i want to define sorting column to be some hidden field. 

For example: I want to provide key-value pair and to sort by key and to show values.

Is this possible?

Thanks.

**Comment by nicolaskruchten** [comment]
This isn't possible, no, sorry.

**Comment by nicolaskruchten** [comment]
To expand on my answer: you can't sort by a hidden column, but you can, however, specify a sort order for a given attribute using the `sorters` parameter. See example here for ordering days of the month: https://pivottable.js.org/examples/montreal_2014.html

**Comment by hkbeer** [comment]
I am same need on sorting based on hidden field (eg ID of something).
Yes I am hard coding sorting like the example in this link.
But it is not an ideal situation as the items keep adding...
Dunno if anyone comes up with a better solution to this case...

**Comment by hkbeer** [comment]
One way I can think of is to render a separate table with 2 columns, ID and display field, order by ID. then extract dispay field one by one and separated by commas, and then use in sortAs. I will try this way later.

**Comment by hkbeer** [comment]
This way works. Just in case you need it, my code is
  var sortdata = [];
                $('#table1 > tbody > tr > td').each(function (index, value) {
                    sortdata.push($(value).text());
                });

**Comment by hkbeer** [comment]
Pls close the post if you have no further comments :-)

**Comment by nicolaskruchten** [comment]
@hkbeer please let me manage the issue workflow, I'm not sure I appreciate your pushing on others' issues like this :)
