### ISSUE TITLE
How to remove blank choice in Aggregator Selection Box

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#799]
PivotUI is a great great tool, thank you for this js.
I am getting very near to what I have dreamed for over 10 years. Thank you.

It is now perfect on my page and one final thing I wish to do for the moment is
There is always a blank choice in the left top corner in the Aggregator selection Box.
Eg the choice now is "Amount" and [Blank].
How to remove the Blank ?
I tried 
```hiddenFromDragDrop: [""," ", null],```
but failed to remove.
Anyway I can remove it ?

Thanks

**Comment by nicolaskruchten** [comment]
I can't think of a way to remove it, no.

**Comment by hkbeer** [comment]
OK Thanks
