### ISSUE TITLE
Is it possible to add exit Filter boxes by Esc button

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#800]
Is it possible to add exit Filter boxes by Esc ?

Now the filter box has Select All Select None, Apply and CANCEL button.
It would be very good if pressing Esc Key kill this prompt as well....

Is it possible to add in next version ?
Thanks

**Comment by nicolaskruchten** [comment]
I would not favour this, because it would be ambiguous: does ESC mean apply
or cancel?

**Comment by hkbeer** [comment]
It would be nice if ENTER key = click "Apply" button
and
pressing ESC key = click "Cancel" button

**Comment by nicolaskruchten** [comment]
Thanks for the input, but I'm really not inclined to add keyboard shortcuts to this library at this time.
