### ISSUE TITLE
How to access pvtTable element by jquery ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#802]
How to access two pvtTable element by jquery ?

I need to access pvtTable > thead > tr > th > pvtAxisLabel and 
pvtTable > tbody > pvtRowLabel

it is a challenge for me as the target AxisLabel could be 1st or 2nd column. I am using this
$("pvtTable > thead > tr > th > thpvtAxisLabel")
 
it is not able to gain access. How should I code this ?
Thanks

**Comment by nicolaskruchten** [comment]
This type of jQuery-selector-specific question is best suited for StackOverflow or something like this, as it's not really PivotTable.js-specific.

**Comment by hkbeer** [comment]
OK Thanks
