### ISSUE TITLE
Freeze/Sticky header possible ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#803]
PivotUI will be near perfect if we can make the header row always maintain and appear on the top even we scroll down the page to look at bottom of the data table.

How can we do this ? Thanks

**Comment by nicolaskruchten** [comment]
There is no support for this in the library but you may be able to get it done with CSS or another Javascript library.

**Comment by hkbeer** [comment]
OK I will try that path, thank you.
