### ISSUE TITLE
PivotUi cannot work with newer Jquery ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#804]
I found if I am using jquery 1.x the pivotUi works but if I use Jquery3.x or 2.x the PivotUi does not render.
Is there way to make it to work with newer Jquery js file ?
Thanks

**Comment by nicolaskruchten** [comment]
I can't replicate this problem... If you change the jQuery version on the JSFiddle examples here it works fine with 2.x and 3.x https://jsfiddle.net/nicolaskruchten/gq6w05j8/

**Comment by hkbeer** [comment]
OK must be some other wrong with my other external js using on the same page. I will investigate further
