### ISSUE TITLE
Use var as parameter of SortAs

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#805]
I am now using the following which is hard coded and working properly.
sorters: {  "Country": sortAs(["US","UK,"Germany"),}

I now need to replace the hard coded values with variable.
I have an array that is called CSVarray having these values in it already: "US","UK,"Germany"
then I use the following but all did not work unfortunately...

sorters: {  "Country": sortAs(CSVarray),}
or
sorters: {  "Country": sortAs( [CSVarray]  ),}
or 
sorters: { "Country": function (CSVarray){return "sortAs([" + CSVarray + "])"},

How should I modify the code ? Thanks

**Comment by nicolaskruchten** [comment]
Is your CSVtext variable a string or an array of strings?

**Comment by hkbeer** [comment]
I can code it either a string or array, depending which one is easier.. thanks

**Comment by nicolaskruchten** [comment]
`sortAs` accepts an array of strings, so that is what you must pass it, as should be clear from the working example...

**Comment by hkbeer** [comment]
Thanks. would you mind posting a sample code ?

**Comment by nicolaskruchten** [comment]
I'm not sure what you're asking here. The sample code you have in the issue description should work fine except that you're missing a `]` after Germany... `{ "Country": sortAs(["US","UK,"Germany"])}` 

You can store that array in a variable and pass it in trivially:

```
var x = ["US","UK,"Germany"];
...{ "Country": sortAs(x)}...
```

**Comment by hkbeer** [comment]
Great I achieved what I want using this intermediate step, 
thanks :-)
