### ISSUE TITLE
how to resize column ?

### ISSUE THREAD

**Issue by jeanmarc78** [nicolaskruchten/pivottable#806]
hello,
when i set pivot table to french , the data is displayed with 2 lines  for long numbers, is there a way to increase column width ?

![image](https://user-images.githubusercontent.com/11042160/31117283-93dbeefa-a829-11e7-9200-6f9069998aae.png)

best regards
jean marc

**Comment by nicolaskruchten** [comment]
That is annoying indeed! A simple fix is to set the CSS of table cells to not wrap text, something like `.pvtVal {  white-space: nowrap; }` ...

**Comment by jeanmarc78** [comment]
thanks a lot,
i do the same for Total and grand Total
.pvtVal { white-space: nowrap; }
.pvtTotal, .pvtGrandTotal { white-space: nowrap; }


best regards
jeanmarc

**Comment by nicolaskruchten** [comment]
happy to help!
