### ISSUE TITLE
cell click Callback open new web page - how

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#807]
I wish on click a cell trigger callback to open a new web page.

This is the code from example page

```
rendererOptions: {
                    table: {  clickCallback: function(e, value, filters, pivotData){
                            var names = [];
                            pivotData.forEachMatchingRecord(filters,
                                function(record){ names.push(record.Name); });
                            alert(names.join("\n"));
```
What is the code I can replace alert so a new blank web page is opened ? 
Thanks

**Comment by nicolaskruchten** [comment]
This is a pretty generic Javascript question that you can get answered on StackOverflow :)

**Comment by hkbeer** [comment]
Thanks, it is :-)
I already asked on the forum and the people 
are saying need to refer to the js as behaviour is different depending on the call back.
For example they said window.open may not work as it is not a direct user click.
I tried window.open replacing alert above and it really did not work ... so I have to come back here...

Thanks

**Comment by nicolaskruchten** [comment]
Did you try window.location ?

**Comment by hkbeer** [comment]
window.location works. It is a quick fix. Better than none  :-)
Thanks
