### ISSUE TITLE
Showing specific aggregators and renderers in the dropdowns

### ISSUE THREAD

**Issue by pkarunyu** [nicolaskruchten/pivottable#81]
Hi Nicolas,
Is it possible to specify only a few aggregators and renderers at the time of calling pivotUI?

For example, I only want to show Table and Bar Chart in the renderers dropdown, and only count, sum and average in the aggregators dropdown.

I have checked in the wiki and I have not found an example of this in use.

Thanks.

Peter.

**Comment by alpertandogan** [comment]
Hi 

I use jquery method but it can works like below.... But Sum or other how can  I add some of them default aggregations template to my pivotUI 

---works only tpl.count if i define fix field name tpl.sum()[ field ....] works also but i dont know which field sum user will select field --------

  var tpl = $.pivotUtilities.aggregatorTemplates;
...
   aggregators:    {
         "Count": function() { return tpl.count()() }
    }
...

------------------THIS IS NOT WORK------------
  aggregators: {
        "Count": $.pivotUtilities.aggregators.count
      , "Sum": $.pivotUtilities.aggregators.sum
      , "Average": $.pivotUtilities.aggregators.average
    }

**Comment by nicolaskruchten** [comment]
@alpertandogan please create a new issues rather than commenting on something that was a closed 4 years ago :)
