### ISSUE TITLE
How can I actually fetch the data of from the tables using onclick events ?

### ISSUE THREAD

**Issue by SiddhantMahajani** [nicolaskruchten/pivottable#810]
First of all thank you for this great library. It actually great to work with. 
My main aim is to display the clicked record using an alert box of javascript or using a dialog box of Jquery. Right now I am able to fire the click event by clicking on the table but my aim is to fetch the x-axis element and y-axis element of the clicked box and display it using alert box or dialog box. Would like to get some help on this query of mine asap.
Thank You

**Comment by nicolaskruchten** [comment]
This example basically does what you're looking for: https://pivottable.js.org/examples/mps_prepop.html

In the callback, the `filters` parameter should contain the information you're looking for.

**Comment by SiddhantMahajani** [comment]
Oh ! Okay. Like in this part clickCallback: function(e, value, filters, pivotData)
I will send my data like the name of the fields which I want to display. Right?

**Comment by SiddhantMahajani** [comment]
Thank You so much. It is done I was able to retrieve the data which I needed on click event. Thank You.
