### ISSUE TITLE
Can I represent the fetched onclick data in tabular format ?

### ISSUE THREAD

**Issue by SiddhantMahajani** [nicolaskruchten/pivottable#811]
Hello,
Like given in the mps_prepop example I was able to fetch the data on click event and data was displayed in an alert box. So similar to that is there any way that I can display the given data in a proper tabular format. 
Thank you

**Comment by nicolaskruchten** [comment]
You can do anything you want with the data, but this library doesn't offer
functionality specifically for this, you'll have to build it yourself :)

**Comment by SiddhantMahajani** [comment]
Okay Cool! Thanks

**Comment by hkbeer** [comment]
Yes you can do this by adding <table> etc element into the sting and use it in alert. 
Inspired by your idea, this is what I am doing now. I combine it with modal to make it looks more nice and apply bootstrap etc :-)

**Comment by SiddhantMahajani** [comment]
So use the <table> in the string and display the string? Correct?

**Comment by SiddhantMahajani** [comment]
@hkbeer How do you actually fire the `<table>` command in the alert box? I mean what is the actual syntax and how do you parse it?

**Comment by hkbeer** [comment]
When you say fire do you mean going to server side to get data from db ? I am not doing this as the pivot.js already getting what I need for my case (not sure if it is your case). I go straight to jquery dialog or js modal so I did not try html in alert but I saw it is accepting things like "\n" so I guess it may be able to read table tags. 

If you indeed need to fire server side code and get data again on click, you may need to run querystring etc and cause page load. I already have done so in testing and may apply in future. But, all these are doable it seems...

**Comment by SiddhantMahajani** [comment]
@hkbeer no no not from the server side. The data is in an array.

**Comment by SiddhantMahajani** [comment]
So I just need to display that data in a tabular format.

**Comment by hkbeer** [comment]
You may go to this for complete tools you can manipulate
https://www.w3schools.com/jsref/jsref_obj_regexp.asp
Look at Metacharacters section....

The following is a quick code I made for you as an illustration

<script type="text/javascript">
var row1 = ["ABC","DEF"];
var row2 = ["STU","XYZ"];
var join1 = row1.join("\t");
var join2 = row2.join("\t");
var Joined = [join1, join2]
var display = Joined.join("\n");
alert(display);
</script>

**Comment by hkbeer** [comment]
As Nicolas said it is possible to do it ourself outside of pivot.js.
Since this is not the issue of pivot.js pls close this post
