### ISSUE TITLE
How to use Pivot Table on Mac ?

### ISSUE THREAD

**Issue by SiddhantMahajani** [nicolaskruchten/pivottable#814]
Hello, 
I downloaded your pivot files but they are not working on Mac's safari browser as well as on chrome. Can you please help me out like how will I be able to run them on Mac.

**Comment by nicolaskruchten** [comment]
Are you able to run the examples at https://pivottable.js.org/ on those
browsers? They work fine for me on Mac of course... maybe try copying them
and figuring out what you missed :)
