### ISSUE TITLE
How can I retrieve the value of the clicked data in the pivot table ?

### ISSUE THREAD

**Issue by siddhantjm** [nicolaskruchten/pivottable#815]
Hello, In the pivot table it displays the values 2,3.... so how can I fetch those values from the pivot table in my javascript code?

**Comment by hkbeer** [comment]
You may refer to this:-
https://pivottable.js.org/examples/mps_prepop.html

**Comment by siddhantjm** [comment]
Not this. I know how to alert something using onclick. I want to access the value present in the table.

**Comment by nicolaskruchten** [comment]
@siddhantjm it's not clear what you're asking for here.. The click callback is passed a `value` arguement which seems like what you need, no?

**Comment by siddhantjm** [comment]
@nicolaskruchten See what i want is if the pivot table has a value 2 and when click on the value 2 the alert box shows 2 entries associated with the same. What i want to do is i want to retrieve that value 2 which is in the table. How can i achieve that. Using the value variable in callback ?

**Comment by nicolaskruchten** [comment]
Have you tried using the value variable in the callback?

**Comment by siddhantjm** [comment]
@nicolaskruchten I'll use it and see if that solves my problem. Thanks in advance.

**Comment by siddhantjm** [comment]
@nicolaskruchten Yes it did solve my problem .That is what I was looking for. Thank You 👍
