### ISSUE TITLE
Aggregators not reflecting 

### ISSUE THREAD

**Issue by pivotkasparrani** [nicolaskruchten/pivottable#816]
Hi Nicolas,

I am new to pivot framework.

Thanks for pivot framework with free of cost. I am new to this framwork.  I am loading the pivot framework with below JSON in a popup view. When i load first time, i can able to change the aggregators like filterValue,party,etc. and the respective value is reflecting in the the table. 

When i drag and drop new field(rawVal,filterValue) to cols or rows, i need to frame new set of json according the selected rows and cols and reload the pivot html table. That time if i change the aggregators(party,rawVal, )the table is not reflecting according to selected aggregators. Please help us to sort us the issue.  I tried many solutions and not able to sort and not found sample for this features. 

**pivot html:**

function loadData(objData){
			 $("#output").html("");
			  var renderers = $.extend($.pivotUtilities.renderers, $.pivotUtilities.export_renderers);
	 $.getJSON("mps.json", function(mps) {
			$("#output").pivotUI(mps, {
				 cols:['qtrVal'], 
                rows: ['filterValue'],
           derivers:$.pivotUtilities.derivers,
                rendererName:'Table',
                 aggregatorName:'List Unique Values',
               
                onRefresh: function(config) {
                    var config_copy = JSON.parse(JSON.stringify(config));
                    //delete some values which are functions
                    delete config_copy["aggregators"];
                   delete config_copy["renderers"];
                    //delete some bulky default values
                   delete config_copy["rendererOptions"];
                   delete config_copy["localeStrings"];
                 
                       Ti.App.fireEvent('app:pivotCallback', {
							 configVal:config_copy			 		
					  });
                    },
                 renderers: renderers,
            });
       
		});
		}

**JSON:**
[
{"filterValue":"Sample",
"party":"Quebecois",
"party":"2017",
"sampleVal":"34",

},

{"filterValue":"xxxxxx",
"party":"Quebecois",
"rawVal":"2017",
"sampleVal":"36",
},

{"filterValue":"yyyyy",
"party":"Quebecois",
"rawVal":"2017",
"sampleVal":"30",
},

{"filterValue":"vvvvv","party":"Conservative","rawVal":"2016","sampleVal":"11"},
{"filterValue":"uuu","party":"Conservative","rawVal":"2016","sampleVal":"13.34"},
{"filterValue":"rrrr","party":"Conservative","rawVal":"2015","sampleVal":"16"},
{"filterValue":"ssss","party":"Conservative","rawVal":"2015","sampleVal":"18.34"},
{"filterValue":"eeeee","party":"Green","rawVal":"2015","sampleVal":"121"},
{"filterValue":"bbbb","party":"Green","rawVal":"2014","sampleVal":"133"},

]

**Comment by nicolaskruchten** [comment]
I'm sorry but I don't understand what you're trying to do... Could you try explaining it differently please?

**Comment by pivotkasparrani** [comment]
[pivot_demo.zip](https://github.com/nicolaskruchten/pivottable/files/1421636/pivot_demo.zip)

[pivot_demo.html.zip](https://github.com/nicolaskruchten/pivottable/files/1421645/pivot_demo.html.zip)
 Thanks for replied me. i have uploaded the sample demo video and html file. I am appcelerator platform to develop iphone application. Basically i am loading html file using webview in a popup . Its like browser. 

When i load the html first time in the popup view, i can able to change the sub aggregators(party,age,etc) and the selected value is reflecting in the table. 
But if l close the view and open it again, i can able to change the sub aggregators(party,age,etc) but the  selected sub aggregators is not reflecting in the pivot table.
At the same time, if i change the renders and aggregators(Sum, list unique value), the data is reflecting even in the second time load. The problem only in the sub aggregators.

Please help us to proceed further.

**Comment by pivotkasparrani** [comment]
Hi Nicolas,

Please let me know the above content helped you to understand the issue.

Thanks
Rani

**Comment by nicolaskruchten** [comment]
OK, I see the issue but I have no idea what is going on in the rest of your app etc so I don't know how to help you, because I can't reproduce this issue here outside of your context.
