### ISSUE TITLE
Setting initial selectable aggregators pivotUI

### ISSUE THREAD

**Issue by alpertandogan** [nicolaskruchten/pivottable#817]
Hi

I use jquery method but it can works like below.... But Sum or other how can I add some of them default aggregations template to my pivotUI

---works only tpl.count if i define fix field name tpl.sum()[ field ....] works also but i dont know which field sum user will select field --------

var tpl = $.pivotUtilities.aggregatorTemplates;
...
aggregators: {
"Count": function() { return tpl.count()() }
}
...

------------------THIS IS NOT WORK------------
aggregators: {
"Count": $.pivotUtilities.aggregators.count
, "Sum": $.pivotUtilities.aggregators.sum
, "Average": $.pivotUtilities.aggregators.average
}

**Comment by alpertandogan** [comment]
My ugly solution just delete options unnecessary for me from library  .

**Comment by nicolaskruchten** [comment]
It seems like you're just using the wrong keys from the `$.pivotUtilities.aggregators` object, no? The definition of this object is here and the keys are case-sensitive: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L155

**Comment by alpertandogan** [comment]
---this is working custum aggregators 
        var tpl = $.pivotUtilities.aggregatorTemplates;
        prev_config.aggregators= {
               "my setup count ": function() { return tpl.count()() }                
                }      
         prev_config.renderers= $.extend($.pivotUtilities.renderers,$.pivotUtilities.c3_renderers )
         var $output = $("#output")
         var $pivotTable=$output.pivotUI(mps.ROWSET,prev_config,true);

----this is not like that 
     prev_config.aggregators= {
               "my setup count ": function() { return tpl.sum(usFmt)() }                
                  }

**Comment by nicolaskruchten** [comment]
Yes because in the second case you're not summing anything. You have two options:

1. To sum `attribute` use: `"my aggregator": function() { return tpl.sum(usFmt)(['attribute']) }`
2. To display menu of attributes to sum use: `"my aggregator": tpl.sum(usFmt)`

There is detailed documentation here: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators

**Comment by alpertandogan** [comment]
prev_config.aggregators= {
 "my aggregator": tpl.sum()
}

Thanks nicolas for perfect feedback.

Works like that.

**Comment by nicolaskruchten** [comment]
Happy to help!
