### ISSUE TITLE
Simple sorting - how ?

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#818]
My data layout is now as follows
Country, Product, Dates, Amount

It is fine Country and Product are sorted in ascending order first and then I wish the Dates field to appear in descending order. How to do this ?
I just cannot do custom sort of every single date and code it. Any easy way to do this ?

Thannks

**Comment by nicolaskruchten** [comment]
Yes, you can write a normal sorting function without using sortAs

**Comment by hkbeer** [comment]
Thanks. How to simple normal sort descending order for a particular dimension ? Pls help to post simple code. Appreciate it in advance

**Comment by nicolaskruchten** [comment]
If you want to use Moment.js to parse the dates then sorting by date for any supported format basically looks like this: https://jsfiddle.net/nicolaskruchten/8r45u464/

```javascript
$("#output").pivot(
  [
  ["date","color"],
  ["15-12-17", "blue"],
  ["15-12-17", "red"],
  ["13-12-17", "blue"],
  ["16-12-17", "blue"],
  ["15-11-17", "red"],
  ["15-12-16", "yellow"],
  ["14-12-16", "yellow"]
  ], 
  {
    rows: ["date"],  cols: ["color"],
    sorters:{
    	"date": function(a,b){
      	return moment(a, "DD-MM-YY").isAfter(moment(b, "DD-MM-YY"));
      }
    }
  });

```

**Comment by hkbeer** [comment]
It works for me, thank you so much. 
Really appreciate this.

**Comment by nicolaskruchten** [comment]
Great!

**Comment by kalimuthu123** [comment]
i also having the same issue in sorting how to customise sorting
