### ISSUE TITLE
Sorting dates on Chrome does not work

### ISSUE THREAD

**Issue by pperliti** [nicolaskruchten/pivottable#819]
Hi Nicolas, 

I'm having a strange issue with Chrome (and I'm quite sure it's my fault but I can't understand what I'm doing wrong).

I have my pivot table and I need to sort it by date (formatted as DD/MM/YYYY).
Since I read your answer to previous post #169, I'm using two columns: one called "Periodo competenza" (formatted as DD/MM/YYYY) and another one (hidden) called "periodoCompetenzaAsISO8601" (same of previous but formatted as ISO8601, "YYYY/MM/DD").

Then I defined my custom sorter as 
`function(a, b) { return moment(a, "DD/MM/YYYY").isBefore(moment(b, "DD/MM/YYYY")); }`

Column "periodoCompetenzaAsISO8601" is used to sort data but it's also hidden since it's not useful to the final user. Instead I'm showing "Periodo competenza" (DD/MM/YYYY).

On both Firefox and IE11 it works as expected (table is sorted correctly by "Periodo competenza"):

![firefox-ok](https://user-images.githubusercontent.com/1265443/32144087-d53db484-bcb3-11e7-9bf0-4947fb68fcdf.png)

On Chrome (and also Opera, that's quite the same) sorting is someway broken:
![chrome-wrong](https://user-images.githubusercontent.com/1265443/32144088-d54bd5dc-bcb3-11e7-911c-25c8d9a957d1.png)

Here's my configuration:

**HTML**
`<div id="pivot-payments"></div>`

**JAVASCRIPT**
```
/* Setup of pivot */
function pivotSetup() {
  /* Setup pivot renderers */
  var renderers = jQuery.extend(jQuery.pivotUtilities.locales["it"].renderers, jQuery.pivotUtilities.export_renderers);

  /* Setup pivot derivers */
  var monthNames = ["GEN", "FEB", "MAR", "APR", "MAG", "GIU", "LUG", "AGO", "SET", "OTT", "NOV", "DIC"];
  var monthDeriver = jQuery.pivotUtilities.derivers.dateFormat("periodoCompetenzaAsISO8601", "%n", null, monthNames, null);

  /* Custom date compariser */
  var dateCompariser = function(a, b) { return moment(a, "DD/MM/YYYY").isBefore(moment(b, "YYYY\MM\DD")); }

  /* Define available configurations */
  configs["default"] = {
    rows: ["Periodo competenza"],
    cols: ["Ente"],
    aggregatorName: "Somma", // "Sum" using italian locale
    vals: ["Totale importi"],
    renderers: renderers,
    sorters: { "Periodo competenza": dateCompariser },
    hiddenAttributes: [ "periodoCompetenzaAsISO8601" ],
    derivedAttributes: { "Mese": monthDeriver }
  };

  /* Load data (AJAX) */
  jQuery.getJSON("http://localhost:8080/quadratura'", {
                   "do": "paymentsData",
                   "dataFrom": "01/08/2017", // 1th august 2017
                   "dataTo": "31/08/2017",   // 31th august 2017
                 function(data) {
                      dataset = data;
                      jQuery("#pivot-payments").pivotUI(dataset, configs["default"], true, "it");
                 });
}
```

**JSON**
[data.zip](https://github.com/nicolaskruchten/pivottable/files/1425101/data.zip)

Am I missing something?

Thanks for your great work! PivotTable is simply amazing!

**Comment by nicolaskruchten** [comment]
It would be really helpful if you could pull this together in JSFiddle or CodePen or something so I can see the issue for myself... :)

**Comment by nicolaskruchten** [comment]
Also, I assume this is Chrome on Windows that is giving you trouble? Can you tell me which version please?

**Comment by pperliti** [comment]
Hi Nicolas,
Here's the fiddle https://jsfiddle.net/boea6xpe/1/ 
Yes, it's Chrome 62.0.3202.75 (for Windows x64, but the same applies for Android).

**Comment by nicolaskruchten** [comment]
The problem seems to be in your comparator: you parse `a` as "DD/MM/YYYY" but you parse `b` as "YYYY\MM\DD".

**Comment by nicolaskruchten** [comment]
I should add that you should not use `isBefore` but rather `diff` to compare the two dates. If you want to reverse the order then just add a minus sign in front of the diff.

**Comment by pperliti** [comment]
Thank you Nicolas. 

> you parse a as "DD/MM/YYYY" but you parse b as "YYYY\MM\DD"

Sorry, that was a mistake in jsfiddle. Actually I was parsing both `a` and `b` the right way ("DD/MM/YYYY").

Using `diff `instead of `isBefore` made the trick!
Thank you very much.

**Comment by pperliti** [comment]
Hi @Nicolas,
I'm reopening this issue since it needs further investigation.
I followed your suggestions and at first it seemed to work. Actually, using the vertical sorting arrows, rows are sorted in a wrong way.

Could you please help me? ([fiddle updated here](https://jsfiddle.net/boea6xpe/1/), just try to sort by date)

**Comment by hkbeer** [comment]
Pls see if this works:

sorters:{
    	"Periodo competenza": function(a,b){
      	return moment(a, "DD/MM/YY").diff(moment(b, "DD/MM/YY"));
      }
    }

**Comment by pperliti** [comment]
Hi @hkbeer 
the initial sort is ok, but when you click on vertical arrows to sort it doesn't work
See [https://jsfiddle.net/pp74/boea6xpe/8/ ](https://jsfiddle.net/pp74/boea6xpe/8/ )

**Comment by nicolaskruchten** [comment]
The sorting arrows sort by total :)

**Comment by pperliti** [comment]
Shame on me!!!
