### ISSUE TITLE
Feature Request: Visualize the data with different plots at a time

### ISSUE THREAD

**Issue by R13104** [nicolaskruchten/pivottable#820]
Is there any way in which we can see the data with a different type of plots at a time? Right now there is a dropdown where we can change the plot options and visualize the data. But If I want to see a line chart as well as a bar chart for the data So how will it be possible?

**Comment by nicolaskruchten** [comment]
This isn't possible at the moment and I don't think it's something I will add in the future. That said, you're welcome to create your own renderers to suit your needs :)

**Comment by R13104** [comment]
Okay cool :) Are we planning to support more library for plotting charts apart from existing ones? I am asking because I am working to integrate plotly.js inside this. Will it be useful? What do you think?

**Comment by nicolaskruchten** [comment]
Interesting coincidence! I'm currently at the Plotly Montreal headquarters working on the Ploty-supporting React port of this library: https://react-pivottable.js.org/ so I will be back-porting the Plotly renderers at some point in the coming weeks :)

**Comment by R13104** [comment]
Hey, This is a great news :) I have seen this React pivottable library. It looks awesome :) Thanks for showing me this. It will be a cool feature.

**Comment by hkbeer** [comment]
Wow so you are at Plotly HQ ? Have fun... their charts are so impressive I have been using it also... yes the renderers you mention coming is definitely a great stuff...

**Comment by hkbeer** [comment]
Hello, any advance in adding Plotly renderer ?

**Comment by nicolaskruchten** [comment]
Should be done by the end of the week :)

**Comment by hkbeer** [comment]
Wonderful. Can't wait to see that and play with it. This would definitely make the pivotTable even more perfect. It is a mission impossible made possible ^^

**Comment by nicolaskruchten** [comment]
The Plotly renderers are part of version 2.18.0, with a demo here: https://pivottable.js.org/examples/plotly.html
