### ISSUE TITLE
Adding hiddenAttributes, derivedAttributes on local code

### ISSUE THREAD

**Issue by carthagod** [nicolaskruchten/pivottable#823]
Hi there!

First of all many thanks @nicolaskruchten for this super cool library, really awesome.
And an important precision to read the following: I'm a TOTAL newbie in code, so please bear this in mind when answering :-)

To be honest, I don't understand much of how this works, but I managed to do some stuff by tweaking some of the examples files (great thing to have so many examples, I only wish the documentation would be more explicit). 

So here's my problem: I want to add hiddenAttributes, derivedAttributes, and special rows and cols on a pivot table that would be loaded **locally** (from csv upload). 

I have managed to add those Attributes as I wanted when parsing data from a previousely updated csv. For this, I have based myself on the montreal_2014.html example, and I got it right (well, at least it works), here's what this looks like:

```
$(function () {
        var dateFormat =       $.pivotUtilities.derivers.dateFormat;
        var sortAs =           $.pivotUtilities.sortAs;
        var tpl =              $.pivotUtilities.aggregatorTemplates;
        var fmt =              $.pivotUtilities.numberFormat({suffix: " °C"});

        Papa.parse("MyFile.csv", {
            download: true,
            skipEmptyLines: true,
            complete: function(parsed){
                $("#output").pivotUI(parsed.data, {
                   
                    hiddenAttributes: ["Datestap"],

                    derivedAttributes: {
                        "Day": dateFormat("Datestamp", "%m/%d", true),
                        "hour": dateFormat("Datestamp", "%H", true)  
                    },

                    rows: ["Day"],
                    cols: ["Raccourci"],
                    rendererName: "Heatmap",

                });
            }
        });
    });
```

Now instead of parsing a previousely uploaded csv, I would like to parse a csv that is uploaded locally. 

I've tried adding my attributes to the code I found in the example file local.html, but it doesn't work :-(

How can I achieve this?

If you could actually give me the full piece of code that works that would be truly awesome because as I said I don't understand too much (and new to JS and even code in general). With explanations additionnaly that would be just fantastic :-)

Thank yo so much for your help guys!!

**Comment by carthagod** [comment]
Oh, forget it... just found!
I spent 3 hours yesterday night on this, thought I'd just leave it and ask for help, but after 10minutes of more investigation this morning I nailed it :-)

I just take advantage of this useless intervention to mention that some more detailed documentation on the functions would be most welcome: your stuff is so awesome even a newbie like me can take advantage of if, so I you just documented it a little more it would be useful to even more people! Or at least save a loooooot of time :-)

**Comment by nicolaskruchten** [comment]
Glad you sorted it out! It would really help to know where you would have
benefitted from more documentation, as its daunting for someone like me to
"just add more" in general :)

**Comment by carthagod** [comment]
Hi @nicolaskruchten,

Thanks for your answer! 
As I said I'm a real newbie, and use your library as a big black box with 0 knowledge of jQuery, D3, C3, and very minimal knowledge of JavaScript. So I'm not sure my need are the needs of most, but anyway here's what I would have loved:

- Detailed documentation on the function pivotUI: what parameters can it take, how to write them
- Comments on every block of code of the example files: easy way to document without annoying everybody with a huge documentation. Your examples are great and allowed me to find my way around, with more comments in the code they would be awesome. In my particular case, I'd love comments on the file local.html, to understand the use of every block of code: var dragging, var endDrag, var dropped... No idea what they're doing, tried removing some to see but it breaks everything (even though in your other examples such a montreal_2014 those lines aren't here), so I'd be glad to understand what they do, what I can remove or configure, etc...

Take what you wish from those inputs and thanks again :-)

**Comment by nicolaskruchten** [comment]
Thanks for the feedback!

Regarding your first point, was this documentation insufficient or did you not come across it? https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by carthagod** [comment]
I'm afraid I did not come accross it, even though I went to the wiki several times: 100% my fault then, it looks great!

**Comment by nicolaskruchten** [comment]
Well, not 100% your fault: I should find ways to make this documentation easier to find :)
