### ISSUE TITLE
Uncaught ReferenceError: c3 is not defined

### ISSUE THREAD

**Issue by BBaek** [nicolaskruchten/pivottable#825]
I want to use c3 chart.

But an error[Uncaught ReferenceError: c3 is not defined] occurs.

![image](https://user-images.githubusercontent.com/6959474/32725649-47384f52-c8b9-11e7-95ac-0a7a23fb60a3.png)

I have defined.
	<script src="/resource/js/pivotjs/dist/c3_renderers.js" type="text/javascript" ></script>
	<script src="/resource/js/pivotjs/dist/c3_renderers.min.js" type="text/javascript" ></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>

Why this error occurs?

**Comment by nicolaskruchten** [comment]
Are you loading C3 *before* the pivottable code?

**Comment by BBaek** [comment]
What is the C3?
c3.min.js??
This file not included github.

Can pivotjs use with jsp(spring framework)?

**Comment by nicolaskruchten** [comment]
C3 is a third-party charting library and so is required but not included in this repo. See http://c3js.org for more details.

It can be loaded from CDNJS as `c3.min.js`, yes, but it must be loaded *after* the `pivot.min.js` and `c3_renderers.min.js` files.

PivotTable.js is a client-side system so is agnostic to server-side technologies: it can be used with JSP, Spring, whatever.

**Comment by BBaek** [comment]
I solved with your guide.
Thank you so mush.^^
