### ISSUE TITLE
jQuery is undefined error when used with webpack

### ISSUE THREAD

**Issue by skidr0w** [nicolaskruchten/pivottable#826]
I get the error message `jQuery is undefined` when using pivottable with webpack and there is no global jQuery object.

[Line 348](https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L348) triggers the error.

The fix should be to change this line to `input instanceof $` as $ is defined as function parameter.

**Comment by nicolaskruchten** [comment]
Thanks for the bug report! This should be fixed in version 2.16.1, which I just published :)
