### ISSUE TITLE
Is it possible to retrieve the HTML pivotJS would render to the DOM without actually inserting it?

### ISSUE THREAD

**Issue by okon3** [nicolaskruchten/pivottable#827]
I need to render the HTML Table pivotJS gives me in a different way than jQuery does, so I was wondering if it's possible to call pivotJS and only get the HTML node element back as a return value without drawing it on the page.

I'm calling pivotJS like this:

```
jQuery(elem).pivot(	tmpData,
	{
		rows: rows,
		cols: cols,
		renderer: jQuery.pivotUtilities.renderers['multifact_table'],
		aggregator: jQuery.pivotUtilities.aggregators['multifact_aggregator'](measures, dictionary),
		aggregatorName: 'multifact_aggregator',
		sortData: visualization.dimensionsOrder
	});
```

Thanks.

**Comment by nicolaskruchten** [comment]
There's definitely no built-in feature for this, so your best bet is to render it to an invisible element (i.e. one with `display: none;`), extract its HTML somehow and then remove it from the DOM.
