### ISSUE TITLE
Feature of drag row up and down is nice

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#829]
If the js would allow us to drag particular row up and down (one at a time) to change the order one by one that would be very nice.
Is this something possible in future ?

Thanks

**Comment by nicolaskruchten** [comment]
This is not something I'm working on, but you're welcome to fork and modify the Table Renderer to suit your needs :)

**Comment by hkbeer** [comment]
Thanks. Would you please kind enough to point me to which file and which section I likely need to work on. If successful I hope to share in here too. Really appreciate it.

**Comment by nicolaskruchten** [comment]
https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L444

I'm not going to lie, though, this seems like a very complex/challenging change to make, and not something which I would incorporate into the main library if you succeed...

**Comment by hkbeer** [comment]
Thanks. I am half way doing this. However I need to add ID attribute into the 
`<Table Class="pvtTable"> `
element in order to proceed further but I am not able to do it. Please help... thanks

[https://github.com/nicolaskruchten/pivottable/issues/831](url)

**Comment by hkbeer** [comment]
I am trying to use TableDnD plug in which rely on table ID.
I finally succeeded in adding ID to Table class="pvtTable" but still the TableDnD is not taking effect... I gave up at the end. Maybe it only applies only to hard code table tag and not table rendered in runtime.
