### ISSUE TITLE
How to add ID to the pvtTable 

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#831]
The pivottable is rendered as

`<table class="pvtTable" etc>`

How to add ID to so it becomes

`<table class="pvtTable" ID="MyTable" etc >` ?

I have tried doing externally like

` $('.pvtTable').attr('id', 'MyTable'); `

but it doesnt work.

Where in pivot.js and what code I need to add to add this ID ?
Thanks

**Comment by nicolaskruchten** [comment]
What do you mean by "it doesn't work"? After executing that code, does `$("#MyTable")` not return the element?

**Comment by hkbeer** [comment]
The default rendered Table has only Class attribute:
<Table class="pvtTable"
without ID.

I am able to add ID subsequently so I am done on it. Thanks
