### ISSUE TITLE
Switching between pivot() and pivotUI()

### ISSUE THREAD

**Issue by Bill-VA** [nicolaskruchten/pivottable#833]
I've noticed that simply removing the "UI" from the function call sort of breaks the table.  I had everything working just the way I wanted with pivotUI and just wanted to turn off the UI elements and leave the table, but doing so caused issues.  Is this something to be expected?

**Comment by nicolaskruchten** [comment]
Yes, it is. Take a look at the documentation for each function here, including the warning that they take similar but different options :)

https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by Bill-VA** [comment]
ok, thanks.

**Comment by nicolaskruchten** [comment]
I've just added a new `showUI` parameter that allows you to use `pivotUI()` without the UI.
