### ISSUE TITLE
Unable to render Treemap correctly

### ISSUE THREAD

**Issue by GetWild** [nicolaskruchten/pivottable#835]
Hi Nicolas, I have been experimenting with PivotUI and have a issue with the d3 Treemap chart, the boxes are rendering down the page instead of within the chart area, see attached. Can you give me any hints as to what could be causing this?

Thanks
Harry

![treemap issue](https://user-images.githubusercontent.com/33935101/33179435-54a2ba24-d061-11e7-82fa-94c56d3a6612.JPG)

**Comment by nicolaskruchten** [comment]
Hi,

I suspect you haven't copied over the CSS from the example file, which
helps with positioning... that's not well-documented, sorry!

Nicolas

**Comment by GetWild** [comment]
Which css is this, I've tried the pivot.css, but this doesn't help?

**Comment by GetWild** [comment]
My colleague spotted this styling, which resolved the issue:
.node {
        border: solid 1px white;
        font: 10px sans-serif;
        line-height: 12px;
        overflow: hidden;
        position: absolute;
        text-indent: 2px;
    }

**Comment by GetWild** [comment]
thanks for the very useful software

**Comment by nicolaskruchten** [comment]
That's the CSS, yeah! Glad you're finding things useful :)
