### ISSUE TITLE
Restrict no.of draggable and droppable

### ISSUE THREAD

**Issue by kirubhakaran1392** [nicolaskruchten/pivottable#838]
is it possible to restrict no.of draggable and droppable in pivotUI?
I want to allow user maximum 3 vs 3 (Row * Column) drop, because my data is large. when i go more than 3 vs 3 , browser hanged.

**Comment by nicolaskruchten** [comment]
There is no mechanism specifically to constrain the number of attributes in the drop area, no, but I'm considering adding a `confirm` warning if someone tries to render a table with more than a million cells or something like that, for this reason. Would that help?

**Comment by kirubhakaran1392** [comment]
thanks for quick reply,  it will help me.but , is there any way to restrict by make change on pivot.js file?

**Comment by nicolaskruchten** [comment]
You can modify pivot.js to make it do pretty much anything you like, but I don't have any time to help you implement this particular change, unfortunately, I'm sorry...

**Comment by hkbeer** [comment]
There may be several ways you may improve:
(1) You may try hiddenAttributes option ? It may reduce the number of fields to 6 the max.
(2) Ensure full aggregate of the data before feeding it to the UI (but I assume you may already have done it, but no harm to check it again
(3) if you really want to have number of fields available far exceed 6, you may create a separate control area (eg checkbox) to have say 12 fields, but in that control area you allow only max 6 selection and that selection combo change the row and column fields of pivotUI to educate the users they can select only 6 or 3+3 the max...

Hope this helps
