### ISSUE TITLE
Python pivottablejs.pivot_ui keyword argument "width"

### ISSUE THREAD

**Issue by jray37** [nicolaskruchten/pivottable#842]
Hi Nicolas, this library is fantastic!

This line is working just fine except when I try to size my pivot table with "width":

pivot_ui(df, width = '150%', cols = ['WW'], rows = ['project_name'], aggregatorName = 'Sum', vals = ['headcount'], rendererName = 'Area Chart')

When I change the width parameter nothing appears to happen. My problem is that I have a lot of WW values, so they are so crowded along the horizontal axis that they overlap each other and are unreadable. I'm trying to space them out.

Any suggestions would be much appreciated!

**Comment by nicolaskruchten** [comment]
Glad you like it!

A couple of things:

1) If this is related to the Python module, please file issues in the corresponding repo, which is https://github.com/nicolaskruchten/jupyter_pivottablejs
2) If I understand correctly you're trying to make a plot wider? There is no generic "width" parameter here but for charts you can pass some options to the underlying C3 renderer with something like `rendererOptions = {"c3": {"size": {"width": <pixels>}}}`

**Comment by jray37** [comment]
Sorry about putting my question in the wrong spot, but yes, this worked perfectly! Thank you

**Comment by nicolaskruchten** [comment]
Super!
