### ISSUE TITLE
Cannot read property 'derivers'

### ISSUE THREAD

**Issue by EridaR** [nicolaskruchten/pivottable#843]
I am using pivot table to my project , i have integrated and when i use it the table is missing and in the console appear this error : Uncaught TypeError: Cannot read property 'derivers' of undefined
    at HTMLDocument.<anonymous> 

Thank you in advance

**Comment by nicolaskruchten** [comment]
I'm going to need some more context to help you out... Can you post a link to your page or a copy of your code or something please?
