### ISSUE TITLE
Make pivottable responsive

### ISSUE THREAD

**Issue by BrunildaDosti** [nicolaskruchten/pivottable#848]
Hello,

Thank you for pivottable.js.
I have integrated it with Gentelella theme and works fine.
But we have an issue with chart display. Chart are not responsive and display wider than the width of page. 
Could you please tell me how to get a fix for that? Is there any way how to integrate Bootstrap framework with pivot or is another way to get this fixed?

Please instruct me, I`m loosed if the chart does not display as it should!

Thank you in advance!
Waiting for your reply.
The attachement show a part of issue I`m having.
![image001](https://user-images.githubusercontent.com/23187783/34528970-db28bda0-f0aa-11e7-9ae0-25f5f964ed9e.png)

**Comment by nicolaskruchten** [comment]
You can set the height/width of the chart using `rendererOptions` as in this example https://pivottable.js.org/examples/scatter.html but there is no built-in way to make things responsive. You can probably force a rerender of the size you like on resize, though.
