### ISSUE TITLE
Set some filters as unselected

### ISSUE THREAD

**Issue by Recongt** [nicolaskruchten/pivottable#849]
Is it possible that some checkboxes in filters are unchecked by default? This option seems very necessary if you do not want to overuse the user with data that is rarely needed.
![przechwytywanie](https://user-images.githubusercontent.com/9448092/34607619-bb2dbbca-f214-11e7-916d-689605be437c.PNG)

The effect after starting the table should look like in the attached picture.
Thank you in advance for your answer.

**Comment by nicolaskruchten** [comment]
Yes, you can use the `inclusions` and `exclusions` parameters.
