### ISSUE TITLE
Doble Grouping 

### ISSUE THREAD

**Issue by Deyzab** [nicolaskruchten/pivottable#855]
Hi this is my proble, i have a data in json but when be displayed do not render by value 
[{
	"nom_sub_actividad": "AMARRA 1                ",
	"nom_centro_costo": "FA.Manza. Rosy.G 14     ",
	"nom_unidad_control": "JORNADA                                           ",
	"dia": "Viernes 5",
	"fecha_rend": "\/Date(1512097200000)\/",
	"Jornadas": [{
		"Rendimiento": 1.00,
		"jornada": 1.00
	}]
}, {
	"nom_sub_actividad": "CONTEO FRUTAS           ",
	"nom_centro_costo": "FA.Manza.BROOK. 14      ",
	"nom_unidad_control": "JORNADA                                           ",
	"dia": "Viernes 5",
	"fecha_rend": "\/Date(1512097200000)\/",
	"Jornadas": [{
		"Rendimiento": 3.00,
		"jornada": 3.00
	}]
}]
![deyzaerror](https://user-images.githubusercontent.com/35265682/34728021-6db840ba-f537-11e7-842d-9ee0605b3fa2.png)

and this is my implementation

 var params = new Object();
            params.id_empresa = 10084;
            params = JSON.stringify(params);
            $.ajax({
                type: "POST",
                url: "RendimientosPorLabor.aspx/ListaRendimientosPorLaborDT",//return de json
                data: params,
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (r) {

                    var mps = JSON.parse(r.d);
                    console.log(mps);

                    $("#output").pivotUI(mps, {
                        hiddenAttributes: [],
                        rows: ["nom_sub_actividad", "nom_centro_costo", "nom_unidad_control"],
                        cols: ["dia", "Jornadas"],
                        aggregatorName: "Lista Valores Unicos",
                        vals: ["Jornadas"],
                        rendererName: "Tabla"
                    });

                }
            });

**Comment by nicolaskruchten** [comment]
The problem here is that your `Jornadas` input is not supported: each value must be a string or number or boolean, not an object or an array.

**Comment by Deyzab** [comment]
thanks ill try to get the data of another way

**Comment by Deyzab** [comment]
I adjusted it a lot to extract the data and it worked, thank so much.
take tow record for the same line
![image](https://user-images.githubusercontent.com/35265682/34737949-5c484fae-f556-11e7-87d5-52f2ddcf2a7b.png)
whit a column "Tipo"
and "Valor"
finaly get this
![image](https://user-images.githubusercontent.com/35265682/34738019-8ad86610-f556-11e7-81bc-9ac00291ff1b.png)

thanks  a lot

**Comment by nicolaskruchten** [comment]
Good! I'm happy to have been able to help!
