### ISSUE TITLE
PIVOT() function is displaying simple pivot grid. not coming with heatmap, average function,percentage function etc.

### ISSUE THREAD

**Issue by HardikParmar91** [nicolaskruchten/pivottable#857]
Below Is my Script which is working as expected for saving the state of the Pivot grid table.
Pivot table is also working as expected when i m loading with saved configuration of Pivot table

But I don't want to give client to edit Pivot table structure so I am using PIVOT() method.
On loading this method **_I don't get any error ON THE PIVOT TABLE but HEAT MAP, AVERAGE FUNCTION ETC IS NOT WORKING SIMPLE GRID IS DISPLAYING ON THE PAGE WITH BY DEFAULT COUNT FUNCTION FOR THE PIVOT GRID_**

> **IS IT POSSIBLE TO ACHEIVE SAME PIVOT GRID WITH HEATMAP , CHARTS & ETC FUNCTIONALITY WITHOUT EDITABLE PIVOT GRID ?**

----->>>>>>>>>>  **_JAVASCRIPT_**
```
<script type="text/javascript">       
	$(function () {
	$.getJSON("mps.json", function (mps) {
		$("#output2").pivotUI(mps);

		$("#save").on("click", function () {
			var config = $("#output2").data("pivotUIOptions");
			var config_copy = JSON.parse(JSON.stringify(config));
			//delete some values which will not serialize to JSON
			delete config_copy["aggregators"];
			delete config_copy["renderers"];
			
			SendConfigData1(JSON.stringify(config_copy));}); //THIS METHOD SENDS DATA TO CODE BEHIND & SAVE DATA TO DB

		$("#restore").on("click", function () {
			ReceiveConfigData1("");}); //THIS METHOD RECEIVES DATA FROM CODE BEHIND & DISPLAYS TO HTML PAGE

		function SendConfigData1(config_copy){
			PageMethods.SendConfigData(config_copy);}

		function ReceiveConfigData1(config_copy) {
			PageMethods.ReveiceConfigData(config_copy, ResponseReveiceConfigData);}

		function ResponseReveiceConfigData(Responsedata){
			$("#output2").pivot(mps, JSON.parse(Responsedata), true);}
	});});
</script> 

```

----->>>>>>>>>>  **_HTML_**

```
<input type="button" value="Save Config to Cookie" id="save" style="font-size: 24px;" />
<input type="button" value="Restore Config from Cookie"  id="restore" style="font-size: 24px;" />
<div id="output2" style="margin: 30px;"></div>

```
----->>>>>>>>>>  **_CONFIGURATION STRING_** 
```
{
  "derivedAttributes": {},
  "hiddenAttributes": [],
  "hiddenFromAggregators": [],
  "hiddenFromDragDrop": [],
  "menuLimit": 500,
  "cols": [
    "Gender"
  ],
  "rows": [
    "Province"
  ],
  "vals": [
    "Age"
  ],
  "rowOrder": "key_a_to_z",
  "colOrder": "key_a_to_z",
  "exclusions": {},
  "inclusions": {},
  "unusedAttrsVertical": 85,
  "autoSortUnusedAttrs": false,
  "sorters": {},
  "inclusionsInfo": {},
  "aggregatorName": "Sum as Fraction of Columns",
  "rendererName": "Col Heatmap"
}
```

**Comment by nicolaskruchten** [comment]
In general, `pivot()` and `pivotUI()` do not accept the same parameters so
there is some adjustment to do:
https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by nicolaskruchten** [comment]
In general, `pivot()` and `pivotUI()` do not accept the same parameters so there is some adjustment to do: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by HardikParmar91** [comment]
Thank you for the awesome ope source tool. It will take my whole life to create this kind of tool. 👍  🥇  ;)
