### ISSUE TITLE
Is this compatible with d3 v4?

### ISSUE THREAD

**Issue by gkamle** [nicolaskruchten/pivottable#860]
what all the libraries to be changed if it is compatible with d3 v4?

Thanks & Regards
Govardhan

**Comment by nicolaskruchten** [comment]
The core library doesn't depend on D3 but the C3 renderers do. C3 itself isn't D3v4 compatible though: https://github.com/c3js/c3/issues/1648

**Comment by amenadiel** [comment]
Current C3 uses D3 v5
What a time to be alive
