### ISSUE TITLE
pivot() not working

### ISSUE THREAD

**Issue by Prateek-Havanur** [nicolaskruchten/pivottable#862]
<script src="scripts/jquery-1.9.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.13.0/pivot.min.js"> </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.13.0/pivot.min.css" rel="stylesheet" />
    <script src="scripts/jquery-1.9.1.js"></script>
   
    <script>
        jQuery(document).ready(function () {

            $(function(){
                $("#output").pivot(
                    [
                        {color: "blue", shape: "circle"},
                        {color: "red", shape: "triangle"}
                    ],
                    {
                        rows: ["color"],
                        cols: ["shape"]
                    }
                );
            });
        })

    </script>
Above is my  code and i am having div with id="output". i am getting the below error
![image](https://user-images.githubusercontent.com/33024468/35280700-f7871ef2-0076-11e8-9a0c-0ec314d7b0da.png)

**Comment by nicolaskruchten** [comment]
You'll need to load jQuery before the other scripts for things to register correctly.

**Comment by Prateek-Havanur** [comment]
Thanks for you reply 

![image](https://user-images.githubusercontent.com/33024468/35282247-025836be-007b-11e8-8a3b-6a442d991709.png)

After changing the order(like above image) i am getting below error
![image](https://user-images.githubusercontent.com/33024468/35282308-2929f7dc-007b-11e8-8853-13051edfb70c.png)

**Comment by nicolaskruchten** [comment]
Are you seeing the same error on a page like this one? https://pivottable.js.org/examples/simple_ui.html

Which operating system and browser are you using?

**Comment by Prateek-Havanur** [comment]
i am not seeing any error while browsing the link-https://pivottable.js.org/examples/simple_ui.html
i am using windows 10 and internet explorer 11

**Comment by nicolaskruchten** [comment]
OK, so I recommend that you try copy-pasting code from that working example into your setup line by line until you find what's different.

**Comment by Prateek-Havanur** [comment]
Thanks a ton!!!!!! its working now i had the div tag with runat="server" attribute.  removed it works perfectly fine
