### ISSUE TITLE
pvtFilterBox position is not correct

### ISSUE THREAD

**Issue by uurtsaikhb** [nicolaskruchten/pivottable#865]
**pvtFilterBox** position is not correct when open filter. 

"angular/cli": "1.5.0",
"angular/core": "^5.0.0",
"pivottable": "^2.18.0"

![pivottablejs](https://user-images.githubusercontent.com/9427019/35593678-63ef445e-05c5-11e8-94e6-c113628c6960.png)

**Comment by uurtsaikhb** [comment]
I don't know what caused this, butI had to add css `position: relative` to `.pvtTriange` and it works as expected.

**Comment by nicolaskruchten** [comment]
Strange. Can you provide me with some details about your browser and operating system so that I might be able to replicate the problem locally?

**Comment by uurtsaikhb** [comment]
@nicolaskruchten 

macOS Sierra v10.12.6
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
"@angular/forms": "^4.2.4",
"pivottable": "^2.18.0",

**Comment by LeeStevens318** [comment]
I also have the same issue and same fix fixes it.

Windows 10 Pro 10.0.16299 Build 16299
FireFox Quantun 58.0.2 (64-bit)
PivotTable (latest version from Git (pulled yesterday))

**Comment by ravinsinghd** [comment]
Same problem on following configuration
Windows 10 
Chrome 69.0.3497.8
Pivottable 2.19.0",

Followed @uurtsaikhb css. It's works
