### ISSUE TITLE
color formatting based on categories in different record name than the value-record.

### ISSUE THREAD

**Issue by karelv** [nicolaskruchten/pivottable#866]
Hello,

I added a "Table Category" as a renderer.
Please find it here:
https://github.com/karelv/pivottable/blob/master/dist/pivot.js

I added also an example:
https://github.com/karelv/pivottable/blob/master/examples/mps_category_table.html
![image](https://user-images.githubusercontent.com/787006/35613223-c35e0a96-066b-11e8-9a05-6c39701fe24b.png)
For this example I started from the mps.html , so you can view the changes here too.

Now I dislike that I modified your release pivot.js.
Therefore I would like that:
- either you merge my update in your git-tree, and take it as part of pivottablejs
- either you give me tricks or hints to add such renderer without touching your pivot.js file.

Thanks,
Karel.

**Comment by nicolaskruchten** [comment]
Hello Karel,

Well done in creating this renderer! A few notes:

1. This library is written in CoffeeScript, from which `pivot.js` is generated, so there is no way for me to upstream your changes to `pivot.js`: they would need to be translated to CoffeeScript and added to `pivot.coffee`
2. This is a neat renderer but I don't think it's of general enough interest to merge into the library at this time. In fact something rather similar can likely be accomplished by passing a custom color-scale to the existing heatmap renderer as in this example: https://pivottable.js.org/examples/montreal_2014.html
3. If you wish, you can likely easily move your new code to a separate file and include that file alongside the unmodified PivotTable.js library and use the two together. `c3_renderers.js` or `export_renderers.js` might be a good place for you to start looking at how that might be done :)

**Comment by karelv** [comment]
Thanks.
1. I just speak a little javascript now :-) , coffee is for me a step too far (for now).
2. Yes, I have seen this, however one need values as data, I have strings as data. Hence categories.
    So not sure how to get heatmap working with textual data (or categories of data, which is located at non-displayed records).
3. That is a good option, I will definitely have a look in this method, thx for the tip.
