### ISSUE TITLE
Function Errors :(

### ISSUE THREAD

**Issue by Ahmetgnczl** [nicolaskruchten/pivottable#874]
Hi !
My English is weak  :(

I get this kind of error in my use 
What's the solution

![screencapture-localhost-56110-container-monthlystockreport-1519656744435](https://user-images.githubusercontent.com/36701116/36714224-5bb472a8-1ba2-11e8-98d7-e049a94168f3.png)

**Comment by Ahmetgnczl** [comment]
Hi
 this is the perfect thing but there are problems with linq js
Resolve the Problem :)

**Comment by nicolaskruchten** [comment]
Duplicate of #708 ... I don't have a fix for this yet.
