### ISSUE TITLE
Plotly pie charts

### ISSUE THREAD

**Issue by rjst** [nicolaskruchten/pivottable#876]
Hi,

Do you plan to support Plotly pie charts ? If you're not planning on adding them, would you accept a PR for it ?

thanks,
Ricardo

**Comment by nicolaskruchten** [comment]
I was not planning on adding pie chart support (or accepting a PR for it) in the near future, as using multiple pie charts is generally not a very effective visualization technique, and plotly.js' support for multiple pie charts is not quite at the level I would like it to be in terms of labels etc. Of course, that doesn't stop anyone from creating and using such a renderer in their own applications! :)

**Comment by rjst** [comment]
Ok. In our case it would be a single pie chart. We'll give it a try and see how it goes. If we build anything that could be useful to other people, we'll let you know.

**Comment by worstenbrood** [comment]
I also added this as a single chart, using both axises, means if you eg select age and state, it will have a a piece per age+state.

**Comment by kevin5657** [comment]
@rjst, @worstenbrood were either of you guys able to successfully add the option for a pie chart?

**Comment by ebellumat** [comment]
I Create a Plotly renderer option to create Donut/Pie Charts, soon i will create a Pull Request. I Hope @nicolaskruchten accept, hehe

![image](https://user-images.githubusercontent.com/26942680/44180498-3440b680-a0d3-11e8-9e7c-bddaacdc844c.png)

![image](https://user-images.githubusercontent.com/26942680/44180962-64895480-a0d5-11e8-8d1a-6c3a9ac203db.png)

**Comment by ebellumat** [comment]
@rjst,  @worstenbrood @kevin5657 , I created a option to render Pie/Donnut in Plotly. If @nicolaskruchten  dont accept my PR, you can use my fork, i will make a pull tomorrow. Its not perfect, but work in most cases. Each row is a Pie, each column is a axis on a pie.

**Comment by kevin5657** [comment]
Thank you Erasmo. I created my own also but it’s kind of primitive, yours looks good.

**Comment by nicolaskruchten** [comment]
Thanks @ebellumat !

I would ask that if this does not end up being merged into the main library, that you not fork this library in total, but rather create a new 'plugin' library with just this renderer, much like https://github.com/nagarajanchinnasamy/subtotal :)

**Comment by nicolaskruchten** [comment]
Pie charts are now built in :)
