### ISSUE TITLE
pivotUI restore

### ISSUE THREAD

**Issue by GetWild** [nicolaskruchten/pivottable#878]
Hi Nicolas, I am trying to get the restore layout functionalty working in pivotUI, but I am getting this error when refreshing with the saved json string (am using your example code https://pivottable.js.org/examples/save_restore.html for this at the moment):

pivot.coffee:1033 Error: unknown input format
    at Function.e.forEachRecord (pivot.coffee:356)
    at jQuery.fn.init.t.fn.pivotUI (pivot.coffee:689)
    at HTMLButtonElement.<anonymous> (businessintelligence:328)
    at HTMLButtonElement.dispatch (jquery-3.1.1.js:5201)
    at HTMLButtonElement.elemData.handle (jquery-3.1.1.js:5009)

**Comment by nicolaskruchten** [comment]
Can you post the code that you're using? The example you linked to does work so the problem must be in the delta between it and your code :)

**Comment by GetWild** [comment]
@section scripts {

    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
    <script src="~/Scripts/plugin/fullscreen/jquery.fullscreen.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.16.1/pivot.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.3.6/papaparse.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.16.1/pivot.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.16.1/export_renderers.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.16.1/d3_renderers.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.16.1/c3_renderers.min.js"></script>
    <script type="text/javascript" src="https://pivottable.js.org/dist/plotly_renderers.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $.getJSON("https://pivottable.js.org/examples/mps.json", function (mps) {
                $("#output").pivotUI(
                    mps
                    //, {
                    //    rows: ["Province", "Party"],
                    //    cols: [],
                    //    rendererName: "Treemap",
                    //    renderers: $.extend(
                    //        $.pivotUtilities.renderers,
                    //        $.pivotUtilities.d3_renderers,
                    //        $.pivotUtilities.plotly_renderers
                    //    )
                    //}
                );

                $("#save").on("click", function () {
                    var config = $("#output").data("pivotUIOptions");
                    var config_copy = JSON.parse(JSON.stringify(config));
                    //delete some values which will not serialize to JSON
                    delete config_copy["aggregators"];
                    delete config_copy["renderers"];
                    $.cookie("pivotConfig", JSON.stringify(config_copy));
                });

                $("#restore").on("click", function (mps) {
                    $("#output").pivotUI(mps, JSON.parse($.cookie("pivotConfig")), true);
                });
            });
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $('#getFormData').click(function () {
                var selected = $('#WorkflowForms option').filter(':selected');
                var SelectedLst = '';

                selected.each(function () { SelectedLst += this.value + ',' });

                var url = '@Url.RouteUrl("DefaultApi", new { httproute = "", controller = "Workflow"})';
                url += '/' + SelectedLst + '/getBIFormData';

                $.ajax({
                    headers: {
                        "Accept": "application/json",//depends on your api
                        "Content-type": "application/x-www-form-urlencoded"//depends on your api
                    }, url: url,
                    success: function (response) {
                        Papa.parse(response, {
                            skipEmptyLines: true,
                            complete: function (parsed) {
                                var derivers = $.pivotUtilities.derivers;

                                var renderers = $.extend(
                                    $.pivotUtilities.renderers,
                                    $.pivotUtilities.c3_renderers,
                                    $.pivotUtilities.d3_renderers,
                                    $.pivotUtilities.export_renderers
                                );

                                $("#output").pivotUI(parsed.data, {
                                    rendererName: "Bar Chart",
                                    renderers: renderers,
                                    hiddenAttributes: ["Gender"],
                                    derivedAttributes: {
                                        "Gender Imbalance": function (mp) {
                                            return mp["Gender"] == "M" ? 1 : -1;
                                        },
                                        "Sex": function (mp) {
                                            return mp["Gender"] == "M" ? "Male" : mp["Gender"] == "F" ? "Female" : "-Not Captured-";
                                        },
                                        "JoinDay": function (mp) {
                                            var objDate = new Date(mp["JoinDate"]),
                                                locale = "en-GB",
                                                day = objDate.toLocaleString(locale, { day: "2-digit" });

                                            return mp["JoinDate"] == "-Not Captured-" ? "-Not Captured-" : day;
                                        },
                                        "JoinMonth": function (mp) {
                                            var objDate = new Date(mp["JoinDate"]),
                                                locale = "en-GB",
                                                month = objDate.toLocaleString(locale, { month: "short" });

                                            return mp["JoinDate"] == "-Not Captured-" ? "-Not Captured-" : month;
                                        },
                                        "JoinYear": function (mp) {
                                            var objDate = new Date(mp["JoinDate"]),
                                                locale = "en-GB",
                                                year = objDate.toLocaleString(locale, { year: "numeric" });

                                            return mp["JoinDate"] == "-Not Captured-" ? "-Not Captured-" : year;
                                        }
                                    }
                                }, true); // Setting pivotUI() third parameter to true to refresh the derivedAttributes (plus config, etc.).
                            }
                        });
                    }
                })
                return false;
            });
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $('.open').click(function () {
                $('#columnContainer').fullscreen();
                $(this).hide();
                $('.close').show();
                return false;
            });
            $('.close').click(function () {
                $.fullscreen.exit();
                $(this).hide();
                $('.open').show();
                return false;
            });
        });
    </script>

}

**Comment by nicolaskruchten** [comment]
OK, and what is it that this is meant to do?

**Comment by nicolaskruchten** [comment]
OK... Unfortunately I'm not able to see what's wrong here, you'll have to build a smaller version of the code that clearly reproduces the problem if you want me to help you debug it :)

**Comment by salimrahal** [comment]
The "Error: unknown input format" is related to input data, you are missing something. If you are using tips data try to import: tips_data.min.js
Example: https://jsfiddle.net/nicolaskruchten/w86bgq9o/

**Comment by GetWild** [comment]
Thanks Salim, yes it was to do with the data. I got it working eventually.
