### ISSUE TITLE
$(...) pivot is not a function in jquery + angular 4 + webpack Compiled successfully

### ISSUE THREAD

**Issue by vaibhav2018** [nicolaskruchten/pivottable#884]
index.html
--------------
![indexhtml](https://user-images.githubusercontent.com/37400751/37456279-fd02f372-2864-11e8-908e-5fc84cbaafa6.png)

pivot.component.html
------------------------------
![pivotcomponenthtml](https://user-images.githubusercontent.com/37400751/37457412-f2140b92-2867-11e8-8708-e9d1d60aa6d9.png)

pivot.component.ts
-------------------------
![pivotcomponentts](https://user-images.githubusercontent.com/37400751/37456401-4483b7ae-2865-11e8-9b87-47a2f05ee8fc.png)

angular-cli.json
--------------------
![angular-clijson](https://user-images.githubusercontent.com/37400751/37456493-8d3dafe0-2865-11e8-83f9-c8f53b11a287.png)

package.json
------------------
![packagejson](https://user-images.githubusercontent.com/37400751/37456628-d47b38b4-2865-11e8-8d48-dd2d5405990f.png)

webpack compiled successfully
------------------------------------------
![webpack compiled successfully](https://user-images.githubusercontent.com/37400751/37456814-46bf7318-2866-11e8-8f91-ffc07e68dffd.png)

localhost:4200/pivot
---------------------------
![localhost 4200](https://user-images.githubusercontent.com/37400751/37456933-89fe03ce-2866-11e8-8abe-6e4c39343949.png)

app.component.ts
------------------------
import { Component } from '@angular/core';
import * as $ from 'jquery';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
}

app.component.html
----------------------------
![appcomponenthtml](https://user-images.githubusercontent.com/37400751/37457455-13a9d28c-2868-11e8-8c03-6a28f6908d5e.png)

I was able to follow some steps to achieve this but still getting error.
Not sure how it can be solved.
Please help guys.

**Comment by nicolaskruchten** [comment]
Posting screenshots of code makes it almost impossible to help you. Can you post a minimal repo or something so that someone can try to execute the code you're wanting help with?

**Comment by FloPrey** [comment]
We had a similar issue and we had to set jquery to global scope in webpack.

We added this to the config.modules:
` { test: require.resolve('jquery'), loader: 'expose-loader?jQuery' }`

Also we imported jquery different:
`import jQuery from 'jquery';`
and than
`const pivotElement = jQuery(element[0]);
pivotElement.pivotUI();`

**Comment by Arezoo-Bozorgmehr** [comment]
Hey guys,

i am not professional in Angular, but I have a project in angular and need in this case a pivot table. This module unfortionattly is for angularjs and i`m working with angular 4. Could you help me please, how can I make this for my ptoject.

**Comment by FloPrey** [comment]
Hi,

actually this project just uses jquery and not angularjs. 
So for using it, you have to import jquery and jquery-ui and the pivot table should work no matter if you use angularjs or angular 4.

**Comment by vaibhav2018** [comment]
@FloPrey already imported jquery and jquery-ui
@Arezoo-Bozorgmehr  this is working in angular 4 also just some proper setup needed
As of now working 
Steps: 
1. **removed**      _import * as $ from jquery_ from pivot.component
2. **added**          _declare var $ : any_ in pivot.component
3. if you are using any google charts, d3, make sure it is available in **angular-cli.json** in scripts
     "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/jquery-ui-dist/jquery-ui.js",
        "../node_modules/pivottable/dist/pivot.min.js",
        "../node_modules/pivottable/dist/d3_renderers.min.js",
        "../node_modules/pivottable/dist/gchart_renderers.min.js"
     ]
4. **added**          _import 'jquery-ui';_ in pivot.component

**Comment by vaibhav2018** [comment]
should we close this issue?

**Comment by nicolaskruchten** [comment]
If your needs are met yes we can close this issue. Note that there is a long discussion of Angular integration here: #208

**Comment by abdelwahebmoalla** [comment]
@vaibhav2018 
I added "../node_modules/pivottable/dist/gchart_renderers.min.js" and I added
script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> in index.html
but I still get TypeError: Cannot read property 'arrayToDataTable' of undefined when I choose line chart 
what am i missing or doing wrong ?
