### ISSUE TITLE
creating rows/columns for missing data

### ISSUE THREAD

**Issue by giko45** [nicolaskruchten/pivottable#885]
Hi,

How can i add rows/column headers/labels for which there is no values in de dataset?

**Comment by nicolaskruchten** [comment]
Unfortunately this is not possible at the moment.

**Comment by amenadiel** [comment]
You could do some preprocessing on the data you feed to Pvt. Worst case scenario: traverse every row and extract all keys (if rows were objects) then do it again ensuring every row has a defined value for such key.

I'm doing this preprocessing by default to infer how many distinct values are there for a given key (0 or 1 will omit the key), infer what properties have scritly numeric values (will remove them from draggable attributes and whitelist them to aggregator properties).

The same could be done in your case. If you're meaning to use user picked datasets, or datasets you just don't know beforehand , you will need to perform some diagnosis
