### ISSUE TITLE
Export to TSV button not available for download

### ISSUE THREAD

**Issue by vaibhav2018** [nicolaskruchten/pivottable#887]
Hello @nicolaskruchten 
I was wondering isn't there any download button for the generated tsv file or it is available and I'm unable to find that.
Or is there any way to download only filtered data
Could you please guide.

![tsv](https://user-images.githubusercontent.com/37400751/37647311-f1314f62-2c51-11e8-8a50-cd80c85c1d58.png)

![table](https://user-images.githubusercontent.com/37400751/37647312-f252d460-2c51-11e8-96a5-8cdd6b2ca823.png)

**Comment by nicolaskruchten** [comment]
There is no built-in feature for this, but others have found various ways of doing it: see #58, #851, #187 ...

**Comment by vaibhav2018** [comment]
Thanks @nicolaskruchten 
I'll close this issue and will follow #58, #851, #187
