### ISSUE TITLE
change heatmap font color and size

### ISSUE THREAD

**Issue by kuhbrille** [nicolaskruchten/pivottable#889]
Hi,
setting the background of the cells in a heatmap and i.e. hide the totals works fine.
But, is there any way to change the size and color of the cell values in a heatmap?
For hiding totals we can use 
  .pvtTotalLabel,
  .pvtTotal,
  .pvtGrandTotal {
    display: none;
  }

is there something similar for pvtVal or pvtTriangle?

KR 
Roland

**Comment by nicolaskruchten** [comment]
This example shows how to control the colour scale in a heatmap https://pivottable.js.org/examples/montreal_2014.html and yes, you can style the cells however you like with `td.pvtVal` and any applicable CSS including `width`, `height`, `font-size` etc...
