### ISSUE TITLE
Legends truncate in charts using C3 & D3 renderers.

### ISSUE THREAD

**Issue by sujit-ltpl** [nicolaskruchten/pivottable#891]
Hi Nicolas,
@nicolaskruchten 

I was working with few big datasets & facing data truncate issue in legends.
It's truncating the legends after its max width reached.
By right it should wrap the legend into multiple lines.

Snaps - 
![1](https://user-images.githubusercontent.com/20333712/37861603-1e17ba02-2f63-11e8-989d-4a48bb6d355a.png)

![2](https://user-images.githubusercontent.com/20333712/37861604-2489c6dc-2f63-11e8-98ec-b77f96836a06.png)

Can you help me with this, will be really appreciated.

**Comment by nicolaskruchten** [comment]
You'll have to see if there are any C3 options you can pass in via `rendererOpts` similar to the way this example does: https://pivottable.js.org/examples/scatter.html

**Comment by sujit-ltpl** [comment]
Hello @nicolaskruchten 

The link you have given seems not to be helpful for my issue.
Basically, I have issues with legends/labels, not with chart area, chart is rendering fine.
If you have any solutions regarding the same, please let me know.

Thanks

**Comment by nicolaskruchten** [comment]
I've updated the documentation for C3 `rendererOptions` which should make it a bit clearer:  https://github.com/nicolaskruchten/pivottable/wiki/Optional-Extra-Renderers#c3-rendereroptions

**Comment by amenadiel** [comment]
C3 Legends are not really smart. It's not pivottable's fault. 

You could pass options to position the legend below the graph, and group the labels in two columns, but they are still svg text elements and won't wrap or provide any kind of responsiveness as you would expect from a proper flex layout.
