### ISSUE TITLE
Pie Chart

### ISSUE THREAD

**Issue by rajuchapagain** [nicolaskruchten/pivottable#893]
Hi, Can we have multiple pie chart in the same way?

**Comment by nicolaskruchten** [comment]
Unfortunately none of the rendering engines support multiple pie charts to my satisfaction today, so not at the moment.

**Comment by Fosnez** [comment]
Also Pie Charts are terrible: https://www.businessinsider.com.au/pie-charts-are-the-worst-2013-6?r=US&IR=T

**Comment by ebellumat** [comment]
I Create a Plotly renderer option to create Donnut/Pie Charts, soon i create a Pull Request. I Hope @nicolaskruchten  accept, hehe

![image](https://user-images.githubusercontent.com/26942680/44176702-3bf75f80-a0c1-11e8-93df-6ea4b4eec88c.png)

![image](https://user-images.githubusercontent.com/26942680/44176761-7e20a100-a0c1-11e8-9073-204a9d57958f.png)

**Comment by Fosnez** [comment]
Pie charts are a terrible way to visualise data, and we shouldn't be
encouraging users to use them:

https://www.businessinsider.com.au/pie-charts-are-the-worst-2013-6?r=US&IR=T

**Comment by nicolaskruchten** [comment]
Thanks @ebellumat !

I would ask that if this does not end up being merged into the main library, that you not fork this library in total, but rather create a new 'plugin' library with just this renderer, much like https://github.com/nagarajanchinnasamy/subtotal :)

**Comment by nicolaskruchten** [comment]
Pie charts are now built in :)
