### ISSUE TITLE
Ability to add hyperlink?

### ISSUE THREAD

**Issue by t1eap** [nicolaskruchten/pivottable#899]
Hi,

First off, I absolutely love this project - it's been extremely useful.  Thank you for providing this to the community.

What I'm wondering is - is there a way to add hyperlinks to the data?  I'm guessing this will require a new/custom renderer (was looking at [this](https://stackoverflow.com/questions/26002789/pivottable-display-html-in-table) but noticed changes were rolled in.  Might still be a way to adapt this to my needs I suppose).  Any pointers would be appreciated.

For background, I have a web interface which is used to enter the data into a database for the pivot table.  I then query the database and generate a csv file to feed into pivot table (I need to work on a more seamless integration, but it works for my needs for now).  It would be extremely helpful to be able to have one column in the row have a link back to the page where the data was entered so that it can be adjusted.  Since I'm pulling the data into a file, I can feed in data as an <a> tag (though that's not very elegant), but I tried this and it's not currently treated as html.  I use PivotUI.

Thanks in advance!

**Comment by PaddingtonTheBear** [comment]
One way around this might be to make it so when a user clicks on one of the data elements within the Pivot Table, it displays a dialog with a list of all the matching records. In this list, you would have a hyperlink to each record that pertains to that pivot table element.

I've done something similar by modifying the PivotUI config object's rendererOptions to display a modal when a user clicks on a cell, and then determining what the current values would be:

https://gist.github.com/PaddingtonTheBear/ca36a825d1d47c7da18f3f9e4a4a8386

**Comment by t1eap** [comment]
@PaddingtonTheBear 
Thank you very much for the reply and example!  I hadn't thought of the approach of using a dialog box to implement.  This also means I failed to notice the other example here: https://pivottable.js.org/examples/mps_prepop.html

Between the two, I came up with the following (modified to be generic):

```
rendererOptions: {
                    table: {
                        clickCallback: function(e, value, filters, pivotData){
                            var names = [];
                            pivotData.forEachMatchingRecord(filters,
                                function(record){ names.push(record.name); });
                            if (window.confirm("Visit Name: "+names[0]+"?"))
                            {
                                var win = window.open('http://linktosite/entry/"+names[0],'_blank');
                                win.focus();
                            };
                        }
                    }
                },
```

In my use case, there should only be one "name" per data value which is why I call out the first one in the array, however if someone has more, they'd want to adjust this.  I'm new to javascript so I'm sure I could have implemented it in a more generic manner.

This creates a popup and when clicking OK opens a new tab (at least in my browser - using Chrome 65), which is what I wanted.
