### ISSUE TITLE
How to define a custom regexp aggregation?

### ISSUE THREAD

**Issue by ohaddahan** [nicolaskruchten/pivottable#903]
Hello, firstly this package is really amazing.
I'm having trouble generating a custom regexp aggregator.
Let's say I have a record with attribute name and I use the regexp:
` var pat   = record.name.match(/(?<name>\w+)(?<number>\d+)/).groups;`
I want to aggregate on `pat.name` , I wrote the aggregator below but it doesn't work.
It seems to store `this.name` randomly and not return the right value in `value` function.
Any help will be appreciated :)

```

var nameAggretator = function() {
    return function() {
        return {
               name: "",
                storage: {},
                push:  function(record) {
                    var pat   = record.name.match(/(?<name>\w+)(?<number>\d+)/).groups;
                    this.name = pat.name;
                    if ( this.storage[this.name] == undefined ) {
                        this.storage[this.name] = 0;
                    }
                    this.storage[this.name]++;
                },
                value: function() { 
                    return this.storage[this.name];
                },
                format: function(x) { 
                    return this.storage[this.name];
                },
                numInputs: 1
        }
    };
}
```
```
 $("#output").pivotUI( $.pivotUtilities.tipsData , { 
        rows: rows,
    cols: cols,
    aggregators: {
        "count":  function() { return $.pivotUtilities.aggregatorTemplates.count()() },
        "name": nameAggretator,

    },
    onRefresh: function(config) {
        var config_copy = JSON.parse(JSON.stringify(config));
        //delete some values which are functions
        delete config_copy["aggregators"];
        delete config_copy["renderers"];
        //delete some bulky default values
        delete config_copy["rendererOptions"];
        delete config_copy["localeStrings"];
        $("#config").text(JSON.stringify(config_copy, undefined, 2));
    },
    })

```

**Comment by ohaddahan** [comment]
@nicolaskruchten

**Comment by nicolaskruchten** [comment]
I'm not sure I understand what you're trying to do here... There are no guarantees as to the order in which the records are passed to aggregators, which is why it will look like `name` gets assigned randomly. If you want to "aggregate by" `pat.name` then you will likely want to create a deriver that extracts the name, and then use the name as a row or column header.

**Comment by ohaddahan** [comment]
What I'm trying to do is , let's say I have data that looks like this:
```
data = [
{name: 'abc1' , status: 'Fail'},
{name: 'abc2' , status: 'Waiting'},
{name: 'xyz1' , status: 'Fail'},
{name: 'xyz2' , status: 'Waiting'},
....
....
....
]
```

When I aggregate by name , I want to have two groups , 'abc' and 'xyz'.
So you're saying that I first need to create a deriver that extract the data and than it will be applied automatically since 'name' attribute will be converted into what I want anyhow?

Thanks.

**Comment by nicolaskruchten** [comment]
I'm still not clear on what you're trying to do... For the `data` above, what output would you want to see in the table, for what values of `rows` and `cols`?

**Comment by ohaddahan** [comment]
For the above `data` , when aggregating with the logic from the original post, I would expect to have two groups. `'abc' = 2` , `'xyz' = 2` since I'm aggregating on r`ecord.name.match(/(?<name>\w+)(?<number>\d+)/).groups.name`.

**Comment by ohaddahan** [comment]
Thanks, I implemented a deriver and it works as expected.
One small thing that confused me, might confuse others.

I used `name: nameDeriver` which overwritten the original `record.name` data since I thought that the deriver is called anything we access `record.name`.

I understood that I need to change it to `derived_name: nameDeriver` and created a new column that works as expected.
