### ISSUE TITLE
problem with date derivers

### ISSUE THREAD

**Issue by zpj61** [nicolaskruchten/pivottable#906]
Hi,
I'm trying to use data derivers in a simple table with count. Maybe I'm doing something wrong  but it seems to me that no derived values are generated for the first row.
The code is trivial, I'm using array of arrays to pass data.

<script type="text/javascript">
       var datain = [["DATE","NAME","JOB","OPERATOR"],["2018-02-29","nikki, tikki","Control","OP 3"],["2018-03-29","mac, donald","food","OP 4"],["2018-04-29","mac, big","food","OP 4"],["2018-05-29","bugher, king","meat","OP 4"]];
$(function () {
        var dateFormat =  $.pivotUtilities.derivers.dateFormat;
        var sortAs =           $.pivotUtilities.sortAs;
                $("#output").pivotUI(datain , {
                    derivedAttributes: {
                        "month name": dateFormat("DATE", "%n", true),
                        "day name":   dateFormat("DATE", "%w", true)
                    },
                    rows: ["day name"],
                    cols: ["month name"],
                    sorters: {
                        "month name": sortAs(["Jan","Feb","Mar","Apr", "May",
                                "Jun","Jul","Aug","Sep","Oct","Nov","Dec"]),
                        "day name": sortAs(["Mon","Tue","Wed", "Thu","Fri",
                                "Sat","Sun"])
                    }    
                });
    });	 
	  </script>

**Comment by ohaddahan** [comment]
I suggest you make your question more readable (http://jsbeautifier.org/) @zpj61 :

```
<script type="text/javascript">
    var datain = [
        ["DATE", "NAME", "JOB", "OPERATOR"],
        ["2018-02-29", "nikki, tikki", "Control", "OP 3"],
        ["2018-03-29", "mac, donald", "food", "OP 4"],
        ["2018-04-29", "mac, big", "food", "OP 4"],
        ["2018-05-29", "bugher, king", "meat", "OP 4"]
    ];
    $(function() {
        var dateFormat = $.pivotUtilities.derivers.dateFormat;
        var sortAs = $.pivotUtilities.sortAs;
        $("#output").pivotUI(datain, {
            derivedAttributes: {
                "month name": dateFormat("DATE", "%n", true),
                "day name": dateFormat("DATE", "%w", true)
            },
            rows: ["day name"],
            cols: ["month name"],
            sorters: {
                "month name": sortAs(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]),
                "day name": sortAs(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
            }
        });
    });
</script>
```

**Comment by nicolaskruchten** [comment]
The issue is that your first row has `2018-02-29` which is not a valid date as 2018 isn't a leap year, so it's being interpreted as if it was March 1 :)

```javascript
new Date("2018-02-28").getUTCMonth(); // 1 = feb
new Date("2018-02-29").getUTCMonth(); // 2 = mar
```

**Comment by zpj61** [comment]
ugh... late night works are prone to stupidity... thank you
