### ISSUE TITLE
Pivot table js subtract two column values 

### ISSUE THREAD

**Issue by mamtakathar** [nicolaskruchten/pivottable#910]
Hello @nicolaskruchten 

I have this pivot table I created using your library pivottable.js,  with the rows and columns as shown in the image below.
![image](https://user-images.githubusercontent.com/20275611/38958188-243cf5e6-4322-11e8-883f-3369a243b2c2.png)

I wanna be able to subtract the sum of sales in the current Quarter( say 2018 second quarter) from the previous quarter ( say 2018 first quarter) and also convert into a percentage value, in a separate column. 

Is that possible?

Thank You, 

Mamta

**Comment by nicolaskruchten** [comment]
No, this is not possible... all cells in the pivot table output are
computed the same way, you cannot have certain columns that are computed
differently.
