### ISSUE TITLE
Hiding totals columns, hiding dropdowns in pivotUI()

### ISSUE THREAD

**Issue by spikemcfarland** [nicolaskruchten/pivottable#911]
Love the pivot table package! Thank you!

I have two issues that I can't find the answer to in the documentation.

1. I only want to display a dropdown selector for one of the values I'm displaying.
My pivot table has row="Output" and columns="Marker", "Sex", "Genotype", and "ID".
I only want the user to select the "Marker". How do I hide the other three? (And can I initialize it to 
a single marker. I won't know them until after I run the query.)

2. In my report the column and row totals are meaningless. How do I hide them?

**Comment by nicolaskruchten** [comment]
Glad you like the library!

1.  If you want to disable the filter menu triangle for certain attributes, this is not possible.
2. See https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#totals

**Comment by Bill-VA** [comment]
I know I can hide the totals column and row, but it sure would be nice if it was never created.  Any chance of making that an option?  The reason this is causing a problem for me now is when I use the NReco plugin to sort the columns, the plugin is changing the size of the table when it sorts to accommodate the totals and then I hide them with CSS and it leaves me with an unattractive table.

**Comment by nicolaskruchten** [comment]
@Bill-VA if you'd like to post a pull request with a flag in the `TableRenderer`'s `rendererOptions` that does this I would happily accept it!

**Comment by Bill-VA** [comment]
I honestly don't know enough about Git to do that.  Every time I click on New Pull Request, it asks me to compare changes - I have no changes or code to offer, just a feature request.

**Comment by Bill-VA** [comment]
Update?

**Comment by nicolaskruchten** [comment]
@Bill-VA To be clear: I’m not actually working on this issue, but I’m open to PRs for it as I’ve mentioned :)

**Comment by nicolaskruchten** [comment]
Update: I've added `rowTotals` and `colTotals` as `rendererOptions` for the table renderer... https://github.com/nicolaskruchten/pivottable/wiki/Renderers#table-rendereroptions

**Comment by Bill-VA** [comment]
That's cool, however it doesn't seem to work with PivotUI.  I can edit the .js file to disable totals, which for me is probably ok, but maybe it should work for both methods.

    defaults = {
        table: {
          clickCallback: null,
          rowTotals: false,
          colTotals: false
        },
        localeStrings: {
          totals: "Totals"
        }
      };

**Comment by nicolaskruchten** [comment]
Did you try passing these options through rendererOptions? It does work
with pivotUI :)

**Comment by dmclark** [comment]
Thanks for adding this to table.
I have a use case where i need rowtotaalss in a plotly  line graph. 

should  i do a custom rendererer?

**Comment by nicolaskruchten** [comment]
@dmclark I'd like to learn more about your use case but could you please create a separate issue for it?
