### ISSUE TITLE
Cannot show values from JSON List in Newline

### ISSUE THREAD

**Issue by Vinayt89** [nicolaskruchten/pivottable#913]
Hi Nicolas,

Thank you for your efforts in making this awesome library..Really Appreciate!

`[{"lineId":20180111129,"saPersonList":["Person1","Person2"],"saPercentage":["25%","75%"],"saAmount":["10,000","30,000"],"salesAmount":"40000","invoiceNumber":"TC1712022"}`

I'm working on one scenario where i'm passing the JSON(mentioned above) to the pivot.
Currently Pivot is  displaying List in a JSON i.e **saPersonList**  like **_Person1_, _Person2_**, I want to show each value in list in a newline by escaping comma. I have tried appending "\n","\\\n" but it didn't worked for me.

Can you please guide me how can i achieve this?

Thanks,
Vinay

**Comment by nicolaskruchten** [comment]
Sorry I didn't get back to you on this, I was on vacation. There's no real support for structured values like arrays or objects unfortunately: attribute values are treated as scalars so you'll need to convert them to strings.

**Comment by Vinayt89** [comment]
No Probs Nicolas.
I got that it only works with strings & solved the problem i was facing so closed the issue.

I'm trying to achieve one more thing but not getting success..Created new issue regarding the same [https://github.com/nicolaskruchten/pivottable/issues/932](url)  

Can you please check?

Thanks Anyways :)
