### ISSUE TITLE
Question : see an un-aggregate view

### ISSUE THREAD

**Issue by ohaddahan** [nicolaskruchten/pivottable#915]
How would you recommend to provide a view to view the underlining results for the aggregation?
For example let's say my data is:
```
data = [
{ name: 'david', age: 10},
{ name: 'robert', age: 10},
{ name: 'jane' , age: 15}
]
```

Let's say that I aggregate on `age` column. Than I'll have two rows `10 => 2, 15 =>1`.
Is it possible to see the actual original rows that were aggregate in each group?

I'll be fine with having another table that the pivottable will rewrite with the data when I click value, for example when I click 2 (which resulted from age group 10) the other table will receive the 2 rows.

I assume I'll need to write some custom render but I'm not sure how to start :)

**Comment by nicolaskruchten** [comment]
Probably the best starting point I could give you would be this one which attaches a click callback to every cell which allows you to grab the original records from the underlying data based on the cell parameters: https://pivottable.js.org/examples/mps_prepop.html

**Comment by ohaddahan** [comment]
Exactly what I needed, thanks.
