### ISSUE TITLE
Date range picker

### ISSUE THREAD

**Issue by LittleHamster** [nicolaskruchten/pivottable#918]
This is an awesome library, thank you for it :)
I was wondering if it is possible to filter the data on the UI for date range. For example, I have a sample data (similar to your Motrean weather example). 

```csv
2014-01-01,-16.5,-24.6,-20.6,0,0
2014-02-02,-22.6,-27.3,-25,0,1.4
2014-02-03,-19.2,-24.3,-21.8,0,0
2014-03-04,-8.6,-23.3,-16,0,0
2014-04-05,0.3,-12.6,-6.2,12.2,1.8
2014-06-05,0.3,-12.6,-6.2,12.2,1.8
2015-05-06,7.1,-11.1,-2,14.3,0.4
```

I want to be able to pick the data from `2014-03-04` to `2015-05-06`
is there any option to allow user filter specific field for range? 

thanks in advance

**Comment by nicolaskruchten** [comment]
Unfortunately this is not possible at the moment or likely to be supported in the near future as this library is not aware of attribute types in the input. One way forward would be #191 but I don't have the time to implement this :)
