### ISSUE TITLE
using dateFormat to group by week numbers

### ISSUE THREAD

**Issue by LittleHamster** [nicolaskruchten/pivottable#925]
Is it possible to use `dateFormat` to group dates based on week numbers?
for example , this week, is week 18
https://www.epochconverter.com/weeknumbers
so any date from `2018-04-30` to `2018-05-6` is grouped to Week 18

**Comment by nicolaskruchten** [comment]
There is nothing built-in, no. Some of the reasoning for this is explained here: https://github.com/nicolaskruchten/pivottable/pull/77

Basically there are too many ways to define "week number" to support in a library like this. You can create a deriver based on Moment.js or something if you need a specific definition of "week number" :)

**Comment by LittleHamster** [comment]
@nicolaskruchten 
thanks
