### ISSUE TITLE
switching aggregator dropdown erases vals attribute

### ISSUE THREAD

**Issue by stiv-yakovenko** [nicolaskruchten/pivottable#926]
I set initial data like this:

![image](https://user-images.githubusercontent.com/4163254/39673906-845c186c-516e-11e8-99b1-4737391c3f1d.png)

(I don't perform any other initialisation)

Component looks reasonable:

![image](https://user-images.githubusercontent.com/4163254/39673913-a33b4ed8-516e-11e8-9bc1-5038143215b7.png)

But if I switch to second aggregator and then back to the fist one, my data is broken:

![image](https://user-images.githubusercontent.com/4163254/39673943-050924aa-516f-11e8-987a-362618db487d.png)

It seems like vals is somehow null now as you can see in debug logs, is it possible to avoid erasing this field?

**Comment by stiv-yakovenko** [comment]
Ok, I've solved it myself, this is how it is supposed to work:

![image](https://user-images.githubusercontent.com/4163254/39676204-cb0d06f0-5190-11e8-945c-4790a0e2b9a9.png)

**Comment by stiv-yakovenko** [comment]
But its a bit strange, why vals value is lost on switch anyways.

**Comment by nicolaskruchten** [comment]
I'm sorry, I can't follow what you're describing with these screenshots... can you provide a CodePen or JSFiddle that shows the problem?

**Comment by stiv-yakovenko** [comment]
I think you can safely close the thread, i was using aggregators in a wrong way.

**Comment by nicolaskruchten** [comment]
OK!
