### ISSUE TITLE
Is there a way to call a renderer from outside the table or access current PivotData object?

### ISSUE THREAD

**Issue by rubenfig** [nicolaskruchten/pivottable#929]
I need to call a renderer with a button outside of the renderer selector. I've tried to call it from inside the onRefresh method, creating a new PivotData with the onRefresh configs, but it doesn't use the selected aggregator.

**Comment by rubenfig** [comment]
I've noticed that you can store the values after calling the renderer. Closing the issue. Thank you so much for your project! It has been very hepful!

**Comment by ohaddahan** [comment]
@rubenfig I was trying to find how to make my own renderer.
I want to place a toggle button in the cell, so I'll be able to show a user if they clicked this cell before or not.
Any tip/reference you can share? Thanks.
