### ISSUE TITLE
Custom Aggregator with filter column/row

### ISSUE THREAD

**Issue by Vinayt89** [nicolaskruchten/pivottable#932]
Hi Nicolas,

I want to integrate filtering function with the new custom aggregator(Ex: Sum of last 6 months)

`filter: function(record){ return record["month"] == "2017/10" }`

The above code works perfectly when loading a pivot but i want to produce the similar kind of result by creating new custom aggregator.

 how can i achieve this?

**Comment by nicolaskruchten** [comment]
Did you figure out how to do this or...?

**Comment by Vinayt89** [comment]
I have managed to solve the issue on Java side..I mean i have filtered the data on java side & on button click the new data gets loaded in Pivot, I know not a efficient solution.
I always struggle, when it comes to JavaScript so i try to do things as much as possible on Java side.

Anyways my requirement has changed , Now i'm having 12 columns as months (Jan - Dec) , rows as employees name & aggregation function "Integer Sum" based on their salary.

I want to add 1 more row below **"Totals"** something like **"Amount Last Year"** which should show last year's Total.
Something like this i want to add several rows which will have different calculations like **"Increase/Decrease % "** etc.

I know its not possible through java.
I have to modify your pivot.js script & do the required calculations/addition there..also tried doing it but being improficient in JavaScript nothing worked for me :(

I know its kind off weird requirement but do you think it's achievable through this library?

As it seems not many people & also you are not active here for answering the issues, I haven't opened a new issue regarding this.

If you could help me regarding this it'll be a great help.

Thank you,
Vinay
