### ISSUE TITLE
TSV Export doesn't change decimal separator from '.' to ','

### ISSUE THREAD

**Issue by MusinAmir** [nicolaskruchten/pivottable#938]
Hey @nicolaskruchten 
I am using Russian locale with decimalSep: ",". It's work properly for default renderers:
![image](https://user-images.githubusercontent.com/14330661/40422047-71b6650a-5ea7-11e8-9384-74c14c160287.png)

But with TSV Export renderer it's doesn't work:
![image](https://user-images.githubusercontent.com/14330661/40422107-a750d592-5ea7-11e8-8d96-3772ae91baf9.png)

**Comment by nicolaskruchten** [comment]
Yes, this is by design, as most spreadsheet importers seem to handle US formats like this. Is this not the case with you?

**Comment by MusinAmir** [comment]
In my system decimal separator depends on locale. So i need tool to change it. I will change export_renderers file if it's no ways to do it.

**Comment by psohm** [comment]
@MusinAmir I face the same problem. What did you change ?
@nicolaskruchten I saw there was a localeStrings var in export_renderers, do you provide a configuration to handle the ',' separator in TSV ?
