### ISSUE TITLE
Display millions of data

### ISSUE THREAD

**Issue by trixieann** [nicolaskruchten/pivottable#942]
hi, is it possible to load millions of data to the pivot table. well i think its possible because it loaded the table on my first attempt and it took more than 30mins to load  but now it wont load anymore. im using it for a dashboard thats why i need to display those million data. thankyou. please help

**Comment by nicolaskruchten** [comment]
This library generally tops out at 100k rows for interactive use. Millions of rows is not recommended for any browser-based system :)

**Comment by SethuICOMM** [comment]
Hi,
My employee base is 20000 .Is't possible to load the content in grid?

Sethu

**Comment by nicolaskruchten** [comment]
20k rows should be fine, depending on hardware and the nature of the output
table.

**Comment by SethuICOMM** [comment]
Hi
Thanks for reply.

From data retieval from web method which one is good 
1. JSON String
2. JSON object

Which one is faster to load the grid. ?
# After loading the data if we transform row into column or vice versa what is the timeline to load the data again.? Approximately 10,000 Employee information (emid, name, business, unit location, zone).

Sethu

**Comment by SethuICOMM** [comment]
Kindly share the latest bug fixed Pivottable.js  script file to use my project.

**Comment by nicolaskruchten** [comment]
@SethuICOMM a few notes:

1. please create a new issue for new questions
2. I can't provide recommendations for cases like this, you'll have to implement multiple approaches and compare them for your specific use-case
3. I don't provide support for excel-import code unrelated to this project
4. the latest files are in this repo, already accessible to you.
