### ISSUE TITLE
vertical scrollbar based on window width

### ISSUE THREAD

**Issue by SethuICOMM** [nicolaskruchten/pivottable#943]
HI,
I have couple of questions
1. How to increase the height of filter column in top band. For example my dataset has 25 fields i want t load the same into top of the grid very first time. But now system moved the filter values into left hand side. How do i avoid and increase the width?

2. I want to restrict the bottom scorll bar for data area. i don't want to show window scrollbar.

Sethu
![grid](https://user-images.githubusercontent.com/26506467/40711448-cf163f92-6418-11e8-9ad0-41ffa595a7d3.png)

**Comment by nicolaskruchten** [comment]
Those both sound like issues that can be addressed via CSS to me :)

**Comment by SethuICOMM** [comment]
Hi,
Could you please share me the code. It would good move to work next stage.

Sethu

**Comment by nicolaskruchten** [comment]
There is no built-in support for loading icons, and I don't have time to build your CSS for you, sorry :)

**Comment by SethuICOMM** [comment]
Thank you.
