### ISSUE TITLE
Multiple Fact Feasibility

### ISSUE THREAD

**Issue by SethuICOMM** [nicolaskruchten/pivottable#944]
Hi,

I want to insert more than 1 fact column. Is't possible to add more than one fact while grid generating?

Need your help.

Regards,
Sethu

**Comment by nicolaskruchten** [comment]
If you're asking about [multiple aggregators](https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi) then the answer is no unfortunately

**Comment by SethuICOMM** [comment]
Hi,
Noted. Will come to you if i have any issues.

Thanks for all help.

Sethu
