### ISSUE TITLE
 Potential vulnerability of jQuery version 1.8.3

### ISSUE THREAD

**Issue by kyrie2carry** [nicolaskruchten/pivottable#948]
We are using pivottable, but security scanner tool was able to detect the version of jQuery used by pivotable.
pivottable has dependency on jQuery.
So we checked jQuery vulnerabilities:
https://www.cvedetails.com/vulnerability-list/vendor_id-6538/Jquery.html
According to this list, there are a total 8 vulnerabilities listed for jQuery.
The detected version from the scan is:
1.8.3
This version was released in 2012.
So can you upgrade it to support the latest jQuery?

**Comment by nicolaskruchten** [comment]
This library supports versions of jQuery from 1.8.3 on upwards, so you're welcome to use whatever version you're comfortable with. If you find cases where this library is incompatible with a more recent/secure version of jQuery, please file a specific issue for that case :)
