### ISSUE TITLE
inclusionsInfo vs inclusions

### ISSUE THREAD

**Issue by dmclark** [nicolaskruchten/pivottable#949]
This is a fantastic library.

I am "prebuilding" charts for the use to selact from.

What is the difference between inclusionsInfo & inclusions? Do I need to define botth?

Example:
   "AWOL": function(){
        var today = new moment;
        return {
            "Base": {
              "id": "Base",
              "desc": "Starter report",
            },
            "Quarter": {
              "id": "Quarter",
              "desc": "Duration vs Age for Quarter",
              "hiddenAttributes": [],
              "hiddenFromAggregators": [],
              "hiddenFromDragDrop": [],
              "menuLimit": 500,
              "cols": [
                "ageGroup"
              ],
              "rows": [
                "duration"
              ],
              "vals": [],
              "rowOrder": "key_a_to_z",
              "colOrder": "key_a_to_z",
              "inclusions": {
                "ageGroup": [
                  "18 or Over",
                  "< 18"
                ],
                "quarter": [
                    [
                        today.format('YYYY'),
                        today.format('Q')
                    ].join('-'),
                ],
                "duration": [
                  "Under 1 hour",
                  "Over 1 hour but under 24 hours",
                  "More than 24 hours"
                ]
              },
              "inclusionsInfo": {
                "ageGroup": [
                  "18 or Over",
                  "< 18"
                ],
               "quarter": [
                    [
                        today.format('YYYY'),
                        today.format('Q')
                    ].join('-'),
                ],
              "duration": [
                  "Under 1 hour",
                  "Over 1 hour but under 24 hours",
                  "More than 24 hours"
                ]
              },
              "aggregatorName": "Count",
              "rendererName": "Table"
            },
            "Month": {
              "id": "Month",
              "desc": "Duration vs Age for Month",
              "derivedAttributes": {},
              "hiddenAttributes": [],
              "hiddenFromAggregators": [],
              "hiddenFromDragDrop": [],
              "menuLimit": 500,
              "cols": [
                "ageGroup"
              ],
              "rows": [
                "duration"
              ],
              "vals": [],
              "rowOrder": "key_a_to_z",
              "colOrder": "key_a_to_z",
              "exclusions": {
                "month": [
                  "Apr-16",
                  "Apr-17",
                  "Apr-18",
                  "Aug-16",
                  "Aug-17",
                  "Dec-16",
                  "Dec-17",
                  "Feb-16",
                  "Feb-17",
                  "Feb-18",
                  "Jan-16",
                  "Jan-17",
                  "Jan-18",
                  "Jul-16",
                  "Jul-17",
                  "Jun-16",
                  "Jun-17",
                  "Mar-16",
                  "Mar-17",
                  "May-16",
                  "May-17",
                  "May-18",
                  "Nov-16",
                  "Nov-17",
                  "Oct-16",
                  "Oct-17",
                  "Sep-16",
                  "Sep-17"
                ],
                "duration": [
                  "unknown"
                ]
              },
              "inclusions": {
                "month": [
                  "Mar-18"
                ],
                "duration": [
                  "Under 1 hour",
                  "Over 1 hour but under 24 hours",
                  "More than 24 hours"
                ]
              },
              "unusedAttrsVertical": false,
              "autoSortUnusedAttrs": false,
              "sorters": {},
              "inclusionsInfo": {
                "month": [
                  "Mar-18"
                ],
                "duration": [
                  "Under 1 hour",
                  "Over 1 hour but under 24 hours",
                  "More than 24 hours"
                ]
              },
              "aggregatorName": "Count",
              "rendererName": "Table"
            },
            "Errors": {
              "id": "Errors",
              "desc": "IDs of restraints of unknown duration",
              "derivedAttributes": {},
              "hiddenAttributes": [],
              "hiddenFromAggregators": [],
              "hiddenFromDragDrop": [],
              "menuLimit": 500,
              "cols": [],
              "rows": [],
              "vals": [
                "test_id"
              ],
              "rowOrder": "key_a_to_z",
              "colOrder": "key_a_to_z",
              "exclusions": {
                "duration": [
                  "Under 1 hour",
                  "Over 1 hour but under 24 hours",
                  "More than 24 hours"
                ]
              },
              "inclusions": {
                "duration": [
                  "unknown"
                ]
              },
              "inclusionsInfo": {
                "duration": [
                  "unknown"
                ]
              },
              "aggregatorName": "List Unique Values",
              "rendererName": "Table"
            }
        };
    },

**Comment by nicolaskruchten** [comment]
They're the same... for whatever reason I had called it `inclusionsInfo` originally and then changed it to `inclusions` but left the old one in for backwards compatibility: https://github.com/nicolaskruchten/pivottable/blob/master/src/pivot.coffee#L1004

**Comment by dmclark** [comment]
Thanks  for the quick reply.

You might want to add
delete config_copy["inclusionsInfo"];
 to https://pivottable.js.org/examples/onrefresh.html 

Just my $.02
