### ISSUE TITLE
request for more pivot examples

### ISSUE THREAD

**Issue by gmculp** [nicolaskruchten/pivottable#95]
Good evening.

Are there any pivot examples out there that show how to:
1. hide column axis attribute name labels (pvtAxisLabel) (e.g., if you were displaying years as the column headings, not to show the word "year" only the actual year values)
2. customize the sorting to sort by hidden sort_key fields (type integer)
3. utilize the getColKeys() and getRowKeys() to get the attribute values 

Thank you!

Gretchen

**Comment by marks** [comment]
@nicolaskruchten I'm very interested in adding sparklines. Any guidance of how to do this or a skeleton (existing even?) aggregator which would be good to work off for a sparkline to the right of the `pivot()`? (My data is similar to screenshot above and I am looking to replace "Totals" (which I've hidden using CSS) with a sparkline

All the aggregators I've written so far are for the data cells, not a new column to the right of the data cells.

Thanks so much!

**Comment by nicolaskruchten** [comment]
To replace the 'totals' column with a sparkline, my recommendation would be to write a bit of Javascript which would execute after the Table Renderer has rendered (i.e. run it from the `onRefresh()` callback) which would use http://omnipotent.net/jquery.sparkline/ to create a sparkline from the data which would be extracted from the table.

**Comment by marks** [comment]
Ok great. That's close to what I did except since I was using pivot and not pivotUI I created the spark lines after initialization and not on refresh. 

Would you want a PR for an example of this?

Mark


--
Mark Silverberg
(m) 512 826 7004
http://twitter.com/skram

**Comment by nicolaskruchten** [comment]
Sure, I'd be curious to see what it looks like! Are you able to use one of the example datasets I already have in the repo, perhaps the Montreal weather data?
