### ISSUE TITLE
PivotTable Mutilple Aggragator Functionality

### ISSUE THREAD

**Issue by KishanManali1824** [nicolaskruchten/pivottable#950]
Respected @nicolaskruchten 
![screenshot-2018-6-13 lis](https://user-images.githubusercontent.com/19813124/41347445-4fa16c22-6f27-11e8-8ddb-2bb0617fc52f.png)

Hello,
It's been great experience to implement this pivotJs in my project.
Now, i have a new request for help.
Currently pivotJs accept one aggregator formula like (Sum,Count) on one field.
But there are some reports where i need to implement two aggregator formula like (Sum,Count) on two field.

So respected sir,Is it possible ?
Need Help in this.
Waiting for positive reply.

Please see the attached file where in Data Block i am using two fields with two aggregator formula.
That's need to implement.

**Comment by nicolaskruchten** [comment]
As per the FAQ, this is not supported. https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#multi

Please note that it is neither necessary nor appreciated to send me direct email in addition to creating Github Issues :)

**Comment by KishanManali1824** [comment]
Respected sir

Thanks for reply.
I'm just asking for help in this issue.
Any help from you will be life saver for me in this project.

**Comment by nicolaskruchten** [comment]
I understand, but as I've mentioned, this is not a supported feature of this library, and likely will not ever be.
