### ISSUE TITLE
Separating the components of the pivotUI

### ISSUE THREAD

**Issue by prajwalkirankumar** [nicolaskruchten/pivottable#951]
Is there any way , the filters and the pivottable can be put into separate components ( in separate divs ) and still preserve the functionality?

The apply button functionality is getting lost when I separate the pivottable and the filters.

**Comment by nicolaskruchten** [comment]
I'm not clear on what you're trying to do here, can you clarify? In general this component builds itself out of a `<table>` element and so it will not be possible to "split" the pieces in any meaningful way.

**Comment by prajwalkirankumar** [comment]
I am trying to keep the filters open all the time ( instead of clicking on the UI to open a filter) . As there are too many filters, it is taking a lot of space : for which i intend to give a scroll. so i separated the table and the filters into two different divs. Now the apply functionality isnt working.

**Comment by nicolaskruchten** [comment]
Ah I see. This is pushing this library pretty far compared to its intended usage so I'm afraid I can't really help you much...
