### ISSUE TITLE
Odd behavior with inclusions & exclusions in pivotui

### ISSUE THREAD

**Issue by dmclark** [nicolaskruchten/pivottable#954]
Hi,

This may be my ineptitude w/i js,  but i' m trying to prepopulate a pivotui.

For the second argument, i'm sending
`{"inclusions": {  
                    "month": ["2017-6", "2017-7", "2017-8", "2017-9", "2017-10", "2017-11", "2017-12", "2018-1", "2018-2", "2018-3", "2018-4", "2018-5"],
                    "duration": [
                        "Under 1 hour",
                        "Over 1 hour but under 24 hours",
                        "More than 24 hours"
                        ]
                    }
}`

but it comes back in the onRefresh as

`  "exclusions": {
    "month": [
      "2016-01",
      "2016-02",
      "2016-03",
      "2016-04",
      "2016-05",
      "2016-06",
      "2016-07",
      "2016-08",
      "2016-09",
      "2016-10",
      "2016-11",
      "2016-12",
      "2017-01",
      "2017-02",
      "2017-03",
      "2017-04",
      "2017-05",
      "2017-06",
      "2017-07",
      "2017-08",
      "2017-09",
      "2018-01",
      "2018-02",
      "2018-03",
      "2018-04",
      "2018-05"
    ],
    "duration": [
      "unknown"
    ]
  },
  "inclusions": {
    "month": [
      "2017-10",
      "2017-11",
      "2017-12"
    ],
    "duration": [
      "Under 1 hour",
      "Over 1 hour but under 24 hours",
      "More than 24 hours"
    ]
  },`

any ideas

**Comment by nicolaskruchten** [comment]
One thing to note is that this library is not type-aware: it treats everything as strings. So if you're including `2017-6` it's normal that `2017-06` shows up in exclusions :)

**Comment by dmclark** [comment]
doh,  of  course\!

Sorry aboutthat!

**Comment by nicolaskruchten** [comment]
No need to apologize, it’s an understandable thing to do and an easy one to miss!
