### ISSUE TITLE
pivotUI() is not working

### ISSUE THREAD

**Issue by prashant71ht** [nicolaskruchten/pivottable#955]
i have added this library 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.21.0/pivot.min.js"></script>
its working fine for pivot() function , but won't work for pivotUI()
 giving  error:  
 An error occurred rendering the PivotTable UI.

**Comment by nicolaskruchten** [comment]
You'll have to provide the actual calling code for me to help you debug.

**Comment by prashant71ht** [comment]
Thank You @nicolaskruchten  
issue was fixed , i have imported  jquery-ui soratble.
