### ISSUE TITLE
Split pivot.coffee aggregation logic into separate module

### ISSUE THREAD

**Issue by mattbishop** [nicolaskruchten/pivottable#958]
I'm looking at running pivot calculations on a node server, and I'd love to use the aggregation logic. To do so, however, I will probably find I have to emulate browser-side concerns because pivot.coffee provides capability around rendering too.

Ideally the aggregation logic would be in a separate module without any UI knowledge. That would make it easier to use it in node.

**Comment by nicolaskruchten** [comment]
It's quite unlikely at this point that I'll split anything out of `pivot.coffee` or break up this module into multiple modules, just in terms of backwards compatibility... That said, if you're not calling `pivot()` or `pivotUI()` then you don't need to provide anything browser-related, just jQuery. You can use the `PivotData` class on its own if you like :)
