### ISSUE TITLE
sample pivotUI error in IE9

### ISSUE THREAD

**Issue by fifcan** [nicolaskruchten/pivottable#96]
Hello, 

I have just download the last version of pivottable to update my sample page and there is a javascript error when using Internet Explorer 9 and trying to access this example : **simple_ui_from_table.html**
Javascript console shows **undefined**
There is no error with Chrome or Firefox.
![image](https://f.cloud.github.com/assets/5551021/1712600/34bf9e90-6178-11e3-8098-60dc105550a5.png)

**Comment by jagb-nvl** [comment]
I downloaded the source code from gib and opened the file c3.html , UI is working in firefox but not in ie and chrome,Please help out in this regard , Thanks

**Comment by nicolaskruchten** [comment]
@jagb-nvl please create a new issue rather than commenting on an old, closed one... thanks!
