### ISSUE TITLE
colTotals renderoption for  multi-line charts

### ISSUE THREAD

**Issue by dmclark** [nicolaskruchten/pivottable#961]
To follow-up on [https://github.com/nicolaskruchten/pivottable/issues/911#issuecomment-400700136]
![screen shot 2018-06-28 at 8 27 26 pm](https://user-images.githubusercontent.com/170558/42066987-d769ffca-7b11-11e8-9792-d205dd41dc13.png)
If i want an additional line that is a sum of the 3 wouldnt it be a colTotal?

**Comment by nicolaskruchten** [comment]
If the aggregator used was `sum` then yes, you could get the data for that line from the column totals. I don't think this is a common-enough use-case that I'd want to make it a supported option of the charting renderers that ship with this library, so i would recommend forking the Plotly renderer if this is a requirement for you.

**Comment by dmclark** [comment]
@nicolaskruchten or anyone more familiar with js than I

i forked the plotly_renderer,    & added 
`        if (opts.with_total) {
          var totals = Object.keys(pivotData.colTotals).map((key) => { let data = pivotData.colTotals[key];  return data.count; });
          data.push({
            name: "total",
            x: pivotData.colKeys.map(function(i){return i[0];}),
            y: totals
          });
        }`

I  know this isnt generic yet, but can someone guide me on how to ensure totals are in the right order?

If this is too off topic, i will delete

**Comment by nicolaskruchten** [comment]
It might be easier to post a link to the complete file so I can read it in-context :)

**Comment by dmclark** [comment]
https://gist.github.com/dmclark/2bed8ea688294c7acc0f8669b39b9693

please don't laugh too hard

**Comment by dmclark** [comment]
On the off chance that it helps someone else, the solution i came up with is
https://gist.github.com/dmclark/2bed8ea688294c7acc0f8669b39b9693/revisions

**Comment by nicolaskruchten** [comment]
Sorry I haven't gotten back to you yet, it's been a hectic month... Your solution seems reasonable to me. Are you encountering any issues with it?

**Comment by dmclark** [comment]
Nope - it works great for my client needs. T even went further & added [regression-js](http://tom-alexander.github.io/regression-js/)

Thanks so much for all your patience
