### ISSUE TITLE
Headers Not Localized( Thousand separator and decimal separator) in PivotUI

### ISSUE THREAD

**Issue by FaheemAnsariReal** [nicolaskruchten/pivottable#963]
Hi,

I'm giving regional settings and localization in PivotTable, but the localization is only applying to the rows of generated table , not in the headers.

Expected output , headers also support decimal and thousand separator just like rows. Below is the attachment which will explain you whats the issue and whats expected outcome, used language in below attachment is Swedish. I'm in urgent development would really appreciate you if you could assist us to get this thing fixed.

Thanks
Muhammad Faheem Ansari
![img_05072018_164001_0](https://user-images.githubusercontent.com/40857840/42320452-fe88bd42-8072-11e8-8330-a3f61aedd3d8.png)

**Comment by nicolaskruchten** [comment]
No processing is done on the column headers at all in this library: if you need them localized you'll have to localize them yourself before input.

Also: please note that the fact that noting that something is "urgent" for you comes across as quite demanding... I've created this library in my spare time and am donating my time to answer your questions so please don't pass your stress along to me.

**Comment by FaheemAnsariReal** [comment]
Thank you Nicholas, I've tried sending formatted numbers but it has destroyed all the calculation of aggregators like Sum, integers.

I'm working on it to resolve this, will post if I find a way out.

**Comment by nicolaskruchten** [comment]
Ah yes, I see the problem if you want to use numbers as both cell headers and computations. I'm afraid I don't have a good answer for this, as number formatting is a property of aggregators, which are not used in generating the table headers. You may need to post-process the table using jQuery.

**Comment by FaheemAnsariReal** [comment]
Thanks Nicolas for your time, I've fixed the issue already and its working perfect :)

After rendering the entire table I process the number/currency based headers and applied localization.

**Comment by nicolaskruchten** [comment]
Great!
