### ISSUE TITLE
Casting of totals don't add up correctly

### ISSUE THREAD

**Issue by csavva** [nicolaskruchten/pivottable#970]
Hi,

If you see the screenshot below, the first row doesn't add up correctly whereas the second row it does. Any ideas on why this is so?

![screen shot 2018-07-16 at 22 11 37](https://user-images.githubusercontent.com/10960117/42780390-b2e35a6e-894b-11e8-8350-405bd99bf831.png)

**Comment by nicolaskruchten** [comment]
Which aggregator are you using? If you're using "count unique" this would make sense.

**Comment by nicolaskruchten** [comment]
Or "max", say

**Comment by csavva** [comment]
Yes, I am using the "Count unique" but still this doesn't make any sense to the user. The totals should reflect the total in the rows and columns.

**Comment by nicolaskruchten** [comment]
The totals is not the sum if you're using count-unique, it's the unique count across the rows or columns.

**Comment by nicolaskruchten** [comment]
If you need different behaviour, you can write a custom aggregator: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators
