### ISSUE TITLE
how to pass json data to pivotUI

### ISSUE THREAD

**Issue by susandotmark** [nicolaskruchten/pivottable#974]
I converted the object returned from the api into Json by JSON.stringify() and passed the result to pivotUI but got error. I too followed the Input Formats doc and my json data in the same format but still got error. Pls suggest where i went wrong

**Comment by nicolaskruchten** [comment]
The output of `JSON.stringify` is a string, which is not the correct input format: you need to pass in the actual object or array. Basically just skip the `stringify` :)

**Comment by susandotmark** [comment]
Yes, i figured it out later, thanks for your response sir
