### ISSUE TITLE
Transpose pivot table option

### ISSUE THREAD

**Issue by ArtinSarraf** [nicolaskruchten/pivottable#982]
Providing a button or right click menu option to transpose the selected fields from index to column and vice-versa. This is helpful for cases where you like to look at data with dates on the index and labels on the column, but when plotting in a plotly line chart the dates need to be on the ~~index~~columns to render correctly.

**Comment by nicolaskruchten** [comment]
Thanks for the feedback! I've considered this but have always decided against it in the interest of keeping things clean... I've even regretted the sorting arrows I had to put in recently as they don't render reliably the same way on all browsers.

I could be convinced otherwise if you were able to suggest a layout where such a button would be unobtrusive and unambiguous about its functionality, though :)

I must say that the extra few drag/drop operations to accomplish this in the absence of a button have never felt totally outrageous, so it doesn't feel like a major shortcoming to not have it.

**Comment by ArtinSarraf** [comment]
I would say that in the absence of a transpose button one option would be to provide an extra display type drop down for “columnwise” and “rowwise” line chart similar to how you have a bar chart option for both orientations.

**Comment by nicolaskruchten** [comment]
I'm confused about what kind of chart you need... can you post a screenshot? 

Also, I'm not sure what you mean when you say "cases where you like to look at data with dates on the index and labels on the column, but when plotting in a plotly line chart the dates need to be on the index to render correctly" ... this sounds like a bug that could/should be fixed, either here or in plotly.js :)

**Comment by ArtinSarraf** [comment]
Fixed my original comment. I will provide a concrete example later today.

**Comment by nicolaskruchten** [comment]
Ok! I believe that dates will render fine on either axis in a Plotly chart actually. If that’s not the case please do let me know!

**Comment by ArtinSarraf** [comment]
Ok so here's an illustration of my point. In figure 1 you can see the table view where the dates are oriented along the vertical axis and the labels are oriented along the horizontal axis. This is the way I've seen most people visualize time series data in a table. However when you choose the line chart option, the default behavior is to create an individual plot series per row with the x axis being composed of the column headers, clearly not very useful. 

In figure 2, you see the transposed table configuration that lends itself to a useful line plot (but a much less popular format for viewing the data in a table). So what I would propose is that the "line chart" option be renamed to "rowwise line chart" (or something similar) and a new option be added called "columnwise line chart". This one will produce a series per column and the x axis will be composed of the labels on the vertical axis. I realize that this tool is not meant to be a time series viewing tool, but it lends itself well to that, and the fact that there is already options for vertical/horizontal oriented heatmaps and bar charts makes it a very logical and (I'm guessing) easy addition.

Figure1: https://imgur.com/a/m1iafNJ
Figure2: https://imgur.com/a/KtNEtF0

**Comment by nicolaskruchten** [comment]
I see what you mean, thanks for clarifying!

I would say that I'm not sure I agree with you that it's much more common to look at tables of dates in this orientation... Certainly I don't and most of my financially-oriented colleagues don't, but I see the reasoning for it.

To me, this doesn't seem like a sufficiently strong reason to add a transposition button, or a new rendererer which would break the pattern of "y as rows, x as columns" which provides a nice intuitive mapping for charts. This 'row-wise' chart would be deeply counterintuitive to use except in the specific case of switching to it from such a table. 

That said, if you want to use such a renderer in your application, it should be quite easy for you to do: just fork and modify the Plotly renderers :)

**Comment by ArtinSarraf** [comment]
Makes sense. Thanks for hearing me out.
