### ISSUE TITLE
"vals: []" property in Pivot() Method.

### ISSUE THREAD

**Issue by ebellumat** [nicolaskruchten/pivottable#984]
I Create a result report screen with Plotly JS charts with pivottable passing columns, row, agregator parameters. But the "vals" property is only exists in PivotUI() Method. I had to use PivotUI method and hide the options configuration after rendered using $(.selector).fadeToggle(). Works, but with Pivot() Method whold be more elegant and faster. 

![43926155-bc5a1d50-9bff-11e8-880a-1ced5fd3e4f4](https://user-images.githubusercontent.com/26942680/44008486-af95873a-9e7a-11e8-9547-92b2c1a1ae75.gif)

**Comment by deepsweech** [comment]
> pivotUI

Is this `showUI` parameter applicable to the react component PivotTableUI?

**Comment by nicolaskruchten** [comment]
No, when using React, you should dynamically switch between the PivotTable and PivotTableUI components at the top level to achieve this.
