### ISSUE TITLE
Server side grouping and consulting support.

### ISSUE THREAD

**Issue by ebellumat** [nicolaskruchten/pivottable#985]
In some cases, the number of rows uses all memory available on Chrome, making him freezes, especially when the dataset have more than 100.000 rows. If the pivottable get only columns from dataset and uses a "query maker" like graphql, maybe make possible consult data "on demand". The only challenge, i see, is make the server side agregators  too. Exists the idea to make him happens someday? I Think the comunity would help in this case.

**Comment by nicolaskruchten** [comment]
This comes up every once in a while but I’m not really interested in taking
this library in this direction... PivotTable.js is, always has been and
always will be a client-side library only :)
