### ISSUE TITLE
Responsive Plotly Charts

### ISSUE THREAD

**Issue by ebellumat** [nicolaskruchten/pivottable#989]
Is it Hard to Implement Responsive Size of Plotly Charts? Currently, when the window change the size, I have to render all charts again, works, but the performance is pretty low. I have a report screen with tons of pivottable js pre-configured to build Plotly charts,

![image](https://user-images.githubusercontent.com/26942680/44226804-60a61280-a167-11e8-91c1-403867461798.png)

**Comment by nicolaskruchten** [comment]
This is how it's supported within plotly.js: https://plot.ly/javascript/responsive-fluid-layout/

**Comment by DaveSimmons1234** [comment]
I've not been able to get this to work in the plotly_renderers.js - I have tried to add it here:

`  Plotly.newPlot(result[0], data, $.extend(layout, {responsive: true}), layoutOptions, opts.plotly));`

However it doesn't work. Could you please let me know? 

Thanks,
Dan

**Comment by DaveSimmons1234** [comment]
Hi Nicolas,

Thanks for your response. I thought that might be the case. I have managed to incorporate a solution myself now. So all good.

Regards,
Dan
