### ISSUE TITLE
[Suggestion] Repo to list all Plugins avaiable in Pivottable

### ISSUE THREAD

**Issue by ebellumat** [nicolaskruchten/pivottable#991]
Currently exists a lot of forks in this project just adding a one single renderer to him, in the other hand, exists a lot of plugins to use it, like [Subtotal](https://github.com/nagarajanchinnasamy/subtotal) and  [NovixPivotJS](https://github.com/fbrussa/NovixPivotJS). If would  did exists a public list of avaiable plugins,  would avoid unecessary forks and helps other devs to find plugins to Pivottable, something like this would be cool, [Awesome-CoreML-Models](https://github.com/likedan/Awesome-CoreML-Models)

**Comment by nicolaskruchten** [comment]
I have this list already and I'm happy to keep adding to it: https://github.com/nicolaskruchten/pivottable/wiki/Used-By
