### ISSUE TITLE
checkbox in headers

### ISSUE THREAD

**Issue by ousemag** [nicolaskruchten/pivottable#994]
Hi, First of all, your stuff is absolutely brilliant! Well done! I have a quick question on the headers, especially on the lines header. In Table mode, I would like to be able to select lines to used them in another page. Kind of a form type with <input type="checkbox" ...> but embedded in the Pivot Table. Is it feasible? 
My level in javascript is very basic so my question might be very basic. Thank you!

**Comment by marclaporte** [comment]
I agree it's brilliant!

**Comment by nicolaskruchten** [comment]
This isn't going to be feasible without writing a fair bit of custom Javascript to hack the TableRenderer...

**Comment by ousemag** [comment]
That was my worry :( Thank you for it
