### ISSUE TITLE
Save rendered PivotTable objects to "Snapshot" File

### ISSUE THREAD

**Issue by rlugojr** [nicolaskruchten/pivottable#998]
Hi Nicolas,

Is there a way to save the final rendered PivotTable objects (pivotData, state, etc.) to a file or set of files?  The idea is to use that "snapshot" file to append the object back into the HTML of future sessions and reattaching or reloading it as a usable PivotTable.  My goal is to save a PivotTable object of about 800K rows of data from a 40MB CSV file.  Since my data changes very infrequently, it would be useful to generate the PivotTable once, save it and reload that pivot table so as to avoid having to download, parse and render each time the pivot table needs to be accessed.

EDIT: Is it possible to achieve this by saving the output div html to a file?

Thanks in advance.

**Comment by nicolaskruchten** [comment]
There's no easy way to do this, and I should add that if there were, the output would actually likely be bigger/slower to parse than your initial 40MB CSV, because it would contain all of that data in a rather uncompressed/verbose format, plus a bunch of other data besides...

**Comment by rlugojr** [comment]
Thank you for taking the time to respond!  I will try another approach.
