### ISSUE TITLE
Display Table and Line Chart together   

### ISSUE THREAD

**Issue by shukryz** [nicolaskruchten/pivottable#999]
Hi Nicolas,

First of all, thank you so much for an awesome library. 

Second, I'd like a help with rendering **table data and the Chart next to each other**. when, table data change from sum to average or different criteria chart should also change. Please let me know, how it can be done.

Thanks!!!

example: 
![screenshot_2](https://user-images.githubusercontent.com/16637570/44596764-72a53800-a79b-11e8-8bc7-a4ad2081608d.png)

**Comment by nicolaskruchten** [comment]
There's no built-in functionality for this, but you may be able to create a custom renderer that combines two existing ones: https://github.com/nicolaskruchten/pivottable/wiki/Renderers

**Comment by shukryz** [comment]
Thanks, Sure, i'll look into it. :)  I'll update this with an example code.
